### ISSUE TITLE
Is 'tests/test_activate.sh' actually run as part of the test suite?

### ISSUE THREAD

**Issue by HaraldNordgren** [pypa/virtualenv#1000]
I'm doing some work on the activation scripts so I looked at `tests/test_activate.sh`.

Am I wrong, or is this script not actually run? To make things break, I added `exit 1` to the beginning of the script, but it doesn't affect the `tox` results.

**Comment by gaborbernat** [comment]
Has been removed as of today and replaced with Python tests.
