### ISSUE TITLE
virtualenv pip freeze returns system modules when space is in containing folder

### ISSUE THREAD

**Issue by fernando-mc** [pypa/virtualenv#1001]
```
~/Desktop $ mkdir my\ test && cd my\ test
~/Desktop/my test $ virtualenv .env 
~/Desktop/my test $ source .env/bin/activate
(.env) ~/Desktop/my test $ pip freeze

```
This prints all system modules not just the ones in the virtual environment.

Happy to provide more context here as needed. I didn't see an issue template but I can add information as needed.

**Comment by HaraldNordgren** [comment]
Duplicate of https://github.com/pypa/virtualenv/issues/994
