### ISSUE TITLE
Document access to `--user` installed packages in `--system-site-packages` virtualenv

### ISSUE THREAD

**Issue by piotr-dobrogost** [pypa/virtualenv#1005]
[The --system-site-packages Option](https://virtualenv.pypa.io/en/stable/userguide/#the-system-site-packages-option) in User Guide does not say anything about visibility of `--user` installed packages in a virtualenv created with `--system-site-packges` virtual environment. This leads to people trying to use `PYTHONPATH` to access them like described in issue #971.

**Comment by pfmoore** [comment]
AIUI, #971 is about an option to access ```user-site-dir``` when ```--system-site-packages``` is *not* specified.

However, that's not relevant - I agree that documenting the fact that ```--system-site-packages``` also makes ```user-site-dir``` visible (and conversely, that ```user-site-dir``` is not visible in a normal virtualenv) is reasonable.
