### ISSUE TITLE
lib-dynload symlinked to wrong path

### ISSUE THREAD

**Issue by arunvelsriram** [pypa/virtualenv#1017]
A newly created virtual environment has `lib-dynload` symlinked to wrong system path. The path actually does not exist.

```
$ mkdir sandbox
$ cd sandbox
$ virtualenv venv
$ source venv/bin/activate
$ ls -la venv/lib/python2.7/lib-dynload/lib-dynload

lrwxr-xr-x  1 arunvelsriram  admin  95 Jan 28 15:08 venv/lib/python2.7/lib-dynload/lib-dynload -> ../../../../../../opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload

$ python -c "open('venv/lib/python2.7/lib-dynload/lib-dynload')"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: 'venv/lib/python2.7/lib-dynload/lib-dynload'

```

Screenshot:

<img width="721" alt="screen shot 2017-02-14 at 6 38 15 pm" src="https://cloud.githubusercontent.com/assets/6568319/22930125/ccfd5bf6-f2e4-11e6-9d3d-7d0a033fe1a5.png">

**Environment:**
OS: Mac OS X El Capitan 10.11.6 (15G1217)
Python: 2.7.13
Virtualenv: 15.1.0

**Comment by yan12125** [comment]
In Python there's no venv/lib/python2.7/lib-dynload/lib-dynload but only venv/lib/python2.7/lib-dynload

> Python: 2.7.13

How did you install this Python? The system default Python 2.7.10 works fine with virtualenv

**Comment by arunvelsriram** [comment]
@yan12125 Looks like my Python installation is broken. I reinstalled Python and its working now. You're right about the path to `lib-dynload`.
