### ISSUE TITLE
python3.6 using virtualenv

### ISSUE THREAD

**Issue by thao6626** [pypa/virtualenv#1018]
in the release history, i can see 

15.1.0 (2016-11-15)
Support Python 3.6.
Upgrade setuptools to 28.0.0.
Upgrade pip to 9.0.1.
Don’t install pre-release versions of pip, setuptools, or wheel from PyPI.

virtualenv 15.1.0 supports Python3.6. But when i create python3.6 env, there is an error: The path python3.6 (from --python=python3.6) is not an executable file. 

what's the reason for this error ???   my virtualenv version is 15.1.0

$ virtualenv --version
15.1.0

Thanks !!!

**Comment by pfmoore** [comment]
Stupid question maybe, but do you have Python 3.6 installed? What does ```which python3.6``` show?
