### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by mjreddy** [pypa/virtualenv#1028]
The setup.sh script seems to run fine. I did have to run it a few times because I didn't do sudo -H the first time and couldn't pip. The log seems to indicate everything is installed. What am I missing?
<img width="1200" alt="screen shot 2017-03-10 at 3 58 10 pm" src="https://cloud.githubusercontent.com/assets/750399/23817773/9468b51e-05aa-11e7-8bb4-1f1acc4950e7.png">

**Comment by yan12125** [comment]
Seems you're trying to install [TabPy](https://github.com/tableau/TabPy/blob/master/setup.sh)? That's unrelated to virtualenv.

**Comment by mjreddy** [comment]
My mistake.
