### ISSUE TITLE
provide virtualenv version information as environment variable

### ISSUE THREAD

**Issue by markfink** [pypa/virtualenv#1033]
We use virtualenv a lot and love it so thank you!

We still have some trouble with old virtualenv versions. I believe the main issue with old versions is that some OS installed packages "shine" through. We do not have similar issues with the current "15.0.1" version.

What we want to do is to check within a python module which virtualenv version we are using and issue a warning in case an old version is used. I propose an environment variable which is set and exported during ". ./venv/bin/activate". i.e:

``` text
export VIRTUAL_ENV_VERSION=15.0.2
```

I would like to discuss that with you and also check if you would accept a pull request for that and what the timeline for something like that is to get into a released version.

**Comment by pfmoore** [comment]
You say "check within a python module". Two options that exist already are (1) check ```virtualenv.__version__``` - it's not "officially" documented that we provide this variable, but we do and it's not likely that we'll stop, or (2) use pkg_resources to read the installed distributions and get the version from that.

I'm not over keen on adding more environment variables. We don't require the activate scripts to be run (it's completely supported to add a venv to your PATH manually, or even run the interpreter from the venv with an absolute path and no changes to PATH at all, so users wouldn't be able to rely on environment variables set in the activate script being available anyway). Also, the environment variable would need to be added to all the various activate scripts, and maintained in all of them.

As a further option, you could always do $(virtualenv --version) to find out what version of virtualenv is installed.

**Comment by markfink** [comment]
hmmm, I do not understand the 1) option
I can not find the variable
``` python
print os.getenv('virtualenv.__version__')
```
am I doing something wrong?

probably this means option 1) == 2) but does not work in my case since I do not install virtualenv in my `venv`. so `pip freeze` does not show virtualenv.

I like your third option (less work for me)
Unless option 1) can be fixed I go with 3). 
thank you... much appreciated

**Comment by pfmoore** [comment]
Yes, options 1 and 2 are using the virtualenv that's on sys.path, so if you don't have virtualenv in your venv, that won't work.

Glad the third option works for you!
