### ISSUE TITLE
Cannot create env using python3

### ISSUE THREAD

**Issue by jjuu** [pypa/virtualenv#1034]
* Version:  15.0.1
* Operating system: MacOS Sierra 10.12

### Description:
I tried to create env with python3 but failed.

### What I've run:
which python3

```
/usr/local/bin/python3
```

### What I've run:
virtualenv -p=/usr/local/bin/python3 py3site
```
The executable =/usr/local/bin/python3 (from --python==/usr/local/bin/python3) does not exist
```

Please help

**Comment by pfmoore** [comment]
Remove the ```=```. The syntax is ```-p /usr/local/bin/python3```.

**Comment by jjuu** [comment]
It works, thank you!
