### ISSUE TITLE
Make virtualenv compatible with both 32bit and 64bit

### ISSUE THREAD

**Issue by Ekultek** [pypa/virtualenv#1036]
You should create a flag that will make virtualenv compatible with both 32bit and 64bit Windows systems.

For example: `virtualenv --bit 32` creates a 32bit virtual python environment. Default will be the systems architecture

**Comment by pfmoore** [comment]
You can already do that, by using ```-p <path to the Python interpreter you want>```.

**Comment by Ekultek** [comment]
Ooo even better, thank you!
