### ISSUE TITLE
pip install with no active env but virtualenv installed has a weird error message

### ISSUE THREAD

**Issue by dyspop** [pypa/virtualenv#1038]
```
$pip install virtualenv
Could not find an activated virtualenv (required).
$virtualenv --version
15.1.0
```
not very helpful!

**Comment by dyspop** [comment]
if you're asking yourself "why would you run pip install when you already have it installed?" i thought i was using an os x user that hadn't installed it but had.

**Comment by pfmoore** [comment]
This looks like http://stackoverflow.com/questions/16460313/pip-could-not-find-an-activated-virtualenv-required

**Comment by dyspop** [comment]
maybe. not looking for the solution, i think it's the wrong output messagae.

**Comment by pfmoore** [comment]
The message is right, if that's the situation. You've set ```PIP_REQUIRE_VIRTUALENV``` which says you can only run pip in a virtualenv, so if you don't you get the message "Could not find an activated virtualenv (required)." Sounds accurate to me.
