### ISSUE TITLE
Update pip and setuptools by default

### ISSUE THREAD

**Issue by fschulze** [pypa/virtualenv#1044]
Virtualenv should install the latest versions of pip and setuptools by default and only use the bundled versions via an option. One reason for that is this: https://github.com/kennethreitz/requests/issues/4006

I think it's important to still have the bundled packages, as that allows for offline installations.

**Comment by dstufft** [comment]
This is the case since uh, virtualenv 15 I think?

**Comment by fschulze** [comment]
Ok, didn't look far enough in the changelog and was fooled by my local devpi installation which caches the downloads, and the changelog entries which show the updated pip/setuptools versions.

It's in since 14.0.1 (2016-01-21):
- Upgrade from pip 8.0.0 to 8.0.2.
- Fix the default of --(no-)download to default to downloading.

Thanks for that!
