### ISSUE TITLE
virtualenv force using pypy when installed

### ISSUE THREAD

**Issue by royir** [pypa/virtualenv#1046]
when pypy is installed virtualenv force using it (ubuntu 16.04):

{noformat}
rm -rf venv && virtualenv venv && . venv/bin/activate &&pip install -r requirements.txt .
New pypy executable in venv/bin/pypy

sudo apt remove -y pypy
rm -rf venv && virtualenv venv
bash: /usr/local/bin/virtualenv: /usr/bin/pypy: bad interpreter: No such file or directory
{noformat}

**Comment by asottile** [comment]
It looks like you (at some point) ran `sudo pypy -m pip install virtualenv --upgrade` (this is the only way I could think that you would get virtualenv at `/usr/local/bin/virtualenv` with a `/usr/bin/pypy` shebang.

You can probably fix your situation with `sudo pip uninstall virtualenv` and `sudo pip install virtualenv`

I wouldn't suggest using `pip` with `sudo`, but it looks like you've already crossed that bridge
