### ISSUE TITLE
virtualenv is not compatible with this system or executable

### ISSUE THREAD

**Issue by ivf777** [pypa/virtualenv#1051]
I deleted old virtualenv "my3" with command 
rmvirtualenv my3

and I created new virtualenv with command
mkvirtualenv my3 -p python3

I have 3 errors:

Running virtualenv with interpreter /home/myname/anaconda3/bin/python3
Using base prefix '/home/myname/anaconda3'
New python executable in /home/myname/.virtualenvs/my3/bin/python3
Also creating executable in /home/myname/.virtualenvs/my3/bin/python
/home/myname/.virtualenvs/my3/bin/python3: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /home/myname/.virtualenvs/my3/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/home/myname/.virtualenvs' (should be '/home/myname/.virtualenvs/my3')
ERROR: virtualenv is not compatible with this system or executable

What can I do to create new virtualenv "my3"?

P.S.
I have Ubuntu 16.04

**Comment by gst** [comment]
For python3 it s recommended to use `venv` module. It s builtin in python3.

**Comment by altendky** [comment]
Recommended by some.  Others like the 2/3 compatibility and separation from core of virtualenv.

But, is this a dup of #1050?  Also, isn't conda what anaconda provides as an alternative?

**Comment by yazabaza** [comment]
I have the same issue on Mac OS 10.12.6 and virtualenv 15.1.0:

```
RonMacAir-4:~ r$ virtualenv --system-site-packages /Users/r/tf13py27
Using base prefix '/Users/r/anaconda'
New python executable in /Users/r/tf13py27/bin/python
dyld: Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/r/tf13py27/bin/python
  Reason: image not found
ERROR: The executable /Users/r/tf13py27/bin/python is not functioning
ERROR: It thinks sys.prefix is '/Users/r' (should be '/Users/r/tf13py27')
ERROR: virtualenv is not compatible with this system or executable
```
This might have something to with Anaconda. I successfully created virtualenv environments before installing Anaconda, and now I cannot.

**Comment by altendky** [comment]
@yazabaza maybe try specifying the python executable you want to use via `-p`.  It looks like it's now using your Anaconda Python instead of whatever you had before based on the base prefix given.

**Comment by yazabaza** [comment]
Yes, pointing to the original python interpreter fixed it. Thanks!

**Comment by wizardboy2010** [comment]
I used this in ubuntu
`virtualenv --system-site-packages -p python3 ~/tensorflow`

my error is
`Running virtualenv with interpreter /home/user/anaconda3/bin/python3`
`Using base prefix '/home/user/anaconda3'`
`New python executable in /home/user/tensorflow/bin/python3`
`Also creating executable in /home/user/tensorflow/bin/python`
`/home/user/tensorflow/bin/python3: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory`
`ERROR: The executable /home/user/tensorflow/bin/python3 is not functioning`
`ERROR: It thinks sys.prefix is '/home/user' (should be '/home/user/tensorflow')`
`ERROR: virtualenv is not compatible with this system or executable`


How to overcome this

**Comment by altendky** [comment]
@wizardboy2010 are you trying to use virtualenv with your anaconda python?  If so, I thought conda was meant for envs with anaconda.  If not, it's finding your anaconda python and you need to specify your regular system python instead.  Anaconda seems to have put itself earlier in the $PATH so python3 points to it.

**Comment by everttrollip** [comment]
If you are still struggling, and experiencing this issue:

`ERROR: virtualenv is not compatible with this system or executable`

Have you tried installing virtualenv with conda and trying again?

`conda install virtualenv`

**Comment by FourSpaces** [comment]
I also encountered this problem, my environment is anaconda python,
Uninstall virtualenv using pip, install virtualenv using conda,
`pip uninstall virtualenv`
`conda install virtualenv`
Virtualenv can be used normally

**Comment by vesellov** [comment]
in my `venv/lib/python3.6/site-packages/virtualenv.py` after line 1118 i added: `prefix = os.path.abspath(prefix)`   and it started working on my MacOS Sierra

**Comment by axiaoxin** [comment]
I ceate virtualenv in a dir which named like `test.2018-08-13_20:16:01` will fail, normal dir name is ok.
```
New python executable in /data/srv/test.2018-08-13_20:16:01/test/bin/python
ImportError: No module named site
ERROR: The executable /data/srv/test.2018-08-13_20:16:01/test/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/data/srv/test.2018-08-13_20:16:01' (should be u'/data/srv/test.2018-08-13_20:16:01/test')
ERROR: virtualenv is not compatible with this system or executable
```

**Comment by jandog8990** [comment]
So I'm having the same problem but I don't think it's an Anaconda thing, I've installed Py3.5 standalone with the latest pip and virtualenv and I get the following errs:

Running virtualenv with interpreter /usr/bin/python
Using base prefix '/System/Library/Frameworks/Python.framework/Versions/3.5'
New python executable in /*/*/PythonInstalls/venv/bin/python
ERROR: The executable /*/*/PythonInstalls/venv/bin/python is not functioning
ERROR: It thinks sys.prefix is '/System/Library/Frameworks/Python.framework/Versions/3.5' (should be '/*/*/PythonInstalls/venv')
ERROR: virtualenv is not compatible with this system or executable

Has anyone solved this without the need for Anaconda? That's a whole set of probs I'm not willing to try at the moment

**Comment by gaborbernat** [comment]
Hmm feels like a problem with the system python of Mac. Can you replicate with the brew one, or the official one with python.org?

**Comment by jandog8990** [comment]
@gaborbernat Hey so I finally got it, instead of using virtualenv executable use the pyvenv for Mac users! 

$ pyvenv --system-site-packages ./venv
