### ISSUE TITLE
Virtualenv should accept a -i or similar flag to allow for custom PyPI servers

### ISSUE THREAD

**Issue by bertjwregeer** [pypa/virtualenv#1052]
Due to a bug in setuptools 36, our CI infrastructure was unable to build new wheels inside of a virtualenv.

I did not realise that it would automatically download and install the latest version from pypi, it would be nice if I could set the PyPI server I'd like to retrieve the packages from instead of using the default pypi.

**Comment by bertjwregeer** [comment]
Related to: https://github.com/pypa/setuptools/issues/1042

**Comment by asottile** [comment]
You can export `PIP_INDEX_URL` as a workaround

**Comment by josephtate** [comment]
The workaround works well.

**Comment by bertjwregeer** [comment]
Thank you stalebot for reminding me about this incident that happened almost two years ago.

**Comment by gaborbernat** [comment]
Yeah, I would say works as designed. By default we take what comes from pip.conf, users can override it by setting the ``PIP_INDEX_URL`` as @asottile pointed it out.
