### ISSUE TITLE
Stop recommending usage of sudo pip in installation documentation

### ISSUE THREAD

**Issue by nanonyme** [pypa/virtualenv#1061]
Please suggest users to use pip --user instead of sudo pip to install virtualenv in https://virtualenv.pypa.io/en/stable/installation/ ; latter can break the system completely and runs setup.py from PyPI as root when pip doesn't support wheels

**Comment by altendky** [comment]
Could also provide a list of system packages for various distributions.

* Ubuntu
  * https://packages.ubuntu.com/artful/virtualenv
  * https://packages.ubuntu.com/artful/python-virtualenv
  * https://packages.ubuntu.com/artful/python3-virtualenv
* Debian
  * https://packages.debian.org/stretch/virtualenv
  * https://packages.debian.org/stretch/python-virtualenv
  * https://packages.debian.org/stretch/python3-virtualenv
* Fedora
  * https://apps.fedoraproject.org/packages/python-virtualenv
  * https://apps.fedoraproject.org/packages/python3-virtualenv
* Arch
  * https://www.archlinux.org/packages/extra/any/python2-virtualenv/
  * https://www.archlinux.org/packages/extra/any/python-virtualenv/
* SUSE
  * https://software.opensuse.org/package/python-virtualenv
  * https://software.opensuse.org/package/python3-virtualenv

Pretty easy to guess but...  And yes, I do realize that you don't need to match the virtualenv Python version to your target.  Just providing all links.

**Comment by nanonyme** [comment]
Won't fix? Really?

**Comment by pfmoore** [comment]
@nanonyme I agree, we shouldn't be recommending `sudo`. Can you provide a PR? Note that I do *not* think we should try to offer system-specific install commands, that's not the role of the virtualenv documentation.
