### ISSUE TITLE
virtualenvwrapper_absolutepath returns incorrect path (git bash on Windows)

### ISSUE THREAD

**Issue by xloggr** [pypa/virtualenv#1075]
Environment: Windows 10, git bash, python 3.6.2

The original issue occurred when I was creating a new project with the following command:
`> mkproject test`

After the virtualenv has been created I got the following error message

> Creating /c/Users/XYZ/Projects/test
> Cannot associate virtualenv with "C:\c\Users\XYZ\Projects\test", it is not a directory

Running 
`> setvirtualenvproject test $(pwd)`
game me the same error

After looking inside virtualenvwrapper.sh I found out that to get an absolute path the script relies on `virtualenvwrapper_absolutepath` function which in turn uses python code. The problem is that python installed on Windows knows nothing about bash, so it returns an invalid path.

One workaround is to run setvirtualenvproject from the project directory without specifying it:
`> setvirtualenvproject test`

It works fine but it needs to be done every time a new project is created.

As a quick fix I replaced python code in the `virtualenvwrapper_absolutepath` with the following command:
`realpath "$1"`

`realpath.exe` is installed by git, so it works for me, but may not work in another environment. I am not a UNIX expert so I cannot suggest a permanent fix that will work in both UNIX and Windows/git/bash.

It is a minor issue, but the `virtualenvwrapper_absolutepath` function (and possibly `virtualenvwrapper_expandpath`) may need to be adjusted to work with git bash.

**Comment by pfmoore** [comment]
```virtualenvwrapper_expandpath``` is presumably from the ```virtualenvwrapper``` project (where ```mkproject```comes from) so you should report this issue there. But be aware that virtualenvwrapper is a Unix project, so they may not support windows or git bash, and hence they may simply say that this usage isn't supported.

**Comment by xloggr** [comment]
Oops, my bad :) - I intended to post it to the virtualenvwrapper bug list.
Thanks for pointing it out.
