### ISSUE TITLE
Not able to install anything using pip inside virtualenv

### ISSUE THREAD

**Issue by monark12** [pypa/virtualenv#1076]
When I activate a virtualenv using source activate, inside that environment, pip is not working. Whenever I try to install something I get an error saying "Could not find a version that satisfies ...". 
Pip is working fine outside the virtualenv. What should I do. Please help

**Comment by gst** [comment]
Please give more infos / context.

Can you show copy/paste entirely commands and outputs when you succeed with normal pip and when it fails within virtualenv in your terminal/shell ?
