### ISSUE TITLE
Wheel 0.30.0 no longer supports Python 2.6 - should virtualenv know this?

### ISSUE THREAD

**Issue by babineaum** [pypa/virtualenv#1088]
Hi folks,

I ran across an issue this past week. Wheel version 0.30.0 no longer supports python 2.6. you can see this here 
https://pypi.python.org/pypi/wheel/0.30.0#downloads
What this means is that if you start a virtualenv using the 2.6 binary and forget to use "--no-download", virtualenv will download the latest and greatest version of wheel, 0.30.0 which breaks your env. 

Should virtualenv know this and circumvent the situation by default to requiring --system-site-packages be set?

**Comment by ssbarnea** [comment]
Are you sure this is not a bug in wheel itself? I think this newer version should not be advertised as available to python2.6. Any idea on how to avoid it?

**Comment by gaborbernat** [comment]
We no longer support Python 2.6 either.
