### ISSUE TITLE
virtualenvwrapper  per user issue, would get `Permission denied` if installed by root.

### ISSUE THREAD

**Issue by eromoe** [pypa/virtualenv#1091]
Hi,

The flow is
1. use root to install virtualenvwrapper
2. su another user, add .bashrc
```
export WORKON_HOME=$HOME/.virtualenvs
source `which virtualenvwrapper.sh`
```
3. source .bashrc , would show error:  (would show everytime su to this user)

```
mkdir: cannot create directory ‘/root’: Permission denied
virtualenvwrapper.user_scripts creating /root/.virtualenvs/initialize
virtualenvwrapper.user_scripts creating /root/.virtualenvs/premkproject
```

4. however  `mkvirtualenv test`  , `workon test` , `pip install  xxx` are fine.
5. but when I install a local project,  it got wrong, can not import sub module.

**Comment by pfmoore** [comment]
This is an issue with virtualenvwrapper, not virtualenv. Please report it to that project.
