### ISSUE TITLE
--relocatable does not point activate script to the correct path

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#11]
Using Ubuntu 10.04,  --relocatable works if I directly invoke the python binary or the setuptools-generated scripts.  However, bin/activate still reflects the old path:

```
> pwd
/home/jhammel
> virtualenv.py foo
New python executable in foo/bin/python
Installing setuptools............done.
> virtualenv.py --relocatable foo
Making script foo/bin/easy_install relative
Making script foo/bin/easy_install-2.6 relative
Making script foo/bin/pip relative
> mv foo bar
> cd bar
> . bin/activate
(foo)> echo $VIRTUAL_ENV
/home/jhammel/foo
(foo)> which python
/usr/bin/python
(foo)>
```

This is because VIRTUAL_ENV is set to an absolute path in the script.  Instead, this should be made relative when --relocatable is called.  

Since the activate script must be sourced, it is a bit more complicated to get the path than just (e.g.) `dirname $0`.  The following seems to work in bash:

```
command=$(history 1) # this should go at the top of the file
parent_path() {
DIRECTORY=$(dirname ${!#})
cd $DIRECTORY/..
pwd
}
VIRTUAL_ENV=$(parent_path $command)
```

If this meets with your approval, Ian, I'm glad to write a patch.

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/37
- Originally Reported By: Jeff Hammel
- Originally Created At: 2010-05-05 19:48:03

**Comment by arizvisa** [comment]
Adding a reference to the newest issue #1067 related to this to help consolidate efforts on solving this half-decade old problem with the activation scripts.

**Comment by adah1972** [comment]
> This is what I am using:
> 
> ```
> VIRTUAL_ENV="$(dirname $(dirname $(readlink --canonicalize --no-newline
> ```
> 
> $BASH_SOURCE)))"
> 
> or with the short options
> 
> ```
> VIRTUAL_ENV="$(dirname $(dirname $(readlink -f -n $BASH_SOURCE)))"
> ```

Using `readlink` could be problematic, as it has different command-line options between Linux, BSD/macOS, and potentially other Linux flavours.

**Comment by arizvisa** [comment]
@adah1972, issue #1067 is the latest one. This issue is from 2012, #1067 is from 2017.

**Comment by adah1972** [comment]
@arizvisa Thanks. I commented in #1067 too.
