### ISSUE TITLE
Virtualenv hangs when initiate inside folder with space, e.g inside "flask\ restful/" folder

### ISSUE THREAD

**Issue by heygema** [pypa/virtualenv#1102]
it hangs, for long time except I changed the folder name to something like flaskrestful.
thank you :)

**Comment by ssbarnea** [comment]
Interesting remark, maybe you can include some extra logs. I am curious because it sounds similar with https://github.com/pypa/virtualenv/issues/1104 which I just raised. Still, In my case it seems not to be related to spaces.

**Comment by pradyunsg** [comment]
Hi @heygema!

It would be awesome if you provide some output and more details about how and when this happens -- your OS, virtualenv version, pip version, exact commands run, the output of the commands, tracebacks if any and anything else you think would be useful.
