### ISSUE TITLE
Package using setup.cfg metadata fails within virtualenv due to outdated setuptools

### ISSUE THREAD

**Issue by ThimoNeubauer** [pypa/virtualenv#1121]
I'm currently in the process of refactoring a lot of Python code into multiple proper Python packages. What I noticed quickly is that each modules "setup.py" was a slightly modified copy&paste. Fortunately I found that setuptools allows to factor everything variable into a separate setup.cfg:

  https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

The feature needs a setuptools >= December 2016. Not a problem in early 2018 I thought ;-)

When I install the package inside a virtual environment (e.g. to run tox tests) all kinds of odd effects happen. This is a demo of the effect:

```
E:\temp>mkdir venv

E:\temp>c:\Python36\python.exe -m venv venv

E:\temp>venv\Scripts\activate
(venv) E:\temp>pip install e:\Dev\Pype\cstutil\dist\cstutil-0.0.zip
Processing e:\dev\pype\cstutil\dist\cstutil-0.0.zip
Installing collected packages: UNKNOWN
  Running setup.py install for UNKNOWN ... done
Successfully installed UNKNOWN-0.0

(venv) E:\temp>pip install --upgrade setuptools
Collecting setuptools
  Using cached setuptools-38.4.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
Successfully installed setuptools-38.4.0

(venv) E:\temp>pip install e:\Dev\Pype\cstutil\dist\cstutil-0.0.zip
Processing e:\dev\pype\cstutil\dist\cstutil-0.0.zip
Collecting six (from cstutil==0.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=30.3.0 in e:\temp\venv\lib\site-packages (from cstutil==0.0)
Installing collected packages: six, cstutil
  Running setup.py install for cstutil ... done
Successfully installed cstutil-0.0 six-1.11.0
```

As you can see the old setuptools version just ignores the metadata. What makes matters worse is that the requirement "setuptools >= 30.3.0" of the package also doesn't work! 

After several "pip install --upgrade setuptools" runs and a lot of scratching my head I discovered that the old setuptools come from within virtualenv.  Is there a chance that the version can be bumped?

Using "install_requires" as parameter in setup.py would allow me to express the setuptools-dependency in a way setuptools 28 understands. Then however setting the (package specific) list of other dependencies would need to go into setup.py again -- defying the whole idea of pushing this information into setup.cfg.

**Comment by pfmoore** [comment]
> `c:\Python36\python.exe -m venv venv`

You're using the stdlib venv, not virtualenv. To report this you should go to https://bugs.python.org. But the version installed when you set up a new virtual environment will always potentially be out of date - running `python -m pip install -U setuptools pip` should be pretty much the first thing you do in any new virtual environment.

**Comment by ThimoNeubauer** [comment]
True: I'm using the stdlib venv module. However what I observed is that it always installed setuptools 28, irregardless of major Python version (2.7.14 or 3.6.4) or OS (Windows 10, Ubuntu LTS). Thus I searched the system where the old setuptools can even come from and the only place I found were the .whls shipped with virtualenv.

Or is this just a coincidence?

**Comment by pfmoore** [comment]
No, I believe that's correct. It installs the wheels shipped with the venv package. If you are asking that it try to install from the web, only falling back to the supplied wheels if the user has no web access, then that would be a feature request to submit on bugs.python.org for Python 3.8 (the 3.7 feature freeze is only a few weeks away, so you're too late for 3.7).

**Comment by ThimoNeubauer** [comment]
Ok, I'll try that.

Still though the ancient setuptools wheel in virtualenv could be updated to a recent version ;-)
