### ISSUE TITLE
time to tag a release?

### ISSUE THREAD

**Issue by anthrotype** [pypa/virtualenv#1122]
The last one was more than a year ago, in November 2016.
Lots of bugs have been fixed, including this one about PYTHON3.DLL not being copied to the venv's Scripts folder on Windows (https://github.com/pypa/virtualenv/pull/1083).

cffi recently added support for Py_LIMITED_API so all extension modules compiled with latest cffi links with PYTHON3.DLL and import fails from within a virtualenv.

https://bitbucket.org/cffi/cffi/issues/355/importerror-dll-load-failed-on-windows

cc @reaperhulk

**Comment by anthrotype** [comment]
@pfmoore sorry if I insist. Do you an ETA for when the next virtualenv release is going to be?

**Comment by anthrotype** [comment]
cffi had to temporarily revert support for Py_LIMITED_API on Windows because virtualenv does not make python3.dll available to virtual environments yet:
http://cffi.readthedocs.io/en/latest/whatsnew.html#v1-11-4

**Comment by pfmoore** [comment]
@anthrotype No, sorry, we don't.

**Comment by anthrotype** [comment]
Thanks. Please let me know if there is something I can do to move this forward.

**Comment by ssbarnea** [comment]
@anthrotype read these threads and you will get an idea about the maintenance status of virtualenv:
* https://groups.google.com/forum/#!topic/python-virtualenv/5xKG8KoBl6g 
* https://groups.google.com/forum/#!topic/pypa-dev/8iVHDOqsj9M

**Comment by nanonyme** [comment]
@pfmoore unless the idea is to force a fork, please, seriously, there needs to be something concrete of a release criteria that community volunteers can help fulfil so a release can be done

**Comment by anthrotype** [comment]
> unless the idea is to force a fork

I believe the idea is to let it rot until python2 reaches end of life and python3 (-m venv) becomes the norm.
Although we all wish this to happen sooner than later, the reality is many of us are stuck with python2.7 for some reason or another.

**Comment by nanonyme** [comment]
Sounds like a very CPython-centric point of view which is likely to result in a fork sooner or later.

**Comment by anthrotype** [comment]
Ah there was a release last week! I was looking forward to that one 👍 
Although the git tag seems to be missing, but at least is on pypi.
Closing this then, thank you.
