### ISSUE TITLE
Support for custom environment variables

### ISSUE THREAD

**Issue by NZSmartie** [pypa/virtualenv#1124]
Hi, virtualenv doesn't provide a mechanism for setting up environment variables and tearing them down again after deactivate. 

A use case would be allowing setting of `PYTHON_EGG_CACHE` to `$VIRTUAL_ENV/.python-egg` (related issue: #459).

I'm aware there is the possibility of using `autoenv` or `direnv` to setup environment variabls for me. but they fall outside the scope of invoking `$VIRTUAL_ENV/bin/activate` and would require manually modifying the activate file if I wish to keep it all contained within a virtual env.

**Comment by Ekultek** [comment]
Support this, it would be a really good idea. You could just add a way to read env variables from a config file to easily implement it

**Comment by warnes** [comment]
I would really appreciate this feature.  It would allow me to consolidate multiple configure files into venv.

For my purposes, it would be ideal to placing a file, say `env.txt` in the venv bin directory with definitions a standard format:
```
VARNAME=value
OTHERVAR=othervalue
```
and then having the activate and deactivate scripts process this file to set/unset the specified variables.

**Comment by m1racoli** [comment]
This would be really nice. We have some environment variables, which are virtual env specific, and would have liked to be set when activating the environment.

Those variables could be defined on environment creation like this for example:

```bash
virtualenv --env VARNAME=value ${VENV_PATH}
```

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
