### ISSUE TITLE
Deactivate script shadowed

### ISSUE THREAD

**Issue by petrmvala** [pypa/virtualenv#1165]
Actually, the problem was all mine. I figured it out during writing of this issue, but let me post it anyway. 

The root of all evil was, that I had forgotten two aliases in my `~/.zshrc`, these:
```bash
alias activate='source /opt/anaconda/bin/activate'
alias deactivate='source /opt/anaconda/bin/deactivate'
```
And here's what it did:

---------------------------------------------
#### System & package info:

 * **OS**: High Sierra 10.13.4
 * **uname**: Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018
root:xnu-4570.51.1~1/RELEASE_X86_64 i386
 * **zsh**: 5.3 (x86_64-apple-darwin17.0)
 * **virtualenv**: 15.2.0
 * **virtualenvwrapper**: 4.8.2
---------------------------------------------

### virtualenvwrapper

Installed virtualenvwrapper via pip, added following to `~/.zshrc`:
```bash
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/devel
source /Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenvwrapper.sh
```

Restarted zsh (got messages from virtualenvwrapper.user_scripts).
Executed `mkvirtualenv test2` and got this:
```bash
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/pv/.virtualenvs/test2/bin/python3.6
Also creating executable in /Users/pv/.virtualenvs/test2/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/pv/.virtualenvs/test2/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/pv/.virtualenvs/test2/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/pv/.virtualenvs/test2/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/pv/.virtualenvs/test2/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/pv/.virtualenvs/test2/bin/get_env_details
source:unset:32: no such hash table element: deactivate
source:12: command not found: virtualenv_deactivate
source:12: command not found: virtualenv_deactivate
source:12: command not found: virtualenv_deactivate
... (truncated)
```
This repeated itself, so I had to kill it. The environment `test2` got activated nevertheless and when i executed `deactivate`, it froze. So I went on to try just virtualenv.

### virtualenv

executed `virtualenv venv`, got
```bash
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/pv/devel/venv/bin/python3.6
Also creating executable in /Users/pv/devel/venv/bin/python
Installing setuptools, pip, wheel...done.
```
`cd`'d into venv, following is directory listing of `.../venv/bin/`
```bash
drwxr-xr-x  16 pv  staff   512B Apr 19 14:31 .
drwxr-xr-x   7 pv  staff   224B Apr 19 14:31 ..
-rw-r--r--   1 pv  staff   2.0K Apr 19 14:31 activate
-rw-r--r--   1 pv  staff   1.0K Apr 19 14:31 activate.csh
-rw-r--r--   1 pv  staff   2.1K Apr 19 14:31 activate.fish
-rw-r--r--   1 pv  staff   1.1K Apr 19 14:31 activate_this.py
-rwxr-xr-x   1 pv  staff   252B Apr 19 14:31 easy_install
-rwxr-xr-x   1 pv  staff   252B Apr 19 14:31 easy_install-3.6
-rwxr-xr-x   1 pv  staff   234B Apr 19 14:31 pip
-rwxr-xr-x   1 pv  staff   234B Apr 19 14:31 pip3
-rwxr-xr-x   1 pv  staff   234B Apr 19 14:31 pip3.6
lrwxr-xr-x   1 pv  staff     9B Apr 19 14:31 python -> python3.6
-rwxr-xr-x   1 pv  staff   2.3K Apr 19 14:31 python-config
lrwxr-xr-x   1 pv  staff     9B Apr 19 14:31 python3 -> python3.6
-rwxrwxr-x   1 pv  staff    25K Apr 19 14:31 python3.6
-rwxr-xr-x   1 pv  staff   231B Apr 19 14:31 wheel
```
When executed `source bin/activate`, got this again
`source:unset:32: no such hash table element: deactivate`
Environment activated, checked via `pip list`. When executed `deactivate` the environment actually deactivated, got `source:unset:32: no such hash table element: deactivate` message again, and then when tried activating it again, via `source bin/activate`, the message was same:
`source:unset:32: no such hash table element: deactivate`
with the difference that this time the environment didn't activate.

### Summary
I know that this is probably a one-of-a-kind problem due to my sloppiness, but given the cryptic behavior, I had no idea where to look for problems, and tried going through stackoverflow fruitlessly. I actually figured it out only when I tried to activate the environment for the second time and it didn't work. Then it was a short path to `which deactivate`.
It would be cool if there was any check for command shadowing, although I am not sure whether it would be reasonably feasible. Perhaps a note in the docs would do.

**Comment by gaborbernat** [comment]
Thanks 👍 I would say works as expected.
