### ISSUE TITLE
COSMETIC: On Windows, --prompt adds a space to the resulting prompt after its argument; doesn't add space on Linux

### ISSUE THREAD

**Issue by bskinn** [pypa/virtualenv#1168]
When creating a new virtualenv with the `--prompt` option, on Windows a space is automatically added between the `--prompt=` value and the tail of the prompt:

```
C:\temp>virtualenv env --prompt="(myenv)"
...

C:\temp>env\scripts\activate

(myenv) C:\temp> 
```

On Debian stretch, a space is not added:

```
me@mycomp:~$ virtualenv env --prompt="(myenv)"
...

me@mycomp:~$ source env/bin/activate

(myenv)me@mycomp:~$ 
```

If auto-insertion of a space is desired behavior, it should be a simple fix: adding a space [here in `activate.sh`](https://github.com/pypa/virtualenv/blob/2f5c75bd4762463e904aa1c06ccba29dd817e940/virtualenv_embedded/activate.sh#L59), before the `$PS1`.

If this is desired, I can create a PR.

-----

**EDIT:** Per discussion below, the decision has been made to ***remove*** the mandatory space after the custom prompt string, for all shells.

**Comment by gaborbernat** [comment]
@bskinn sure, feel free to do so.

**Comment by asottile** [comment]
maybe I'm being contrary, but I actually think the windows behaviour is incorrect here.  After adding a space it makes it impossible to produce a prompt _without_ a space.  However you can make a prompt with a space by doing `--prompt='(foo) '`

**Comment by bskinn** [comment]
@asottile Very good point. At the time I composed this issue, I hadn't really tried to think of use-cases where a required space would be undesirable... but, for example, a forced space prevents crafting a prompt like:

```
envname-C:\git\project> 
```

For how ***I*** construct my prompts, I would like the space to be there by default.  But, you're right, it's far more flexible *not* to mandate the trailing space. I'm now inclined to go the other way with it, and remove the default space on Windows (as long as `cmd` allows its removal...).

@gaborbernat?

**Comment by gaborbernat** [comment]
I can see peoples complaining once we remove, but let's bite the bullet. Let's remove it.

**Comment by bskinn** [comment]
Ok, I will revise the PR to **REMOVE** the mandated space from both Windows [`cmd`](https://github.com/pypa/virtualenv/blob/d683eaeb97895d90ba685dc2708774082d0e0e3f/virtualenv_embedded/activate.bat#L12) and [`bash`](https://github.com/pypa/virtualenv/blob/d683eaeb97895d90ba685dc2708774082d0e0e3f/virtualenv_embedded/activate.sh#L59) templates, and add tests for both to check for the lack of the trailing space.

It looks like a mandated space should similarly be removed from the [`csh`](https://github.com/pypa/virtualenv/blob/d683eaeb97895d90ba685dc2708774082d0e0e3f/virtualenv_embedded/activate.csh#L34) and [PowerShell](https://github.com/pypa/virtualenv/blob/d683eaeb97895d90ba685dc2708774082d0e0e3f/virtualenv_embedded/activate.ps1#L57) templates.  (If new tests are desired for these shells, I'm not sure how to add them so that they integrate with the CI.)

OTOH, [`fish`](https://github.com/pypa/virtualenv/blob/d683eaeb97895d90ba685dc2708774082d0e0e3f/virtualenv_embedded/activate.fish#L90) looks ok to me; and, if I read the [`xonsh`](https://github.com/pypa/virtualenv/blob/d683eaeb97895d90ba685dc2708774082d0e0e3f/virtualenv_embedded/activate.xsh) template correctly, it doesn't even mess with the prompt, and so doesn't need to be changed.

**Comment by bskinn** [comment]
Just to raise the possibility...what if this change turns out to be a https://xkcd.com/1172/ ?  If, say, someone is inspecting %PROMPT% &c to sniff which venv is active.

**Comment by asottile** [comment]
Seems unlikely when $VIRTUAL_ENV is a thing

**Comment by bskinn** [comment]
Now that I look at it, I think `activate.csh` actually ***ignores*** `--prompt`. The line of code I linked to above appears actually just to always use the environment name as the prefix.

Is this desired behavior?

**Comment by gaborbernat** [comment]
I would say should be revised 👍
