### ISSUE TITLE
Not working: pip install virtualenv

### ISSUE THREAD

**Issue by pramitbiswas** [pypa/virtualenv#1172]
I was trying to install `virtualenv` using `pip`. It shows `ConnectTimeoutError`. While finding the problem files.pythonhosted.org seems not responding. Manual download of `virtualenv-15.2.0-py2.py3-none-any.whl` (SHA256: `e8e05d4714a1c51a2f5921e62f547fcb0f713ebbe959e0a7f585cc8bef71d11f`) from [here](https://pypi.org/project/virtualenv/#files) or [here](https://pypi.org/simple/virtualenv/) is also not possible.

**Comment by Mirona** [comment]
Try this one: 
https://packaging.python.org/guides/installing-using-pip-and-virtualenv/#installing-virtualenv

![image](https://user-images.githubusercontent.com/5847160/39952809-c378a8c4-5553-11e8-8598-a743603c9e38.png)

**Comment by gaborbernat** [comment]
You're probably behind a proxy, either way feels a network issue so not something actionable for us.
