### ISSUE TITLE
EPERM when calling os.chflags() on a file with SF_RESTRICTED set

### ISSUE THREAD

**Issue by indygreg** [pypa/virtualenv#1173]
On macOS 10.13, some files in `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload` (which `virtualenv.py` may attempt to copy) have the `SF_RESTRICTED` stat file set. When `shutil.copystat()` is eventually called, it will attempt to carry over `SF_RESTRICTED` as part of calling `os.chflags()`. This will raise an `OSError` with `EPERM` as the error code because normal users can't set the `SF_RESTRICTED` stat flag.

`SF_RESTRICTED` is not defined in CPython - even on the `master` branch as of this writing. Its value is `0x80000` (`2^19`). The Python standard library is blissfully unaware of this flag's existence.

One potential workaround for this is to monkeypatch `os.chflags()` in `virtualenv.py` to drop `SF_RESTRICTED` from the flags. This looks to be the approach we're going to take at Mozilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1459071). (Having `SF_RESTRICTED` set shouldn't matter for the virtualenv's copied files.)

**Comment by gaborbernat** [comment]
As no one else seems to requested this, I'll close it as won't fix for now. Seems a dangerous thing to do, so we'll defer for now. Not sure why those are marked restricted, I feel they shouldn't be and if anything should be fixed probably in core python.
