### ISSUE TITLE
Virtualenv --system-site-packages does not seem to check Mac OS ~/Library for the user site directory

### ISSUE THREAD

**Issue by qqrs** [pypa/virtualenv#1177]
While setting up a Python environment on a new computer, my goal was to be able to install larger packages (numpy, scikit-learn, ...) into the user site directory with `pip install --user ...` and create many virtualenvs using the `--system-site-packages` flag. These virtualenvs would share the large packages, and would additionally have their own unique package dependencies.

In the past, I've frequently abused `sudo pip ...` out of necessity, but I believe I've succeeded this time without it.

Virtualenv has been a tremendously helpful piece of my Python workflow (many thanks!) so I'm creating this issue in case it might be possible for the virtualenv developers to streamline the process and save others the trial-and-error. (Of course, it's also very possible I have a quirk in my setup or there's an easier way that I've missed.)

----

I was happy to find this Github issue indicating that `virtualenv --system-site-packages ...` does include the user site directory: https://github.com/pypa/virtualenv/issues/1005

-----

I installed Python using Homebrew, following the Mac OS instructions [here](https://chriswarrick.com/blog/2017/07/03/setting-up-a-python-development-environment/#macos).

After doing so, `pip install --user` installed packages to `~/Library/Python/2.7/lib/python/site-packages`.

But it appears that virtualenv is only looking in `~/.local/lib/python2.7/site-packages/`. [PEP 370](https://www.python.org/dev/peps/pep-0370/#mac-os-x-notes) indicates that both are valid user site directories on Mac OS. (I am out of my element here, but I do see that [cpython site.py](https://github.com/python/cpython/blob/2.7/Lib/site.py#L258) has substantial differences from [virtualenv site.py](https://github.com/pypa/virtualenv/blob/master/virtualenv_embedded/site.py#L309).)

The solution I found was to create a `.pth` file pointing from `~/.local/lib/python2.7/site-packages/` to `~/Library/Python/2.7/lib/python/site-packages`.

----

Outside virtualenv. Numpy found.
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199
$ which python
/usr/local/bin/python
$ which pip
/usr/local/bin/pip
$ env | grep PYTHON
$ env | grep PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ python -V
Python 2.7.15
$ python3 -V
Python 3.6.5
$ pip -V
pip 10.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
$ pip3 -V
pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
$ virtualenv --version
15.2.0
$ python -m site --user-base
/Users/zzz/Library/Python/2.7
$ python -m site --user-site
/Users/zzz/Library/Python/2.7/lib/python/site-packages
$ pip freeze | grep numpy
numpy==1.14.3
$ pip show numpy | grep Location
Location: /Users/zzz/Library/Python/2.7/lib/python/site-packages
```

Make a virtualenv.
```
$ mkvirtualenv --system-site-packages testenv
New python executable in /Users/zzz/.virtualenvs/testenv/bin/python2.7
Also creating executable in /Users/zzz/.virtualenvs/testenv/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/zzz/.virtualenvs/testenv/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/zzz/.virtualenvs/testenv/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/zzz/.virtualenvs/testenv/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/zzz/.virtualenvs/testenv/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/zzz/.virtualenvs/testenv/bin/get_env_details
```

Inside virtualenv. Numpy not found.
```
(testenv) $ which python
/Users/zzz/.virtualenvs/testenv/bin/python
(testenv) $ which pip
/Users/zzz/.virtualenvs/testenv/bin/pip
(testenv) $ python -m site --user-base
/Users/zzz/.local
(testenv) $ python -m site --user-site
/Users/zzz/.local/lib/python2.7/site-packages
(testenv) $ pip freeze | grep numpy
(testenv) $ pip show numpy
```
Create `.pth` file.
```
(testenv) $ deactivate
$ echo "$HOME/Library/Python/2.7/lib/python/site-packages/" > ~/.local/lib/python2.7/site-packages/Library.pth
```

Inside virtualenv, again. Numpy found.
```
$ workon testenv
(testenv) $ which python
/Users/zzz/.virtualenvs/testenv/bin/python
(testenv) $ python -m site --user-base
/Users/zzz/.local
(testenv) $ python -m site --user-site
/Users/zzz/.local/lib/python2.7/site-packages
(testenv) $ pip freeze | grep numpy
numpy==1.14.3
(testenv) $ pip show numpy | grep Location
Location: /Users/zzz/Library/Python/2.7/lib/python/site-packages
```

**Comment by gaborbernat** [comment]
Can you replicate with latest virtualenv? If so I'll reopen.
