### ISSUE TITLE
broken Python 3.3 support due to wheel

### ISSUE THREAD

**Issue by matejcik** [pypa/virtualenv#1179]
With #1176, Python 3.3 support is broken because wheel 0.31 dropped support.

This means that virtualenv 16.0.0 will install fine on a Python 3.3 config, but then fail to create any virtualenvs.

virtualenv should also declare that it doesn't support 3.3

**Comment by pganssle** [comment]
Yes, this is causing all my Travis tox projects to break.

A post release should be made on 16.0 to update the `requires_python` to exclude 3.3.
