### ISSUE TITLE
Missing libs subdirectory in virtualenv environments on Windows

### ISSUE THREAD

**Issue by campanelli-resonon** [pypa/virtualenv#1182]
I am developing on Windows, and virtualenv does not install any libraries in a `libs` subdirectory under the root directory of the virtualenv. This directory does appear in my default Windows Python installation (e.g., "C:\Python27\libs", as well as in all conda-based virtual environments that I have created. There doesn't appear to be a configuration flag to get virtualenv to install these libraries, which I need (specifically, libs\python27.lib) to link some compiled C code into a .pyd file using SCons.

This is a blocker to using pipenv+virtualenv instead of conda. Am I missing something obvious?

**Comment by gaborbernat** [comment]
@campanelli-resonon please try again with 16.2.0 and if still persist re-open with further details.

**Comment by campanelli-resonon** [comment]
@gaborbernat I just tried again, and I am still hitting this with Python 2.7.15 and virtualenv 16.4.3.

Can you reopen this issue and suggest a workaround?

**Comment by campanelli-resonon** [comment]
There also seems to be a fundamental issue here where virtualenv (and venv in Python 3) do not follow the same directory structure as a "base" Windows 10 Python 2 (or 3) installation.

For example, in the my base Python2 installation, the python.exe is installed at the same level as the `Scripts` directory:
- C:\Python27\python.exe
- C:\Python27\Scripts
but in the virtualenv I created (called Spectronon) I have
- C:\Users\campa\dev\test\Spectronon\Scripts\python.exe
- C:\Users\campa\dev\test\Spectronon\Scripts
This causes headaches in some of our scripts that search for other directories based off of the Python exectuable's location.

conda does not change this directory structure, and our build scripts run as expected in conda virtual environments. conda also installs the `libs` directory containing `python.lib` (with `libs` at the same level as `Scripts`), as mentioned above.

**Comment by campanelli-resonon** [comment]
For posterity, I discovered another unexpected behavior while investigating this, which may/may not be a bug: https://bugs.python.org/issue36383

**Comment by campanelli-resonon** [comment]
Looks like on Windows this missing `libs' directory in the virtual environment is expected, and one can use

```python
distutils.sysconfig.get_config_vars()['LIBDIR']
```

See https://virtualenv.pypa.io/en/latest/changes/?highlight=distutils#v1-3-4

**Comment by gaborbernat** [comment]
I think the rewrite branch, release 20.0.0b2 fixed this.
