### ISSUE TITLE
Expected: virtualenv 16.0.0 does not run correctly on CentOS 6.6 (with Python 2.6.6)

### ISSUE THREAD

**Issue by zfields** [pypa/virtualenv#1184]
I don't know if it is possible or not, but can your pip recipe check to see which Python is installed, then install a compatible version of virtualenv, instead of attempting to install the latest version?

**Comment by gaborbernat** [comment]
We no longer support Python 2.6.

**Comment by zfields** [comment]
I understand you no longer support it. I am asking that you codify that in your pip recipe.

**Comment by gaborbernat** [comment]
what pip recipe? 👍

**Comment by zfields** [comment]
I don't understand python well, but I do see a `pyproject.toml` file that details dependencies.

```
[build-system]
requires = [
    "setuptools >= 40.6.3",
    "wheel >= 0.29.0",
]
...
```

Perhaps there is a way to specify python 3.x as a requirement of `virtualenv`. Then my Python 2.x pip could find the last version that does not require python 3.x. Obviously, this must be interpreted loosely, as it is more of a concept than an implementation description.

**Comment by gaborbernat** [comment]
We already add python requires - https://github.com/pypa/virtualenv/blob/master/setup.cfg#L38 not pip must be though new enough to understand this.
