### ISSUE TITLE
Embedded Python Failed to copy pythonXX.zip

### ISSUE THREAD

**Issue by imben1109** [pypa/virtualenv#1185]
I am using embedded python 3.7 and install pip by get_pip.py.

After that I have modified python37._pth in order to make pip work.

```
python37.zip
.
Lib
Lib\site-packages

# Uncomment to run site.main() automatically
#import site
```

Then install virtualenv by pip 

```
pip install virtualenv
```

And I tried to create a virtual env by 

```
virtualenv env
```

But I have found that not files or folders are copy to env folder and throwing exception.

```
D:\Software\python-3.7.0rc1-embed-win32\Lib\site-packages\virtualenv.py:1041: DeprecationWarning: the imp module is deprecate
cumentation for alternative uses
  import imp
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "D:\Software\python-3.7.0rc1-embed-win32\Lib\site-packages\virtualenv.py", line 2343, in <module>
    main()
  File "D:\Software\python-3.7.0rc1-embed-win32\Lib\site-packages\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "D:\Software\python-3.7.0rc1-embed-win32\Lib\site-packages\virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "D:\Software\python-3.7.0rc1-embed-win32\Lib\site-packages\virtualenv.py", line 1149, in install_python
    writefile(site_filename_dst, SITE_PY)
  File "D:\Software\python-3.7.0rc1-embed-win32\Lib\site-packages\virtualenv.py", line 363, in writefile
    with open(dest, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\temp\\env\\python37.zip\\site.py'
```

**Comment by codejamninja** [comment]
I am getting the same problem

**Comment by gaborbernat** [comment]
I'm seeing an rc1 python build, and this information is missing some details (exact package, etc). Will re-open if someone is able to provide a reproduction against latest release.

**Comment by flooriin-cloud** [comment]
I comment python37.zip line from _pth file and it worked (on Windows). The error about site.py persists but the env was built eventually.

**Comment by codejamninja** [comment]
Could you try python 2 and see what happens? I'm assuming you're on Windows. Windows is the hardest platform to get python working on.

**Comment by codejamninja** [comment]
@qrqhuang can you file this as a new issue?

**Comment by davincif** [comment]
Having the exact same issue where with python embeded for windows. Just the same behavior as described by @codejamninja.
So as long as this issue is already closed, sould I it won't be fixed then? .-.
