### ISSUE TITLE
Some builtin modules should be preimported in site.py on PyPy

### ISSUE THREAD

**Issue by microdog** [pypa/virtualenv#1201]
For PyPy, some built-in modules should be pre-imported in `site.py` to match CPython, or some programs may not be working properly, for example, the Python Console in PyCharm.

What PyPy does currently(L532-539, L545): 

https://bitbucket.org/pypy/pypy/src/314ddd2d83c5e467aed4f64ab4b8b2fc0047540b/lib-python/2.7/site.py?at=default&fileviewer=file-view-default#site.py-532:539,545

The original commits:

https://bitbucket.org/pypy/pypy/commits/1c6dc3e6e70c6fadad60ba9c3990b49c8aaf16bd
https://bitbucket.org/pypy/pypy/commits/f160281ab6613617a49a73129f81d7ef3540755a

**Comment by microdog** [comment]
A quick patch:

https://gist.github.com/microdog/47fc0545c0c3c7abce94c533f91efdda#file-virtualenv_embedded-site-py-patch

and patch to the distributed virtualenv.py(version 16.0.0):

https://gist.github.com/microdog/47fc0545c0c3c7abce94c533f91efdda#file-pypy-preimport-patch

**Comment by gaborbernat** [comment]
@microdog can you create a PR against master?
