### ISSUE TITLE
move python environment between machines

### ISSUE THREAD

**Issue by csskysea** [pypa/virtualenv#1212]
does `virtualenv` support copy python environment from one machine to another?

**Comment by gaborbernat** [comment]
I don't think so, what's your use case?

**Comment by csskysea** [comment]
machine a: python2.7.5 ,use virtualenv create a virtual environment and pip install some packages inside
and i hope to move the virtual environment to machine b which have installed python 2.7.15

**Comment by csskysea** [comment]
I just did a experiment , and active virtual environment in machine b, then check with command `which python` ,it still point to system's python , not virtual environment's python. and `sys.path` not include virtual environment's path. @gaborbernat

**Comment by pradyunsg** [comment]
It's probably going to be easier to `pip download` the packages and use `pip install --find-links` to install them.

**Comment by csskysea** [comment]
@pradyunsg  yes, you're right, but you may need to rename the wheel package name after download them. maybe pip tool does not support it.

**Comment by merwok** [comment]
> and sys.path not include virtual environment's path.

That could be another problem.  Can you test the copied environment without using activate?  For example, can you run `path/to/venv/bin/python` and import modules from the stdlib and the venv site-packages with success?

**Comment by gaborbernat** [comment]
This falls outside of the scope of this project as such will close for now.
