### ISSUE TITLE
upgrade pip 18.1

### ISSUE THREAD

**Issue by tarekelgindy** [pypa/virtualenv#1215]
I've been having issues with virtualenv when I've been trying to run pre-commit on Windows. 
We've been using a pre-commit .yaml file that looks like this:
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      python_version: python3.6
```
and errors were being thrown by pip in virtualenv.
The problems seem to occur because virtualenv is using pip 10.0.1 to download packages, while later versions of pip are required for the build. The latest pip version is 18.1. My solution to the problem was to replace the wheel file `pip-10.0.1-py2.py3-none-any.whl`  in `virtualenv_support`  with the latest pip wheel. I download the latest pip wheel with 
`python -m pip wheel --wheel-dir=. pip`, which downloads `pip-18.1-py2.py3-none-any.whl` and then copied it over to the `virtualenv_support` folder so virtualenv was now using pip 10.0.1. This managed to solve my problem.

I'm not sure exactly what the change is in the latest pip version is that's fixed it but it may relate to [this]( https://github.com/pypa/pip/issues/3905) bug that was fixed in pip 18.0:

I was wondering if you'd be able to update this pip wheel in virtualenv in your next release? Or would it be possible to auto-download the latest pip wheel when installing virtualenv? 

Thanks a lot!

**Comment by pganssle** [comment]
@gaborbernat I think this can be closed now.

**Comment by gaborbernat** [comment]
yes it can
