### ISSUE TITLE
In README, link to webchat for Freenode IRC channels

### ISSUE THREAD

**Issue by brainwane** [pypa/virtualenv#1235]
The `README.rst` file currently *mentions* IRC channels but does not link to them.

Please add links so that

> #pypa on Freenode

links to https://webchat.freenode.net/?channels=%23pypa

and

> #pypa-dev on Freenode

links to https://webchat.freenode.net/?channels=%23pypa-dev .

Thanks.

**Comment by satyajitdam** [comment]
I'm picking this one up.

**Comment by brainwane** [comment]
Closed via #1236. Thanks!
