### ISSUE TITLE
16.1.0 breaks installation using node-vritualenv

### ISSUE THREAD

**Issue by YifeiZuo01** [pypa/virtualenv#1240]
Traceback from windows, but is OS independent, as same issue occured in  Linux, Mac as well.

There is something wrong, but not sure where it locates.

FYI: https://github.com/mjpizz/node-virtualenv/blob/master/lib/virtualenv.js#L237-L246 (node-virtualenv file which raised exception)

```
Finding virtualenv *
Downloading https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz
Unzipping https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz
Creating C:\my-project\node_modules\mbedls\.node-virtualenv
python: can't open file 'virtualenv.py': [Errno 2] No such file or directory
Error: Error while creating virtualenv: exit 2
    at VirtualEnv.<anonymous> (C:\my-projecct\node_modules\virtualenv\lib\virtualenv.js:246:31)    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Workaround:  use 16.0.0 instead will passed.

**Comment by gaborbernat** [comment]
Feels more like a node-virtualenv integration issue than bug on our end 🤔

**Comment by jupe** [comment]
> Feels more like a node-virtualenv integration issue than bug on our end 

Could be. I would like to understand reasons why you think it's not virtualenv issue ?
