### ISSUE TITLE
Custom bootstrap script does not contain extra_text

### ISSUE THREAD

**Issue by rinrinne** [pypa/virtualenv#1244]
Below is how to create custom bootstrap script.
https://virtualenv.pypa.io/en/latest/reference/#creating-your-own-bootstrap-scripts

But created script does not contain extra_text with virtualenv 16.1.0 and master.

```
$ python -c "import virtualenv; print(virtualenv.create_bootstrap_script('HELLOWORLD'))"| grep HELLOWORLD
$
```

Seems expected bootstrap script can be created with virtualenv 16.0.0
```
$ python -c "import virtualenv; print(virtualenv.create_bootstrap_script('HELLOWORLD'))"| grep HELLOWORLD
HELLOWORLD
$
```

**Comment by gaborbernat** [comment]
Thanks for this report, I'll address this.

**Comment by gaborbernat** [comment]
@rinrinne this now has been fixed inside the master and will roll out in a few days with 16.2.
