### ISSUE TITLE
Creating virtualenv with non system-wide python

### ISSUE THREAD

**Issue by Emi1305** [pypa/virtualenv#1246]
Hi all, I'm trying to create a virtualenv using a python3.7 installation inside the virtualenv directory. My steps are as following

```
curl -q https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tar.xz | unxz | tar -x;
cd Python-3.7.1;
./configure --prefix $(pwd)/.. ;
make -s;
make install;
cd ..;
bin/pip3 install --upgrade pip;
bin/pip3 install --upgrade pipenv;
bin/virtualenv -p bin/python3.7 .;
. ./bin/activate;
# Other stuff
```

But I keep getting the following error:

```
Running virtualenv with interpreter bin/python3.7
Please use the *system* python to run this script
Traceback (most recent call last):
  File "/home/mr-x/froxy/lib/python3.7/site-packages/virtualenv.py", line 2462, in <module>
    main()
  File "/home/mr-x/froxy/lib/python3.7/site-packages/virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "/home/mr-x/froxy/lib/python3.7/site-packages/virtualenv.py", line 998, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/home/mr-x/froxy/lib/python3.7/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

In case it matters, my use case is to install an application that only runs on python 3.7 on systems that do not yet support python 3.7 or that have older versions and are not willing to upgrade to 3.7 yet

Is this possible?

**Comment by gaborbernat** [comment]
Hmm, this should work, there must be some messup with passing in NoneType 👍  are there any intermediate stack trace in between create environment and abs path?

**Comment by Emi1305** [comment]
That was the only stacktrace. Anyway, I was able to fix it choosing a new path for the python installation. 

Apparently python was being installed under `{virtualenv path}/bin`, the same path where virtualenv was trying to add its python symlink

Changing my building script to install python under `{virtualenv path}/python/bin` solved the problem

I don't know if it's worth keeping this open to handle this use case in a different way

**Comment by Emi1305** [comment]
Given that there my issue has been solved I'm closing this issue

**Comment by gaborbernat** [comment]
Thanks!
