### ISSUE TITLE
Where does virtualenv get its version of site.py from?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [pypa/virtualenv#1250]
[Ubuntu 14.04]
I have Python 2.7.6 and Python 3.4.3 installed on my system.
I'm in the process of learning how virtual environments are managed and have come across an anomaly I can't explain.
When I create a new environment `mkvirtualenv myenv` (regardless of the site-packages flag), I end up with a `site.py` that is different from the Python versions I have on my system.  I've searched my server for a _template_ file which virtualenv copies into my environment, but there aren't any.  Where does this version come from?

I have read https://github.com/pypa/virtualenv/issues/228 but that hasn't help me understand.

**Comment by gaborbernat** [comment]
It's a custom site.py baked within virtualenv code itself.

**Comment by gaborbernat** [comment]
https://github.com/pypa/virtualenv/blob/master/virtualenv_embedded/site.py

**Comment by gaborbernat** [comment]
That's not true, we've been syncing it up from time to time.
