### ISSUE TITLE
Deleting no-global-site-packages.txt allows access to global site packages

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [pypa/virtualenv#1251]
I'm learning python and virtual environments, so perhaps I'm missing something here.
But if I delete the `no-global-site-packages.txt` file (owned by me), then my environment seems to effectively become one where I used the `--system-site-packages`.

Is this a possible security risk?

**Comment by gaborbernat** [comment]
If they can delete that file they might as well just use it to create an env with that flag. virtualenv offers no security guarantee at all. You should use another security system on top of it if you want security guarantees.

**Comment by gaborbernat** [comment]
Otherwise note you need read access on the global for this work, at which point you can read and load/run all python packages from global.
