### ISSUE TITLE
Virtualenv should not override cert option from pip.conf

### ISSUE THREAD

**Issue by daa** [pypa/virtualenv#1260]
Consider following setup: in our organization we have internal pypi server serving https with certificate signed with our internal root certificate authority, in ``/etc/pip.conf`` I have following settings:
```
[global]
cert = /etc/ssl/certs/ca-certificates.crt
```
to make ``pip`` use system certificates. Also I set ``PIP_INDEX_URL`` environment variable pointing to our internal pypi. ``pip`` works as expected with such settings.

The problem arises when ``virtualenv`` tries to install ``pip``, ``setuptools``, ``wheel`` and looks at our pypi for packages but does not use certificates from ``/etc/pip.conf`` because it's overridden by ``--cert`` option in ``install_wheel`` script:
```
            if cert_file is not None:
                args += ["--cert", cert_file.name{}]
```
It results in failure to install those requirements from our internal pypi. However ability to install latest ``pip`` and ``setuptools`` from our internal pypi on virtualenv setup is very desirable for me.

I know of workarounds like setting ``PIP_TRUSTED_HOST`` environment variable or setting ``trusted-host`` in ``/etc/pip.conf`` but I'd very like to not use them because they are not required for ``pip`` to work. Or if checking for ``cert`` in ``pip.conf`` is complicated I'd like to be able to specify option for ``virtualenv`` to use given certificates.

**Comment by gaborbernat** [comment]
I'll try to think of a good solution for this. Thanks for reporting this, I agree we should allow some way to make this work.

**Comment by daa** [comment]
What do you think about approach in #1273?

**Comment by gaborbernat** [comment]
officially pip has no public interface other than the CLI, if you get the value via that I'm on board with this change.

**Comment by pfmoore** [comment]
There's no means that I know of to get that information via pip's CLI. (A case could be made for exposing it via the CLI, but that would be a new feature). So at the moment, you have to use the internals if you need that data.

The code in question already uses pip's internals (the `main` function, and the location of the cert files in the vendored modules) so the proposed change doesn't add *that* much more of a problem. But you should carefully review this code with every pip release to ensure it still works. I think the code is on;y run against the embedded copy of pip that you ship with virtualenv - so the exposure is limited. If you run that code against an arbitrary copy of pip you'll have to be far more careful.

Ultimately, the internals you are using can break arbitrarily, with no warning, in any release of pip. As long as you're managing that risk, though, this is probably the only reasonable way of getting that data.

**Comment by daa** [comment]
I recently discovered that ``pip`` has ``config`` command since version 10, so I guess I can use it to find out if ``cert`` option is defined in configuration file or environment variable.

**Comment by pfmoore** [comment]
Whoops. I should have known that :-) Good catch!

The code here already digs around in pip's internals, though, so I'm honestly not sure it's *that* beneficial to avoid the extra internal calls at the cost of an extra subprocess... (If the code were being refactored to avoid use of internals at all, then the `pip config` route would *definitely* be the way to go).

**Comment by gaborbernat** [comment]
the way I view it Paul the other one can't be avoided, using here the official API we'll have one less thing that could break 😁

**Comment by pfmoore** [comment]
Works for me.

**Comment by gaborbernat** [comment]
Merged in now, thanks @daa

**Comment by daa** [comment]
Thank you very much!
