### ISSUE TITLE
macOS zsh question

### ISSUE THREAD

**Issue by muuvmuuv** [pypa/virtualenv#1261]
I'm using iTerm2 with zsh and oh-my-zsh on my Mac. I recently started working with python again and came up to venv, what is great for shared projects. Now every time I activate a venv I see the name of the venv above my console initial line and was wondering if someone here knows how I could move it somewhere else. 

I'm using the theme honukai and would like to have it at the end. I see in the honukai.zsh-theme file is a line with `prompt` but I don't know what I should type there to display it somewhere else.

![bildschirmfoto 2018-12-20 um 21 04 32](https://user-images.githubusercontent.com/11534760/50308275-0dd4c280-049b-11e9-94fe-11b1587b35b9.png)

```bash
PROMPT="
%{$terminfo[bold]$fg[blue]%}#%{$reset_color%} \
%{$fg[cyan]%}%n \
%{$fg[white]%}at \
%{$fg[green]%}$(box_name) \
%{$fg[white]%}in \
%{$terminfo[bold]$fg[yellow]%}${current_dir}%{$reset_color%}\
${hg_info}\
${git_info} \
%{$fg[white]%}[%*]
%{$terminfo[bold]$fg[red]%}→ %{$reset_color%}"
```

**Comment by gaborbernat** [comment]
Can you reproduce it with other themes? If not this is an issue for the theme owner or iterm.
