### ISSUE TITLE
16.1.0 with --python creates symlink to distutils directory 

### ISSUE THREAD

**Issue by fungi** [pypa/virtualenv#1270]
PR #1227 seems to have created a regression in 16.1.0 as compared to 16.0.0 and earlier, at least on my dev systems where I use `make altinstall` to keep a bunch of different builds of Python for compatibility testing purposes. Now, ``lib/pythonX.Y/distutils`` in the virtualenv is created as a symlink to the distutils directory for my Python installation if `--python=pythonX.Y` is supplied, and then the subsequent ``install_distutils()`` call overwrites ``distutils/__init__.py`` in that Python's stdlib (following the symlink) with virtualenv's modified version. This of course results in all manner of later havoc as other callers into distutils end up getting virtualenv's init for it rather than the stdlib implementation.

Prior to the PR (or with it reverted), files in the virtualenv libdir are still symlinked as expected but the distutils directory is (correctly) not a symlink. I apologize for not having a better suggestion at this point than a revert, though hopefully someone with a deeper knowledge of the linkfarm bits will see a simple solution. As it stands, this basically renders tox unusable for me in conjunction with non-system-packaged Python interpreters.

Python built as follows:

    export TAG=3.7.2
    git clean -dfx
    git checkout v$TAG
    ./configure --enable-optimizations --prefix /home/fungi/lib/cpython/$TAG
    make profile-opt
    make altinstall
    ln -sf ../lib/cpython/$TAG/bin/python3.7 ~/bin/

Virtualenv installed with:

    python3.7 -m venv ~/lib/virtualenv
    ~/lib/virtualenv/bin/pip install virtualenv
    ln -sf ../lib/virtualenv/bin/virtualenv ~/bin/

Behavior reproduced with:

    virtualenv --python=python3.7 foo

With this, ``foo/lib/python3.7/distutils`` is created as a symlink to ``~/lib/cpython/3.7.2/lib/python3.7/distutils`` so then virtualenv overwrites the stdlib-supplied ``~/lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py`` with the contents from the https://github.com/pypa/virtualenv/blob/master/virtualenv_embedded/distutils-init.py file.

**Comment by gaborbernat** [comment]
Just for reference, the claim is that https://github.com/pypa/virtualenv/pull/1208 (a MacOS fix) conflicts with (Linux?). Can you detail the exact error you're getting? For reference, I have MacOS with custom compiled pythons (system-wide installation though) which works just fine. I'm not clear here what's the issue is here and I would be reluctant to do any changes before we get to the bottom of this (even though as such we're probably missing the next release with this).

**Comment by fungi** [comment]
> Just for reference, the claim is that #1208 (a MacOS fix) conflicts with (Linux?).

Correct. While #1208 may have been trying to solve a MacOS-specific problem, it most definitely does *not* alter only MacOS-specific code paths within ``virtualenv.py`` and so has altered behavior in some other environments in detrimental ways.

> Can you detail the exact error you're getting?

I'm not sure what you're asking for. While this is erroneous behavior, it doesn't necessarily emit any error message (though as pypa/pipenv#3395 also indicates, this can result in permission errors if the ``lib/pythonX.Y/distutils`` at the dereferenced symlink target or its content is not writable by the user).

I can however provide comparative example output from 16.0.0 and 16.1.0 for the same environment to show you what non-error messages are emitted:

    fungi@dhole:~$ virtualenv --version
    16.0.0
    fungi@dhole:~$ md5sum lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py
    ce44c86dc92e40d9c3d59dfbacd7029c  lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py
    fungi@dhole:~$ rm -rf foo
    fungi@dhole:~$ virtualenv --python python3.7 foo
    Running virtualenv with interpreter /home/fungi/bin/python3.7
    Using base prefix '/home/fungi/bin/../lib/cpython/3.7.2'
    /home/fungi/lib/virtualenv/lib/python3.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses  import imp
    New python executable in /home/fungi/foo/bin/python3.7
    Also creating executable in /home/fungi/foo/bin/python
    Installing setuptools, pip, wheel...done.
    fungi@dhole:~$ ls -dl foo/lib/python3.7/distutils
    drwxr-xr-x 3 fungi fungi 4096 Dec 31 14:49 foo/lib/python3.7/distutils
    fungi@dhole:~$ md5sum lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py
    ce44c86dc92e40d9c3d59dfbacd7029c  lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py

    fungi@dhole:~$ virtualenv --version
    16.1.0
    fungi@dhole:~$ md5sum lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py
    ce44c86dc92e40d9c3d59dfbacd7029c  lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py
    fungi@dhole:~$ rm -rf foo
    fungi@dhole:~$ virtualenv --python python3.7 foo
    Running virtualenv with interpreter /home/fungi/bin/python3.7
    Using base prefix '/home/fungi/bin/../lib/cpython/3.7.2'
    New python executable in /home/fungi/foo/bin/python3.7
    Also creating executable in /home/fungi/foo/bin/python
    Overwriting /home/fungi/foo/lib/python3.7/distutils/__init__.py with new content
    Installing setuptools, pip, wheel...
    done.
    fungi@dhole:~$ ls -dl foo/lib/python3.7/distutils
    lrwxrwxrwx 1 fungi fungi 53 Dec 31 14:51 foo/lib/python3.7/distutils -> /home/fungi/lib/cpython/3.7.2/lib/python3.7/distutils
    fungi@dhole:~$ md5sum lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py
    552b973cb01606c0cc2818b686e42eb0  lib/cpython/3.7.2/lib/python3.7/distutils/__init__.py

In particular, the ``Overwriting /home/fungi/foo/lib/python3.7/distutils/__init__.py with new content`` message is the obvious difference in output for 16.1.0, and as you can see the checksum of the Python 3.7.2 stdlib's distutils init module indicates it has indeed been overwritten.

**Comment by daa** [comment]
Recently I've met this issue too and found that symlink from virtual environment's ``distutils`` to original Python's ``distutils`` is created by the code copying files when ``sys.prefix`` does not match ``sys.exec_prefix`` in case when they do not match literally but actually are the same paths.

Related part of code:
```
    if sys.exec_prefix != prefix and not IS_PYPY:
        if IS_WIN:
            exec_dir = join(sys.exec_prefix, "lib")
        elif IS_JYTHON:
            exec_dir = join(sys.exec_prefix, "Lib")
        else:
            exec_dir = join(sys.exec_prefix, "lib", PY_VERSION)
        if os.path.isdir(exec_dir):
            for fn in os.listdir(exec_dir):
                copyfile(join(exec_dir, fn), join(lib_dir, fn), symlink)
```
Here ``sys.exec_prefix`` is compared to prefix got from ``sys.prefix`` or ``sys.base_prefix``. Change in #1208 transformed that prefix to absolute path so if that prefix contained relative parts they were eliminated however no such transformation is applied to ``sys.exec_prefix`` and thus ``prefix`` and ``sys.exec_prefix`` may become literally unequal if they were literally equal orignally and point to the same path.

For example when I run ``python`` and check prefixes I get this:
```
>>> import sys
>>> sys.exec_prefix
'/usr/lib/python-exec/python2.7/../../..'
>>> sys.prefix
'/usr/lib/python-exec/python2.7/../../..'
```
``virtualenv`` uses ``abspath(sys.prefix)`` for ``prefix`` which is equal to ``/usr`` and later it compares this prefix with original ``sys.exec_prefix``  and thus prefixes which were equal originally happen to be not equal.

**Comment by asottile** [comment]
hitting this as well using docker on linux.  Here's a minimal reproduction:

```dockerfile
FROM ubuntu:bionic
RUN : \
    && apt-get update \
    && apt-get install -y --no-install-recommends virtualenv \
    && apt-get clean \
    && rm -rf /var/lib/apt/sources.list

ENV PATH=/venv/bin:$PATH
RUN virtualenv /venv -ppython3 && pip install virtualenv==16.2.0
RUN install --directory /code --owner nobody
USER nobody
RUN virtualenv /code/venv -ppython3
```

```
$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM ubuntu:bionic
 ---> 113a43faa138
Step 2/7 : RUN :     && apt-get update     && apt-get install -y --no-install-recommends virtualenv     && apt-get clean     && rm -rf /var/lib/apt/sources.list
 ---> Using cache
 ---> bc1bb0c9fe28
Step 3/7 : ENV PATH=/venv/bin:$PATH
 ---> Using cache
 ---> cce5f5616d0a
Step 4/7 : RUN virtualenv /venv -ppython3 && pip install virtualenv==16.2.0
 ---> Using cache
 ---> d1e2f1b3e5e1
Step 5/7 : RUN install --directory /code --owner nobody
 ---> Using cache
 ---> 82e145e0d850
Step 6/7 : USER nobody
 ---> Using cache
 ---> b76311ec04a9
Step 7/7 : RUN virtualenv /code/venv -ppython3
 ---> Running in 9c630e490c8c
Already using interpreter /venv/bin/python3
Using real prefix '/usr'
Path not in prefix '/venv/include/python3.6m' '/usr'
New python executable in /code/venv/bin/python3
Also creating executable in /code/venv/bin/python
Overwriting /code/venv/lib/python3.6/distutils/__init__.py with new content
Traceback (most recent call last):
  File "/venv/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/venv/lib/python3.6/site-packages/virtualenv.py", line 768, in main
    symlink=options.symlink,
  File "/venv/lib/python3.6/site-packages/virtualenv.py", line 1016, in create_environment
    install_distutils(home_dir)
  File "/venv/lib/python3.6/site-packages/virtualenv.py", line 1597, in install_distutils
    writefile(os.path.join(distutils_path, "__init__.py"), DISTUTILS_INIT)
  File "/venv/lib/python3.6/site-packages/virtualenv.py", line 431, in writefile
    with open(dest, "wb") as f:
PermissionError: [Errno 13] Permission denied: '/code/venv/lib/python3.6/distutils/__init__.py'
The command '/bin/sh -c virtualenv /code/venv -ppython3' returned a non-zero code: 1
```

**Comment by daa** [comment]
In this case the cause is that in virtual environment ``exec_prefix`` is really different from prefix ``virtualenv`` uses and consequently ``virtualenv`` copies all files from ``sys.exec_prefix`` including ``distutils``. To solve it I think that copying code should be limited to ``REQUIRED_FILES`` only.
