### ISSUE TITLE
can i install some depent of virtualenv to confirm copy one virtualenv file to apline ,and run a python service

### ISSUE THREAD

**Issue by sunjiansen** [pypa/virtualenv#1272]
apline is without python

**Comment by gaborbernat** [comment]
Sorry I don't understand, you'll need to elaborate exactly what you're looking to do.

**Comment by sunjiansen** [comment]
I want to install virtualenv in Python3.6 image and use command `virtualenv env` to create a virtualenv environment, and then copy the env file to a apline image which without Python,and I use use command `souce /env/bin/activate` it work ,but the command `/env/bin/active/python -v` it doesn't work,say no such file or command,I have see the alike issue [https://github.com/pypa/virtualenv/issues/1212]，is it really can't come true this demand ,I use this demand in Dockerfile (multi-stage) of Python

**Comment by gaborbernat** [comment]
This is not supported at the moment, as there's no cross platform way to achieve this. I know there's a demand on this, however there's no way to do this in a cross platform way and as such out of scope for virtualenv. We might try to create something platform specific, but this will not be part of the core virtualenv.
