### ISSUE TITLE
Source distribution of Virtualenv 16.2.0 missing on PyPi

### ISSUE THREAD

**Issue by StephanErb** [pypa/virtualenv#1278]
There is no source distribution of Virtualenv 16.2.0 available on PyPi. This breaks various bootstrapping scripts used in the wild. 

For example, accessing https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-16.1.0.tar.gz works as expected. Accessing https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-16.2.0.tar.gz does not. For further details, please see https://pypi.org/project/virtualenv/#files

Thanks!

**Comment by gaborbernat** [comment]
Hello, can you please detail how this breaks various bootstrapping scripts (with exact examples) and why it's important for those to have a sdist over using the wheel? Thanks!

**Comment by moubctez** [comment]
The source code is also needed for packaging (e.g. PkgSrc.org). :)

**Comment by gaborbernat** [comment]
I would like to hear more detailed usage scenarios, e.g. why can't pkgsrc.org work with the wheel instead? I'm not saying publishing sdist should not happen, however before we do that would like to have strong understanding of why sdist should be preferred over wheel in some cases.

**Comment by pfmoore** [comment]
Personally (and this is simply my opinion) I disagree with binary-only distributions (I know the source is present in the wheel, but conceptually the sdist is the "source code"). I don't think that PyPI should host package binaries but leave the user to go elsewhere for sources (in particular, I think the exact source tree matching a given binary release should be available for direct download, not by hunting for the right tag in the git repo).

Also, without the sdist, `pip install --no-binary :all: virtualenv` will install the wrong version:

```
>pip install virtualenv
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/6a/d1/e0d142ce7b8a5c76adbfad01d853bca84c7c0240e35577498e20bc2ade7d/virtualenv-16.2.0-py2.py3-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 3.2MB/s
Requirement already satisfied: setuptools>=18.0.0 in c:\users\gustav\.virtualenvs\2eced57af4085e\lib\site-packages (from virtualenv) (40.6.3)
Installing collected packages: virtualenv
Successfully installed virtualenv-16.2.0
>pip uninstall -y virtualenv
Uninstalling virtualenv-16.2.0:
  Successfully uninstalled virtualenv-16.2.0
>pip install --no-binary :all: virtualenv
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 2.4MB/s
  Installing build dependencies ... done
Skipping bdist_wheel for virtualenv, due to binaries being disabled for it.
Installing collected packages: virtualenv
  Running setup.py install for virtualenv ... done
Successfully installed virtualenv-16.1.0
```

**Comment by gaborbernat** [comment]
I wanted to get some use concert use cases where having a sdist is must over wheel. Neither of those yet enumerated showed such though, other than yeah it's missing. 

In the meantime released the sdist, https://files.pythonhosted.org/packages/59/38/55dd25a965990bd93f77eb765b189e72cf581ce1c2de651cb7b1dea74ed1/virtualenv-16.2.0.tar.gz

**Comment by moubctez** [comment]
Thanks for the source code release, but… next time, please, remove `tests/__pycache__` and `tests/activation/__pycache__`. :-)
