### ISSUE TITLE
ADMINISTRATIVE: CONTRIBUTING.rst & docstring of tasks/update_embedded.py appear out of date

### ISSUE THREAD

**Issue by bskinn** [pypa/virtualenv#1284]
[CONTRIBUTING.rst currently says](https://github.com/pypa/virtualenv/blob/59a5ab8ce460de950f97ffba8e1af6d79d530aa9/CONTRIBUTING.rst):

> * All changes to files inside `virtualenv_embedded` should be integrated to `virtualenv.py` with `bin/rebuild-script.py`.

If I read the project tree correctly, though, that update script is now [`tasks\update_embedded.py`](https://github.com/pypa/virtualenv/blob/59a5ab8ce460de950f97ffba8e1af6d79d530aa9/tasks/update_embedded.py).  As well, the script [docstring](https://github.com/pypa/virtualenv/blob/59a5ab8ce460de950f97ffba8e1af6d79d530aa9/tasks/update_embedded.py#L3) appears to be incorrect, as `virtualenv.py` is now updated from `virtualenv_embedded`, not `virtualenv_support`.

Small fixes, I'm happy to make the PR if I'm on the right track here.

**Comment by gaborbernat** [comment]
Indeed we need to upgrade those. Though we no longer recommend calling those scripts directly, but instead via tox (see embed, fix_lint targets). We would love you to make a PR fixing this, thanks!

**Comment by bskinn** [comment]
Ok -- so, contributors should:

 1.  Run `tox -e embed` after making any changes to the scripts in `virtualenv_embedded`; and
 2.  Run `tox -e fix_lint` before committing to feature branches

?

**Comment by gaborbernat** [comment]
yes

**Comment by bskinn** [comment]
Note to self .. temporarily setting `skip_install = False` in the `[testenv:fix_lint]` environment settings within `tox.ini` resolved a `.../.tox/fix_lint/bin/python: No module named virtualenv` error initially encountered.

**Comment by bskinn** [comment]
This was fixed as part of #1330.
