### ISSUE TITLE
No option to skip installing setuptools/distribute altogether.

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#13]
It would be nice to skip both; instead I ended up with this hack when I wanted a specific version of setuptools in a virtualenv but had distribute installed globablly:

```
#!/bin/sh

SETUPTOOLS=specific-setuptools-version.egg

/path/to/virtualenv/bin/pip uninstall distribute

/path/to/virtualenv/bin/python -c "import sys,os; sys.path.insert(0,os.path.abspath('$SETUPTOOLS')); from setuptools.command.easy_install import bootstrap; sys.exit(bootstrap())"
```

What would have been ideal in my situation would have been options to skip installation of setuptools; and an option that took various eggs to pre-install instead?

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/34
- Originally Reported By: Anonymous
- Originally Created At: 2010-05-05 00:12:49

**Comment by gaborbernat** [comment]
I think this has been done via https://virtualenv.pypa.io/en/latest/reference/#cmdoption-no-setuptools
