### ISSUE TITLE
`user = yes` breaks virtualenv 

### ISSUE THREAD

**Issue by jpalczewski** [pypa/virtualenv#1306]
# Minimal reproducible example or detailed descriptions
Recently(about one month before posting here) I had problems with venvs on arch linux with fresh packages - activating venv makes pip _read-only_, which means all installed packages were landing into user repository, but weren't visible in venv. Tried multiple shells, but anything worked. But now I tried removing:
```
[install]
user = yes
```
from pip.conf and everything is working fine. That's file was in my dotfiles for about a year, so there might be some breaking changes in venv-related files.

# OS and `pip list` output
Recent arch linux, python 3.7.2.

**Comment by gaborbernat** [comment]
Thanks for reporting this, can you try to put in a fix pull request?

**Comment by jpalczewski** [comment]
Sure, I can try - but what kind of behavior is wanted in this particular situation? There's a story behind this switch, f.e. #803 - but now I haven't figured any elegant solution to that(`pip --verbose` didn't show anything useful, `strace pip install` helped me to recognize that in dark past I added something like this to pip.conf). Some kind of deprecation warning, when pip is running with user in venv?

**Comment by gaborbernat** [comment]
Reading through the issue again seems this is an issue in venv not in virtualenv; so I'll close for now.
