### ISSUE TITLE
Import error from collections for python 3.5

### ISSUE THREAD

**Issue by GGurtner** [pypa/virtualenv#1307]
Hi there, I found a bug when using python 3.5. In short, there is no "Collection" in the collections module in 3.5, contrary to python 3.3, 3.4, and 3.6. Way to check:

```
python3.5 -c "from collections import Collection"
```
returns `ImportError: cannot import name 'Collection'`, whereas 
```
python3.6 -c "from collections import Collection"
```
does not.

I tried to have a look, but I see nowhere else this Collection object could be in collections in python3.5, so I am not sure how to fix this.

PS: related to this closed issue for backwards compatibility with python 3.3 and 3.4 [https://github.com/pypa/virtualenv/issues/1059](https://github.com/pypa/virtualenv/issues/1059)

**Comment by pfmoore** [comment]
I'm not sure how this is related to virtualenv, but from the docs "Changed in version 3.3: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely."

You should be getting `Collection` from `collections.abc`, not from `collections` directly.

**Comment by GGurtner** [comment]
Actually, BlueSky checks for collections.abc before even checking collections itself if it fails (that's the patch done in the issue I mentioned in my first message). And indeed, running:
```
python3.5 -c "from collections.abc import Collection"
```
does not do the trick. Also, contrary to what I said in the first message, the same problem appears with python3.4 on my machine. That's puzzling. I'll use 3.6 for now in a virtual environment and come back with more information if I can.

**Comment by GGurtner** [comment]
How the fuck did I do that? I am absolutely not commenting in the right repository. Thanks for the help nevertheless, but please, do forget about this issue.

I need a break I think.
