### ISSUE TITLE
can't find '__main__' module...

### ISSUE THREAD

**Issue by joe247** [pypa/virtualenv#1310]
`$ virtualenv --system-site-packages -p python3 ~/PyVEnv`
`Running virtualenv with interpreter /usr/bin/python3
/usr/bin/python3: can't find '__main__' module in '/usr/local/lib/python2.7/dist-packages/virtualenv-16.3.0-py2.7.egg/virtualenv.py'`

I'm trying to install virtualenv for python 3.5.3, not sure if this is the right platform, but this issue is persistent.
`$ virtualenv --version 16.3.0`
System: Debian 9.7 64bit

Any help appreciated.

**Comment by gaborbernat** [comment]
This is strange why you're having an egg file? did you install with a recent pip? or it conflicts with some bad os installation, eggs have been deprecated for a few years.

**Comment by joe247** [comment]
Well yes with _recent pip_ (on friend's laptop), then I found that it was absurd and that it must be installed with the deb packages, so I did it the apt-get way _and then_ uninstalled the one which is under pip.

Yes, I had encountered some _issues in OS installation_ (on friend's laptop). The usb wouldn't boot in UEFI mode (made bootable by [PowerISO](https://www.poweriso.com/)), but then I tried creating a bootable USB using [balenaEtcher](https://www.balena.io/etcher/), from my Laptop (which has only BIOS) it (balenaEtcher) and for no reason created an EFI partition in the USB. Anyway then, Debian installation went smoothly in UEFI mode.

![screenshot-2019-2-8 toshiba satellite l50-b931 i5-4200 6gb 1tb in saudi arabia price catalog ksa-price com specs best pr](https://user-images.githubusercontent.com/38415384/52481947-ef0ac680-2bd5-11e9-8c08-59bfc368fb91.png)

I had updated to Windows 10 and only then I installed Debian.

What am I forgetting?

**Comment by asottile** [comment]
.egg-info != .egg

More of a remnant of the older times but is still used for metadata

.egg-info is fine

**Comment by joe247** [comment]
Now as I experiment on the things are getting weird...

ran `pip uninstall virtualenv` -> leads me [here](https://stackoverflow.com/questions/41092519)

So I moved the `virtualenv.py` (refer above screen-shot) to `/home`
Okay...

Then I went to `snaps` and searched for `virtualenv` and `marked for complete removal` ->  `Apply`
![Uploading Screenshot from 2019-02-13 18-38-10.png...]()
Thats fine...

Then ran `sudo apt-get remove virtualenv` & `sudo apt-get purge virtualenv`

Rebooted, Opened the terminal and ran `virtualenv --version`
`16.1.0`

It freaked me out!

Whats going on?

Why does bash recognize the package that has been removed?

**Comment by asottile** [comment]
try
```
which virtualenv
head -1 $(which virtualenv)
$(head -1 $(which virtualenv) | cut -d! -f2) -c 'import virtualenv; print(virtualenv.__file__)'
```

that should tell you where it's coming from at least

**Comment by joe247** [comment]
Oh... okay
`$(head -1 $(which virtualenv) | cut -d! -f2) -c 'import virtualenv; print(virtualenv.__file__)'`

`/usr/local/lib/python2.7/dist-packages/virtualenv-16.3.0-py2.7.egg/virtualenv.pyc`

Tells me its from virtualenv installed under python2.7 _but_ I never install it manually, neither did I install pip for python2.

So now I install pip for python2, uninstall virtualenv using the same.

Did `pip3 install virtualenv` ran `which virtualenv` doesn't give _any_ output.

Why was the path not set up after installation from pip3?

**Comment by asottile** [comment]
That install indicates at some point you ran `sudo easy_install virtualenv`.

Now what does `python3 -c 'import virtualenv; print(virtualenv.__file__)'` produce?

**Comment by joe247** [comment]
It gives me this path
`/home/jsheyon/.local/lib/python3.5/site-packages/virtualenv.py`
& `which python3` gives me
`/usr/bin/python3`

**Comment by asottile** [comment]
Probably means it is installed in `~/.local/bin`

You can probably put something like this in your `.bashrc`

`export PATH="$HOME/.local/bin:$PATH'`

**Comment by joe247** [comment]
This worked `export PATH=$HOME/.local/bin:$PATH` (without quotes).

**3 Questions:**

1. How was `virtualenv` installed under pip even before installing pip?
2. Why does `easy_install` copy/port `virtualenv` from pip3 to pip?
3. How will I run `virtualenv` under python3 & python2 simultaneously (I mean is there virtualenv3 & virtualenv)?

**Thanks very much!**

**Comment by asottile** [comment]
1. `pip` and easy_install install to the same place (just easy_install uses eggs and doesn't have uninstall). easy_install comes with python-setuptools (probably why it was there?)
2. Hmmm not sure it does, it only installs things for the python it is running as
3. You can, but you don't need to - - you can just use `virtualenv -p python3` etc.
