### ISSUE TITLE
Please stop using the Probot's "stale" bot

### ISSUE THREAD

**Issue by sampablokuper** [pypa/virtualenv#1311]
Closing bug reports whose bugs have not been fixed is an anti-pattern. It gives a false sense of buglessness.

Recently, a bug that I filed was [closed](https://github.com/pypa/virtualenv/issues/1129#event-2086132734) by a [bot](https://probot.github.io/apps/stale/), without any evidence that the bug had in fact been fixed. This was an example of that anti-pattern.

Please disable that bot, so that it stops implementing that anti-pattern all over your bug-tracker. Thanks.

**Comment by gaborbernat** [comment]
The projects has multiple release every year, as such bugs can potentially get stale. This project is maintained by volunteers so we don't have resources to check bugs manually ourselves. We increased the stale time to three months to be accommodating, no issues confirmed to still be an issue have been closed. Again if any of the issues are to be confirmed to still be an issue we'll reopen it. Hope that clears it up, and we don't consider this to be a bad practice or anti pattern.

**Comment by sampablokuper** [comment]
@gaborbernat wrote:
> If any of the issues are [...] confirmed to still be an issue we'll reopen it.

This mitigates the anti-pattern _somewhat_, so thank you. IMO it is still an anti-pattern, though.

> This project is maintained by volunteers so we don't have resources to check bugs manually ourselves. ... we don't consider this to be a bad practice or anti pattern.

The bugs are likely reported by volunteers, and you are requiring *more* work from them, and potentially creating more work for yourselves, too.

- You are effectively saying to your community: "*Reporting a bug is no longer enough. If you want it to be addressed, you may have to actively stop the bug from being closed, by logging in periodically and making a comment on it that would otherwise be unnecessary. Otherwise we may ignore it.*"

- You are requiring bug report threads to become longer and more convoluted, due to the noise from the bot and from the users answering the bot.

- You increase the risk of people creating duplicate issues, because searching for their issue in the issue tracker is likely to show them closed threads - which might prompt them to engage in the anti-pattern of opening a duplicate thread - than open threads, even if the issue was already reported and is unfixed. Duplicate issues increase maintenance overhead.

So, as I say: thanks for your reply and the mitigation, but disabling the bot would be better.

**Comment by gaborbernat** [comment]
We had 350+ issues open. We tried what you're proposing and the effect it had was that truly important issues got lost in between tons of old not relevant anymore issues. Again given we have very limited developer resources on this (meaning mostly me on part of my spare time) we'll going ahead require users periodically confirm what is still a problem. Again if some issues are reported to be valid at any point we'll reopen it. Reopening it takes minimal time overall.

**Comment by sampablokuper** [comment]
> truly important issues got lost in between tons of old not relevant anymore issues.

I don't really know what you mean by "lost". Those "truly important issues" were still there, and more importantly, they were still open, so that it was clear they still needed addressing.

Now, by contrast, if someone reports a "truly important issue" that isn't recognised as such within three months, then the Stale bot will close it, and if that person does not log in to the bug tracker to re-open the issue, then effectively their effort in reporting the bug has been wasted and you have missed an opportunity to address it. To me, these are clear anti-patterns.

Anyhow, I have made my point. The decision is yours (the maintainers'). There is no need to reply, but please do think over what I have said. I am trying to be helpful to you and to others who use this bug-tracker. Thanks.

**Comment by gaborbernat** [comment]
if it's a truly important issues someone will soon comment on it to reopen it 😀

**Comment by gaborbernat** [comment]
Would someone had time fixing those bugs post mortem they can just go though issues closed by the stale bot. And we of course do accept PRs for closed issues.
