### ISSUE TITLE
python3.dll/python34.dll in Python 3.4 virtualenvs

### ISSUE THREAD

**Issue by reaperhulk** [pypa/virtualenv#1314]
When creating a Python 3.4 virtualenv `python3.dll` is not copied into the virtualenv. This is because in 3.4 `python3.dll` is not in the same directory as `python.exe`, but rather in `DLLs`.

This is the code that looks for the files right now:
https://github.com/pypa/virtualenv/blob/fef732c7be63f11efd52a2e8d94bb1288cb7b9a3/virtualenv.py#L1485-L1497

A potential resolution would be to try to find the DLL with something like 
```python
python_dll_alt = os.path.join(os.path.dirname(sys.executable), "DLLs", py_executable_dll)
```

This is more prominent now because the newly released cffi 1.12.0 attempts to link against `python3.dll` so this bug results in import failures on Windows.

I believe this also affects Python 3.x lower than 3.4 as well but since virtualenv doesn't support those versions we can ignore them.

**Comment by gaborbernat** [comment]
So python 3 is no longer supported, so I guess this makes the issue obsolete-ish.
