### ISSUE TITLE
Create a mechanism to allow access to chosen global site-packages

### ISSUE THREAD

**Issue by Midnighter** [pypa/virtualenv#1323]
This is an enhancement inquiry. At the moment `--system-site-packages` is an all or nothing option. I'm wondering if it is very hard to instead allow for a list of package names that would then be symlinked into the virtualenv (or made available by another mechanism). [This was requested some time ago on tox](https://github.com/tox-dev/tox/issues/79) and in the context of tox I find it a very useful feature. If you think this is possible I can certainly try to make a PR but I have never looked at virtualenv internals before.

**Comment by gaborbernat** [comment]
I don't think this is something that we want. It would be **very very very** hard to get it right and I see little benefit for it (in context of tox it goes against reproducible builds spirit).
