### ISSUE TITLE
virtualenv with python3 overrides existing bash prompt

### ISSUE THREAD

**Issue by knibbl** [pypa/virtualenv#1325]
When I create a virtualenv with `virtualenv --python=/usr/bin/python3 ~/.virtualenvs/test` and afterwards activating it, it will override my existing prompt, which is configured in my `.bashrc`. After deactivation of virtualenv I'll get my former prompt back. This doesn't happen when I create a virtualenv without specifing a python version (default - python 2.7). 

I didn't find a workaround to handle this issue.

OS information:
Description: Debian GNU/Linux buster/sid
Release: testing
virtualenv version: 15.1.0

**Comment by asottile** [comment]
I'm having trouble reproducing, even with the old version of virtualenv (15.1.0) -- can you provide reproduction steps and show the output of both situations?

**Comment by gaborbernat** [comment]
Close for lack of updates.
