### ISSUE TITLE
selinux should be copied or linked from system python on virtualenv creation

### ISSUE THREAD

**Issue by ssbarnea** [pypa/virtualenv#1334]
[selinux](https://github.com/pycontribs/selinux) python bindings are kinda special and they are needed by a huge number of python packages.

I think that the selinux bindings should be copied even if the virtualenv is created without system-site-packages. 

I seen at least of dozen of blog articles where people do recommend cp operations to copy the few files inside the virtualenv after its creation. This is kinda insane as it adds a serious amount of additional operations on CI testing. For example tox users would have rely on advanced steps to run in pre-command in order to patch the virtualenvs and to manually copy the selinux files in each env.

References:
* https://pypi.org/project/selinux/
* https://github.com/pycontribs/selinux
* [selinux use in openstack projects](http://codesearch.openstack.org/?q=selinux&i=nope&files=tox.ini%7Crequirements.txt&repos=) 
* [examples on how people deal with selinux](https://github.com/search?utf8=%E2%9C%93&q=selinux+path%3A%2F+filename%3Atox.ini+filename%3Asetup.cfg+filename%3Arequirements.txt&type=Code&ref=advsearch&l=&l=)

**Comment by gaborbernat** [comment]
@ssbarnea care to link some of these?

**Comment by gaborbernat** [comment]
Closing due to lack of response.

**Comment by ssbarnea** [comment]
I missed that notification, see few links:
* https://pypi.org/project/selinux/
* https://github.com/pycontribs/selinux

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
