### ISSUE TITLE
Activating virtual environment doesn't affect py.exe launcher

### ISSUE THREAD

**Issue by NN---** [pypa/virtualenv#1335]
Thanks for submitting an issue!

If submitting a BUG please provide:

- [X] Minimal reproducible example or detailed descriptions

a.py:
```python
#!python3
import jinja2
```

```cmd
virtualenv venv
venv\scripts\activate
pip install jinja2
```

**This works fine:**
python a.py

**This doesn't work:**
py a.py
```
ModuleNotFoundError: No module named 'jinja2'
```

- [X] OS and `pip list` output
Windows 10

**Comment by pfmoore** [comment]
The py launcher only uses the currently active virtualenv if the shebang line is `#!/usr/bin/env python` (which has the special property of triggering a `PATH` search). See [the documentation](https://docs.python.org/3/using/windows.html#shebang-lines) for full details.

**Comment by NN---** [comment]
I see. Thanks.
The issue is that several machines have python 2 and python 3 installed, and that's why #!python3 is required to work properly.
