### ISSUE TITLE
RFE: isolated pip cache per virtualenv

### ISSUE THREAD

**Issue by jonathanunderwood** [pypa/virtualenv#1341]
When running a `pip install <pkg>` in a virtualenv, pip will use the same wheel cache for all virtualenvs. This can cause a problem when wheels are built on install (i.e. when pypi has only an sdist and no wheels for a package). It would be better to have a cache per virtualenv.

This recently lost me a bunch of time due to this scenario with owlready2, which is a Python package, with an optional Cython optimized component. 

Background: owlready2 is distributed via PyPi as a source tarball only, no wheels. The `setup.py` for the package detects whether Cython is available and builds the `owlready2_optimized` module if it is, and otherwise falls back to a pure Python implementation.

I wanted to test some code with both the the Python only implementation, and with the Cython optimised implementation, so I did this:

1. I created a virtual env (venv1) to test some code using the owlready2 package. In this virtualenv I simply did a `pip install owlready2`. Then I did my testing.
2. Next I wanted to run the tests using the owlready2 package, but with the Cython optimized library, so I deactivated venv1 and created a second virtualenv (venv2) and then did `pip install Cython` followed by `pip install owlready2` expecting to have, in this new environment, the `owlready2_optimized` module available. To my surprise, the optimised module wasn't present in venv2.

The reason is that, in step 1, pip creates a wheel and stores it in its cache. Then, in step 2, since pip always uses the same cache irrespective of virtualenv, it sees an already existing wheel in the cache, that has been built without Cython, and installs that into venv2.

It would be much cleaner to have a separate cache for each virtualenv.

**Comment by pfmoore** [comment]
If you are testing different builds, should you not be using the `--no-binary` pip option anyway? The cache isn't the only place pip could accidentally pick up a prebuilt wheel from (the project could start shipping binaries on PyPI, for instance...)

A cache per virualenv would result in a significant loss of performance for the normal use case where reusing built wheels is the correct approach.

**Comment by gaborbernat** [comment]
Not sure how this relates to virtualenv. It's up to the user to specify the PIP_CACHE_DIR appropriately before invoking the install. At best what we could do is that the activation script set it for you based on some creation flag. @pfmoore am I right?

**Comment by pfmoore** [comment]
@gaborbernat Yes, you're right.

**Comment by jonathanunderwood** [comment]
Sure. I don't disagree with any points made. OTOH, I've been using Python, and pip, for more than a decade, and this caught me out for a good half an hour wondering what was going on. I am happy for this to be closed as out of scope for virtualenv, though.

**Comment by gaborbernat** [comment]
Thanks for reporting it, we'll close it now but if more people chime in for it we'll reopen it. In the meantime out of scope.
