### ISSUE TITLE
Creating virtualenvs with PyPy always warns about a missing LICENSE file

### ISSUE THREAD

**Issue by Julian** [pypa/virtualenv#1352]
```
⊙  pypy ~/Development/virtualenv/virtualenv.py --quiet foo                                                                     jberman@USNYHJBERMANMB2
  No LICENSE.txt / LICENSE found in source
```

https://github.com/pypa/virtualenv/blob/5e3a70c365f62cfb0f39dc4851d2104efc76c02f/virtualenv.py#L1321 looks like the problematic line, introduced in #1318.

The `license()` builtin in PyPy is static, and doesn't have a LICENSE to copy.

**Comment by asottile** [comment]
This seems specific to pypy installed via homebrew, we should be able to retrieve the LICENSE file there as well:

https://github.com/pypa/virtualenv/pull/1318#issuecomment-489340292

**Comment by m1keil** [comment]
also seem to happen on my fedora 30 install.
using system python with virtualenv installed with --user.

**Comment by asottile** [comment]
@m1keil I assume that's pypy packaged by fedora? is there a `LICENSE` in any of the files that get installed?

**Comment by m1keil** [comment]
sorry for the mix up. This actually happens with the regular system pip and python for me.

```
$ which virtualenv
~/.local/bin/virtualenv

$ virtualenv --version
16.6.0

$ virtualenv test
Using base prefix '/usr'
  No LICENSE.txt / LICENSE found in source
New python executable in /tmp/tmp.pVP6AhACXo/test/bin/python3
Also creating executable in /tmp/tmp.pVP6AhACXo/test/bin/python
Installing setuptools, pip, wheel...
done.
```

**Comment by gaborbernat** [comment]
@asottile so did we fix this then?

**Comment by asottile** [comment]
We did not, I vote just deleting the warning since it seems inconsistent where packagers chose to move the README and in some cases it is completely missing

**Comment by hroncok** [comment]
All the Pythons distributed with Fedora have this warning. We have the LICENSE file in `/usr/share/licenses/python3/LICENSE` - I wonder whether this needs to be fixed.

**Comment by hroncok** [comment]
OK, we shall fix this... https://src.fedoraproject.org/rpms/python38/pull-request/33

**Comment by hroncok** [comment]
Weirdly, even if `/usr/lib64/python3.8/LICENSE.txt` is present and the `license()` on `python3.8` shows it, virtualenv still warns:

```
$ virtualenv -p python3.8 py38
Running virtualenv with interpreter /usr/bin/python3.8
Already using interpreter /usr/bin/python3.8
Using base prefix '/usr'
  No LICENSE.txt / LICENSE found in source
...
```

**Comment by asottile** [comment]
@hroncok weird, what does this resolve to for fedora pythons? https://github.com/pypa/virtualenv/blob/d997faa8d44887508df0bb36e1b43b743d455925/virtualenv.py#L1338

**Comment by hroncok** [comment]
/usr/lib/python3.8/LICENSE.txt

We have lib64 (on 64bit arches).

**Comment by hroncok** [comment]
I'll send a PR.

**Comment by hroncok** [comment]
Here: https://github.com/pypa/virtualenv/pull/1382

**Comment by gaborbernat** [comment]
we'll need to exam again this issue with the rewrite

**Comment by gaborbernat** [comment]
This seems to be resolved with the rewrite.
