### ISSUE TITLE
Connection closed by remote host when installing with pip and python 2.7

### ISSUE THREAD

**Issue by Zomhad** [pypa/virtualenv#1355]
Hi,
I'm trying to install virtualenv on Win10 with the latest Python 2.7 (2.7.16) and pip (19.1.1). Both seem to work fine, as I get a usual response when doing "python --version" or "pip --version". However when trying to do "pip install virtualenv" I always get this error: 

C:\Windows\system32>pip install virtualenv
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting virtualenv
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, 'Current connection closed by remotehost'))': /simple/virtualenv/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, 'Current connection closed by remotehost'))': /simple/virtualenv/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, 'Current connection closed by remotehost'))': /simple/virtualenv/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, 'Current connection closed by remotehost'))': /simple/virtualenv/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, 'Current connection closed by remotehost'))': /simple/virtualenv/
  ERROR: Could not find a version that satisfies the requirement virtualenv (from versions: none)
ERROR: No matching distribution found for virtualenv

C:\Windows\system32>

I already reinstalled Python and tried again, disabled my antivirus and had a good Google, but nothing seems to work and I can't find this error...

**Comment by gaborbernat** [comment]
This is a pip issue not, virtualenv. Please open the issue under https://github.com/pypa/pip
