### ISSUE TITLE
pip.exe changes on Windows

### ISSUE THREAD

**Issue by digulla** [pypa/virtualenv#1368]
Not sure whether this is a bug or feature but the file pip.exe changes on Windows (and on Linux) when virtualenv copies it into Scripts\ folder (virtualenv puts the absolute path into the exe). The same happens for wheel.exe and easy_install.exe.

This confuses our Anti-virus. Since pip downloads stuff from the Internet, it would be great to make sure no one tampered with it.

I'm thinking of using `python -m pip` as a workaround but I'd like to hear your opinion on this. Shell scripts can detect the folder of the script. pip should be able to do the same.

**Comment by gaborbernat** [comment]
> Not sure whether this is a bug or feature but the file pip.exe changes on Windows (and on Linux) when virtualenv copies it into Scripts\ folder (virtualenv puts the absolute path into the exe). The same happens for wheel.exe and easy_install.exe.

This is not done by virtualenv, but pip whom we ask to install the seed packages. So the issue/feature request should be there.

**Comment by digulla** [comment]
Done: https://github.com/pypa/pip/issues/7528
