### ISSUE TITLE
CI failing: ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by jayvdb** [pypa/virtualenv#1374]
Im pretty sure the failures on https://github.com/pypa/virtualenv/pull/1373 are unrelated to the content of the PR.

My guess is the recent release of tox is the cause.

**Comment by pradyunsg** [comment]
It's not you, it's not tox, it's the CI service: https://developercommunity.visualstudio.com/content/problem/588219/sqlite3-importerror-python-357-and-373.html

:)

**Comment by gaborbernat** [comment]
Not much we can do about this on our side
