### ISSUE TITLE
crash attempting to symlink when it is not supported (msys python)

### ISSUE THREAD

**Issue by asottile** [pypa/virtualenv#1378]
```console
$ virtualenv --version
16.6.1
$ virtualenv myvenv
Using base prefix '/usr'
New python executable in /tmp/pre-commit/myvenv/bin/python3.exe
Also creating executable in /tmp/pre-commit/myvenv/bin/python.exe
Traceback (most recent call last):
  File "/tmp/pre-commit/venv/bin/virtualenv", line 10, in <module>
    sys.exit(main())
  File "/tmp/pre-commit/venv/lib/python3.7/site-packages/virtualenv.py", line 862, in main
    symlink=options.symlink,
  File "/tmp/pre-commit/venv/lib/python3.7/site-packages/virtualenv.py", line 1137, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/tmp/pre-commit/venv/lib/python3.7/site-packages/virtualenv.py", line 1648, in install_python
    os.symlink(py_executable_base, full_pth)
FileNotFoundError: [Errno 2] No such file or directory: 'python3.exe' -> '/tmp/pre-commit/myvenv/bin/python3'
```

This seems to happen [here](https://github.com/pypa/virtualenv/blob/d997faa8d44887508df0bb36e1b43b743d455925/virtualenv.py#L1648) -- I see similar guards around symlinking done [here](https://github.com/pypa/virtualenv/blob/d997faa8d44887508df0bb36e1b43b743d455925/virtualenv.py#L416-L418) though not in this case

as far as I can tell, the `symlink` in this (odd) platform succeeds if the files exist at the time of symlinking, but fail otherwise (?)

- **`sys.version`**: `'3.7.3 (default, Apr 25 2019, 06:50:16) \n[GCC 7.4.0]'`
- **`os.name`**: `'posix'`
- **`sys.platform`**: `'msys'`
- **`platform.system()`**: `'MINGW64_NT-10.0-17134'`
- **`platform.python_implementation()`**: `'CPython'`
- **`sys.implementation.name`**: `'cpython'`
- **`sysconfig.get_platform()`**: `'mingw64_nt-10.0-17134-3.0.7-338.x86_64-x86_64'`

**Comment by gaborbernat** [comment]
We'll need to check if this will still be the case with the rewrite in the pipeline. Until then it goes on hold the issue.

**Comment by asottile** [comment]
yeah no problem, there's something very strange with this cygwin-like python 🤔

**Comment by zcodes** [comment]
```py
     if not IS_WIN:
        # Ensure that 'python', 'pythonX' and 'pythonX.Y' all exist
        py_exe_version_major = "python{}".format(sys.version_info[0])
        py_exe_version_major_minor = "python{}.{}".format(sys.version_info[0], sys.version_info[1])
        py_exe_no_version = "python"
        required_symlinks = [py_exe_no_version, py_exe_version_major, py_exe_version_major_minor]

        py_executable_base = os.path.basename(py_executable)

        if py_executable_base in required_symlinks:
            # Don't try to symlink to yourself.
            required_symlinks.remove(py_executable_base)

        for pth in required_symlinks:
            full_pth = join(bin_dir, pth)
            if os.path.exists(full_pth):
                os.unlink(full_pth)
            if symlink:
                os.symlink(py_executable_base, full_pth)
            else:
                copyfile(py_executable, full_pth, symlink)
```

I think these code in virtualenv.py cause this issue, on msys2, the python executable is end with ".exe", so the py_executable_base (python.exe or python3.exe) here is not execulde from required_symlinks, the installed python is unlinked by `os.unlink(full_pth)`.

**Comment by danyeaw** [comment]
This is fixed downstream: https://github.com/msys2/MINGW-packages/pull/5625

**Comment by gaborbernat** [comment]
We explicitly check for this now upfront, so things should work on the rewrite branch.
