### ISSUE TITLE
Creating virtual env failed with python 3.7.4

### ISSUE THREAD

**Issue by leihuagh** [pypa/virtualenv#1381]
- [Python ] Python 3.7.4
- Windows 10
- Virtualenv 16.6.1

Try to create a virtual environment using 
- virtualenv env
Then got unending messages
![virtualenv](https://user-images.githubusercontent.com/6012153/61017589-c2640200-a361-11e9-9098-f434a174164c.PNG)

**Comment by 0msLaw** [comment]
I'm having the same issue with Python 3.7.4
Windows 10
Virtualenv 16.6.1

**Comment by pfmoore** [comment]
Duplicate of #1380
