### ISSUE TITLE
macOS: "OSError: [Errno 62] Too many levels of symbolic links"

### ISSUE THREAD

**Issue by c0d3h4x0r** [pypa/virtualenv#1401]
My company takes the official Python release package for MacOS from python.org, installs/extracts the entire Python.framework folder, and then runs a shell script against it to make it relocatable (by replacing hard-coded absolute paths with paths relative to the folder location as defined by an environment variable that points to that folder location).  This is how we enable our build pipeline to bootstrap its own exact toolchain requirements independent of whatever happens to be installed on the machine.  Our build pipeline pulls down the relocatable Python we've created, then uses it to build out a virtual environment containing all prerequisite packages.  This system was developed in-house, and we're a closed-source workshop, so I'm not able to share any of our code with you for this issue report.

Incidentally, we do preserve the `Python.framework` folder itself so that it continues to appear in `sys.prefix` no matter where the `Python.framework` folder may reside, since `virtualenv.py` contains some sketchy logic that appears to rely on (rather than a proper platform check) to know it's dealing with MacOS.

While working in our build pipeline code, I've run into the error mentioned in the issue title, and by debugging it in PyCharm, I've tracked it down to its root cause.

In virtualenv==16.7.2, in virtualenv.py, at line 1661, you'll find the following code:

```
        if py_executable_base in required_symlinks:
            # Don't try to symlink to yourself.
            required_symlinks.remove(py_executable_base)
```

This code is not working as intended on MacOS.  The actual Python executable (`py_executable_base`) on MacOS is literally named `Python` (capitalized), which differs from the required symlink `python` only by case.  Because the MacOS filesystem is not fully case-sensitive (it is case-preserving but not case-matching), `Python` and `python` are not distinct files, so the code subsequently does what the comment above says it shouldn't -- it symlinks `Python` to itself, creating a circular symlink, which causes the "too many symlinks" OSError when line 1681 tries to run it.

EDIT: I suspect the real problem is earlier, in the following chunk of code:

```
    if 'Python.framework' in prefix:
        # OS X framework builds cause validation to break
        # https://github.com/pypa/virtualenv/issues/322
        if os.environ.get('__PYVENV_LAUNCHER__'):
            del os.environ["__PYVENV_LAUNCHER__"]
        if re.search(r'/Python(?:-32|-64)*$', py_executable):
            # The name of the python executable is not quite what
            # we want, rename it.
            py_executable = os.path.join(
                    os.path.dirname(py_executable), 'python')
```

That regex chunk should probably always apply if running on macOS, regardless of whether `Python.framework` is in `prefix` or not, like so:

```
    if 'Python.framework' in prefix:
        # OS X framework builds cause validation to break
        # https://github.com/pypa/virtualenv/issues/322
        if os.environ.get('__PYVENV_LAUNCHER__'):
            del os.environ["__PYVENV_LAUNCHER__"]

     if IS_DARWIN and re.search(r'/Python(?:-32|-64)*$', py_executable):
         # The name of the python executable is not quite what
         # we want, rename it.
         py_executable = os.path.join(
                 os.path.dirname(py_executable), 'python')
```

**Comment by c0d3h4x0r** [comment]
You can see that other folks have hit this issue out in the wild too, so it's not just us: https://github.com/tensorflow/tensorflow/issues/11037

**Comment by gaborbernat** [comment]
I think this should be solved by the rewrite branch, please confirm and if not we'll reopen.
