### ISSUE TITLE
Virtualenv --clear installs system python not env python version

### ISSUE THREAD

**Issue by themmes** [pypa/virtualenv#1406]
**To reproduce:**

1. virtualenv env -p python3.6
2. source env/bin/activate
3. pip install pandas
4. deactivate
5. virtualenv --clear env
6. python --version

In my case returns `Python 3.5.2` instead of the expected `Python 3.6.9`. It seems virtualenv does detect Python3 being used, but not takes correct version.

**Environment**

Linux Xenial 16.04
System python: Python 2.7.12
Used python: Python 3.6.9

Thanks for taking the time to read this, I love virtualenv and use it every single day. Would like to submit PR if you can point me to where to start?

**Comment by tobiasherp** [comment]
Are you sure there is not Python 3 installed anywhere in the system?
Have your tried `which python`?
