### ISSUE TITLE
Python.exe evoke is working, but python not, same appears to other binary files in scripts dir

### ISSUE THREAD

**Issue by HoshiYamazaki** [pypa/virtualenv#1413]
I use Windows 10 and PyCharm Pro, and I don't know why (seriously) Windows can't evoke Python without .exe extension.

So I tried to debug that - there is my log of working on it:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004952619-PyCharm-does-not-see-python-pip-without-exe-extension-under-Windows-10-Home

So basically at first I had Windows python path defined to Microsoft Store shortcut, which I removed from global Windows variables. Then, I tried to use `python`/`pip` without extension and it evoked global `python`/`pip` from PATH win variable, so I removed it and I can do only now call `python.exe` or `pip.exe` to run them via venv.

Also, I saw there is `PATHEXT` variable, which contains extensions that can be evoked from command line, but it contains default string option.

I have broken Windows installation or what?
This are my `set` variables:
https://pastebin.com/FEUSYZLR

This is little irritating to evoke every time python with .exe. I assume it's not certainly `virtualenv` bug, I think this is probably Windows (installation) issue (?) but something is wrong.

I tried to reinstall Python and PyCharm also, I can't reinstall Windows (because I have data on it) though.

**Comment by gaborbernat** [comment]
This should work from within shells, how you're calling it?
