### ISSUE TITLE
Virtualenv not working with some distros' pip.conf (fix proposal)

### ISSUE THREAD

**Issue by zabealbe** [pypa/virtualenv#1416]
Hello!

Today i had this error
`ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`
which really confused me as there was no --user in my command
`(venv) user$ pip install numpy`

So I searched a bit on google but unfortunately i didn't find anything helpful.
I decided to take a look into pip source code and found that there is a config (never touched it before so It's the first time I hear about it), in my case in /etc/pip.conf (Linux Manjaro)

> [global]
> user = true

Although I agree that installing modules in the user's directory is safer, I think that this configuration might be a problem for a lot of users specially because if you get that error you won't find any solution searching for it.
So my proposal is to include a pip.conf inside the venv by default:

> [global]
> user = false

**Comment by pfmoore** [comment]
I would argue that this is a misconfiguration on the part of the distribution. Well-intentioned, perhaps, but not properly thought through. So it's probably something that should be raised with the distro in the first instance.

Note also that pip is looking at improving this - see https://github.com/pypa/pip/issues/4575 which links a number of other issues but is a good place to start from.

I'm not at all sure that virtualenv is the right place to fix this (for a start, it wouldn't help users of the stdlib venv module, who presumably have the same issue).

**Comment by zabealbe** [comment]
> I would argue that this is a misconfiguration on the part of the distribution. Well-intentioned, perhaps, but not properly thought through. So it's probably something that should be raised with the distro in the first instance.
> 
> Note also that pip is looking at improving this - see [pypa/pip#4575](https://github.com/pypa/pip/issues/4575) which links a number of other issues but is a good place to start from.
> 
> I'm not at all sure that virtualenv is the right place to fix this (for a start, it wouldn't help users of the stdlib venv module, who presumably have the same issue).

Indeed they do have the same issue, but the behavior is much different, it actually installs the modules in user directory but then python can't find them, it's a mess.
My main goal was to help the next person searching for this on Google as I lost way too much time on that

**Comment by gaborbernat** [comment]
This feels like a pip issue, so I'll close.
