### ISSUE TITLE
coolprop failed installation on matlab

### ISSUE THREAD

**Issue by paolo1911** [pypa/virtualenv#1417]
Good morning. 
I'm currently trying to install CoolProp library on my Matlab environment.(Just to be clear my PC has the windows 10 software)
I've followed the instructions provided on the official website. So I installed the Anaconda python interpreter and I can succesfully load it on Matlab.
But at the moment of installing coolprop a mistake related to the TLS/SSL module occurs and I  can't go on with the procedure. 
I share a screenshot of the mistake so that you can make an idea yourselves.
Does anyone have the same problem?
![screenshot](https://user-images.githubusercontent.com/55240358/64786522-dd740d80-d56e-11e9-87cc-0cb0b201605b.JPG)
Thanks for Your help!

**Comment by gaborbernat** [comment]
This means your python does not have SSL module. Such use case is not supported.
