### ISSUE TITLE
Windows activate is in the wrong folder

### ISSUE THREAD

**Issue by earonesty** [pypa/virtualenv#1418]
- currently when creating a venv, the "sourceable" bash activate script is located in either bin/ or Scripts/ depending on whether you're running windows

- mingw CI runners, users of Git bash and anyone who develops on multiple platforms would deeply appreciate at least a *copy* of the Scripts/activate file be placed in bin/activate

- be happy to do the PR, if others agree

**Comment by gaborbernat** [comment]
I think we should allow this to happen on user request, but cannot be the default; as that would mean we would out of box behave differently than the core venv. Feel free to create PR on top of the rewrite branch.

**Comment by earonesty** [comment]
i'd like to note that this was discussed in core: https://bugs.python.org/issue35003.   mostly closed because of lack of interest and some confusion about moving vs copying vs optionality

**Comment by gaborbernat** [comment]
The solution I can see here is to keep Scripts, that's needed for pip install and etc. However it would be reasonable to have an option to also generate bin that's just a junction for Scripts.

**Comment by earonesty** [comment]
i submitted a draft pr to core that does copy/link `scripts/activate` to `bin/activate` (probably won't happen but)

**Comment by gaborbernat** [comment]
I think copying would be a mistake the junction sounds like the good decision as that would be automatically kept in sync. Can you link the PR you've submitted it?

**Comment by earonesty** [comment]
Links to the PR and discussion are at the core issue ticket.

**Comment by gaborbernat** [comment]
So it's https://github.com/python/cpython/pull/18083.

**Comment by anton-danielsson** [comment]
This would be really useful.
Having both `Scripts/activate` to `bin/activate` would makes things so much easier for generic scripts running on both Windows and Linux/POSIX.
Vote to revisit https://github.com/python/cpython/pull/18083

**Comment by gaborbernat** [comment]
Closing as upstream rejected it.
