### ISSUE TITLE
Virtualenv does not work with Windows x86 embeddable zip file

### ISSUE THREAD

**Issue by ChadBailey** [pypa/virtualenv#1453]
I put together a detailed bug report in tox, so I'm going to link to it. I hope that is sufficient.

The long story short is, virtualenv does not support the windows embeddable zip file format. I suspect the issue is caused by python internally treating the site packages zip file as if it's a mounted directory and virtualenv trying to copy the site packages folder which doesn't actually exist.

https://github.com/tox-dev/tox/issues/1465

**Comment by pfmoore** [comment]
The embeddable zip format is not intended for this sort of usage, so this is unlikely to be something that will ever be supported. See [the documentation](https://docs.python.org/3/using/windows.html#the-embeddable-package) for more clarification on intended uses.

**Comment by gaborbernat** [comment]
This is definitely stretching the possibilities. I would not say definitely not, though just yet. In a post rewrite world maybe we can have a look at how feasible this would be e.g. for running tox test suits (even though they were not designed for this entirely).

**Comment by pfmoore** [comment]
The embeddable distribution doesn't include venv...

**Comment by gaborbernat** [comment]
It doesn't have to, virtualenv is capable of creating virtual environments without venv if the underlying technology allows it.

**Comment by pfmoore** [comment]
Sorry - good point (I was mistakenly assuming that the fact that the virtualenv rewrite used the core virtual environment mechanisms "under the hood" meant that it needed venv - which is obviously not the case in retrospect).

So yes, it might be possible to do this in the future. It seems to me that it would be a lot of work to allow a usage that the core Python team wouldn't support, but that's up to you.

FWIW, I would have thought that the nuget distribution would be a better match for the OP's original (tox) use case, assuming there's a reason why a normal Python installation isn't suitable.

**Comment by ChadBailey** [comment]
I can see many use cases for this use pattern, not the least of which is the absence of admin access on the local PC. That said, I didn't file this report to advocate for this usage pattern - just to simply bring awareness to this limitation existing. Whether to fix it or not isn't terrible important to me - I'd prefer just using whatever the typical usage pattern is for this.

The reason I was trying this was because I was trying to find the "most best" way of satisfying having that many installs of python for testing purposes. When I say "most best", I mean that it is typical for me to gravitate towards small self-contained environments for needs like this. I won't actually be needing all of these python installs for actual use, so I'd prefer an easy drop-in solution that involves the least amount of effort/system modification possible.

That said, I will confess I have no idea what you mean by the "nuget distribution". I am only vaguely familiar with "nuget", in that it's .NET and that's as far as I wanted to go with that. I am not a .NET developer and have no current need/desire to learn that ecosystem. That said, perhaps now I have a need if you're saying using nuget is the "most best" way to have multiple concurrent python installations for use with tox

**Comment by pfmoore** [comment]
https://docs.python.org/3.7/using/windows.html#the-nuget-org-packages

**Comment by ChadBailey** [comment]
Excellent, thanks for the pointer! Looks like this is probably what I was after.

**Comment by gaborbernat** [comment]
Will close this for now then 👍
