### ISSUE TITLE
have not deactivate command in virtualvenv  bin dir

### ISSUE THREAD

**Issue by huangyanxiong01** [pypa/virtualenv#1457]
Thanks for submitting an issue!

If submitting a BUG please provide:

- [x] Minimal reproducible example or detailed descriptions
```bash
 virtualenv -p  python3.7 .venv
➜  bin git:(master) ✗ ls
activate  activate.csh  activate.fish  activate.ps1  activate.xsh  activate_this.py  easy_install  easy_install-3.7  pip  pip3  pip3.7  python  python-config  python3  python3.7  wheel
```
- [x] OS and `pip list` output
`os`
```bash
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
`pip lst`
```bash
Package        Version  
-------------- ---------
asn1crypto     0.24.0   
certifi        2019.9.11
chardet        3.0.4    
colorclass     2.2.0    
cryptography   2.1.4    
docopt         0.6.2    
enum34         1.1.6    
idna           2.8      
ipaddress      1.0.17   
keyring        10.6.0   
keyrings.alt   3.0      
packaging      19.2     
pip            19.3.1   
pip-upgrader   1.4.15   
pycrypto       2.6.1    
pygobject      3.26.1   
pyparsing      2.4.4    
pyxdg          0.25     
requests       2.22.0   
SecretStorage  2.3.1    
setuptools     39.0.1   
six            1.13.0   
terminaltables 3.1.0    
urllib3        1.25.6   
virtualenv     16.7.8   
wheel          0.30.0 
```

if submitting an ENHANCEMENT issue:

- [ ] a clear problem statement with an example
- [ ] suggested change with example
- [ ] if you have want help to do a PR yourself

**Comment by pfmoore** [comment]
The activate script defines a shell function to do the deactivate, so there's no need for a script.

**Comment by gaborbernat** [comment]
Only the batch script runner works like that, but that's windows only. For that, we do generate a deactivate script. For all other shells, the deactivation happens by defining a function during the activation that allows redoing the activation operation. So long story short, the deactivation is not done by script call but by rather simply typing in deactivate and hitting enter (unless you're using the batch script mode - aka cmd.net on Windows).

**Comment by huangyanxiong01** [comment]
@pfmoore @gaborbernat thanks for your quick response, I understanded
