### ISSUE TITLE
add zipapp support

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#1464]
We need to support a zipapp deploy format.

> @asottile: setuptools ran into the exact same issues when unvendoring -- it might make sense to bundle wheels for these dependencies?

**Comment by gaborbernat** [comment]
@asottile any reason why this can't just be a pex?

**Comment by asottile** [comment]
I seem to remember pex doesn't have windows support but I could be misremembering -- there's also the additional issue of native dependencies (if any exist, I don't know quite what the tree has expanded to for `virtualenv`)

**Comment by gaborbernat** [comment]
yeah just found out Windows support is hacky at best; I'll take a look how we can generate a zipapp with dependencies 🤔

**Comment by pfmoore** [comment]
[Shiv](https://pypi.org/project/shiv/) might be worth a look. I used shiv for a while to package the old virtualenv, and it worked pretty well.

**Comment by gaborbernat** [comment]
Seems to be also just Python 3.6+ and no windows as I understood.

**Comment by pfmoore** [comment]
Shiv definitely works on Windows. But may well not support 2.7, I didn't need that.

**Comment by gaborbernat** [comment]
Solved via https://github.com/pypa/virtualenv/pull/1491, supporting python 2.7 & 3.4-3.9 👍 cpyhton and pypy
