### ISSUE TITLE
python3.4 on CI

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#1472]
So officially we would like to support python3.4 for one more year; however, Azure decided to remove python3.4 from it's CI matrix very soon after the upstream deprecation. Now we can't test python3.4; we need to look into if and how we can still run these CI environments (with potentially not running coverage under them, as they can't be merged back).

**Comment by gaborbernat** [comment]
Having had a good thought about this we might defer this to a post 20.0.0 world 🤔

**Comment by gaborbernat** [comment]
Yeah, defer to 20.1.0 🤷‍♂ , for now, I'll run int manually before release.

**Comment by pradyunsg** [comment]
Travis CI has pyenv installed on their CI systems, which can be used to install + test, on Ubuntu at least. It'd be a good idea to add that, until we figure out a more "full" solution for this.

**Comment by asottile** [comment]
deadsnakes has bionic python3.4 packages if you want to try that route as well

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
