### ISSUE TITLE
[Rewrite] Creating a Python 2.7 environment does not copy python27.dll

### ISSUE THREAD

**Issue by pfmoore** [pypa/virtualenv#1484]
To reproduce, start with an environment with no Python 2.7 installed.

* Get the 2.7.17 MSI installer from python.org and run it.
* Select the "install just for me" option (the default option to install globally puts `python27.dll` in the windows directory, which masks the bug).
* Choose all defaults, but **deselect** "Register extensions" and "Add Python to PATH".
* `C:\Python27\python.exe -m pip install virtualenv-rewrite.whl` (I built the rewrite branch to a local wheel file and installed that, you can probably install the rewrite branch any way you like).
* `C:\Python27\python.exe -m virtualenv xx`

Now look in `xx\Scripts` and there is no `python27.dll` file. Running `xx\Scripts\python.exe` fails with an error "python27.dll not found".

**Comment by gaborbernat** [comment]
Yeah, this seems like something we need to fix; I'll tackle this and other feedback issues after #1482, which turned out a lot harder than expected (pypy unicode support with files has lot of gaps compared to CPython 😢) Thanks!
