### ISSUE TITLE
support quotes in paths

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#1488]
based on feedback https://github.com/pypa/virtualenv/pull/1481#discussion_r363312122 from @asottile 

> right, but now it can't work with single quotes within the path -- using pipes.quote when substituting will make both of them work here

**Comment by frenzymadness** [comment]
Just a note: `pipes` module will be removed from stdlib in Python 3.13, see: https://docs.python.org/3.11/whatsnew/3.11.html

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
