### ISSUE TITLE
Need pydoc in $VIRTUALENV/bin

### ISSUE THREAD

**Issue by krid** [pypa/virtualenv#149]
The bin directory should include a pydoc executable:

```
#!/usr/bin/env python

import pydoc
if __name__ == '__main__':
     pydoc.cli()
```

**Comment by blueyed** [comment]
Should I open a new issue for the comment above?

**Comment by Ivoz** [comment]
`pydoc` is now included in virtualenv scripts as a shell function for unix activate scripts

**Comment by pravic** [comment]
How about Windows activate scripts?

**Comment by rsd** [comment]
Try this:
`alias pydoc="python -m pydoc"`
[https://notoriousno.blogspot.com/2016/09/python-alias-commands-that-play-nice.html](url)

**Comment by pravic** [comment]
`alias`? On Windows?

**Comment by rsd** [comment]
`doskey pydoc=python -m pydoc`

**Comment by blueyed** [comment]
I've mentioned it before already, but an alias/shell function is different from an executable.

As of now pyenv-virtualenv creates a pydoc executable itself, and in general some custom shell wrapper that calls `python -m pydoc` should do:

```sh
#!/bin/sh

python -m pydoc "$@"
```
