### ISSUE TITLE
activate.sh fails if 'nounset' option is set

### ISSUE THREAD

**Issue by billputer** [pypa/virtualenv#150]
I get the following error when I try to activate a virtualenv.

```
$ source test-env/bin/activate
-bash: _OLD_VIRTUAL_PATH: unbound variable
```

This is happening because I've configured Bash to use the *nounset* option, which throws an error when accessing unset variables (see [here](http://tldp.org/LDP/abs/html/options.html))

**Comment by blueyed** [comment]
This might be fixed by https://github.com/pypa/virtualenv/pull/723, which uses `if ! [ -z "${_OLD_VIRTUAL_PATH+x}" ] ; then`.

Please note that `$_OLD_VIRTUAL_PATH` itself is meant to be removed in #722 though.  But #723 fixes it for the other vars, too.

**Comment by b-long** [comment]
:+1:

**Comment by JordanP** [comment]
I am hitting this too....

**Comment by pottmi** [comment]
It is kinda weird that such a easy problem is not fixed after four years.
beaumartinez's work-a-round is the most simple for now.

**Comment by alex** [comment]
This is fixed by #645.

**Comment by dstufft** [comment]
Fixed

**Comment by ssbarnea** [comment]
@dstufft could you please specify in which release was this fixed so we can assure that we have the minimal needed version installed? From the bug is not clear at all regarding which release includes the fix.

**Comment by pfmoore** [comment]
@ssbarnea It was fixed on 12 Aug 2015, as noted in the comments above, so any version released after that date. From https://virtualenv.pypa.io/en/latest/changes/ that means 13.1.1 (and indeed the note for that version mentions this change specifically). All of that information is easily available, so you could probably have found it with a brief search (that's what I did).

**Comment by ssbarnea** [comment]
I have some bad news: this bug should be reopened because now I get `activate: line 13: _OLD_VIRTUAL_PYTHONHOME: unbound variable` and while fixing this I think there is critical to introduce a test that does attempt to activate the virtual environment using [strict bash](http://redsymbol.net/articles/unofficial-bash-strict-mode/)

**Comment by ssbarnea** [comment]
This also applies to `line 22: ZSH_VERSION: unbound variable`... and wondering how long the list would go... my workaround command line starting to look perverse:
```
PS1="${{PS1:-}}" _OLD_VIRTUAL_PATH="${{_OLD_VIRTUAL_PATH:-}}" _OLD_VIRTUAL_PYTHONHOME="${{_OLD_VIRTUAL_PYTHONHOME:-}}" source "$VENV/bin/activate"
```

**Comment by pfmoore** [comment]
You can of course just set up the environment yourself, or use the full pathname of the Python executable.

**Comment by ssbarnea** [comment]
Sorry for reopening the discussion on this, I made the mistake of not checking the versions of virtualenv that we had on the build server and I made an ugly discovery, an ancient version 1.10.1. This would count for lots of bugs. I am going to upgrade it tomorrow.

**Comment by pottmi** [comment]
No apology necessary; In fact I learned a few things from this revived
conversation.

**Comment by ssbarnea** [comment]
It seems that the bug still exists even in the current release, so I raise it as https://github.com/pypa/virtualenv/issues/1029

**Comment by allan-simon** [comment]
it's fixed now https://github.com/pypa/virtualenv/pull/922
