### ISSUE TITLE
Default verbosity on v20.0.0b1/Win10 gives no output; '-v' gives too much to serve as a concise summary of the actions taken

### ISSUE THREAD

**Issue by bskinn** [pypa/virtualenv#1510]
A bit more output in the default verbosity would be nice; perhaps not identical to the prior incarnation, but on that level of detail.

**Thank you** for all the work on this!!

----

Windows 10, virtualenv 16.7.9:

```
C:\Temp>python3.6 -m virtualenv envtest2 --prompt="(envtest2) "
Using base prefix 'C:\\...\\Python36'
New python executable in C:\Temp\envtest2\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

C:\Temp>
```

virtualenv 20.0.0b1:

```
C:\Temp>python3.7 -m virtualenv envtest --prompt="(testenv) "

C:\Temp>
```

virtualenv 20.0.0b1, with `-v` flag:

```
C:\Temp>python3.7 -m virtualenv envtest --prompt="(testenv) " -v
find interpreter for spec PythonSpec(str_spec=C:\...\Python37\python.exe, path=C:\...\Python37\python.exe)
proposed PythonInfo(spec=CPython3.7.4.final.0-64, exe=C:\...\Python37\python.exe, platform=win32, version='3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)
accepted target interpreter PythonInfo(spec=CPython3.7.4.final.0-64, exe=C:\...\Python37\python.exe, platform=win32, version='3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)
create virtual environment via CPython3Windows(dest=envtest, global=False, clear=False)
add seed packages via FromAppData pip=latest setuptools=latest wheel=latest app_data_dir=ReentrantFileLock(C:\...\pypa\virtualenv\seed-v1)
add activators for Batch, PowerShell, Python, Xonsh
done in 4607ms

C:\Temp>
```

**Comment by pfmoore** [comment]
I actually like the new "quiet" default.

**Comment by bskinn** [comment]
I'm sure I'll get used to it if that's where it stays, but I'd prefer at least a short happy-path `Environment created` or `Environment created in {PATH}` message.

CLIs that don't say *anything* about what they've done make me a bit antsy.

**Comment by gaborbernat** [comment]
@rbtcollins dunno; not having output if there's no warn/error seems to be sensible. Neither mkdir, touch, rm commands print stuff 🤔 It's more in Linux Mantra.

**Comment by gaborbernat** [comment]
The single -v prints one line per phase (5 overall), so I think it's sane IMHO. 🤔

**Comment by bskinn** [comment]
Yeah, but creating a virtualenv is a more complex operation than those POSIX commands are.

No, sorry, I wrote poorly -- I think the output that `-v` produces is great for a `-v` invocation. It's just that there's no middle ground between no output by default, and the `-v` output with `-v`.

**Comment by bskinn** [comment]
More broadly, apologies for diving right into a bikeshedding discussion -- it's working so well so far that this level of nitpick is the only issue I've had!

**Comment by gaborbernat** [comment]
There were a few duplicate information on the single verbosity, addressed part of https://github.com/pypa/virtualenv/pull/1511

**Comment by gaborbernat** [comment]
I'll close this now as I tend to agree with @pfmoore that the quiet mode by default is fine. It also mirrors how venv operates. If more people will comment on this issue we might add some type of report generation in some shape or form.
