### ISSUE TITLE
20b1: problems with editable installs

### ISSUE THREAD

**Issue by mgedmin** [pypa/virtualenv#1517]
I've decided to try running `tox` on [all the Python projects I maintain](https://projects.gedmin.as/) with virtualenv 20.0.0b1, to check for regressions in the new beta.  Three of the projects failed, all on Python 2.7:

- gtimelog (python: No module named gtimelog)
- irclog2html (ImportError: No module named zope.testrunner)
- zodbbrowser (ImportError: No module named zope.testrunner)

Here's how to reproduce the gtimelog issue:

- git clone https://github.com/gtimelog/gtimelog
- virtualenv -p python2.7 /tmp/venv
- /tmp/venv/bin/pip install -e gtimelog --no-deps
- /tmp/venv/bin/python -c 'import gtimelog'

I expect: no output, the import should succeed.

I get

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gtimelog
```

The `--no-deps` to pip install is there to make the test simpler and faster; I get the same failure if I do a full `pip install -e gtimelog`.

I'll create a separate bug for the irclog2html/zodbbrowser issue (they're the same issue): #1518.

I'm on Ubuntu 19.10.  I installed virtualenv 20.0.0b1 with `pipx install --pip-args=--pre` using my system Python 3.7.  `pipx runpip virtualenv list` produces

```
Package            Version 
------------------ --------
appdirs            1.4.3   
filelock           3.0.12  
importlib-metadata 1.5.0   
pip                20.0.2  
pkg-resources      0.0.0   
setuptools         45.1.0  
six                1.14.0  
virtualenv         20.0.0b1
wheel              0.34.1  
zipp               2.1.0   
```

**Comment by mgedmin** [comment]
One difference between virtualenv-created-with-20b1 and virtualenv-created-with-15 appears to be in sys.path: the working virtualenv has ~/src/gtimelog/src in it, the non-working one doesn't.

They both have identical easy-install.pth files in site-packages, and they both have identical gtimelog.egg-link files.

Could it be that the core problem with both this and #1518 is that `*.pth` files are not processed in the virtualenv's site-packages directory in virtualenvs created with 20b1 on Python 2.7?

**Comment by gaborbernat** [comment]
@mgedmin we no longer ship our own site.py but rather use the host ``site.py``, so in theory, it well could be that Ubuntu decided to not honour pth files in their ``site.py`` which causes the issue. This also explains why I can't reproduce this on macOS.

**Comment by gaborbernat** [comment]
I think https://github.com/pypa/virtualenv/pull/1521 solves this. Please can you validate?

**Comment by mgedmin** [comment]
Yes, #1521 fixes this.
