### ISSUE TITLE
20b1: problems with namespace packages

### ISSUE THREAD

**Issue by mgedmin** [pypa/virtualenv#1518]
I've decided to try running `tox` on [all the Python projects I maintain](https://projects.gedmin.as/) with virtualenv 20.0.0b1, to check for regressions in the new beta.  Three of the projects failed, all on Python 2.7:

- gtimelog (python: No module named gtimelog; I've created #1517 for this one).
- irclog2html (ImportError: No module named zope.testrunner)
- zodbbrowser (ImportError: No module named zope.testrunner)

Here's how to reproduce the irclog2html/zodbbrowser issue (they're the same issue):

- virtualenv -p python2.7 /tmp/venv
- /tmp/venv/bin/pip install zope.testrunner
- /tmp/venv/bin/python -c 'import zope.testrunner'

I expect: no output, the import should succeed.

I get

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named zope.testrunner
```

I suspect this was caused by `zope` being a namespace package.  Incidentally `import zope` also fails.  There's no `__init__.py` in the `/tmp/venv/lib/python2.7/site-packages/zope` directory.

I'm on Ubuntu 19.10.  I installed virtualenv 20.0.0b1 with pipx install using my system Python 3.7.
`pipx runpip virtualenv list` produces

```
Package            Version 
------------------ --------
appdirs            1.4.3   
filelock           3.0.12  
importlib-metadata 1.5.0   
pip                20.0.2  
pkg-resources      0.0.0   
setuptools         45.1.0  
six                1.14.0  
virtualenv         20.0.0b1
wheel              0.34.1  
zipp               2.1.0   
```

**Comment by mgedmin** [comment]
For the record, when I create a virtualenv using an older version of virtualenv (15.1.0, packaged by Ubuntu 19.10), there's also no `__init__.py` in site-packages/zope.  The namespace package magic is done via site-packages/zope.*-nspkg.pth files, and they're the same in both virtualenvs.

**Comment by gaborbernat** [comment]
I think https://github.com/pypa/virtualenv/pull/1521 solves this. Please can you validate?

**Comment by mgedmin** [comment]
Yes, #1521 fixes this.

(Why does virtualenv on that branch say it is version 0.1.dev51+gd23e5ac?  This makes tox 3.14.3 unhappy, due to its virtualenv>=16.0.0 version constraint.  Anyway, that's immaterial and pip doesn't enforce version constraints anyway, only warns about them.)

**Comment by gaborbernat** [comment]
Probably does not pull in the git tags 🤔 how did you install the branch version?

**Comment by mgedmin** [comment]
```
git clone https://github.com/pypa/virtualenv
cd virtualenv
git pr 1521  # an alias that does git fetch origin +refs/pull/1521/head:refs/remotes/origin/pull/1521 && git checkout pull/1521
pipx runpip virtualenv install -e .
```

and yeah, there are no tags in the git history of this particular branch.
