### ISSUE TITLE
20b1: --download / --no-download help text is ambiguous

### ISSUE THREAD

**Issue by asottile** [pypa/virtualenv#1525]
```
  --download                         download latest pip/setuptools/wheel from PyPi (default: False)
  --no-download, --never-download    download latest pip/setuptools/wheel from PyPi (default: True)
```

my reading of this is that `--no-download` is now the default, but it's potentially a little confusing -- I don't really have any good suggestions on how to format this properly, an ideal formatting would be something like:

```
  --download / --no-download / --never-download    download latest pip/setuptools/wheel from PyPi (default: --no-download)
```

(or something like that)

I will send a PR to correct the casing of PyPI though :)

**Comment by gaborbernat** [comment]
The reason why we have those two separate is to be compatible with virtualenv 16 at the interface level. 🤔 Though maybe we can *hack* argparse to accept to merge those two.

**Comment by gaborbernat** [comment]
Updated message slightly to contain enable/disable feature aspects, see https://virtualenv.pypa.io/en/rewrite/cli_interface.html#download
