### ISSUE TITLE
20b1 feedback: Unable to generate bash "activate" script on Windows.

### ISSUE THREAD

**Issue by vphilippon** [pypa/virtualenv#1527]
Hello!

Working on Windows 10, using Git Bash as my default shell pretty much everywhere.

From my understanding, the bash activation script is not generated by default on Windows anymore.
That's going to break users in a similar solution to mine.

But the really bad news for me:
```
$ python -m virtualenv --activators bash myvirtualenv
usage: virtualenv [--version] [-v | -q] [--discovery {builtin}] [-p py] [--creator {builtin,cpython2-win}] [--seeder {app-data,none,pip}] [--without-pip] [--activators comma_separated_list]
virtualenv: error: argument --activators: the following activators are not available bash
```
`bash` is considered not available on Windows, and that's a no-go for me, or anyone using a bash equivalent on Windows.

I'd plead for keeping bash script by default on Windows.
Or at the very least, allow it as an option, although its still going to be a pain.

Cheers!

**Comment by gaborbernat** [comment]
Does anyone have any idea how we can check if bash is available on Windows?

**Comment by gaborbernat** [comment]
Though maybe we should generate both bash and fish by default all the time 🤷‍♂ https://fishshell.com/ seems to be also available on all platforms.

**Comment by vphilippon** [comment]
FYI I tested the top of the `rewrite` branch and the bash script is present and working on Windows so far.

Thanks!

**Comment by gaborbernat** [comment]
Thanks for testing, we run the bash test on windows too so we should be good going ahead.
