### ISSUE TITLE
virtual environments created via relative paths on Windows creates bad console executables

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#1552]
Seems https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve does not generate the absolute path on Windows, but does everywhere else.

**Comment by gaborbernat** [comment]
An example of this can be seen in our own CIs zipapp/readme tox environments.

**Comment by pradyunsg** [comment]
There is an undocumented `Path.absolute` method, which might be what you want here.

I suggest passing the Path object through a `os.path.realpath(os.path.abspath(path))` though -- it's documented and works exactly like we want it to. (maybe the `abspath` call here is unnecessary?)

**Comment by gaborbernat** [comment]
In my experience resolve is much more reliable in resolving symlinks, so I prefer that; I'm just also invoking absolute which I'm fine, already submitted via #1550

**Comment by pfmoore** [comment]
The only case I know of where `resolve` doesn't give an absolute path is if the file doesn't exist. But that doesn't seem like it would be the case here...?

Can you give an example of the issue? It feels like we might be over-complicating the solution, or missing the actual problem, here 🙁

**Comment by gaborbernat** [comment]
@pfmoore that is the case here 👍

**Comment by pfmoore** [comment]
Ah, OK. Thanks for the clarification. Apologies that I couldn't find that information for myself.

**Comment by gaborbernat** [comment]
Oh and I'm happy to switch back to ``Path.absolute()`` if upstream decided to actually document and support it, but that's still a WIP as I read from those threads
