### ISSUE TITLE
Overview of v20 changes

### ISSUE THREAD

**Issue by rpkilby** [pypa/virtualenv#1562]
Hi. Is there anything documenting the high level changes in v20? I see the proposal in #1366, but it's not clear what's changed/what hasn't/etc... e.g., is the builtin `venv` module used for Python 3 environments? Thanks.

**Comment by gaborbernat** [comment]
https://discuss.python.org/t/virtualenv-20-0-0-beta1-is-available/3077/24

https://virtualenv.pypa.io/en/latest/cli_interface.html#creator

It's there just not default

**Comment by rpkilby** [comment]
Thanks - it might be good to link that or formalize that post into the docs somewhere.

**Comment by gaborbernat** [comment]
Yeah will be done part of fixing this issue, but first we must deal with bugs ☺️

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
