### ISSUE TITLE
virtualenv 20.0.1 breaks mypy CI on windows

### ISSUE THREAD

**Issue by hauntsaninja** [pypa/virtualenv#1566]
Hello!

Sorry for the lazy issue report... I don't currently have access to a Windows machine to debug further but figured maybe reporting the issue sooner might be helpful. The v20 release seems to have broken https://github.com/python/mypy/blob/master/mypy/test/testpep561.py, errors visible at:

https://github.com/python/mypy/pull/8388/checks?check_run_id=437561678
https://github.com/python/mypy/pull/8388/checks?check_run_id=437561694
https://ci.appveyor.com/project/gvanrossum/mypy/builds/30708439

Presumably reproducible using something like https://github.com/python/mypy/blob/master/appveyor.yml#L16

**Comment by gaborbernat** [comment]
I believe this now should be fixed, if not please report more in detail.

**Comment by hauntsaninja** [comment]
Thanks! Can confirm CI runs with 20.0.8 :-)
