### ISSUE TITLE
Support IronPython

### ISSUE THREAD

**Issue by guillermooo** [pypa/virtualenv#159]
I see `virtualenv` supports Jython. Is there any technical reason preventing it from working with IronPython too?

**Comment by afeezaziz** [comment]
@guillermooo Just wondering, it is okay to use virtualenv now with IronPython?

**Comment by ronsmith** [comment]
How about now?

**Comment by manojc99** [comment]
Is there any update on this issue? Does ironpython support virtualenv?

**Comment by zhouwangyang** [comment]
It still seems to be unsupportive at present.

**Comment by gaborbernat** [comment]
This is within the scope of this project. Any PRs trying to add this is welcomed.

**Comment by GhostofGoes** [comment]
Bumping issue to keep alive

**Comment by imsudo** [comment]
Bump

**Comment by gaborbernat** [comment]
The rewrite branch is close to release. I encourage you to try to create a plugin on top of it's plugin system that to support this. Initially let's keep it out of bound (aka you can have it as virtualenv-ironpython project). Once if matures we can pull it in here.

**Comment by gaborbernat** [comment]
virtualenv 20 is now out, I recommend creating a virtualenv-ironpython package that implements ironpython support by subclassing https://github.com/pypa/virtualenv/blob/master/src/virtualenv/create/creator.py
