### ISSUE TITLE
Version output changed

### ISSUE THREAD

**Issue by horriblyUnpythonic** [pypa/virtualenv#1601]
Hi,
I was wondering what the rational for the change in the output of the `--version` flag is. Our salt state for virtualenvs broke because it's expecting an parsable number output from virtualenvs and now the output is something like `virtualenvs 20 from /path/to/lib/__init__.py`. We're not on the latest version of Salt, so it might be a non issue already, but I'm wondering if there is a rationale for this change, or if it aligns better with PEP 440 or something?

Cheers

**Comment by gaborbernat** [comment]
Most new tools use this to show clearly where that version is coming from, as the package might be installed in multiple destinations.
