### ISSUE TITLE
location of site.__file__ is changed after upgrade to 20.0.x

### ISSUE THREAD

**Issue by kyanite** [pypa/virtualenv#1603]
1. virtualenv testenv
2. source testenv/bin/activate
3. python -c "import site; print(site.__file__)"
    output: /usr/lib64/python2.7/site.pyc

Before 20.0.x, the location of site is under the location of virtualenv, this change make some broken in our current product.

Please check this is a bug or expected.

**Comment by gaborbernat** [comment]
This is very much expected. It should have always been the standard library path, and this now has been fixed.

**Comment by kyanite** [comment]
So how easily to get the path of site-packages under virtualenv?

**Comment by gaborbernat** [comment]
You should be manifesting the sysconfig paths for the purelib if this is the goal, can post snippet later.

**Comment by gaborbernat** [comment]
On Python 2 only, you can use the os modules file path, 👍That's a Landmark file for the python bootstrap operation so is guaranteed to exist on cpython/pypy - but not in case of other implementations. The purelib sysconfig path is the most stable across all implementations.

**Comment by kyanite** [comment]
thanks @gaborbernat , looks like purelib works as i wanted
