### ISSUE TITLE
New v20.0.3 missing __version__?

### ISSUE THREAD

**Issue by rubendibattista** [pypa/virtualenv#1608]
I'm updating the `virtualenv` [package on Macports](https://github.com/macports/macports-ports/pull/6365) and I'm getting this error: 

```
:info:build AttributeError: module 'virtualenv' has no attribute '__version__'
:info:build Command failed:  cd "/opt/local/var/macports/build/_Users_rubendibattista_git_macports-ports_python_py-virtualenv/py37-virtualenv/work/virtualenv-20.0.3" && /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 setup.py --no-user-cfg build -j8
```

(I actually can't find the `version.py` module where in `virtualenv.__init__.py` the version is imported from... But it's also not present in `v20.0.2`, so I guess there's some magic somewhere that stopped working... :))

**Comment by gaborbernat** [comment]
How is macports generating the package? Via wheel sdist?

**Comment by gaborbernat** [comment]
Do you provision the build requirementes per pep 517?
