### ISSUE TITLE
produce build artifacts for master branch

### ISSUE THREAD

**Issue by ssbarnea** [pypa/virtualenv#1617]
Virtualenv CI should product build artifacts for each change made to master branch. 

There is no need to overload PyPi with pre-releases and because we use Azure Pipelines it should be easy to build and publish artifacts using their feeds.

See https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml -- Universal Artifact Feed is likely what we want to use.

This step requires the repo-owner to configure the feed so I cannot really help with it, but please do not ignore it as we want to make it easy to download wheels produced by master.

**Comment by gaborbernat** [comment]
What would be the value in generating these wheels?

**Comment by gaborbernat** [comment]
So the idea here would be to make easier for people to test with the latest master; I'm ok with publishing snapshot wheels from master to Azure DevOps (the goal here mainly would be to allow installation on platforms that don't have a recent pip capable of building a wheel out of box).

**Comment by gaborbernat** [comment]
```
[distutils]
Index-servers =
  virtualenv-latest

[virtualenv-latest]
Repository = https://pkgs.dev.azure.com/pypa/virtualenv/_packaging/virtualenv-latest/pypi/upload
```

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
