### ISSUE TITLE
Attribute 'real_prefix' missing in latest release of virtualenv

### ISSUE THREAD

**Issue by Paradoxis** [pypa/virtualenv#1622]
After upgrading to the latest version of virtualenv, the property `real_prefix` on `sys` no longer seems to be present whereas it was before. Minimal reproduction steps:

```
$ docker run -it python:3.7 /bin/bash
root@c6b8b966ec83:/# pip install -U pip virtualenv

root@c6b8b966ec83:/# source venv/bin/activate

(venv) root@c6b8b966ec83:/# pip list
Package    Version
---------- -------
pip        20.0.2 
setuptools 45.2.0 
wheel      0.34.2 

(venv) root@c6b8b966ec83:/# python
Python 3.7.6 (default, Feb  2 2020, 09:00:14) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.real_prefix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sys' has no attribute 'real_prefix'
```

This attribute is used in many of my packages to check that the current installation is inside of a virtualenv to prevent cluttering the system with global packages. Is there any plan of re-introducing this property or has it been moved somewhere else?

---

Quick fix for anyone experiencing the same issue: downgrade back to virtualenv 16.7.9

```
$ pip install virtualenv==16.7.9
```

**Comment by gaborbernat** [comment]
The latest virtual environment no longer sets this as we no longer generate old-style virtual environments, but rather venv style ones. The ``venv`` module instead sets ``base_prefix``, so that's what we do too.

**Comment by Paradoxis** [comment]
@gaborbernat so to clarify, is that the 'accepted' method of checking wether the program is running inside a virtual envrionment or is there a new and improved api to do so?

**Comment by gaborbernat** [comment]
It's checking either real prefix or base prefix exists 👍
