### ISSUE TITLE
🚒 unicode garbage seen while running virtualenv tests

### ISSUE THREAD

**Issue by ssbarnea** [pypa/virtualenv#1634]
Not sure where it comes from but I keep seeing garbage on pytest output while running virtualenv tests on MacOS. This happened on two different machines.

```
creator=CPython2Posix(dest=/private/var/folders/br/99tfdvcs3vvfwdk69z7f0xmc0000gn/T/pytest-of-ssbarnea/pytest-0/activation-tester-env0/e-$ èрт🚒♞中片-j, clear=False, global=False),
interpreter=PythonInfo({u'platform': u'darwin', u'file_system_encoding': u'utf-8', u'distutils_install': {u'headers': u'
```

**Comment by asottile** [comment]
this is intentional, there's a test which validates that virtualenv can create environments within unicode paths

**Comment by gaborbernat** [comment]
That being said these should cleanup nicely not show that errors so there's a bug somewhere in our test suite 🤔

**Comment by ssbarnea** [comment]
Given the nature of the string I expected to be related to an unicode test but apparently that comes multiple times in the long console log. I wonder if we can find a way to make it less distracting. Do we need emoji or CJK on it or is enough to use something less visible?

![ss](https://sbarnea.com/ss/Screen-Shot-2020-02-15-09-25-11.25.png)

**Comment by gaborbernat** [comment]
I like the fact it's visible; it's very helpful when things break and you need to test what's up.
