### ISSUE TITLE
RuntimeError: failed to find interpreter for Builtin discover of python_spec='/usr/bin/python3'

### ISSUE THREAD

**Issue by Brettfodor** [pypa/virtualenv#1646]
[root@rhel7 ]# virtualenv -p /usr/bin/python3 /usr/local/src/.python-venvs/python_v3.7
RuntimeError: failed to find interpreter for Builtin discover of python_spec='/usr/bin/python3'

I'm just trying to install a virtual environment on my Rhel 7 VM and it's giving me all sorts of issues.  This is likely not a "bug" but more just my lack of understanding on the topic.  Can anyone help?

**Comment by gaborbernat** [comment]
Looks like the python executable you specify via -p does not exist.
