### ISSUE TITLE
parse error or some name is wrong : -irtualenv 

### ISSUE THREAD

**Issue by ujinyoung** [pypa/virtualenv#1647]
os : macOS catalina 

In locale home directory

I try this :
`pip freeze>tflist.txt`

but show : 
`WARNING: Could not generate requirement for distribution -irtualenv 20.0.4 (/usr/local/lib/python3.7/site-packages): Parse error at "'-irtuale'": Expected W:(abcd...)
`

 and the file tflist.txt is generated, but empty.

I think 'virtualenv' is correct, but when I command 'pip list'
the result is : 
```
Package            Version
------------------ -------
-irtualenv         20.0.4

.
.
.

```
but I cannot uninstall -rtualenv. 
I try this : `pip uninstall -irtualenv`, and `pip uninstall virtualenv`
Both are failed, the message is `is not installed`

well, I succese to reinstall virtualenv, using `pip install virtualenv`

but How can I remove the wrong name package?
and who knows why the problem happens?

**Comment by ujinyoung** [comment]
when I try `pip freeze`
'-virtualenv', the worng name is not involved the ouput .
So I think maybe the `pip list` command is wrong and have some bug. etc. parse error..
 
I leave this issue, pip repo too.
pypa/pip#7763

**Comment by gaborbernat** [comment]
This doesn't seem like our issue but pip-s, thanks. If it turns out it's related to us we'll reopen.
