### ISSUE TITLE
virtualenv sensitive to unnormalized python paths

### ISSUE THREAD

**Issue by ianb** [pypa/virtualenv#165]
If you install a package globally with easy_install, then create a virtualenv, `sys.path` will be sensitive to how you invoke the virtualenv Python interpreter.

A rough way to reproduce:

```
$ /usr/bin/easy_install SomePackage
$ virtualenv test-env
$ ./test-env/bin/python -c 'import sys, pprint; pprint.pprint(sys.path)' > normal-path.txt
$ ./test-env/../test-env/bin/python -c 'import sys, pprint; pprint.pprint(sys.path)' > unnormal-path.txt
$ diff -u normal-path.txt unnormal-path.txt
```

You should see that /usr/lib/pythonX.Y/site-packages/SomePackage-X.Y.egg appears in different locations on sys.path depending on how the Python interpreter is invoked.  In practice this can mean the global egg does or does not override the local egg depending on the invocation.

Note: this has only been reproduced on two different Ubuntu systems, I'm not sure about other platforms.

**Comment by gaborbernat** [comment]
This is becoming obsolete with #1366 now in full swing.
