### ISSUE TITLE
virtualenv v20 breaks poetry (and presumably untold other software)

### ISSUE THREAD

**Issue by Drarok** [pypa/virtualenv#1678]
**Issue**

[Poetry](https://github.com/python-poetry/poetry) is a dependency and packaging management tool which is [seemingly broken](https://github.com/python-poetry/poetry/issues/2093) by virtualenv v20.

I'm a user of CircleCI who appear to have updated their base images to use the latest version of virtualenv which causes poetry to break.

**Environment**

Provide at least:
- OS: CircleCI Python images
- ~~``pip list``~~: unavailable

**Output seen when attempting to install dependencies**

```console
$ poetry install
Installing dependencies from lock file
[ImportError]
cannot import name create_environment
```

---

I would expect a breaking change like this to first issue deprecation warnings before removing an object/import/etc.

**Comment by gaborbernat** [comment]
We've been following semantic versioning, so as such version 16 did not break API. A new major version can introduce breaking change. It's not our fault that poetry does not pin correctly it's dependencies.
