### ISSUE TITLE
Did the '--no-site-packages' flag recently disappear?

### ISSUE THREAD

**Issue by gvanrossum** [pypa/virtualenv#1681]
Some readthedocs jobs recently started failing with a complaint from virtualenv about `--no-site-packages` (https://github.com/readthedocs/readthedocs.org/issues/6725). It seems readthedocs [passes this flag unless `--system-site-packages` is requested](https://github.com/readthedocs/readthedocs.org/blame/master/readthedocs/doc_builder/python_environments.py#L293). From the logs it seems there used to be a flag by this name, and then its behavior was made the default (around 2012?), but the flag was kept. Did it recently get removed? I can't quite nail it by grepping the logs, but this code has apparently been in readthedocs for ages.

Python 3.7 on Linux.

**Comment by gvanrossum** [comment]
OK, it looks like it disappeared in 20.0.0. Can't find a trace of it there, but it's present in 16.7.9. Since that answers my question, I'll close this. Sorry for the noise!

**Comment by gaborbernat** [comment]
Hello, you can still find the legacy (v16) documentation here https://virtualenv.pypa.io/en/legacy/reference.html. v20 aimes to be cli compatible with v16 baring some flags that have been deprecated for years now. https://virtualenv.pypa.io/en/legacy/reference.html#cmdoption-no-site-packages is one of this, so we've dropped it during the migration to the new major version. We're sorry if this caused issues for you, you're right we should have mentioned it somewhere in our release changelog though.

**Comment by vietvudanh** [comment]
Have just met this issue too, not much a problem since I find it early but it should be in released notes.

**Comment by gaborbernat** [comment]
@vietvudanh I'm a bit surprised how this long-deprecated no-op flag is still used by people 😱

**Comment by vietvudanh** [comment]
@gaborbernat I did not explicitly use the flag myself, `spark-submit` command from Apache Spark is what caused the error when I upgraded virtualenv to use `pyspark`.

Well, I think I might be the only one to have this problem with our offline Spark cluster, and I am the only Python dev in our mostly Scalar dev team.
