### ISSUE TITLE
Pythonw.exe work in the same way as Python.exe

### ISSUE THREAD

**Issue by wenderti** [pypa/virtualenv#1686]
Pythonw.exe displays terminal in the same way as Python.exe, the terminal should not be displayed with this executable.

**Comment by AndrewUshakov** [comment]
Just notices the same behavior with the virtualenv 20.0.7. While I started pyw using subprocess.Popen(), if create virtualenv, activate it and directly run pythonw - its output will be visible in the same cmd window, if run pyw - new windows will be opened.


![image](https://user-images.githubusercontent.com/7263403/75898455-1f5d7c80-5e4b-11ea-8eff-ea2a2c565401.png)

**Comment by AndrewUshakov** [comment]
Additionally, prompt about venv activation is also missed, compare with the virtualenv 16.7.10 below:
![image](https://user-images.githubusercontent.com/7263403/75900056-6482ae00-5e4d-11ea-82c1-ecff04c866e2.png)

**Comment by gaborbernat** [comment]
@AndrewUshakov your last comment is https://github.com/pypa/virtualenv/issues/1570

**Comment by AndrewUshakov** [comment]
Thx!

**Comment by gaborbernat** [comment]
Hello, a fix for this issue has been released via virtualenv 20.0.9; see https://pypi.org/project/virtualenv/20.0.9/ (https://virtualenv.pypa.io/en/latest/changelog.html#v20-0-9-2020-03-08). Please give a try and report back if your issue has not been addressed; if not, please comment here, and we'll reopen the ticket. We want to apologize for the inconvenience this has caused you and say thanks for having patience while we resolve the unexpected bugs with this new major release.
![thanks](https://media.tenor.co/images/1114067881329bb4218880eeb7ec34fd/tenor.gif)

**Comment by AndrewUshakov** [comment]
@gaborbernat: :) At first glance, everything is OK. Thank you!!!
