### ISSUE TITLE
python-config should be linked

### ISSUE THREAD

**Issue by lunaryorn** [pypa/virtualenv#169]
virtualenv should provide `pythonX.Y-config` of the python interpreter used for the virtual environment as `python-config` in the virtual environment.

Usage case:  Building of extension modules inside virtualenvs.  Some extension modules use autotools as build system.  Autotools uses python-config to find the extension module.  This fails, if the "python" inside the virtualenv is Python 3, but "python-config" coming from the system Python is Python 2.

**Comment by bchretien** [comment]
:+1: This can be handy to find the proper include directory containing `Python.h`.

**Comment by wookayin** [comment]
+1
This is needed, to deal with annoying troubles on building (native) extensions.

**Comment by mentalbrew** [comment]
+1 also. This issue dates to 2011. Any idea if this is going to be addressed?

**Comment by StefanD986** [comment]
I posted this on the `python-ideas`  mailinglist as possible feature for the standard library `venv` module.

@lunaryorn , @madprog @josharian @hoangelos @wiseman @offbyone @mentalbrew @bchretien @hoodie @wookayin and anyone who's stumbling on this issue:
If this is still relevant for you, please give it a *thumbs up* in the discussion here (You can log in with your github account): https://mail.python.org/archives/list/python-ideas@python.org/thread/QTCPOM5YBOKCWWNPDP7Z4QL2K6OWGSHL/
