### ISSUE TITLE
deactivate.ps1 is missing

### ISSUE THREAD

**Issue by Halfbax** [pypa/virtualenv#1724]
**What's the problem this feature will solve?**
deactivate.ps1 is missing

**Describe the solution you'd like**
deactivate.ps1:
```powershell
$script:THIS_PATH = $myinvocation.mycommand.path
$script:BASE_DIR = Split-Path (Resolve-Path "$THIS_PATH/..") -Parent

function global:deactivate([switch] $NonDestructive) {
    if (Test-Path variable:_OLD_VIRTUAL_PATH) {
        $env:PATH = $variable:_OLD_VIRTUAL_PATH
        Remove-Variable "_OLD_VIRTUAL_PATH" -Scope global
    }

    if (Test-Path function:_old_virtual_prompt) {
        $function:prompt = $function:_old_virtual_prompt
        Remove-Item function:\_old_virtual_prompt
    }

    if ($env:VIRTUAL_ENV) {
        Remove-Item env:VIRTUAL_ENV -ErrorAction SilentlyContinue
    }

    if (!$NonDestructive) {
        # Self destruct!
        Remove-Item function:deactivate
        Remove-Item function:pydoc
    }
}

deactivate -nondestructive
```

**Comment by gaborbernat** [comment]
No need, you can just invoke the method deactivate (is added/defined by the activation). Only batch does not allow defining custom methods, so that's why it has a deactivate.bat. all other shells don't need it.

**Comment by Halfbax** [comment]
It doesnt work for me when I use the Powershell in [Windows Terminal](https://github.com/microsoft/terminal).

**Comment by gaborbernat** [comment]
In that case if we define the function wrong or some other bug is at play. Feel free to submit an issue describing how the deactivated does not work, so we can track down the underlying issue. It should.
