### ISSUE TITLE
How to use virtualenv install python3.6 in Ubuntu19.10 whose default python version is 3.7?

### ISSUE THREAD

**Issue by appleyuchi** [pypa/virtualenv#1726]
**Issue**

Describe what's the expected behaviour and what you're observing.
I want python3.6 be installed with virtualenv,
but my system default support is python3.7

**Environment**
Ubuntu19.10

①when we use virtualenv to create environment for python ,we need the support from system-python,
such as:
mkvirtualenv -p /usr/bin/python3.7 python3.7
if we use python3.6 from tar.gz,it will fail.

②some package in virtualenv will be installed into fail if your system have no file "Python.h"
the solution is`apt install python3-dev`
but Ubuntu only has python3-dev(3.8)
,not python3-dev(3.6)

I really hope  virtualenv decompled from system python.
Hope to get your help,thanks

**Comment by gaborbernat** [comment]
This is a question for your operating system forums. virtualenv is a package that creates virtual environments that refer to the installed system pythons; it does not provide python itself.  You might want to take a look at https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa for arbitrary Python version on Ubuntu.

**Comment by appleyuchi** [comment]
@gaborbernat this will harm ubuntu's other software-base components such as libpython.

**Comment by gaborbernat** [comment]
Not sure I follow 👍
