### ISSUE TITLE
[regression][20.0.11] RuntimeError: failed to find interpreter for Builtin discover of python_spec='.tox/bin/python'

### ISSUE THREAD

**Issue by webknjaz** [pypa/virtualenv#1735]
**Issue**

It looks like the regression manifests itself when combined with tox.
Here's a GitHub Actions log: https://github.com/ansible/ansible-lint/runs/518006247?check_suite_focus=true#step:7:13.

**Environment**

Provide at least:
- OS: Ubuntu and macOS @ GitHub Actions
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console
  appdirs==1.4.3
  distlib==0.3.0
  filelock==3.0.12
  importlib-metadata==1.5.0
  importlib-resources==1.3.1
  packaging==20.3
  pip==20.0.2
  pluggy==0.13.1
  py==1.8.1
  pyparsing==2.4.6
  setuptools==28.8.0
  six==1.14.0
  toml==0.10.0
  tox==3.14.5
  virtualenv==20.0.11
  zipp==1.2.0
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`: Not sure how to do this with tox.

**Comment by gaborbernat** [comment]
Fixed with https://github.com/pypa/virtualenv/pull/1734, released under https://pypi.org/project/virtualenv/20.0.12/
