### ISSUE TITLE
Doesn't work with colons in path

### ISSUE THREAD

**Issue by jonashaag** [pypa/virtualenv#174]
``` sh
$ virtualenv2 foo:bar
New python executable in foo:bar/bin/python2
Also creating executable in foo:bar/bin/python
ImportError: No module named site
ERROR: The executable foo:bar/bin/python2 is not functioning
ERROR: It thinks sys.prefix is u'/tmp' (should be '/tmp/foo:bar')
ERROR: virtualenv is not compatible with this system or executable
```

**Comment by azrdev** [comment]
Moreover, if `$PWD` contains a colon then virtualenv will succeed without complaining, likewise `source env/bin/activate`. Still, the prefix added to `$PATH` contains a colon and is therefore not recognized by libc: <https://stackoverflow.com/questions/14661373/how-to-escape-colon-in-path-on-unix>

I'd suggest for virtualenv to at least issue a warning if the prefix contains a colon.

**Comment by gaborbernat** [comment]
Resolved via https://github.com/pypa/virtualenv/pull/1360
