### ISSUE TITLE
stdout:     AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython3macOsFramework'

### ISSUE THREAD

**Issue by ssbarnea** [pypa/virtualenv#1740]
Apparently `virtualenv==20.0.10` got us a new breaking bug.
```
centos-8 |     AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython3macOsFramework'
```
Something really bad slipped into this release as I can see a macos related exception on a linux platform.

Example: https://c549f30e8d3868372e7a-306bf88b8b0223e04364eb41d42ffe2c.ssl.cf5.rackcdn.com/713904/5/check/tripleo-ansible-centos-8-role-addition/3c03c6d/job-output.txt

If this really proves to be 20.0.10 regression, I would be happy to see it removed from pypi due to its nature.

**Comment by gaborbernat** [comment]
How did you install things? This feels like you have a bad install there.

**Comment by gaborbernat** [comment]
Is it still the case with 20.0.12?

**Comment by gaborbernat** [comment]
That class was added with 20.0.11; so it's right to be missing with 20.0.10. See https://github.com/pypa/virtualenv/commit/3816e7c7881bdc9ca99e18fe69810c856c9a9d2d

How do you pull it in from 20.0.10 when it's a 20.0.11 addition?

**Comment by gaborbernat** [comment]
This feels mostly like a bad install; something that installed 20.0.10 over 20.0.12 or something like that and did not clear up correctly the old files. I'll close this for now without a reproducible example.

**Comment by rsslldnphy** [comment]
Hi, is it possible to reopen this? I'm running into the same problem with my circleci build, which uses this circleci docker image: https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.7.7/Dockerfile

Error happens when i run:

```
pip install pipenv --user
pipenv install
```

Error:

```
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython3macOsFramework'
```

**Comment by gaborbernat** [comment]
As explained above the only way this can happen is to have a faulty installation of virtualenv. If that's the case it's either a pip or the docker images bug. I'd try looking into it and opening issues there. If you can provide a simplified docker image that replicates the issue that could help though to identify the faulty element.

**Comment by ssbarnea** [comment]
This is no longer a problem but I will post the investigation discoveries, so we maybe find a way to avoid it in the future. OpenStack is using an upper-constrains installation method for keeping its requirements under control and at that point it this was [`virtualenv==20.0.10`](https://opendev.org/openstack/requirements/src/branch/master/upper-constraints.txt#L813), one week later it was bumped to 20.0.13. These bumps mostly automated and based on periodic jobs that look for new versions, performs some minimal testing and propose a bumping change to refresh them.

Now the funny part is that regardless our attempt to pin virtualenv to a newer version inside tox.ini file, we ended up getting the older broken version.

I am almost sure this was not a faulty installation of virtualenv but more likely a failed upgrade, maybe related to pip. Still, this seems to happen on CI on totally different users, so we should probably try to find what is causing it and how we can prevent it from happening.

I am not so much worried about the specific error here because we know this can happen if a newer version is installed without a full cleanup of the old version. Now the question is what can cause this? Because this happened on CI and was reproducible enough, I would rule out acts-of-god causes, I bet there is a bug somewhere.

I am worried because bigger projects do have a natural-lag in bumping versions, so they will be affected by regression in a release of virtualenv and it would not be uncommon for them to endup upgrading to an already outdated version of virtualenv, without them even knowing it. For example on openstack merging a single change can take one day, and when waiting-for review is close to zero. The real numbers are more like 1 week-ish and during last week we had 3-4 new virtualenv releases, we cannot really cope with that.

It may worth mentioning that this is not a complaint, I really appreciate all the time @gaborbernat is investing in virtualenv project, I am just trying to find ways to limit the amount of surprises from newer releases.

**Comment by gaborbernat** [comment]
Just to be clear here. There was no faulty release here. The error you're describing can only come to life if somehow the installer pulled in the latest version, tried to install the older version and this somehow passed, but failed to uninstall the new version correctly. Both releases work fine, however you seem to have an installation that has some files from latest, some from the pinned version 🤷‍♂️

**Comment by monkut** [comment]
Just hit this issue today in circleci...

Related circleci issue.
https://discuss.circleci.com/t/python-tox-doesnt-build-anymore/35059/6

I guess a cache issue with circleci?

**Comment by kalpeshtawde** [comment]
Thank you. It has solve the problem for me as well.
