### ISSUE TITLE
Include venv_tools into programmatic API

### ISSUE THREAD

**Issue by aragilar** [pypa/virtualenv#1744]
Back in 2013/2014, I wrote a [wrapper around virtualenv/venv](https://venv-tools.readthedocs.io/en/latest/index.html) which added two bits of functionality: creating a temporary env (via tempfile + calls to either virtualenv or venv), and being able to run scripts/code within that env. The code still works, though with the recent improvements to virtualenv (wrapping venv, a real API), it might make sense to add this functionality to virtualenv. I'm happy to look at porting the code, and creating a PR, but I figured I should ask first if you would actually be interested in it.

**Comment by gaborbernat** [comment]
Can you describe some use cases where people would want to use this? How popular is it? Depending on this it might or might not belong to core virtualenv 🤔

**Comment by aragilar** [comment]
Back when I wrote it, I used it to generate temporary envs to build science packages, and then modify them via distlib to include dependency data (this was needed due to said dependency metadata missing), basically a pre-PEP517/518 hack. Most packages have since fixed their metadata, so I only rarely need to use it now. Tox is the only vaguely similar project I know of (in the automatic generation of envs), but venv_tools tried to allow both usage of virtualenv and venv (this is less important now given virtualenv seems to build itself on top of venv).

I'm not aware of anyone using it (no one ever filed any bugs or contacted me about it), but then I never told people about it either.

**Comment by gaborbernat** [comment]
I'll put it on hold then for now; feels to me like a less evolved implementation of tox, so people wanting such feature should probably use tox instead. https://pypistats.org/packages/venv-tools the usage statistics seem to suggest it would not get much usage, and the maintenance cost would outweight the benefits.
