### ISSUE TITLE
why????

### ISSUE THREAD

**Issue by mobinasadi** [pypa/virtualenv#1747]
`created virtual environment CPython3.6.9.final.0-64 in 637ms
  creator CPython3Posix(dest=/root/flaskproject/flaskprojectenv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator`

**Comment by gaborbernat** [comment]
Not sure I understand the problem here. Please provide more details.
