### ISSUE TITLE
sys.path does not include the virtualenv site-packages when started from a link

### ISSUE THREAD

**Issue by Wyrmwood** [pypa/virtualenv#1773]
**Issue**
With any 20.X I tried that would install
ln -s venv/bin/python pyenv
./pyenv
>>> import sys; sys.path
[venv/lib/python3.7/site-packages MISSING]
Running directly, 
venv/bin/python 
The venv site-packages are present. 

Change virtualenv==16.7.10, repeat the process and venv/lib/.../site-packages present, whether started with full path or link to path.

debian 10, python3.7

**Comment by gaborbernat** [comment]
This is by design, pep 405 https://www.python.org/dev/peps/pep-0405/ does not support symlinks to virtual environments. Use proxy scripts instead 👍

**Comment by Wyrmwood** [comment]
If you have created a link you'd like to use, say pyenv that points to your virtualenv (venv/bin/python)

alias pyenv=$(readlink pyenv)
pyenv
import sys; sys.path
[/usr/lib..., pyenv site-packages ]

At least for *nix,

**Comment by gaborbernat** [comment]
More details can be found at https://github.com/pypa/virtualenv/issues/1599#issuecomment-590306182 of which duplicate this is
