### ISSUE TITLE
Elvish support

### ISSUE THREAD

**Issue by ghost** [pypa/virtualenv#1775]
**What's the problem this feature will solve?**

Virtualenv activators currently does not include [Elvish](https://elv.sh/)

**Describe the solution you'd like**
Add Elvish activator, please.

**Comment by gaborbernat** [comment]
I invite elvish maintainers to provide this first as part of a separate package (``virtualenv-elvish``) via https://virtualenv.pypa.io/en/latest/extend.html#activation-scripts, and once it's stable and used we can reopen this and consider merge. Before that, though I'm not planning to accept this into the core before that.
