### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by 5hubh0** [pypa/virtualenv#1778]
**Issue**

os.listdir raises PermissionError while accessing /media/user/ext_drive while the user has access to said directory

**Environment**

Provide at least:
- OS: debian stable

**Comment by gaborbernat** [comment]
Can you please detail the full creation trace as requested in the template? ``virtualenv -vvv --with-traceback``

**Comment by 5hubh0** [comment]
Cannot reproduce the issue with virtualenv version=20.0.18

The issue arose on PyCharm Community installed via flatpak, where I guess
some version of virtualenv comes built-in with the flatpak/PyCharm.

The issue occurs if the following happens in this exact sequence:
Step 1: activate virtual environment i.e. $source venv/activate OR start
PyCharm
Step 2: mount an ext4 external drive via USB (auto mounted by Thunar)
Step 3: ls -l /media/user/mountpoint (no read or write permissions) and
file_handle = open('path/name', 'r') exits with access denied.

Thereafter, upon exiting the virtual environment permissions shows proper
read write permissions. Also,  open('path/name', 'r') works well. Also, can
access the file via Thunar.

However, if Step 2 is carried out before Step 1, then there is no issue
i.e. mount the drive and later enter virtual environment.

**Comment by gaborbernat** [comment]
I'll mark this as an unsupported workflow for now then.
