### ISSUE TITLE
Document the name of the config file

### ISSUE THREAD

**Issue by webknjaz** [pypa/virtualenv#1792]
**What's the problem this feature will solve?**

Docs only say "virtualenv looks for a standard ini configuration file": https://virtualenv.pypa.io/en/latest/cli_interface.html. But there's not a single mention of how that "standard ini file" is named.

**Describe the solution you'd like**

The file name should be documented.

**Alternative Solutions**

Read the source code?

**Additional context**

N/A

**Comment by gaborbernat** [comment]
``virtualenv -help`` would print it... but we should document on the web page.
