### ISSUE TITLE
Revamp Docs

### ISSUE THREAD

**Issue by SanketDG** [pypa/virtualenv#1801]
I have a proposal to revamp the current documentation that stays at https://virtualenv.pypa.io/en/latest/index.html

### Planned Layout

- Installation
- Quick Start
- User Guide
- Reference Guide
- Plugin API
- Contributing
- Release Notes

### Front Page

The front page should not be a list of things about what we do different from `venv` but instead just make a subtle note that `virtualenv` is different from inbuilt `venv` and link to a more exhaustive list of differences that is placed later in the documentation.

Related projects - I am not sure how relevant `pew` still is (also last commit is in 2019)

Should we keep the tutorials? - The `mod_wsgi` seems pretty irrelevant on the first page.

@gaborbernat's talk is helpful here espescially with the rewrite, I am not sure how the other one is, given its been quite some years since the talk.

### Installation

We should first and foremost make the distinction that this is different from `venv` and to the link to the said differences (as we did on the front page)

`pip` is ubiquitous, `pipx` is not, it should still be the recommended form of installation.

The rest of the content just needs to be brushed up a little.

---

I am going to propose required changes of each part of the docs with a comment here, so that folks don't get overwhelmed.

**Comment by gaborbernat** [comment]
I don't agree on the pipx point, on the rest we can come to an agreement.

**Comment by SanketDG** [comment]
From gitter:

> @gaborbernat I have started working on the docs at https://github.com/SanketDG/virtualenv/tree/sanketdg/revamp-docs
I have done a preliminary amount of work and I will be waiting until we found a scalable model for undergoing a full documentation rewrite
My naive idea is to create a upstream branch where I can send periodic PRs which can be reviewed, and at the end we merge the whole branch into master
Let me know what your thoughts are on this.

**Comment by gaborbernat** [comment]
Thanks will check, send it as a pr?

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
