### ISSUE TITLE
Generate VCS ignores to avoid version controlling virtual environments

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#1806]
As per https://twitter.com/metalikus/status/1256853693153947649

List of VCSs targeted is https://www.python.org/dev/peps/pep-0610/#registered-vcs

**Comment by SanketDG** [comment]
I would like to take this up, where would be this best placed?

https://github.com/pypa/virtualenv/blob/6dffcf2ae7b5b55098cf3c8326472f988277cb70/src/virtualenv/create/creator.py#L151-L156

Is something like `self.write_gitignore`/`self.ensure_gitignore` after `self.set_pyenv_cfg()` be a good way to implement this?

**Comment by gaborbernat** [comment]
Yeah somewhere there 🤔

**Comment by gaborbernat** [comment]
This now has been released via https://virtualenv.pypa.io/en/latest/changelog.html#v20-0-21-2020-05-20
