### ISSUE TITLE
20.0.19 does not install pip on Python 3.4

### ISSUE THREAD

**Issue by andy-maier** [pypa/virtualenv#1809]
**Issue**

In Travis with Python 3.4, virtualenv 20.0.19 does not seem to install a pip into a newly created virtualenv when creating it while a virtualenv is already acrive. "which pip" returns the pip from the first virtualenv after the new one is created and active. It fails only on Python 3.4 (the errors with pypy in the Travis logs below have a different cause). virtualenv before 20.0.19 does not have that behavior and succeeds on Python 3.4.

Version and location of Python and Pip after having activated the second virtualenv: Note that Python is shown to come from the correct second virtualenv while Pip is shown to come from the incorrect first virtualenv that Travis had set up:
* Python version: Python 3.4.8 from /home/travis/build/pywbem/pywbem/tmp_installtest/virtualenvs/pywbem_test_test1/bin/python
* Pip version: pip 19.1.1 from /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pip (python 3.4)

To see this in the Travis logs, search for "Creating virtualenv:" case sensitively (around line 2500):
* Travis build with virtualenv 20.0.19, showing the issue: https://travis-ci.org/github/pywbem/pywbem/builds/682738409
* Travis build with virtualenv 20.0.18, showing success: https://travis-ci.org/github/pywbem/pywbem/builds/682740925

**Environment**

Provide at least:
- OS: MacOS 10.14.6
- ``pip list`` of the host python where ``virtualenv`` is installed:
  see Travis logs

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

see Travis logs

**Comment by gaborbernat** [comment]
Hello, this now has been released via https://pypi.org/project/virtualenv/20.0.20/

![heads up](https://media.tenor.co/images/0118006f847acfcfd22e8bf0fd405e42/tenor.gif)

**Comment by andy-maier** [comment]
Wow. Super fast! Thanks!!

**Comment by andy-maier** [comment]
I verified that it works again with virtualenv 20.0.20.
See Travis log for Python 3.4 job in this build: https://travis-ci.org/github/pywbem/pywbem/builds/682843614
