### ISSUE TITLE
Use identifier string to set the target interpreter when creating virtualenv.

### ISSUE THREAD

**Issue by hongyi-zhao** [pypa/virtualenv#1819]
Hi,

According to the help of virtualenv, it supports the following usage:

`-p py, --python py            target interpreter for which to create a virtual (either absolute path or identifier string) `

But I still cannot figure out how to assign the ` identifier string ` to pointing to the target interpreter when I create the virtualenv.  Any hints for this?

Regards,
HY

**Comment by gaborbernat** [comment]
Please read https://virtualenv.pypa.io/en/latest/user_guide.html#python-discovery that details what format of identifier strings are accepted.
