### ISSUE TITLE
Is there any reason to keep old version in embed folder?

### ISSUE THREAD

**Issue by earthday** [pypa/virtualenv#1842]
The old versions are still embedded in https://github.com/pypa/virtualenv/tree/20.0.21/src/virtualenv/seed/embed/wheels, I want to know why they are kept, and is there any concern if remove them?
<img width="1011" alt="Screen Shot 2020-05-31 at 09 48 28" src="https://user-images.githubusercontent.com/90078/83342615-09653800-a324-11ea-94cb-1517f6ac1e5c.png">

I pop up this question because our WhiteSource scan reported the security issue about it.
![image](https://user-images.githubusercontent.com/90078/83342637-4af5e300-a324-11ea-84bd-9c76a07cee7b.png)

**Comment by earthday** [comment]
OK, I just found the reason that is for the old python version. See here, https://github.com/pypa/virtualenv/blob/078ed06eb7e46e3ef4286528da4cf40023c53e56/src/virtualenv/seed/embed/wheels/__init__.py#L30

I closed this issue for I found the reason.

**Comment by gaborbernat** [comment]
You're right. The older versions are used for older Python versions. E.g. if we're creating a virtual environment for Python3.4 the last version we can use is ``19.1.1`` for pip.
