### ISSUE TITLE
How to update pip permanently for new venv?

### ISSUE THREAD

**Issue by tbrodbeck** [pypa/virtualenv#1852]
**Describe the bug**
Every new environment has the old pip version (19.2.3)

**Expected behavior**
My system python has pip version 20 so I would expect direnv also to use the most recent pip version. But it installs the old pip version for every new environment

**Environment**
 - OS: macOS Catalina 10.15.4
 - Shell: zsh 5.7.1
 - Python version: stable 3.7.7 (homebrew bottled)

**To Reproduce**
  ```console
➜  ~ pip list
Package            Version
------------------ -------
appdirs            1.4.4
astroid            2.4.1
distlib            0.3.0
filelock           3.0.12
importlib-metadata 1.6.1
isort              4.3.21
lazy-object-proxy  1.4.3
mccabe             0.6.1
numpy              1.18.5
pip                20.1.1
pylint             2.5.2
python-dateutil    2.8.1
pytz               2020.1
setuptools         40.8.0
six                1.12.0
toml               0.10.1
typed-ast          1.4.1
virtualenv         20.0.21
wheel              0.33.1
wrapt              1.12.1
zipp               3.1.0
➜  ~ python3 -m venv ./foobar
➜  ~ source ./foobar/bin/activate
(foobar) ➜  ~ pip list
Package    Version
---------- -------
pip        19.2.3 
setuptools 41.2.0 
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by pradyunsg** [comment]
#1841 will address this need.

**Comment by gaborbernat** [comment]
I'd just like to mention that you're using venv module, not virtualenv. Feature requests for those should be filled under https://bugs.python.org/, not here. Note venv is not virtualenv - see https://virtualenv.pypa.io/en/latest/. That being said if you're fine with paying the performance penalty passing in the ``--download`` should help.
