### ISSUE TITLE
virtualenv 20.0.21 has requirement importlib-resources<2,>=1.0; but you'll have importlib-resources 2.0.0 which is incompatible.

### ISSUE THREAD

**Issue by Aricg** [pypa/virtualenv#1854]
**Issue**
importlib-resources bumped to 2.0
https://gitlab.com/python-devs/importlib_resources/-/issues/96

I think this line needs a bump as well.
`
./setup.cfg:    importlib-resources>=1.0;python_version<"3.7"`

`ERROR: virtualenv 20.0.21 has requirement importlib-resources<2,>=1.0; python_version < "3.7", but you'll have importlib-resources 2.0.0 which is incompatible.`

**Comment by gaborbernat** [comment]
Already resolved via https://github.com/pypa/virtualenv/pull/1851, just not yet released

**Comment by Aricg** [comment]
Any chance we are getting a point release for this? I can't speak for anyone else, but I have to deploy code changes across many ci systems to work around this..

**Comment by gaborbernat** [comment]
Will do today.

**Comment by Aricg** [comment]
Amazing, thank you!

**Comment by gaborbernat** [comment]
Done under https://pypi.org/project/virtualenv/20.0.22/
