### ISSUE TITLE
Support for fish?

### ISSUE THREAD

**Issue by mrillusi0n** [pypa/virtualenv#1872]
I was using the [**friendly, interactive shell**](https://fishshell.com/) which uses a syntax that doesn't match with that of bash or zsh. So, had to do some modifications to the `activate` script to make it comply with fish's syntax to get it working. Will this shell be supported?

**Comment by gaborbernat** [comment]
You can source the ``activate.fish`` we already provide. ``activate`` is always for BASH shell.

**Comment by gaborbernat** [comment]
The template of the fish activation you can find at https://github.com/pypa/virtualenv/blob/master/src/virtualenv/activation/fish/activate.fish
