### ISSUE TITLE
Can't create a new environment 

### ISSUE THREAD

**Issue by ShyamSundhar1411** [pypa/virtualenv#1878]
Input:
virtualenv v
Output:
OSError: [Errno 9] Bad file descriptor
I thought this was my mistake but i enquired with m friend too about this. He too gets the same

```

**Comment by gaborbernat** [comment]
# Please provide the requested information on how to reproduce with detailed log.

**Comment by ShyamSundhar1411** [comment]
Ok I actually degraded virtualenv now to a lower version and its working well  .But i can explain you the error and what I saw.
Whenever I try to create a new environment it was coming like OSERROR[9] Bad File Descriptor.But the virtualenv was created.
When I try to activate it its coming like python interpreter unexpectedly closed ...

**Comment by gaborbernat** [comment]
I need exact commands, package versions, output with verbose mode. Anecdotal high level description is not enough to replicate.
