### ISSUE TITLE
`virtualenv --version` prints spurious error as of 20.0.24

### ISSUE THREAD

**Issue by benkehoe** [pypa/virtualenv#1885]
**Issue**

When running `virtualenv --version`, a logger error is printed to stderr, though the return code is still 0.

**Environment**

Tested with Python 3.7 and 3.8, virtualenvs managed with pipenv
Ubuntu 18.04 on WSL

```
$ rm-rf tmp && mkdir tmp && cd tmp
$ pipenv install "virtualenv==20.0.23"
$ pipenv run virtualenv --version
virtualenv 20.0.23 from tmp/.venv/lib/python3.7/site-packages/virtualenv/__init__.py

$ rm-rf tmp && mkdir tmp && cd tmp
$ pipenv install "virtualenv==20.0.24"
$ pipenv run virtualenv --version
virtualenv 20.0.24 from tmp/.venv/lib/python3.7/site-packages/virtualenv/__init__.py
ERROR:root:SystemExit: 0
$ pipenv run virtualenv --version > /dev/null
ERROR:root:SystemExit: 0
$ echo $?
0
```

Nothing else is printed with `-vvv --with-traceback`

**Comment by benkehoe** [comment]
Quick followup question: is it intended behavior for it to print out `virtualenv 20.0.24 from tmp/.venv/lib/python3.7/site-packages/virtualenv/__init__.py` when previous versions simply printed the version number? I ask because I discovered this when a script I don't own broke as it parsed the output expecting a bare version number.

**Comment by gaborbernat** [comment]
It's expected, and the new contract with version 20.
