### ISSUE TITLE
Documentation for configuration file is inconsistent with example

### ISSUE THREAD

**Issue by szafranek** [pypa/virtualenv#1901]
**Issue**

The [CLI interface documentation page](https://virtualenv.pypa.io/en/latest/cli_interface.html) says that:

> The keys of the settings are derived from the command line option (left strip the `-` characters, and replace `-` with `_`).
> Where multiple flags are available first found wins (where order is as it shows up under the `--help`).

However, the provided example config flag from the init file doesn't have `-` replaced with `_`:

```
[virtualenv]
extra-search-dir =
    /path/to/dists
    /path/to/other/dists
```

What is the correct way to provide these options? With `-` or `_`?

**Comment by gaborbernat** [comment]
It's always ``_`` instead of ``-``, so the example is the one incorrect. Can you put in a PR for this?

Thanks!
