### ISSUE TITLE
Correct remove _PYTHON_VENV_PROMPT_PREFIX

### ISSUE THREAD

**Issue by whintu** [pypa/virtualenv#1913]
The following instruction causes powershell to store the error in variable $Error after activating the script `Activate.ps1`
```powershell
    # Just remove the _PYTHON_VENV_PROMPT_PREFIX altogether:
    if (Get-Variable -Name "_PYTHON_VENV_PROMPT_PREFIX" -ErrorAction SilentlyContinue) {
        Remove-Variable -Name _PYTHON_VENV_PROMPT_PREFIX -Scope Global -Force
    }
```

And if i use the custom theme in powershell (for example Paradox theme), I observe the following nasty artifact:
![изображение](https://user-images.githubusercontent.com/20277698/89205887-1c64e480-d5c1-11ea-86a0-6add78d03592.png)
[red cross on the start of the line]

I suggest the following solution to the problem:

```powershell
    # Just remove the _PYTHON_VENV_PROMPT_PREFIX altogether:
    if (Test-Path "variable:global:_PYTHON_VENV_PROMPT_PREFIX") {
        Remove-Variable -Name _PYTHON_VENV_PROMPT_PREFIX -Scope Global -Force
    }
```

**Comment by gaborbernat** [comment]
@whintu feel free to send a PR 🤔

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
