### ISSUE TITLE
pip 2.20 included in v20.0.29 breaks checking if package with dotted name is installed

### ISSUE THREAD

**Issue by elfosardo** [pypa/virtualenv#1914]
Expected behaviour:
When installing a package in a virtualenv with a minimum version required, for example pip install oslo.config>=5.2.0, if that package is installed and already satisfies the minimum version required, it should not be upgraded. This works fine until v20.0.28 with pip 20.1.1

With v20.0.29, which embeds pip 20.2, this behaviour is broken with packages that contains a dot in their name.
Please also see https://github.com/pypa/pip/issues/8645 for more information.

The fix is included in pip 20.2.1

**Comment by gaborbernat** [comment]
Note you can select the pip version via ``--pip`` or via ``VIRTUALENV_PIP`` to workaround this.

**Comment by gaborbernat** [comment]
released via https://pypi.org/project/virtualenv/20.0.30/

**Comment by elfosardo** [comment]
@gaborbernat awesome! Thanks!
