### ISSUE TITLE
Virtual environments referencing global python install when installing in a different drive.

### ISSUE THREAD

**Issue by DeeparthGupta** [pypa/virtualenv#1919]
I created a virtualenv in the D drive while python is installed in C with the command `C:\python\python37\python.exe -m virtualenv env`. If I type `which python` I get the reference to the python install in the PATH environment variable instead of the the one in my virtualenv. This makes pip install packages globally instead of in the virtualenv. The effect is also seen in Vscode where plugins refer to the global install even when the configuration should make them refer to the one in the virtualenv. This used to work till sometime in July.

This problem did not occur when I created one in C:\Users\<username>

**Environment**

I have both 3.8.3 and 3.7.7 and I'm trying to create a virtualenv with the latter.

- OS: Windows 10 v2004
- ``pip list`` of the host python where ``virtualenv`` is installed: 
It was a fresh python install before pip installed the packages in global instead of the virtualenv.

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

[env_creation.txt](https://github.com/pypa/virtualenv/files/5063541/env_creation.txt)
[pyvenv.cfg.txt](https://github.com/pypa/virtualenv/files/5063610/pyvenv.cfg.txt)

**Comment by gaborbernat** [comment]
> If I type `which python` I get the reference to the python install in the PATH environment variable instead of the the one in my virtualenv.

Did you use an activation script? Which one? Can you post your environment variables before and after?

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
