### ISSUE TITLE
Please also provide a versioned virtualenv.pyz file  

### ISSUE THREAD

**Issue by pombredanne** [pypa/virtualenv#1930]
It should be possible to have a versioned virtualenv.pyz from https://bootstrap.pypa.io/virtualenv/ for each new version of 
virtualenv  .... but today this is not possible and this ends up being something of a rolling release that cannot be use for reliably reproducible builds as the version may change at any time.
Could you upload the virtualenv.pyz with a version in its name or path too (possibly with some simple hardlinks) to https://bootstrap.pypa.io/virtualenv/  or the Github release tag?
Thank you for your kind consideration!

**Comment by gaborbernat** [comment]
I don't think this is as simple as you make it sound to be 🤔if using latest release sounds like causing issues to you, maybe fill in those as bug requests instead?

**Comment by pombredanne** [comment]
It seems that there are already many versions published ... like one for each python version (even though these are the same)... I was wondering if using the same approach but archiving all versions under a version /20.0.7/ dir and having the latest as a link may work?

**Comment by pombredanne** [comment]
Before the advent of the .pyz zipapp, I could fetch a versioned `virtualenv.py` straight from the git repo that would contain all the needed vendored thirdparties: the version would be either a tag or a commit. Since the zipapp that replaced it, there is no way to get a virtualenv.pyz that is versioned anymore.
If it is not easy to get all the versions in the CDN at https://bootstrap.pypa.io/virtualenv/ at least each version of a zipapp could be uploaded as "release asset" together with each tagged version in this repo here https://github.com/pypa/virtualenv/tags (and specifically for one tag here: https://github.com/pypa/virtualenv/releases/tag/20.0.31 )?

I would love to help and provide a script or update existing scripts to do this release alright if this can help, but I could not see anywhere the script that would handle uploading the zipapp to https://bootstrap.pypa.io

**Comment by pradyunsg** [comment]
If you're OK with fetching from a Git repository, you can use https://github.com/pypa/get-virtualenv -- it has tags and will have a stable structure (as long as we don't reorganize how bootstrap.pypa.io works).

**Comment by pombredanne** [comment]
@pradyunsg this is all I need! I guess it would be a good idea to link it somewhere in the readme too :)
Thanks!
