### ISSUE TITLE
virtualenv does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by pra-dan** [pypa/virtualenv#1931]
**Issue**

I am using Python3.7 and following the `virtualenv` and `virtualenvwrapper` installation as mentioned on [this FreeCodeCamp article](https://www.freecodecamp.org/news/virtualenv-with-virtualenvwrapper-on-ubuntu-18-04/). 

The changes to my `.bashrc` file look as follows:
```bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# popo edit: Add Python alias
alias python=python3

# popo edit: Step to activate virtualenvs
export WORKON_HOME=$HOME/.virtualenvs

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
# SOme more things....

#Virtualenvwrapper settings:
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV=/home/pra-dan/.local/bin/virtualenv
source /usr/local/bin/virtualenvwrapper.sh
```

ALthough, I managed to make an environment (idk how) and on typing `workon`, I get its name. 

But now when I wish to make a new environment, I enter `$ mkvirtualenv wrk -p python3`, I get

```
ERROR: virtualenvwrapper could not find /home/pra-dan/.local/bin/virtualenv in your path
```

**Environment**

- OS: Ubuntu 20.04

- ``pip list`` of the host python where ``virtualenv`` is installed:

 ```console
Package            Version
------------------ -------
appdirs            1.4.4
distlib            0.3.1
filelock           3.0.12
importlib-metadata 1.7.0
pbr                5.4.5
pip                20.2.2
setuptools         41.2.0
six                1.15.0
stevedore          3.2.0
virtualenv         20.0.31
virtualenv-clone   0.5.4
virtualenvwrapper  4.8.4
wheel              0.35.1
zipp               3.1.0
```

When I try creating a new environment now, I get

```console
    $ mkvirtualenv wrk -p python3 -vvv --with-traceback
ERROR: virtualenvwrapper could not find /home/pra-dan/.local/share/virtualenv in your path

```

**Comment by gaborbernat** [comment]
You're not invoking virtualenv, you're invoking virtualenvwrapper instead, please report this to their issue tracker instead. You can reopen this if you can replicate with invoking virtualenv command.
