### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by FendinX** [pypa/virtualenv#1935]
pyinstxtractor.py:95: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses import imp [*] Processing PrimeKiller Cracked.exe [*] Error : Unsupported pyinstaller version or not a pyinstaller archive

**Comment by pradyunsg** [comment]
Hi! Thanks for filing this but this isn't the right place for this issue.

I think that [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists, [#python on Freenode](https://webchat.freenode.net/?channels=%23python) (IRC) or [StackOverflow](https://stackoverflow.com) would be better channels to get support for the issue you're facing.
