### ISSUE TITLE
Cygwin and msys2 bash activator compatibility

### ISSUE THREAD

**Issue by yilei** [pypa/virtualenv#1940]
**Issue**

Run the following via msys2:

```
$ /c/Users/builder/AppData/Local/Programs/Python/Python39/Scripts/virtualenv.exe --no-pip --no-setuptools --no-wheel -p /c/Users/builder/AppData/Local/Programs/Python/Python39/python.exe /tmp/tmp.uw7eZfvJIO
$ source /tmp/tmp.uw7eZfvJIO/Scripts/activate
$ python
python: command not found
```

The content of `/tmp/tmp.uw7eZfvJIO/Scripts/activate` contains `VIRTUAL_ENV='C:\tools\msys64\tmp\tmp.uw7eZfvJIO'`, but it's expected to be `VIRTUAL_ENV='/c/tools/msys64/tmp/tmp.uw7eZfvJIO'`, thus it can't locate `python`.

I believe the legacy version handles this correctly here: https://github.com/pypa/virtualenv/blob/4c9899f471139670b0f1bfd359c37a67c507447d/virtualenv.py#L1742-L1748

which contains:

`VIRTUAL_ENV="$(if [ "$OSTYPE" "==" "cygwin" ]; then cygpath -u 'C:\tools\msys64\tmp\tmp.uw7eZfvJIO'; else echo '/C/tools/msys64/tmp/tmp.uw7eZfvJIO'; fi;)"`

**Environment**

Provide at least:
- OS: Windows 7, using msys2 v20200903.0.0

**Comment by danyeaw** [comment]
I am also having this issue. I would be glad to submit a PR if someone could help point me in the right direction. It seems like the creator is correctly building the virtualenv, but we need to modify the path only for setting the VIRTUAL_ENV in the activate script.

**Comment by gaborbernat** [comment]
You probably want to massage around here https://github.com/pypa/virtualenv/blob/master/src/virtualenv/activation/via_template.py#L36-L39
