### ISSUE TITLE
Allow plugin activators to override the usual activators

### ISSUE THREAD

**Issue by AWhetter** [pypa/virtualenv#1954]
**What's the problem this feature will solve?**

We have a custom, proprietary implementation of Python such that the default activation scripts do not work because we need to additional bits to get the virtualenv to operate properly. Some IDE integrations (eg vscode) and other tools for interacting with virtualenvs expect the "bin/activate" script to enter the virtualenv properly, but in our case that doesn't work. Tools treat the activate scripts like part of the "public API" to a virtualenv.

**Describe the solution you'd like**
Our plugins for virtualenv have a custom `Activator` class with an implementation of `Activator.supports` that checks that the creator is using an implementation that matches our version. However the built in `Activator` classes use the base `supports()` implementation that always returns `True`.

The simplest change to virtualenv that I can think to get this particular case working would be for the default `Activator.supports` implementation to only support the default implementations that virtualenv supports ("CPython", "PyPy").
A plugin that wants use the built in activator scripts with a custom implementation of Python can create an Activator class that inherits from `BashActivator` (and so on for additional shells to support) and override the `supports()` method to check that `creator.implementation` matches the custom implementation.

**Alternative Solutions**
We cannot overrwrite the default scripts because the unordered nature of entry points means that there's no guarantee that the default activators won't write over our version (in reality entry points seem to be discovered in alphabetical order by package name, and with virtualenv being late in the alphabet the built in activators are always found last and so written out last :wink:).

**Additional context**
We don't actually have a full blown implementation of Python, but regular CPython wrapped up in a build system that we use

**Comment by gaborbernat** [comment]
> We don't actually have a full blown implementation of Python, but regular CPython wrapped up in a build system that we use

This counts as a flavor of CPython.

> We have a custom, proprietary implementation of Python such that the default activation scripts do not work because we need to additional bits to get the virtualenv to operate properly.

A virtual environment should already work once the create operation has passed, the activation script just alters the shell enough to replace the system python/pip with the virtual environments one. However per contract virtual environments **must** work without activation. If your python implementation fixes virtual environments within the activation script then you're doing it wrong, such fixes should happen either during creation (custom creator). Custom startup changes can be added to your virtual environment by generating a pth file part of the virtuale environment (see ``_virtualenv.pth`` we already generate).

**Comment by AWhetter** [comment]
I should have also said that we are definitely pushing the limits of what a virtualenv is supposed to be. We also break various parts of the command line API of virtualenv to make this happen. We end up with something that works for most cases so is good enough at the moment. So it's totally fine to say that this isn't a valid use case.

> the activation script just alters the shell enough to replace the system python/pip with the virtual environments one.

Our build system encompasses binaries built from other languages. At it's core, it's basically a bash script that you source to set a bunch of variables like `PATH`, `PYTHONPATH`, `LD_LIBRARY_PATH`. We're using virtualenvs as a developer interface to the system because the workflow is much nicer and we get things like IDE integrations for free. What I'm trying to achieve is to have the activate script also essentially source this environment script so that it's entering the build system's environment as well, but this is obviously something that a virtualenv isn't usually supposed to be for.

The more conventional way of doing what we're doing would be to enter the build system's environment, and then run virtualenv as normal. But there's a whole bunch of negatives to this approach, such as use tox to test multiple environments at once, which is why we started doing what we're doings.

> However per contract virtual environments must work without activation.

It does, but we ... hack to make this work :grimacing: So it doesn't really work without activation because for us, activation involves entering a whole new environment.

Like I said, we are definitely pushing the limits of what a virtualenv is supposed to be. :sweat_smile:

**Comment by gaborbernat** [comment]
> such as being unable to use tox to test multiple environments at once

Wait, if you're using tox is even more true that the created virtual environment needs to work without activation. tox does not call the activation at all. How does it work still?

**Comment by AWhetter** [comment]
I don't know if I want to say because it's embarrassingly hacky :sweat_smile: But we wrap the Python executable in bash script to enter the build system environment and then run the Python binary inside the virtualenv.

**Comment by gaborbernat** [comment]
I'm not sure I follow. Does tox call the python binary, or the bash script? Where are each called?

**Comment by AWhetter** [comment]
Tox calls the bash script. We rename the binary and place the bash script at `bin/python`.

So the creator is doing something like

```python
def create(self):
    super(MyCreator, self).create()

    bin_path = self.bin_dir / "python"
    orig_bin_path = self.bin_dir / "python.orig"
    shutil.copyfile(bin_path, orig_bin_path)
    bin_path.write_text(PYTHON_WRAPPER)
```

Where `PYTHON_WRAPPER` is something like:
```bash
#!/bin/bash

if [ ! in_environment ]; then
    enter_environment
fi

python.orig "$@"
```

**Comment by gaborbernat** [comment]
If that's so couldn't you just put the env/shell activation logic in that bash script?

PS. tox is always written with all lowercase.

**Comment by AWhetter** [comment]
We can, and do. But it makes more sense to enter the "complete environment" when you activate and not just the virtualenv because there's non-Python things that come with being in that environment.

**Comment by gaborbernat** [comment]
So you mean other than the python interpreter is also expecting the side effect of those activation script?

**Comment by AWhetter** [comment]
I don't understand your question.

But the "bin/python" script does need the "bin/activate" script at all. However we want the `enter_environment` bit that's in "bin/python" to also happen when a user is manually (or IDE is automatically) entering the virtualenv using the activate script.

**Comment by gaborbernat** [comment]
> However we want the `enter_environment` bit that's in "bin/python" to also happen when a user is manually (or IDE is automatically) entering the virtualenv using the activate script.

Why? The user already has a fully functional virtualenv when invoking the python command via ``bin/python``, not?

**Comment by AWhetter** [comment]
They do have a fully functional virtualenv with the default activate scripts. However the build system environment has script and binaries from other languages that it would be nice to have access to as well.
Think of it like a chroot jail almost. We're aiming for doing "source venv/bin/activate" to enter the chroot as well as activate the virtualenv.

**Comment by AWhetter** [comment]
From this conversion I've learnt more about what the contract of parts of virtualenv are. I'm going to close this because we are doing things that we shouldn't be and we are rethinking our approach.
Thanks for your help @gaborbernat

**Comment by gaborbernat** [comment]
Hello, I've been busy with other things and this slipped under the radar, so please don't consider my lack of response unwillingness to help you with your problem. I'm still open to make changes to virtualenv, if needed, in order to achieve your goals. Thanks!
