### ISSUE TITLE
Relax importlib-metadata version pinning

### ISSUE THREAD

**Issue by aachkar-miovision** [pypa/virtualenv#1955]
Is this pinning to <2 of importlib-metadata required? It is preventing installing that version into environments where for example I also have pre-commit, which depends on virtualenv. 
https://github.com/pypa/virtualenv/blob/5e46e4a8d4f816812619ca67c4ff41f4aaf4006f/setup.cfg#L46

```
pre-commit 2.7.1 A framework for managing and maintaining multi-language pre-commit hooks.
├── cfgv >=2.0.0
├── identify >=1.0.0
├── importlib-metadata *
│   └── zipp >=0.5
├── nodeenv >=0.11.1
├── pyyaml >=5.1
├── toml *
└── virtualenv >=20.0.8
    ├── appdirs >=1.4.3,<2
    ├── distlib >=0.3.1,<1
    ├── filelock >=3.0.0,<4
    ├── importlib-metadata >=0.12,<2
    │   └── zipp >=0.5
    └── six >=1.9.0,<2
```

**Comment by gaborbernat** [comment]
It's not required but we need a patch that removes it and makes the ci pass to validate it's not breaking things. Prs welcome.

**Comment by gaborbernat** [comment]
Fixed via https://github.com/pypa/virtualenv/pull/1953
