### ISSUE TITLE
Suggestion: CI / multi-tenant mode which stores nothing in .local

### ISSUE THREAD

**Issue by tgs** [pypa/virtualenv#1961]
**Describe the problem**

At my organization, we have a TeamCity continuous integration server, which runs tests from several projects under one user account.  The build directory is removed/cleaned between builds, but the home directory of the build user is not.  This means that the ~/.local directory is a way for changes to leak from one build configuration into another, and from one time to a later time, which is surprising in that context and can be very hard to debug.

The build systems have a centrally-managed installation of virtualenv, which has its embedded wheel packages.  Our system administrators go through a testing process with this installation, so we know the embedded wheel versions work with our locally developed software.

The specific symptom we saw was that some builds suddenly started failing, and continued to fail, with no code changes.  The actual bug seems to be https://github.com/pypa/setuptools/issues/2355 , but I'm not really worried about that - I'm worried about how it showed up in our CI workflow.  Apparently what happened was that at some point, virtualenv on a couple of the build hosts seems to have updated its app-data image to a combination of pip and setuptools that didn't work for us. From that point, all builds on those hosts, but no others, failed.  Our workaround was to remove the .local directories, re-create them empty, and `chmod 000`.

**Describe the solution you'd like**

I would suggest a `--no-user`,  `--no-user-config`, or `--vanilla` argument for virtualenv.  It would disable any optimizations that require the use of the ~/.local directory.

(I am very impressed with the speed of the app-data image feature, by the way - it's really wonderful for interactive use!)

I'm not sure, but possibly the same effect can be achieved by saying `--app-data $(mktemp -d)`.  However, the embedded wheels can still be updated per-user, right?  My goal is that I don't want to keep track of every way virtualenv uses per-user caching and configuration - I want a single way to disable it.

We had a conceptually-related issue with pip, where our system default of --system-site-packages interacted badly with pip's newish default of doing an install --user if there's no virtualenv active.  This meant that any accidental package installation without an env active would leak through to all the builds on that host.  For pip, we added `user = no` to /etc/pip.conf, and that was a nice central way to avoid the issue.

**Alternative Solutions**

We have done `chmod 000 ~/.local`.  This is okay, but we must do it for each build server we set up.

Ultimately, I suppose we somehow need to completely disable access to the home directory of the build user, but this is not an easy lift for our administrators.

**Comment by pradyunsg** [comment]
IIUC, using `--seeder pip` should give you the behaviors you want.

**Comment by gaborbernat** [comment]
Yeah. Either switching to pip seeder or setting app data to a folder within the ci will work. Things will be slower.
