### ISSUE TITLE
Set VIRUTAL_ENV_PROMPT

### ISSUE THREAD

**Issue by Tadaboody** [pypa/virtualenv#1968]
**What's the problem this feature will solve?**

Currently it's hard for third-party tools to get what's passed from the `--prompt` option
**Describe the solution you'd like**

On activation, set an enviroment variable of `VIRTUAL_ENV_PROMPT` to be whatever is passed to `--prompt` at build time

For an example of this pain see https://github.com/starship/starship/issues/1698
**Alternative Solutions**

Grepping the activation script :/ 

**Additional context**

This was already implemented in `venv`: https://github.com/python/cpython/pull/21587

**Comment by gaborbernat** [comment]
You don't need to grep the activation script, it's saved in the pyvenv.cfg.

**Comment by Tadaboody** [comment]
@gaborbernat Is there a `pyvenv.cfg` file created? I can't find one and https://github.com/pypa/virtualenv/issues/719 tells there isn't

**Comment by gaborbernat** [comment]
Starting with virtualenv 20 there always is at the root of the virtual environment folder.

**Comment by Tadaboody** [comment]
Woops my bad 😅 Looks like the behaviour is the same in python3.8's `venv`, Too bad this wasn't mentioned in https://bugs.python.org/issue35328. Thanks!

**Comment by gaborbernat** [comment]
Yeah, virtualenv works for all python versions though.

**Comment by Tadaboody** [comment]
It does!
I meant that even though this behavior also appears in the `venv` module at the time that bug report was opened, nobody mentioned it in the bug report and `VIRTUAL_ENV_PROMPT` was the solution they arrived at.

virtualenv works in all python versions and works great! thank you for this package :)
