### ISSUE TITLE
WinError 1 Incorrect Function when target dir can't accept symlinks but tempdir can

### ISSUE THREAD

**Issue by jaraco** [pypa/virtualenv#1992]
In tox-dev/tox#1706, I reported an issue where tox was unable to create a virtualenv for Python 3.5 when on a mounted file system from the host.

In that case, it seems that the test for "can symlink" happens on the local file system (and succeeds), but the attempt to create a symlink on the mounted filesystem fails.

The issue was only triggered in virtualenv creation on Python 3.5 (not 3.9) as seemingly symlinks are only needed for older Pythons.

**Comment by domdfcoding** [comment]
I've just run into this on Python 3.6. Works fine on 3.7 so I think this is now isolated to EOL versions of Python.

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by gaborbernat** [comment]
We no longer support these EOL pythons.
