### ISSUE TITLE
Allow user to skip the creation of plain 'python' exec when creating a python3 environment

### ISSUE THREAD

**Issue by ericriff** [pypa/virtualenv#1999]
Hi guys!

I've noticed that environments created for `python3` also have a plain `python` executable in them, which points to `python3`. This is sometimes an issue since historically `python -> python2`. 

This is an example of poetry (which relies on virtualenv) breaking a C++ project since cmake thinks it has found python2 when it actually found python3. 
https://gitlab.kitware.com/cmake/cmake/-/issues/21371

Another issue that I face is, on a repo that has a mixture of python 2 and 3 code, the python2 code gets executed with python3 if the shebang has just python in it.

Could it be possible to add a flag to avoid the creation of the python -> python3 symlink on python3 environments?

Thanks!

**Comment by gaborbernat** [comment]
I understand your problem but I don't think here your proposed solution is the appropriate one. If a script just advertises that it needs python, then it should accept any Python. If not true then those scripts need to be updated to specify explicitly their version requirements. The name ``python`` never got reserved for ``python2``, so IMHO here those scripts are broken not our naming best practice.

**Comment by ericriff** [comment]
I changed all the scripts that only specify `python` to explicitly require `python2`. Regardless if you take a look into the link I posted, there is no way for me to instruct CMake to ignore the virtual environment `python` binary. I've found a workaround for that, but it would be cleaner if I could just prevent virtualenv from creating that executable in the first place.

**Comment by gaborbernat** [comment]
For reference, you're talking about making some of these lines optional:

https://github.com/pypa/virtualenv/blob/main/src/virtualenv/create/via_global_ref/builtin/cpython/common.py#L34-L36

https://github.com/pypa/virtualenv/blob/main/src/virtualenv/create/via_global_ref/builtin/pypy/common.py#L28-L33

The main problem I envision with such a proposal is that at the moment, we offer it as a guarantee that python within the bin folder exists. This is an invariant of the system. We are actively relying on this when we calculate the executable within the virtual environment here: https://github.com/pypa/virtualenv/blob/main/src/virtualenv/create/describe.py#L81, which is defined transitively here https://github.com/pypa/virtualenv/blob/main/src/virtualenv/create/via_global_ref/builtin/cpython/common.py#L23.

As you can see, if we would allow for turning the generation of python off, we'd also have to change the executable path we're exposing. This, in turn, would break users who are not using our API to determine the executable (but instead rely on their own internal logic to build it). Such an example is tox. Most ``tox.ini`` files just contain just `python` and expect it to work within their commands section. So if there's an option to turn this off and someone turns it on for whatever reason, that might fix their cmake issues but break their tox runs inadvertently.

IMHO here, the solution should be coming from the poetry/cmake side. Not the virtualenv side.

**Comment by ericriff** [comment]
Thanks for your time. I though it might be easier to fix.
