### ISSUE TITLE
Optionally skip creation of .gitignore in virtualenv directory

### ISSUE THREAD

**Issue by compwiztobe** [pypa/virtualenv#2003]
While version controlling the virtualenv binaries etc. is not desirable, some of us version control pyvenv.cfg as well as other metadata we store about each environment (such as a pip requirements file), to facilitate portability of venv definitions.  Before the merge of #1825 in response to #1806, that problem was already easily solvable with a top level .gitignore listing the typical Python bin/, lib/, share/, etc. directories to be ignored.

The `*` directive in the virtualenv subdirectories cannot be overridden by any .gitignore files in parent directories.  If we could pass an option to virtualenv to disable the creation of this blanket `*` .gitignore, then existing .gitignore files in the venv directory AND all parent directories would continue to work as expected, and we could continue to track chosen config files stored in each environment directory.

For now, here's a workaround:
```
if [[ ! -f "$venv/.gitignore" ]]; then
  virtualenv $venv
  rm $venv/.gitignore
else
  virtualenv $venv
fi
```
but I would much rather be able to do this with something like
```
virtualenv $venv --no-gitignore
```
to recover the old behavior.

**Comment by gaborbernat** [comment]
@compwiztobe if you want to force adding some files you can just use:

```
git add -f venv/pyenv.cfg
```

The gitignore file is advisory for the add and can be ignored.

**Comment by compwiztobe** [comment]
This is part of a de- and re-hydrating workflow with virtualenvwrapper, where all my venvs are in a venv repository I share between systems.  Creating a separate directory for the dried metadata would work but is messier (and might interfere with venv discovery tools and collide with existing venv names).

Forcibly tracking each file by hand means I have to do this for every file, and I still don't get `git diff` and `git status` to tell me when new environments or metadata needs indexing (for example when I first create or dehydrate a venv).  What I'm looking for is the ignore directives to discriminate between my dehydrated metadata and the hydrated venv binaries.

I'm hoping to upstream this stuff into virtualenvwrapper, including my workaround wrapper `premkvirtualenv`
```
if ! grep -q "# track venv metadata" "$1/.gitignore"; then
cat >> "$1/.gitignore" << EOF

# track venv metadata
!.gitignore
!pip-packages
!pythonexec
!pyvenv.cfg
EOF
fi
```

But the .gitignore file creation could be an issue for other virtualenv use cases (not just my situation with virtualenvwrapper) so I wanted to bring it up here, namely, the creation of a blanket `*` .gitignore at low-level subdirectory where it cannot be overridden, and with no option to skip creating that file.
