### ISSUE TITLE
Allow importlib-metadata v3.0.0

### ISSUE THREAD

**Issue by abtreece** [pypa/virtualenv#2019]
Receiving test failures due to the recent upgrade of `importlib-metadata` to [v3.0.0](https://github.com/python/importlib_metadata/releases/tag/v3.0.0)

```
virtualenv 20.2.0 has requirement importlib-metadata<3,>=0.12; python_version < "3.8", but you have importlib-metadata 3.0.0.
```

https://github.com/pypa/virtualenv/blob/ced984abfd4f1531f9075113e77af7ec01479d29/setup.cfg#L47

**Comment by Aparna-BS** [comment]
Hi @gaborbernat,
I am facing the same issue. May I know when will the next build be released with this merged fix? Thanks.

**Comment by abtreece** [comment]
glitch fixed! tests re-ran without `importlib-metadata` failure...

```
py37 installed: ..., importlib-metadata==3.0.0, ..., virtualenv==20.2.1, ...
___________________________________ summary ____________________________________
  py37: commands succeeded
  congratulations :)
```
