### ISSUE TITLE
CPython2 suppport on Apple M1

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#2024]
👍 I don't have access to such hardware, so PRs are welcome.

**Comment by gdubicki** [comment]
Hi! I also did run into this issue and spent quite a lot of time figuring out what was going on.

How about we start with adding code that will show a friendly error message when trying to create a virtualenv for Python 2 on a Apple Silicon Mac, explaining that it doesn't work as of now.

Would such PR be accepted?

**Comment by gaborbernat** [comment]
Sure.
