### ISSUE TITLE
Python interpreters broken after system update

### ISSUE THREAD

**Issue by whatsthecraic** [pypa/virtualenv#2028]
Hi there,
I am unable to start anymore the python interpreters after a system update from python v3.8 to python v3.9. In the environments created before the update, these interpreters now refer to the non existing python v3.8:
```
(ds19) # /workspace/virtualenv/ds19/bin: ldd python
	linux-vdso.so.1 (0x00007ffd9bddc000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fcdbdfe4000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fcdbe1dc000)
	libpython3.8.so.1.0 => not found
```
while creating a new environment, after the  system update, correctly refers to the current python version:
```
(ds20) # /workspace/virtualenv/ds20/bin: ldd python
	linux-vdso.so.1 (0x00007ffca8f33000)
	libpython3.9.so.1.0 => /usr/lib/libpython3.9.so.1.0 (0x00007f932e2b7000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f932e0ee000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f932e0cc000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f932e0c6000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f932e0c1000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f932df7b000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f932e6ac000)
```
What is the proper way to update the interpreters in the existing virtualenv environments after a system update?

O.S. Arch Linux, 64bit.

**Comment by gaborbernat** [comment]
> What is the proper way to update the interpreters in the existing virtualenv environments after a system update?

Simply put the python ecosystem does not support this. Looking past the interpreter itself, some packages that worked on 3.7 are not guaranteed to still be operating on 3.8. The recommended way is to recreate all your virtual environments, and reinstall dependencies.

**Comment by whatsthecraic** [comment]
as `pip freeze` is also broken for the same reason, is there a way to retrieve the list of packages present in the environment, without having to reinstall the old python interpreter?

**Comment by gaborbernat** [comment]
You could navigate over the site-packages folder of the interpreter and find all ``{package name}.dist-info`` folders.
