### ISSUE TITLE
An option to show details of the currently active environment

### ISSUE THREAD

**Issue by greatvovan** [pypa/virtualenv#2031]
**What's the problem this feature will solve?**
As a developer who works with multiple projects and has a few Terminal windows open, I need to know (at least):
- the directory of the current virtual environment,
- the base Python from which it was created.

**Describe the solution you'd like**
A CLI option, e.g. `--show` or `--current`

**Alternative Solutions**
A rough equivalent of above is:
```
echo $VIRTUAL_ENV
cat $VIRTUAL_ENV/pyvenv.cfg 
```

**Additional context**
Having such an option is time-saving as one does not need to memorize file and variable names.

**Comment by gaborbernat** [comment]
This request didn't see much support for 3 years, so closing it.
