### ISSUE TITLE
Breakdown of Multiprocessing capabilities

### ISSUE THREAD

**Issue by PurvPatel** [pypa/virtualenv#2044]
**Issue**
It seems that multiprocessing (library) capabilities are broken in the environments created by virtualenv==20.2.2 and python==3.7.2. The problem can be replicated by running the first example code from the python multiprocessing docs in a active environment created by the above version python language and virtualenv package. The code will fail to compile  (due to a live or dead lock most likely). It's similar to this bug: https://bugs.python.org/issue35797. Its changeset: https://github.com/python/cpython/commit/4e02f8f8b4baab63f927cfd87b401200ba2969e9

Tested Code:
```code
from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))
```
Expected Output:
```Expected Output
[1, 4, 9]
```
Actual Output if ran on environment created by virtualenv==20.2.2 on python==3.7.2:
nothing, it just locks up. I can't even terminate the process from task manager :(.

**Environment**
windows cmd
python: 3.7.2
virtualenv: 20.2.2

Provide at least:
- OS: Windows 10 (64-bit) 20H1
- ``pip list`` of the host python where ``virtualenv`` is installed:

```console
Package    Version
---------- -------
appdirs    1.4.4
distlib    0.3.1
filelock   3.0.12
pip        20.2.3
setuptools 49.2.1
six        1.15.0
virtualenv 20.2.2
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the 'c:\users\purv8\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
```
**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console

```
edit:
works fine if environments are created from virtualenv==20.0.31

**Comment by gaborbernat** [comment]
Can you replicate the issue when using the `venv` module instead of `virtualenv`? If yes, this is a core interpreter bug, and you should report it to  bugs.python.org.

**Comment by PurvPatel** [comment]
I can replicate the issue with venv which I knew was possible so framing this as a bug  might not have been the way to go about this. I just found it strange that older versions of virtualenv did not seem to have this issue ( ie it works fine for virtualenv==20.0.31, everything else kept constant), while the newer version of virtualenv seems to be causing this issue.

**Comment by gaborbernat** [comment]
Upstream bug in cpython.
