### ISSUE TITLE
Update activate.bat VIRTUAL_ENV path

### ISSUE THREAD

**Issue by rmoser** [pypa/virtualenv#2053]
**What's the problem this feature will solve?**
This issue may exist for other operating systems, but I work in Windows...

If I create a venv, and then move the folder, activate.bat has a static path which no longer exists.  So to move a venv folder I have to delete the venv, then re-create it in the new location.  Or manually update activate.bat.  This static nature seems completely unnecessary.

I can make these changes, so I'm offering this up first for discussion...  Though, I'm not sure I know enough about the other environments to apply similar changes, so if consistency across os'es is something you want/ require, then I'd either need help, or I'd just make these changes privately for my own use.

**Describe the solution you'd like**
1.  Windows batch file syntax supports "%dp0" as the path to the folder where the batch file exists.  The value includes the trailing backslash, so for batch, this line `set "VIRTUAL_ENV=__VIRTUAL_ENV__"` could be replaced with `set "VIRTUAL_ENV=%dp0.."`.

2.  I'd also suggest omitting this line, so that a folder rename also continues to work:
`set "ENV_PROMPT=(micro-mart) "`
There's already code to use the actual folder name when this variable hasn't already bet set.

With both these changes, the activate.bat file would not differ across venv instances...

**Alternative Solutions**
If you don't want them, I can implement these changes for my own personal use...no hard feelings.

**Additional context**
None

**Comment by gaborbernat** [comment]
> If I create a venv, and then move the folder

This operation is not supported by either venv or virtualenv.
