### ISSUE TITLE
importlib-metadata dropped support for python 3.5

### ISSUE THREAD

**Issue by jimmyharris** [pypa/virtualenv#2059]
https://github.com/pypa/virtualenv/blob/9093686efdd17995900ac3ea75035c1573140a80/setup.cfg#L48

Importlib-metadata dropped support for python 3.5 which is the python used in ubuntu 16.4 LTS. This effectively limits virtualenv to python 3.6 and newer. for its host platform.

The last version that supported python 3.5 was importlib-metadata v2.1.1.

**Comment by jimmyharris** [comment]
I'm not sure how to express the correct requirement for python 3.5 but it is something that should be added if virtualenv is expected to continue to support python 3.5

**Comment by gaborbernat** [comment]
> Importlib-metadata dropped support for python 3.5 which is the python used in ubuntu 16.4 LTS. This effectively limits virtualenv to python 3.6 and newer. for its host platform.

Not true. You'll get pulled in the latest compatible versions of all packages, and everything still works with those:

```
  "3.5": {
    "==any": {
      "appdirs": "__virtualenv__/appdirs-1.4.4-py2.py3-none-any/appdirs-1.4.4.dist-info",
      "distlib": "__virtualenv__/distlib-0.3.1-py2.py3-none-any/distlib-0.3.1.dist-info",
      "filelock": "__virtualenv__/filelock-3.0.12-py3-none-any/filelock-3.0.12.dist-info",
      "six": "__virtualenv__/six-1.15.0-py2.py3-none-any/six-1.15.0.dist-info",
      "importlib_metadata": "__virtualenv__/importlib_metadata-2.1.1-py2.py3-none-any/importlib_metadata-2.1.1.dist-info",
      "zipp": "__virtualenv__/zipp-1.2.0-py2.py3-none-any/zipp-1.2.0.dist-info",
      "importlib_resources": "__virtualenv__/importlib_resources-3.2.1-py2.py3-none-any/importlib_resources-3.2.1.dist-info"
    }
  },
```

This should happen automatically if you use any recent pip to install it, or you use our zipapp.
