### ISSUE TITLE
Downloading with pip install is downloading some other packages also. 

### ISSUE THREAD

**Issue by jprasanna1981** [pypa/virtualenv#2099]
**Issue**

1. Downloading with pip install is downloading some other packages also. Like distlib filelock appdirs six importlib-resources importlib-metadata pathlib2 scandir

Command used **pip --disable-pip-version-check install --download=/tmp/internal/virtualenv virtualenv**

How to avoid these extra downloaded packages?

2. Also what is the difference between virtualenv-20.4.4 and virtualenv-13.0.3 ? We are facing some issue after the latest release.

**Environment**

Provide at least:
- OS: CentOS Linux release 7.9.2009 (Core)
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console

  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console

```

**Comment by gaborbernat** [comment]
> How to avoid these extra downloaded packages?

You can't.

> 1. Also what is the difference between virtualenv-20.4.4 and virtualenv-13.0.3 ? We are facing some issue after the latest release.

A complete rewrite. virtualenv 20+ is now using the same mechanism venv is.
