### ISSUE TITLE
site.getsitepackages() doesn't respect --system-site-packages on python2

### ISSUE THREAD

**Issue by freundTech** [pypa/virtualenv#2106]
**Issue**

site.getsitepackages() doesn't respect --system-site-packages being set on python2. System site-package paths are never included. 
I came across this while working on #2105. In contrast to #2105 this is not specific to debian, which is why I am creating a separate issue for it.

```
python -m virtualenv --system-site-packages -ppython2 testenv
. testenv/bin/activate
python -c "import site; print(site.getsitepackages())"
['/home/adrian/Documents/dev/uni/bachelor/mypy/testenv/lib/python2.7/site-packages', '/home/adrian/Documents/dev/uni/bachelor/mypy/testenv/lib/site-python']
```

**Environment**

Provide at least:
- OS: Tested on both Ubuntu 18.04.3 LTS and Arch Linux
- ``pip list`` of the host python where ``virtualenv`` is installed:

Same as #2105 

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:
Same as #2105

**Comment by c0d3h4x0r** [comment]
This is still broken for my use case in virtualenv==20.4.6 w/ python 2.7.16 (at least on Windows).

`site.getsitepackages()` does not contain the system site packages locations when specifically called from within `sitecustomize.py`.

**Comment by c0d3h4x0r** [comment]
It appears to me that this ordering is wrong:

`    load_host_site()
    if global_site_package_enabled:
        add_global_site_package()`

I'm guessing that `add_global_site_package()` really should be called _before_ `load_host_site()`.
