### ISSUE TITLE
virtualenv --list ?

### ISSUE THREAD

**Issue by iburunat** [pypa/virtualenv#2112]
As a way to keep track of already created environments, it would be great to have this option (unless it has it already and I'm not aware of it). Thanks!

**Comment by gaborbernat** [comment]
There's no easy way to do this. And might be less useful than you think. Many tools use virtualenv under the hood, so this list could also contain a lot of elements that were not created manually by the users. Can you clarify, when, why, and how would you use this feature?

**Comment by iburunat** [comment]
Understood. I just wanted to keep track of my projects-environments, and potentially find heavy ones I could dispose of, but this I can achieve by other means. Thanks again.
