### ISSUE TITLE
Add encapsulation layer for project settings

### ISSUE THREAD

**Issue by moghadas76** [pypa/virtualenv#2114]
**What's the problem this feature will solve?**
Add config file(like YAML file) to venv sub directories to customize project settings per venv. So we can run single project simultaneously with different settings.  

**Describe the solution you'd like**
Create config.yaml during venv creation and set initial settings as default settings. We can enable it by ```--config``` flag.

**Comment by gaborbernat** [comment]
Can you please clarify what exactly you're aiming for here and why do you think this should be solved at the virtual environment creation level? Thanks!

**Comment by moghadas76** [comment]
Suppose I have a django project and I want to deploy it(the same project) with two different configs in two virtualenv. We need a facility that customized configs(settings.py) are fed to virtualenv. Also memory is limited so we cannot use docker.

**Comment by gaborbernat** [comment]
What you describe here sounds like you want different configuration packages rather than two different virtual environments. That being said you could probably achieve this by creating a virtual environment plugin (see https://virtualenv.pypa.io/en/latest/extend.html), but I'd recommend against that.

**Comment by moghadas76** [comment]
No I have two environments, which are development and test.

**Comment by moghadas76** [comment]
We create package for django app rather than django project which settings are in the project not in an app
