### ISSUE TITLE
Insert virtualenv path before PYTHONPATH on creation

### ISSUE THREAD

**Issue by Flamefire** [pypa/virtualenv#2118]
**What's the problem this feature will solve?**

On HPC clusters we install software as modules, e.g. numpy and scipy go into an extra folder (via pip --prefix) and extend PYTHONPATH when "loading" the module so python finds them. This is so that 100s of users don't install stuff themselves on a shared file system. Separation those installations out into different folders is necessary due to dependencies.

Now the problem is that when creating a virtualenv (even with `--system-site-packages`) the packages installed into the virtualenv have lower priority than those in PYTHONPATH, so they can't be easily updated by users.

**Describe the solution you'd like**

When creating a virtualenv with `--system-site-packages` it could take the current PYTHONPATH and insert its own paths **before** that so it takes precedence.

**Alternative Solutions**

Manually adding the virtualenvs site-packages folder in front of PYTHONPATH works, but requires an extra step. This could be done in the activate script, but that would need to be modified for every virtualenv created

**Comment by gaborbernat** [comment]
We don't plan to add this functionality out of the box, however you can implement this now via our plugin system - see https://virtualenv.pypa.io/en/latest/extend.html
