### ISSUE TITLE
Add option to disable pip update request

### ISSUE THREAD

**Issue by mitchhentges** [pypa/virtualenv#2125]
**What's the problem this feature will solve?**
The tooling for my project uses `virtualenv` and its embeds to get a consistent virtualenv online. However, when installing packages into that environment, pip prints the outdated warning:
```
WARNING: You are using pip version 20.3.1; however, version 21.1.2 is available.
You should consider upgrading via the '<snip>/python -m pip install --upgrade pip' command.
```

This warning isn't accurate for my case: for a given commit, we want dependencies pinned, including `pip`: so, other developers should not manually upgrade `pip` within these environments. When the tooling devs bump the `virtualenv` version, we'll let that cause `pip` to be upgraded for developers accordingly.

By disabling the warning, we'd ensure that developers don't have to consider whether the `pip` warning is one they need to resolve or one they can ignore.

**Describe the solution you'd like**
Perhaps we can add a command-line option to `virtualenv` to automatically configure `pip` to avoid printing the "outdated" warning?
`virtualenv <target> --no-pip-outdated-warning`?

This can be implemented using the functionality that [`pip` set up for distros](https://github.com/pypa/pip/issues/5346): configure `pip` such that [`pip`'s `dist.installer` is not `"pip"`](https://github.com/pypa/pip/blob/5ee933aab81273da3691c97f2a6e7016ecbe0ef9/src/pip/_internal/self_outdated_check.py#L100-L101).

**Alternative Solutions**
In the meantime, I'll manually configure `pip`'s `dist.installer` after `virtualenv` has created the environment.

**Additional context**
[Downstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1712819).

**Comment by gaborbernat** [comment]
This sounds like a pip configuration issue, and likely fixable via a virtualenv plugin you can create https://virtualenv.pypa.io/en/latest/extend.html
