### ISSUE TITLE
Stdout: file not found error

### ISSUE THREAD

**Issue by ag-monk** [pypa/virtualenv#2140]
**Issue**

While running pre-commit install hooks using repo as Yelp/detect-secrets getting below error:

Error:
pre-commit install-hooks
[INFO] Installing environment for https://github.com/Yelp/detect-secrets
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes…
An unexpected error has occurred: CalledProcessError: command: (‘c:\users\user\dir\python-3.8.5-embed-amd64\python.exe’, ‘-mvirtualenv’, ‘C:\Users\user\.cache\pre-commit\repolfrsus6q\py_env-default’)
return code: 1
expected return code: 0
stdout:
FileNotFoundError: [WinError 3] The system cannot find the path specified: ‘c:\users\user\dir\python-3.8.5-embed-amd64\DLLs’

stderr: (none)
Check the log at C:\Users\user\.cache\pre-commit\pre-commit.log

**Environment**

OS: windows 10 64 bit 
Python version: 3.8.5
Pre-commit —version: 2.13.0
detect-secrets —version: 1.0.3

pip list
![E262A668-D848-4F65-B4E2-41B652F7F0C2](https://user-images.githubusercontent.com/79554786/124863647-1b101900-dfd5-11eb-9eae-c6bdaa5bdeb3.jpeg)

pre-commit-config.yaml

repos:
-repo: https://github.com/Yelp/detect-secrets
rev: v1.1.0
hooks:
- id: detect-secrets
args: [‘—baseline’, ‘.secrets.baseline’]
exclude: ./tests

Python.exe -m virtualenv venv 
File not found error : [WinError 3] The system cannot find the path specified: ‘C:\\ Users\user\dir\python-3.8.5-embed-amd64\DLLs’

**Comment by gaborbernat** [comment]
Please try with latest release, and open issue for pre-commit.
