### ISSUE TITLE
making activate.bat relocatable (windows)

### ISSUE THREAD

**Issue by kbrowder** [pypa/virtualenv#215]
set VIRTUAL_ENV=somepath

could be changed to
set VIRTUAL_ENV=%~dp0..

and then the virtual env would be relocatable on windows with the exception of exe script wrappers.

**Comment by arizvisa** [comment]
Adding a reference to the newest issue #1067 related to this to help consolidate efforts on solving this half-decade old problem.

**Comment by tobiasherp** [comment]
+1

**Comment by arizvisa** [comment]
@tobiasherp, please +1 in issue #1067. You can also use the "reaction" icon instead of a comment to show relevance.
