### ISSUE TITLE
Add symlinks to Python shared library in $VIRTUAL_ENV/lib

### ISSUE THREAD

**Issue by omansion** [pypa/virtualenv#216]
Hi,

I compiled a CPython 2.7.2 with the --enable-shared option. As a consequence, some libpython.so.\* are generated in $PYTHONHOME/lib

Would it be possible to add symlinks to these libraries in $VIRTUAL_ENV/lib when creating the virtualenv ? It would be less confusing to export LD_LIBRARY_PATH on this folder than on the $PYTHONHOME/lib one when installing some packages including C (such as netifaces) ?

Thanks!

**Comment by lambdafu** [comment]
I also encountered this problem.

**Comment by black-puppydog** [comment]
In conda this seems to have been fixed. How come this has been sitting here since 2012 without much activity? If I understand correctly, this also prevents any package with compiled components to run correctly?
