### ISSUE TITLE
Add option to specify 

### ISSUE THREAD

**Issue by bedge** [pypa/virtualenv#2162]
**What's the problem this feature will solve?**

**Describe the solution you'd like**

**Alternative Solutions**

**Additional context**

**Comment by gaborbernat** [comment]
The body of this issue seems empty.

**Comment by bedge** [comment]
> The body of this issue seems empty.

Apologies, hit commit too soon then got distracted.

**Comment by gaborbernat** [comment]
The feature set you described seems like highely specifc to an OS and how you install the project. virtualenv does not control the installation of the project so there's nothing we should or can do here.
