### ISSUE TITLE
ModuleNotFoundError virtualenv.activation.nushell since 20.8.0

### ISSUE THREAD

**Issue by StephanHCB** [pypa/virtualenv#2187]
**Issue**

expected: poetry install successfully creates virtual env

observed: 
- fails with today's new release 20.8.0
- works if I run `pip3 install 'virtualenv==20.7.2' --force-reinstall` first
 
**Environment**

Provide at least:
- OS: alpine linux 3.12

**Output of the virtual environment creation**

(running in docker using alpine 3.12)

```
RUN poetry install --no-root --no-dev
Creating virtualenv in ...

  ModuleNotFoundError

  No module named 'virtualenv.activation.nushell'

  at <frozen importlib._bootstrap>:984 in _find_and_load_unlocked
```

I may be mistaken (not really a python expert), but I believe this commit/line is the culprit that broke things:

https://github.com/pypa/virtualenv/commit/e0410cafc8feedf72562174dee983fc709a5a36e#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R112

**Comment by gaborbernat** [comment]
What's broken here is your poetry installation. How did you install it?

**Comment by StephanHCB** [comment]
Thanks for the feedback.

I'll be happy to try and build a minimal example in the form of a Dockerfile later today that can hopefully reproduce the problem.

Basically this is what I do (in an alpine-image created from the alpine distribution tar.gz)

```
RUN apk upgrade --no-cache \
      && apk add --update --no-cache python3 py3-pip py3-pytest py3-openssl py3-requests py3-crypto py3-httplib2 py3-jwt py3-setuptools
RUN pip3 install tox --ignore-installed
RUN apk add --update --no-cache curl gcc musl-dev python3-dev

# install poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

# and unless I first do 
# RUN pip3 install 'virtualenv==20.7.2' --force-reinstall

# this fails with the given error
RUN poetry install --no-root --no-dev
```

**Comment by pfmoore** [comment]
> `RUN pip3 install tox --ignore-installed`

This line seems dangerous, as it will drop newer versions of libraries (including virtualenv) over the top of existing versions, which potentially leaves a "mix" of old and new code.

Why do you do `--ignore-installed` rather than a simple install (or if absolutely necessary, a `--force-reinstall`)?

**Comment by StephanHCB** [comment]
> > `RUN pip3 install tox --ignore-installed`
> 
> This line seems dangerous, as it will drop newer versions of libraries (including virtualenv) over the top of existing versions, which potentially leaves a "mix" of old and new code.
> 
> Why do you do `--ignore-installed` rather than a simple install (or if absolutely necessary, a `--force-reinstall`)?

I actually don't remember why I added that. I have now removed it and it didn't change the behavior. Thank you for the tip.

I think I have found the problem, though - @gaborbernat was right -  my container was still using poetry 1.1.7 instead of 1.1.8. With poetry 1.1.8, it works without the virtualenv downgrade.

Sorry about the confusion and thank you all for your help. Closing this.

**SOLUTION TL/DR: ensure you're on the latest poetry version!**

**Comment by ri0t** [comment]
I am just now getting this with Debian's python3-virtualenv at 20.10.0+ds-1

```
21-12-25 20:11:14 with riot in ~/src is 📦 v0.0.0 via ⬢ v14.17.0 via 🐍 system 
➜ python3                                                                     
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import virtualenv.activation.bash
>>> import virtualenv.activation.nushell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'virtualenv.activation.nushell'
>>> 
```

**Comment by gaborbernat** [comment]
This seems like a failed installation on debian :+1:
