### ISSUE TITLE
Improve documentation for --no-seed option

### ISSUE THREAD

**Issue by Exagone313** [pypa/virtualenv#2188]
Hi,

With `virtualenv` 20.8.0, seed ("embedded") packages are getting updated. This set of versions are installed automatically when a virtualenv is created.

The current help for `--no-seed` and `--no-download` are as follow:

```bash
# python -m virtualenv --help
  --no-seed, --without-pip      do not install seed packages (default: False)
  --no-download, --never-download
                                pass to disable download of the latest pip/setuptools/wheel from PyPI (default: True)
```

It is not straight forward that pip/setuptools/wheel will also be "upgraded" when `--no-seed` is not passed to the command, if `--no-download` is passed.

I think it would be best to improve the help to make it clear what seed packages are.

I think this is a documentation issue rather than an implementation bug, but you can edit this issue if not so.

**Additional context**

`setuptools` 58 removed support for 2to3, used by dependencies from our packages. `virtualenv` now upgraded to this version.

**Comment by Exagone313** [comment]
I hesitate to create an issue in tox regarding their `download` options which suffers from this issue.

**Comment by gaborbernat** [comment]
> It is not straight forward that pip/setuptools/wheel will also be "upgraded" when `--no-seed` is not passed to the command, if `--no-download` is passed

They don't get upgraded always. Only periodically and is governed by https://virtualenv.pypa.io/en/latest/cli_interface.html#no-periodic-update 

The --no-download is related to the non-periodic update.

**Comment by Exagone313** [comment]
I misunderstood how virtualenvs are created and I now understand that it caches wheels in `~/.local/share/virtualenv`.

I can't say that this is not documented, but I still think that you need to dig into the documentation to know how it works. I would have assumed that creating a virtualenv has no side effect, but this is wrong.

**Comment by gaborbernat** [comment]
Without side effect would be slow. You can switch to the pip seeder in the global virtualenv.ini configuration file if you want slow but without side effect mode.
