### ISSUE TITLE
Virtualenv 20.0.3 does not create soft link from lib64 to lib

### ISSUE THREAD

**Issue by hanxinke** [pypa/virtualenv#2193]
**Issue**
The fix_lib64 method does not exist in virtualenv 20.0.0 and later versions? The PR of the old version is https://github.com/pypa/virtualenv/commit/244b23b5e89b58a4c2777a0f0975bbab7fda4dd2. Will it be synchronized to the later versions?

**Environment**

Provide at least:
- OS: openEuler
- ``pip list`` of the host python where ``virtualenv`` is installed:
virtualenv

**Output of the virtual environment creation**
[root@localhost usr1]# pip3 list|grep virtu
virtualenv               20.0.3
[root@localhost usr1]# /usr/local/bin/virtualenv -p python3 venv20.0.3
created virtual environment in 1004ms CPython3Posix(dest=/usr1/venv20.0.3, clear=False, global=False) with seeder FromAppData pip=latest setuptools=latest wheel=latest app_data_dir=/root/.local/share/virtualenv/seed-v1 via=copy
[root@localhost usr1]# ll venv20.0.3/
total 16K
drwxr-xr-x. 2 root root 4.0K Sep 22 11:07 bin
drwxr-xr-x. 3 root root 4.0K Sep 22 11:07 lib
**drwxr-xr-x. 3 root root 4.0K Sep 22 11:07 lib64**
-rw-r--r--. 1 root root  201 Sep 22 11:07 pyvenv.cfg
[root@localhost usr1]#

[root@localhost usr1]# pip3 list|grep virtu
virtualenv               16.0.0
[root@localhost usr1]# /usr/local/bin/virtualenv -p python3 venv16.0.0
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /usr1/venv16.0.0/bin/python3
Also creating executable in /usr1/venv16.0.0/bin/python
Installing setuptools, pip, wheel...done.
[root@localhost usr1]# ll venv16.0.0
total 16K
drwxr-xr-x. 2 root root 4.0K Sep 22 11:10 bin
drwxr-xr-x. 2 root root 4.0K Sep 22 11:10 include
drwxr-xr-x. 3 root root 4.0K Sep 22 11:10 lib
**lrwxrwxrwx. 1 root root    3 Sep 22 11:10 lib64 -> lib**
-rw-r--r--. 1 root root   61 Sep 22 11:10 pip-selfcheck.json

**Comment by gaborbernat** [comment]
That's on purpose. We don't overload lib64 to lib, instead we keep them in parallel which IMHO is the better intent.
