### ISSUE TITLE
Please update pip to v21.3

### ISSUE THREAD

**Issue by Ark-kun** [pypa/virtualenv#2214]
The version of pip bundled with virtualenv ( v21.2.4) gets stuck for days trying to install some of the packages.
https://github.com/pypa/pip/issues/10584

**Comment by Ark-kun** [comment]
>wait for the first patch release

JFYI, the v21.3.1 has been released.
https://github.com/pypa/pip/releases/tag/21.3.1

**Comment by gaborbernat** [comment]
Released via 20.10.0 see https://github.com/pypa/virtualenv/commit/4a1328b8f764683bffe860cd34ab0510f6e790d7
