### ISSUE TITLE
How to use venv in c embedded Python?

### ISSUE THREAD

**Issue by zeng-qinghui** [pypa/virtualenv#2230]
I need call a function written by Python by program language C. And this function depends some libraries installed in venv. It works well in cli, but breaks in embedded python. When I call it in C, the function cannot import any library in venv.

I had tried to set PATH and PYTHONPATH before Py_Initialize, but it's not worked.

**Comment by gaborbernat** [comment]
This is the virtualenv package, not venv. venv questions can be asked under https://bugs.python.org/
