### ISSUE TITLE
Allow seeding extra packages in virtualenvs while not using `--extra-index-url`

### ISSUE THREAD

**Issue by gdubicki** [pypa/virtualenv#2250]
**What's the problem this feature will solve?**

I would like to make it possible so that the newly created virtualenvs include the [keyring](https://pypi.org/project/keyring/) and packages that provide alternative keyring backends (like [keyrings.google-artifactregistry-auth](https://pypi.org/project/keyrings.google-artifactregistry-auth/)) so that [pip can use it to authenticate to repositories](https://pip.pypa.io/en/stable/topics/authentication/#keyring-support).

**Describe the solution you'd like**

Frankly I don't know how to implement it as I don't know virtualenv well enough.

There are 2 problems here to solve:
1. install some extra packages while seeding,
2. make it possible to NOT use `--extra-index-url` configured in global or user-level pip config while installing the extra packages,

The former perhaps could be achieved by something like `--extra-seed-packages` parameter that could accept a path to a `requirements.txt` file.

But unfortunately as far as I know pip doesn't know how to unset `--extra-index-url` - see https://github.com/pypa/pip/issues/6394... :/ 

**Alternative Solutions**

I found a [workaround](https://stackoverflow.com/a/19459977/2693875) where you create the virtualenv with `--system-site-packages` and then install all the packages with `pip install --ignore-installed` but it's a very ugly hack in my opinion as it has all the downsides of using `--system-site-package` and it's inconvenient to use as it requires a custom way of installing each package in it.

**Additional context**

I would like to roll out the [Google Cloud Artifact Registry](https://cloud.google.com/artifact-registry) for Python across my organization but I am having a problem with providing a simple to use instructions for our developers.

This solution's [user docs](https://cloud.google.com/artifact-registry/docs/python/quickstart#setup-venv) assume that you configure each virtualenv individually for use with this registry. That's quite lot of extra work for develop working on many projects. That's why I would like to provide a way to do it once and then use virtualenv like before.

So if you install the keyring and keyrings.google-artifactregistry-auth into your _system_ Python, add `--extra-index-url` to your _user-level_ `~/.pip/pip.conf` and log in to Google Cloud SDK once, then you _can_ use the custom registry using automatic, non-interactive authentication.

However if afterwards you create a virtualenv and activate it, then as it doesn't contain keyring and keyrings.google-artifactregistry-auth packages and it will read your user-level config, it will try to use the extra index and trigger an interactive authentication request...

Perhaps there are existing options to achieve this that I am not aware of. Please let me know if there are.

**Comment by gaborbernat** [comment]
> I would like to make it possible so that the newly created virtualenvs include the [keyring](https://pypi.org/project/keyring/) and packages that provide alternative keyring backends (like [keyrings.google-artifactregistry-auth](https://pypi.org/project/keyrings.google-artifactregistry-auth/)) so that [pip can use it to authenticate to repositories](https://pip.pypa.io/en/stable/topics/authentication/#keyring-support).

This is definitely encouraged to be added and supported as a separate plugin as documented here https://virtualenv.pypa.io/en/latest/extend.html#seed-mechanism

If you do create and publish that plugin please come back with a comment here to let other people know about it.
