### ISSUE TITLE
virtualenv 20.11.0 broke our pre-commit checks

### ISSUE THREAD

**Issue by dhalperi** [pypa/virtualenv#2257]
**Issue**

After overnight upgrade of virtualenv to 20.11.0, our precommit checks started failing with:

```
File "/home/batfish/.cache/pre-commit/repozzh13x5u/py_env-python3/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 92, in create_module
--
  | return importlib.import_module('setuptools._distutils')
  | File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | ModuleNotFoundError: No module named 'setuptools'
```

**Environment**

Provide at least:
- OS: Ubuntu 20.04, AWS Linux
- ``pip list`` of the host python where ``virtualenv`` is installed:
  ```console
    Installing collected packages: six, platformdirs, filelock, distlib, virtualenv, toml, pyyaml, nodeenv, identify, cfgv, pre-commit
      | Successfully installed cfgv-3.3.1 distlib-0.3.4 filelock-3.4.2 identify-2.4.1 nodeenv-1.6.0 platformdirs-2.4.1 pre-commit-2.16.0 pyyaml-6.0 six-1.16.0 toml-0.10.2 virtualenv-20.11.0
  ```

**Investigation**

Last succeeding build (public): https://buildkite.com/batfish/pybatfish-pre-commit/builds/27313#bbf21871-a3c6-44e6-b63b-f797e3c7de1f

Next run, first failing build (public): https://buildkite.com/batfish/pybatfish-pre-commit/builds/27314#475992ad-c90a-4457-ad74-1b94a0f78762

The only difference appears to be the upgrade to virtualenv-20.11.0 and the correspond loss of `backports.entry-points-selectable`.

It has something to do with `isort`; I've tried both `5.8.0` (as in the existing pre-commit file) and the latest `5.10.1` release. Disabling `isort` check in `pre-commit` makes the build pass. https://github.com/batfish/pybatfish/pull/805

**Comment by gaborbernat** [comment]
As https://github.com/pre-commit/pre-commit/issues/2178#issuecomment-1002163763 details the culprit here is pip and setuptools, virtualenv just makes easier that bug to manifest. There's nothing to be done on our end though.

**Comment by dhalperi** [comment]
Thank you!

**Comment by gaborbernat** [comment]
https://pypi.org/project/virtualenv/20.11.1/ now ships setuptools 60.1.1 with the fix
