### ISSUE TITLE
virtualenv always switch back to embedded wheels after a recent periodic update 

### ISSUE THREAD

**Issue by mayeut** [pypa/virtualenv#2265]
**Issue**

virtualenv **always** switch back to embedded wheels after a recent periodic update (less than an hour).
Here, **always** means it does this even if a previous manual / periodic update was valid.
This can lead to outdated `pip`, `setuptools` & `wheel` packages in the created environment (they could have been more recent if the periodic update had not kicked-in less than an hour ago).

**Environment**

up-to-date main branch: 51408e689b3eb28d87cb4d9638b09e6e4d81f618
```console
tox -e dev
```

**Reproducer**

```diff
diff --git a/tests/unit/seed/wheels/test_bundle.py b/tests/unit/seed/wheels/test_bundle.py
index 16ea2fd..beee540 100644
--- a/tests/unit/seed/wheels/test_bundle.py
+++ b/tests/unit/seed/wheels/test_bundle.py
@@ -1,12 +1,14 @@
 from __future__ import absolute_import, unicode_literals
 
 import os
+from datetime import datetime
 
 import pytest
 
 from virtualenv.app_data import AppDataDiskFolder
 from virtualenv.seed.wheels.bundle import from_bundle
 from virtualenv.seed.wheels.embed import get_embed_wheel
+from virtualenv.seed.wheels.periodic_update import dump_datetime
 from virtualenv.seed.wheels.util import Version, Wheel
 from virtualenv.util.path import Path
 
@@ -26,9 +28,9 @@ def app_data(tmp_path_factory, for_py_version, next_pip_wheel):
     app_data_ = AppDataDiskFolder(str(temp_folder))
     app_data_.embed_update_log("pip", for_py_version).write(
         {
-            "completed": "2000-01-01T00:00:00.000000Z",
+            "completed": dump_datetime(datetime.now()),
             "periodic": True,
-            "started": "2000-01-01T00:00:00.000000Z",
+            "started": dump_datetime(datetime.now()),
             "versions": [
                 {
                     "filename": next_pip_wheel.name,
```

**Comment by gaborbernat** [comment]
A pr for this would be welcome.

**Comment by mayeut** [comment]
@gaborbernat,

> A pr for this would be welcome.

Was going to but when investigating this, I found other issues:
- patch versions are ignored if less than 28 days old (from what I read, I thought they were always considered ?)
- manual upgrades are discarded once a periodic upgrade is done (e.g. force a manual upgrade at t+0, this has setuptools released at t+0 which is used because update triggered manually, at t+14, periodic update kicks in, setuptools released at t+0 won't be used anymore until t+28)

I'm thinking that a PR shall tackle all of these at once. Shall I open an issue for each one and just one PR ?
This will likely lead to the embed JSON format to change.
I guess the `1` in the path `{app data}/virtualenv/wheel/3.9/embed/1/setuptools.json` is related to versioning of this JSON format.

**Comment by gaborbernat** [comment]
Yes, the 1 is the file format version 👌

**Comment by mayeut** [comment]
PS: the improvement I mentioned on the Discourse channel could probably done more easily with the embed JSON format change I'm thinking about
