### ISSUE TITLE
Do not attempt to download previously downloaded wheels

### ISSUE THREAD

**Issue by mayeut** [pypa/virtualenv#2268]
**What's the problem this feature will solve?**
Speed-Up virtualenv creation when using previously downloaded wheels.

**Describe the solution you'd like**
Cache the fact that it was already downloaded in the relevant JSON embed file.

Real world example:
cibuildwheel uses pinned versions of all those packages, this would speed-up the virtual environment creation.

Timings:
Using CPython 3.9 on my macOS laptop, I expect the creation time to drop from around 3 seconds to less than 1 second. 

**Alternative Solutions**
Custom seeder but it wouldn't benefit everyone for what I consider a base feature. Furthermore, the API is marked as unstable in the docs.

**Additional context**
Needed evolution to the JSON embed file format can be taken into consideration when solving #2265, #2266, #2267

**Comment by gaborbernat** [comment]
Released via https://virtualenv.pypa.io/en/latest/changelog.html#v20-13-0-2022-01-02
