### ISSUE TITLE
Filelock 2.4.2 dropped support for python 3.6

### ISSUE THREAD

**Issue by axlroden** [pypa/virtualenv#2280]
Currently virtualenv supports python 3.6, but on a recent install I got issues with filelock 2.4.2 as it dropped support for python 3.6.
Not sure if this is the right place to complain? But can the dependency check be fixed or is python 3.6 getting dropped ?

I'm stuck on this version on some old servers with no easy way to upgrade.

**Comment by gaborbernat** [comment]
How did you install virtualenv? pip should pick an older version and this shouldn't be an issue. Alternatively you can use the zipapp that has all the compatible versions too.

**Comment by axlroden** [comment]
was a pip3.6 install, I can fix the issue by using filelock 2.4.1, just wierd the dependency tree doesn't work

**Comment by gaborbernat** [comment]
> was a pip3.6 install, I

Can you please post a detailed output of this? Including the pip version.

**Comment by axlroden** [comment]
```
pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
development [root@thor ~]# pip install virtualenv
Collecting virtualenv
  Downloading virtualenv-20.13.0-py2.py3-none-any.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 26.5 MB/s
Collecting filelock<4,>=3.2
  Downloading filelock-3.4.1-py3-none-any.whl (9.9 kB)
```

I can't recreate it now, it seems to have been fixed?

**Comment by gaborbernat** [comment]
Probably you had an old pip that did not understand python-requires 👍
