### ISSUE TITLE
Virtual Env don't work if a package operator is in same dir

### ISSUE THREAD

**Issue by LeandroMoura3** [pypa/virtualenv#2291]
When I create a package called operator, virtual env don't working well. And when I remove the virtual env and create another, I can't. I don't know if it a expected behavior, but I assume that is stranger. Follow steps to reproduce that:

```
mkdir test
mkdir operator
touch __init__.py
cd ..
python -m venv .myenv
```

This don't work in my ubuntu. Here the stacktracer:
```
Could not import runpy module
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 15, in <module>
    import importlib.util
  File "/usr/lib/python3.8/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/usr/lib/python3.8/contextlib.py", line 5, in <module>
    from collections import deque
  File "/usr/lib/python3.8/collections/__init__.py", line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
ImportError: cannot import name 'itemgetter' from 'operator' (***/test/operator/__init__.py)
```

But if I change the folder name, it works:

```
mv operator another_name
python -m venv .myenv
```

And then my .myvenv is created.

Ubuntu 20 lts,
Python 3.8

**Comment by gaborbernat** [comment]
`python -m venv .myenv` is part of cpython - https://github.com/python/cpython/tree/main/Lib/venv and is not this project. Issue for CPython can be filled at https://bugs.python.org/
