### ISSUE TITLE
Add an environment variable to designate where virtual env are stored by default, and add project link

### ISSUE THREAD

**Issue by julie777** [pypa/virtualenv#2297]
**What's the problem this feature will solve?**
1. I have to provide a path the virtual env when creating it. 
2. Many tools are build on top of virtualenv and don't know where to look for existing virtual envs
3. some tools create virtual envs in the project directory (hatch, tox)
4. virtual envs don't reference a project directory so tracking how to use them and when they can be deleted is more difficult.

**Describe the solution you'd like**
Define an environment variable that the user can set to provide the location for storing virtual envs. Perhaps VIRTUALENV_HOME.
Add to pyenv.cfg in the virtual env a project setting that has the path to the related project.

I want all tools to be able to find existing virtual environments.
I want tools to have a standard location to create virtual environments.

Virtualenvwrapper provides WORKON_HOME as the location for virtual envs it creates and therefore it can list them provide autocomplete to change the active environment, etc. This works extremely well. However, other tools don't use the WORKON_HOME from virtualenvwrapper, and they shouldn't. For example: I can ask hatch to list venvs and it will report there are none.

virtualenvwrapper also links projects to venvs by adding a .project file to the venv. This allows tools to have knowledge of where the actual project code for a given venv resides. Again this is just providing more information for tools built upon virtualenv to better manage and work with projects and their virtualenvs. 

By making these small changes to virtualenv, the entire ecosystem will benefit from standardization and compatibility.

**Alternative Solutions**
I use virtualenvwrapper now.
I would like other tools to work just as smoothly.

**Additional context**
One thing to note: I use git-bash in on Windows to work with all my windows projects. The only windows specific install I do is for Python. All other python related tools and libraries are installed with pip or pipx. For the most part they all work well. This also allows me to have a common setup with a shared home directory and dot files. With Windows now having WSL integrated switching from Linux to bash on windows and working on cross-platform development has become very easy, excepting a few minor glitches.

**Comment by gaborbernat** [comment]
What you're describing is out of scope for this project and they are specialized tools that use virtualenv under the hood to provide differing functionality; e.g. .tox very much wants the virtualenv to be in line with the project. You're free to use any virtual environment managers, but this project will not do so. It's tightly focused on just creation of projects.
