### ISSUE TITLE
provide support for XDG directories on all platforms.

### ISSUE THREAD

**Issue by julie777** [pypa/virtualenv#2298]
**What's the problem this feature will solve?**
Allow uniformity across platforms.
Allow sharing a HOME directory and configuration (dot) files across platforms.
Let users decide where files go and how visible or sharable they are.

**Describe the solution you'd like**
If any of the XDG directory variables are set, use those values instead of hard coding platform values.
This is critical for XDG_CONFIG_HOME as a user's HOME directory and dotfiles may be shared across multiple platforms.

Currently I develop for Windows and Linux (with WSL) and share a common HOME directory and all my configuration files. 

I have been sharing a common home directory and dotfiles across multiple platforms even before there was Linux. It was common practice for Unix networks to have a network home directory for each user and use it regardless which machine of variant OS was running.

In addition to providing an easy way to share configuration files with a shared HOME directory, allowing users to always specify directories that applications use for various kinds of storage helps users understand and control storage without dealing with esoteric platform specific directories. Yes I am talking mostly about Windows and the use of AppData for many things, given that the user can't even see it without changing Windows settings. This might be okay for a Windows GUI app that manages all it own configuration/settings, but for command line dev tools, hiding config files in awkward to get to location by default is not a great idea.

**Alternative Solutions**

**Additional context**
Refer to the XDG directories spec
https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

**Comment by gaborbernat** [comment]
We don't manage this, it's handled by upstream, for that see https://github.com/platformdirs/platformdirs/issues/4
