### ISSUE TITLE
provide better support for changing verbosity on the command line

### ISSUE THREAD

**Issue by julie777** [pypa/virtualenv#2305]
**What's the problem this feature will solve?**
Currently the default value of INFO and that produces messy output. Most programs are silent by default if there are no errors.

Ex:
```
$ virtualenv  dummyenv
created virtual environment CPython3.10.2.final.0-64 in 1057ms
  creator CPython3Windows(dest=C:\Users\julie\juliehome\code\projects\didi28797\dummyenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\julie\AppData\Local\pypa\virtualenv)
    added seed packages: pip==22.0.3, setuptools==60.6.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
```

While writing this and reading the help many times, I finally realized that the default is INFO. That leaves me wondering what the defaults for -v and -q really mean. Given that they are mutually exclusive I think there are values of verbosity that cannot be set.
```
verbosity:
  verbosity = verbose - quiet, default INFO, mapping => CRITICAL=0, ERROR=1, WARNING=2, INFO=3, DEBUG=4, NOTSET=5

  -v, --verbose                 increase verbosity (default: 2)
  -q, --quiet                   decrease verbosity (default: 0)
```
In any case there is no reason for -v and -q to be exclusive. I don't know what NOTSET means. I would expect that any value over 4 to be set to 4.

I want to run virtual_env with no output unless there are errors, or run showing warnings and errors.

**Describe the solution you'd like**
```
verbosity:
  default = INFO
  mapping => CRITICAL=0, ERROR=1, WARNING=2, INFO=3, DEBUG=4

  --verbosity N              directly set the value of verbosity
  -v, --verbose               increment verbosity - may appear multiple times
  -q, --quiet                   decrement verbosity - may appear multiple times
```
And, at the default level, whatever that is, there should be no output if there are no ERRORS. (I believe that the default should be ERROR or possibly INFO, but I am not sure which.

Extra: the `--verbosity` could take identifiers such as WARNING in addition to int

**Additional context**

**Comment by gaborbernat** [comment]
> Currently the default value of INFO and that produces messy output. Most programs are silent by default if there are no errors.

During the rewrite, we did set by default no output. However, users seem used that venv/virtualenv prints, so the overall feedback was users think without any output the command did not work. You can use the user-specific config file (see `virtualenv --help`) to change this default for yourself if you disagree with this.

**Comment by gaborbernat** [comment]
> Given that they are mutually exclusive I think there are values of verbosity that cannot be set.

Not that I'm aware:

CRITICAL: `virtualenv -qqq`
ERROR: `virtualenv - qq`
WARNING: `virtualenv -q`
INFO: `virtualenv`
DEBUG `virtualenv -v`
NOTSET `virtualenv -vv`
