### ISSUE TITLE
Activate should fail properly on moved environments

### ISSUE THREAD

**Issue by Aerilius** [pypa/virtualenv#2308]
**Issue**

When an environment's location is changed, `source venv/bin/activate` completes successfully and shows the `(venv)` prompt, although invoking the Python interpreter uses the system python and invoking executables from `bin` raises "command not found". It seems to be in an intermediate state giving the impression of being activated but not really activated. Issues can be very hard to debug if the virtualenv fails silently and claims being activated.

Since `--relocatable` is not supported anymore, `activate` should fail properly when an environment's location is changed. An environment's location can (unknowingly) change when running jobs on servers where you don't control on which absolute path the environment will be extracted and the job executed.

**Steps to reproduce**

```bash
$ virtualenv venv
$ source venv/bin/activate
(venv) $ pip install dummy_test
(venv) $ pip show dummy_test | grep Location
Location: /home/user/venv/lib/python3.8/site-packages
(venv) $ deactivate
$ mv venv venv_moved
$ source venv_moved/bin/activate                                                     # exit status 0
(venv) $ pip show dummy_test | grep Location
WARNING: Package(s) not found: dummy_test                                            # exit status 1
(venv) $ 
```

**Environment**

- OS: Ubuntu 20.04

**Comment by gaborbernat** [comment]
Did you raise the topic upstream at https://bugs.python.org? Also a PR trying to achieve this for all shells would be welcome.

**Comment by huanganding** [comment]
you shouldn't move "venv "directly because full path of it is hardcoded in shell script "activate".

**Comment by Aerilius** [comment]
Clear. But it should fail loudly. In my specific case I even didn't move the environment myself.

**Comment by gaborbernat** [comment]
There's no easy way to detect this and fail loudly.
