### ISSUE TITLE
(Re-)Add documentation of VIRTUAL_ENV_DISABLE_PROMPT

### ISSUE THREAD

**Issue by ktetzlaff** [pypa/virtualenv#2334]
**Issue**

The documentation rewrite of commit 7a5d03fe15 (just before tag/release v20.0.0b2) removed any reference to the `VIRTUAL_ENV_DISABLE_PROMPT` environment variable from the documentation.

If this was just an oversight, the documentation of `VIRTUAL_ENV_DISABLE_PROMPT` should be added back.

**Comment by gaborbernat** [comment]
A PR with this is welcome 👍

**Comment by ktetzlaff** [comment]
> A PR with this is welcome 👍

PR added as #2339.
