### ISSUE TITLE
Virtualenv 15 has PySpark virtualenv starting with pip 9.0.1 but host machine has pip 20.2.2

### ISSUE THREAD

**Issue by rankol** [pypa/virtualenv#2343]
**Issue**

I am using an AWS managed service called EMR Studio to provision Jupyter Notebooks that use a PySpark kernel. My understanding of this kernel is that a virtualenv is created. The issue I am facing is that the virtualenv uses pip 9.0.1 initially and requires each notebook to run a `sc.uninstall_package('pip')` command to revert to pip 20.2.2 on the host machine. I am not running any commands to create the virtual environment and am a bit limited on what I can change.

In the PySpark kernel initially if I run `sc.list_packages()` I see `pip (9.0.1)`. If I run `import pip` then `pip` to get the module location I see:

```
<module` 'pip' from '/mnt1/yarn/usercache/<LIVY_IMPERSONATION_ROLE>/appcache/application_1652110228490_0001/container_1652110228490_0001_01_000001/tmp/1652113783466-0/lib/python3.7/site-packages/pip/__init__.py'> 
```

If I run `sc.uninstall_package('pip')` then `sc.list_packages()` I see `pip (20.2.2)`. Running `import pip` then `pip` shows a new module location at  `<module 'pip' from '/usr/lib/python3.7/site-packages/pip/__init__.py'>` which seems to be the same pip location as on the host machine when running `pip show pip` at a CLI terminal.

I was able to find some references to virtualenv-15.1.0 and a pip 9 wheel in `/usr/lib/python2.7/site-packages`:

```console
- virtualenv-15.1.0-py2.7.egg-info
- virtualenv.py
- virtualenv.pyc
- virtualenv.pyo
- virtualenv_support (directory)
```

Inside the `virtualenv_support` directory I see a few wheel files.
```console
- pip-9.0.1-py2.py3-none-any.whl
- setuptools-28.8.0-py2.py3-none-any.whl
- wheel-0.29.0-py2.py3-none-any.whl
```

This is the only reference I have found to a pip 9 wheel when recursively searching directories. I have attempted to only replace that file with a `pip-20.2.2-py2.py3-none-any.whl` file but this caused some errors in the creation of the virtualenv. I did not replace setuptools or wheel with a current version. Would I need to do that?

I looked into the virtualenv.py file and came across some pieces of code that I thought were relevant to virtualenv 15 and installing wheels from the virtualenv_support directory. Gist link below. If the rest of the file is needed I can provide that.

https://gist.github.com/rankol/025bc98be9336096270db01c47d4a81b

**Environment**

Provide at least:
- OS: Amazon Linux 2
- ``pip list`` of the host python where ``virtualenv`` is installed:
```console
Package                    Version
-------------------------- ----------
beautifulsoup4             4.9.3
boto                       2.49.0
click                      7.1.2
jmespath                   0.10.0
joblib                     0.17.0
lxml                       4.6.1
mysqlclient                1.4.2
nltk                       3.5
nose                       1.3.4
numpy                      1.16.5
pip                        20.2.2
py-dateutil                2.2
python37-sagemaker-pyspark 1.4.1
pytz                       2020.1
PyYAML                     5.3.1
regex                      2020.10.28
setuptools                 62.2.0
six                        1.13.0
tqdm                       4.51.0
wheel                      0.37.1
windmill                   1.6
```
- `sc.list_packages()`:
```console
beautifulsoup4 (4.9.3)
boto (2.49.0)
click (7.1.2)
jmespath (0.10.0)
joblib (0.17.0)
lxml (4.6.1)
mysqlclient (1.4.2)
nltk (3.5)
nose (1.3.4)
numpy (1.16.5)
pip (9.0.1)
py-dateutil (2.2)
python37-sagemaker-pyspark (1.4.1)
pytz (2020.1)
PyYAML (5.3.1)
regex (2020.10.28)
setuptools (28.8.0)
six (1.13.0)
tqdm (4.51.0)
wheel (0.29.0)
windmill (1.6)
```

**Comment by gaborbernat** [comment]
This is not a virtualenv issue but rather your OS packaging of it over which we have no control.
