### ISSUE TITLE
20.15.0 - 'PythonInfo' object has no attribute 'version_nodot' (Jenkins / tox / py35)

### ISSUE THREAD

**Issue by matthuisman** [pypa/virtualenv#2367]
Suddenly getting the below with the latest virtualenv 20.15.0
This is on a work jenkins build so I am unable to provide any more details / logs than below.
Hopefully its enough.

```
unittest-py35 uses C:\Python35\python.exe
unittest-py35 start: getenv C:\jenkins\workspace\omation_report_generators_master@2\.tox\unittest-py35
unittest-py35 cannot reuse: no previous config C:\jenkins\workspace\omation_report_generators_master@2\.tox\unittest-py35\.tox-config1
unittest-py35 create: C:\jenkins\workspace\omation_report_generators_master@2\.tox\unittest-py35
[49544] C:\jenkins\workspace\omation_report_generators_master@2\.tox$ 'C:\jenkins\workspace\omation_report_generators_master@2\venv\Scripts\python.exe' -m virtualenv --no-download --python 'C:\Python35\python.exe' unittest-py35
AttributeError: 'PythonInfo' object has no attribute 'version_nodot'
ERROR: invocation failed (exit code 1)
ERROR: InvocationError for command 'C:\jenkins\workspace\omation_report_generators_master@2\venv\Scripts\python.exe' -m virtualenv --no-download --python 'C:\Python35\python.exe' unittest-py35 (exited with code 1)
unittest-py35 finish: getenv C:\jenkins\workspace\omation_report_generators_master@2\.tox\unittest-py35 after 9.27 seconds
___________________________________ summary ___________________________________
ERROR:   unittest-py35: InvocationError for command 'C:\jenkins\workspace\omation_report_generators_master@2\venv\Scripts\python.exe' -m virtualenv --no-download --python 'C:\Python35\python.exe' unittest-py35 (exited with code 1)
cleanup C:\jenkins\workspace\omation_report_generators_master@2\.tox\.tmp\package\1\report_generators-1.0.42+4c3f2cb-py2.py3-none-any.whl
```

The py27 and py37 steps still work fine. So appears to be just py35
Maybe TOX needs to be updated to support?

**Comment by gaborbernat** [comment]
Probably the cache is not forward compatible. Can you clear the app data for virtualenv and try again as a quick workaround until we fix this?

**Comment by matthuisman** [comment]
`virtualenv api -vvv --reset-app-data` correct for doing that?

**Comment by gaborbernat** [comment]
Yeah, or rm -rf the folder pointed out in virtualenv --help

**Comment by matthuisman** [comment]
Yes, that fixed the issue.
Would you like me to close this issue or keep it open?

**Comment by gaborbernat** [comment]
Let's keep it open.

**Comment by bparzella** [comment]
It seems like this issue is Windows specific, I have not seen it on the Linux nodes.

Are there any plans for automatic cache migration or deletion? It is a pain to run the command on 50+ Windows nodes 😅.

**Comment by gaborbernat** [comment]
I'll try to put in a fix release that would address this 😮 been just busy with other stuff, would help if you could put in that PR 👍

**Comment by jadeidev** [comment]
it seems like this is also affecting my python 3.9.7 on windows only. if you experience the same issue downgrade to 20.14.0

**Comment by gaborbernat** [comment]
Downgrade isn't a good solution, please instead do the `python -m virtualenv api -vvv --reset-app-data` to solve it.

**Comment by earonesty** [comment]
just got this as well

**Comment by gaborbernat** [comment]
I think this is fixed now.
