### ISSUE TITLE
Add some notes in changelog or docs about `site` after v20.0.0b1

### ISSUE THREAD

**Issue by YouJiacheng** [pypa/virtualenv#2378]
There are lots of issues about site.py in legacy implementation.
But thing seems completely different in the second iteration of implementation, according to the source code, https://github.com/pypa/virtualenv/issues/2105, https://github.com/pypa/virtualenv/issues/2106 and https://github.com/pypa/virtualenv/issues/1421#issuecomment-568541639.
This could be confusing, e.g. https://stackoverflow.com/a/46071447 said "With virtualenvs [getsitepackages is not available](https://github.com/pypa/virtualenv/issues/228)".
When I searched about this, there isn't any thing tell me the thing is differenet now, I only got numerous issues that said virtualenvs doesn't support `site` module well.
Related issues:
https://github.com/pypa/virtualenv/issues/228
https://github.com/pypa/virtualenv/issues/355
https://github.com/pypa/virtualenv/issues/434
https://github.com/pypa/virtualenv/issues/571
https://github.com/pypa/virtualenv/issues/587
https://github.com/pypa/virtualenv/issues/737
https://github.com/pypa/virtualenv/issues/1250 (link in this issue should be updated to https://github.com/pypa/virtualenv/blob/legacy/virtualenv_embedded/site.py)
They all said "there isn't `site.getsitepackages`".

**Comment by gaborbernat** [comment]
Please open a PR for it 👍
