### ISSUE TITLE
20.16.4: test suite is failing in several units

### ISSUE THREAD

**Issue by kloczek** [pypa/virtualenv#2408]
**Issue**
Both tox and pytest are failing in the same units.

**Environment**
- OS: Linux x86/64
- `pip list` of the host python where `virtualenv` is installed:
<details>

```console
Package                           Version
--------------------------------- -----------------
alabaster                         0.7.12
attrs                             22.1.0
Babel                             2.10.2
backports.entry-points-selectable 1.1.1
Brlapi                            0.8.3
build                             0.8.0
charset-normalizer                2.1.0
click                             8.1.3
click-default-group               1.2.2
codespell                         2.1.0
coverage                          6.4.4
cycler                            0.11.0
distlib                           0.3.4
distro                            1.7.0
docutils                          0.18.1
extras                            1.0.0
filelock                          3.8.0
fixtures                          4.0.0
flaky                             3.7.0
fonttools                         4.37.1
freezegun                         1.2.1
gpg                               1.17.1-unknown
idna                              3.3
imagesize                         1.4.1
importlib-metadata                4.12.0
incremental                       21.3.0
iniconfig                         1.1.1
Jinja2                            3.1.1
kiwisolver                        1.4.4
libcomps                          0.1.18
louis                             3.22.0
MarkupSafe                        2.1.1
matplotlib                        3.5.3
numpy                             1.23.1
olefile                           0.46
packaging                         21.3
pbr                               5.9.0
pep517                            0.12.0
Pillow                            9.2.0
pip                               22.2.1
platformdirs                      2.5.2
pluggy                            1.0.0
py                                1.11.0
Pygments                          2.13.0
PyGObject                         3.42.2
pyparsing                         3.0.9
pytest                            7.1.2
pytest-freezegun                  0.4.2
pytest-mock                       3.8.2
pytest-randomly                   3.12.0
pytest-timeout                    2.1.0
python-dateutil                   2.8.2
pytz                              2022.1
requests                          2.28.1
rpm                               4.17.0
setuptools                        65.3.0
setuptools-scm                    7.0.5
six                               1.16.0
snowballstemmer                   2.2.0
Sphinx                            5.1.1
sphinx-argparse                   0.3.1
sphinx-rtd-theme                  1.0.0
sphinxcontrib-applehelp           1.0.2.dev20220730
sphinxcontrib-devhelp             1.0.2.dev20220730
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1.dev20220730
sphinxcontrib-qthelp              1.0.3.dev20220730
sphinxcontrib-serializinghtml     1.1.5
testtools                         2.5.0
toml                              0.10.2
tomli                             2.0.1
towncrier                         22.8.0
tox                               3.25.1
typing_extensions                 4.2.0
urllib3                           1.26.12
virtualenv                        20.16.2
wheel                             0.37.1
zipp                              3.8.1
```
</details>

**Output of the virtual environment creation**
N/A

**Comment by kloczek** [comment]
Here are tox and pytest outputs in attachments.
[python-virtualenv-tox.txt](https://github.com/pypa/virtualenv/files/9461035/python-virtualenv-tox.txt)
[python-virtualenv-pytest.txt](https://github.com/pypa/virtualenv/files/9461050/python-virtualenv-pytest.txt)

**Comment by gaborbernat** [comment]
https://github.com/pypa/virtualenv/issues/2371#issuecomment-1170474376 still applies.

**Comment by gaborbernat** [comment]
PRs to fix are welcome 👍

**Comment by kloczek** [comment]
> [#2371 (comment)](https://github.com/pypa/virtualenv/issues/2371#issuecomment-1170474376) still applies.

No it isn't because in this case you have clear prove ith tox failing and this time you have prove as well that both tox and pytest are failing **exactly** the same way (which is obviouse ad I'm building all my packages in freshly created build envs with ONLY installed build dependencies wich almost 1:1 equivalent o the same using tox.

> PRs to fix are welcome 👍

If you don't care that tox fails (as you wished last time to have look on that) that is not my problem.
Your wish have been fulfilled and now you are telling "pleas fix my bugs" ..
Last time you even did not gave me chance to reply with tox result by blocking ticket comments (which was very rude).
Closing this time ticket with tox output without any opinion/expertise/asking to perform some test/whatever is rude as well. This is like "I don't care about those issues". If you don't care why I shoud care? 🤔 

Really I'm not going to spend week or so to only to figure out what was your intention implmenting exact units and/or is it code or test units issues.

I'm only a messanger .. and I'm only packaging stuff.
In my packaging procedure I've added all failing units to --deselect list (to have baseline to observe progress on next reelase).
Thanks to that baseline I can only tell you that since my prev ticket one unit dropped from the failing units list and one new popped out in exachange. In other words you new about at least one cause of one unit in meantime. and that unit have been fixed and/or tested code have bin fixed or unit has been removed.
Nothing about that apeared in new version release notes.

I can only guess that all those reported fails are probably test suite issues because so far on building any other packaged python modules I didn't notice any issues caused by `virtualenv`.

**Comment by gaborbernat** [comment]
> Your wish have been fulfilled and now you are telling "pleas fix my bugs" ..

Just to be clear here, this is not my bug. This is a community project. The bug is a community bug, one you're part of. You've paid 0$ for us to work on this project, so you're not entitled to bug fixes. When that changes you can start feeling entitled, but until then please either contribute or don't feel requests that impact your custom distribution.

**Comment by kloczek** [comment]
So what is you houlrly/dayly rate for at least have look on that issue without assuming that it is my fault? 🤔 
Should I charge you for opening this ticket? 🤔 

Sometimes really "speech is silver, but silence is golden".

**Comment by gaborbernat** [comment]
Congratulations, you are banned going ahead in all projects I maintain. All the best!
