### ISSUE TITLE
Batch activators unexpectedly turn echo off for subsequent commands

### ISSUE THREAD

**Issue by pawelszramowski** [pypa/virtualenv#2411]
**Issue**

Consider the following batch script:
```batch
python -m virtualenv --quiet venv
CALL venv\Scripts\activate.bat
REM spam
CALL deactivate.bat
REM eggs
```
The expected output is:
```console
W:\>python -m virtualenv --quiet venv

W:\>CALL venv\Scripts\activate.bat

(venv) W:\>REM spam

(venv) W:\>CALL deactivate.bat

W:\>REM eggs

```
The actual output is:
```console
W:\>python -m virtualenv --quiet venv

W:\>CALL venv\Scripts\activate.bat

```
This is caused by `@echo off` at the beginning of both scripts that need to be undone after calling them:
```batch
python -m virtualenv --quiet venv
CALL venv\Scripts\activate.bat
@ECHO ON
REM spam
CALL deactivate.bat
@ECHO ON
REM eggs
```

**Environment**

- OS: Windows 10
- `pip list`: not relevant

**Output of the virtual environment creation**

Also not really relevant. `virtualenv` version 20.16.4.

**Comment by gaborbernat** [comment]
PR welcome. Also, try please the latest release, that's the only version really supported, and yes it might be relevant.
