### ISSUE TITLE
module 'minisam' has no attribute 'DiagonalLoss'

### ISSUE THREAD

**Issue by Shubham-2302** [pypa/virtualenv#2417]
I am using [PyICP](https://github.com/gisbi-kim/PyICP-SLAM) github repo. I built the Sophus from this commit (commit a0fe89a323e20c42d3cecb590937eb7a06b8343a) [Reference](https://github.com/dongjing3309/minisam/issues/14).
I am using Ubuntu 22 and used virtual environment (venv with python version 3.7.14) to build the PyICP repo, minisam and Sophus repo.

Finally when I run the command  `python3 main_icp_slam.py` it runs in this error. 

![DiagonalLoss_no_attribute](https://user-images.githubusercontent.com/83492152/190079424-ec138299-51fd-4617-8e78-a4f496149f68.png)

I am not sure is it caused by Sophus, Eigen, Venv or minisam.

Let me know if anymore information is needed.

Thanks, for any and all the help.

**Comment by gaborbernat** [comment]
This is not a virtualenv issue.
