### ISSUE TITLE
GraalPython support

### ISSUE THREAD

**Issue by steve-s** [pypa/virtualenv#2427]
GraalPython (https://github.com/oracle/graalpython) is an alternative Python 3 implementation. As it becomes more mature, it is useful to better integrate it into the Python ecosystem. Virtualenv plugin for GraalPy would be an important step, because it, among other things, enables testing on GraalPython via tox.

We would like to contribute GraalPy Creator plugin (based on `ViaGlobalRefVirtualenvBuiltin`) to virtualenv core.

One issue that GraalPython is facing are changes in pip and setuptools that break those packages on GraalPython. This is a chicken-egg problem. We need better integration in Python tools in order to gain wider recognition and to eventually enable continuous testing of some of those packages on GraalPython. Without that the GraalPy virtualenv plugin may become unusable when pip/setuptools release new version. There are several options how to approach this:

* ignore: users of the GraalPython plugin would have to know to pass extra options to virtualenv to pin the versions of pip/setuptools
* new Seeder "ensurepip", which would use target Python's `ensurepip` module to seed the new virtual environment. GraalPython's `ensurepip` takes care of installing the right versions. Users of the GraalPython plugin would have to know to use this seeder.
* building on the previous option: set the "ensurepip" seeder as the default when GraalPython is detected -- GraalPython plugin would work out of the box without any extra options

What do the maintainers of virtualenv think about this issue and the possible solutions?

**Alternative Solutions**

Alternatively, the GraalPython plugin can be external. There are some disadvantages:

* testing: if the plugin is in virtualenv core, it will be tested in virtualenv CI, issues will be detected earlier
* APIs: we would need to iron out what is virtualenv public API that the plugin can use and rely on being stable
   * if classes such as `ViaGlobalRefVirtualenvBuiltin` are not exposed, it seems that that would mean significant code duplication in the external plugin
* we cannot do the suggested change of default seeder for GraalPy unless virtualenv exposes some new hook for that
* we need to capture one GraalPy specific property in `py_info.py`
* ease of use for the end users: it is not a major obstacle, but included out of the box is always better experience than having to install a separate plugin

Another alternative is to use the Venv creator for GraalPython. The issue is that the GraalPython implementation is not recognized by virtualenv and at that point it refuses to continue to invoke the `venv` module. There does not seem to be any way to add a "recognized implementation" without implementing a Creator service for it.

**Comment by gaborbernat** [comment]
Hello, I would say that I like this to start out as an external plugin. The main reason for this is that the virtualenv developer team is small. If the CI will break often, we will not have the time to keep continuously fixing it, and will block virtualenv releases when we don't necessarily have the expertise or access to fix it ourselves. Especially as it's very likely that most of the bugs will be in the standard library rather than virtualenv itself. When the plugin becomes stable, as in its ci Will not break for a few months, we can start discussing adding it to the core.

**Comment by pfmoore** [comment]
> One issue that GraalPython is facing are changes in pip and setuptools that break those packages on GraalPython.

What precisely do you mean by this? If you need changes to virtualenv to handle the fact that you can't use the standard versions of pip and setuptools, it would be much better to fix things so you *can* use the standard versions...

Have you discussed the issues you have with the pip or setuptools developers (I'm a pip developer and I don't recall seeing any such issues raised)? As you say, there's a chicken and egg situation here - pip won't support GraalPython if it diverges too much from standard Python, for example - but it seems like you should at least be opening a discussion on the matter.

**Comment by steve-s** [comment]
Hello, thank you for quick responses.

@gaborbernat

> I like this to start out as an external plugin

Sure. We can also include the `EnsurePipCreator` in such plugin. What we cannot move to a plugin is the extra info extracted in `py_info.py`. Do you have any suggestion what we can do there? Maybe `py_info.py` could load some extra stuff via entry point API.

@pfmoore 

> One issue that GraalPython is facing are changes in pip and setuptools that break those packages on GraalPython.

Indeed I was not precise in my description. 

We monkey patch pip internals to add a hook that allows us to patch some packages to overcome their incompatibilities with GraalPython. This is not a good solution and we should do something better eventually. I commented about that here: https://github.com/pypa/pip/issues/8938#issuecomment-1080377007.

In an idea world, we wouldn't need to patch any packages, because a) GraalPython would fully implement standard Python, and b) packages would use only standard Python. We are working on a), but for upstreaming patches for b) it would be good to have tox and virtualenv integration. 

In the case of virtualenv specifically, we need functional setuptools, otherwise all bets are off. I did not deep dive into the reasons why exactly we need to patch them (so it may be reason a) or b)), but even if that was all fixed, unless new release are tested on GraalPython, they may stop working. That's the chicken-egg issue I was referring to.
