### ISSUE TITLE
Nushell activation script results in broken prompt

### ISSUE THREAD

**Issue by dpatterbee** [pypa/virtualenv#2480]
**Issue**

The Nushell activation script no longer handles prompts correctly due to the split of closures and blocks in 0.72.

https://github.com/pypa/virtualenv/blob/beb7d66b5575f75d4b660d90ad75c3a56deb8a20/src/virtualenv/activation/nushell/activate.nu#L95

This lines checks for type `block`, but many/(most?) prompts will now be of type `closure`, causing them to render as `<Closure X>` rather than actually running the prompt function.

eg.
```
(venv) <Closure 11>〉
```

I don't have the expertise to know whether switching that check to "closure" is the correct fix or not so I'm just leaving this bug report rather than opening a PR. Editing that line in my `activate.nu` does work as a temporary fix though.

**Environment**

Provide at least:

- OS: macos 13.1
- `pip list` of the host python where `virtualenv` is installed:

```
asdf
Package      Version
------------ -------
distlib      0.3.6
filelock     3.8.0
pip          22.3.1
platformdirs 2.5.4
setuptools   65.6.3
virtualenv   20.17.1
wheel        0.38.4
```

**Output of the virtual environment creation**

This isn't an issue with creation so I'm not including this.

**Comment by zbraniecki** [comment]
Even with #2481 the activate.nu is broken in Nushell 0.73 (not sure about 0.72), with:

```
…/investigator2(main)〉source venv/bin/activate.nu
Error: nu::parser::unexpected_keyword (link)

  × Statement used in pipeline.
     ╭─[activate.nu:116:1]
 116 │ export alias pydoc = python -m pydoc
 117 │ export alias deactivate = overlay hide activate
     ·                           ───┬───
     ·                              ╰── not allowed in pipeline
     ╰────
  help: 'overlay' keyword is not allowed in pipeline. Use 'overlay' by itself, outside of a pipeline.
```
