### ISSUE TITLE
Link package outside virtualenv as instaled

### ISSUE THREAD

**Issue by ManPython** [pypa/virtualenv#2482]
**What's the problem this feature will solve?**
I often installing module/package that need in many venvs and this same in in pain python.. in some reason.

**Describe the solution you'd like**

Want install module/package in (virtualenv) as active into other as paralel where can in main python site-package dir and "linked" in to `virtualenv` or `virtualenv` and `virtualenv`, etc.

**Alternative Solutions**

Can be implemented in PIP

**Additional context**

`pip install pandas --base` as main Python site-package dir

`pip install pandas --base --virtualenv` as main Python site-package dir + virtualenv as paralel instalation
`pip install pandas --base --virtualenv activated` as main Python site-package dir + virtualenv as paralel instalation
`pip install pandas --base --virtualenv activated e:/other/path/virtualenv1 e:/other/path/virtualenv2` as main Python site-package dir + virtualenv as **paralel** instalation
`pip install pandas --base --linked activated e:/other/path/virtualenv1 e:/other/path/virtualenv2` as main Python site-package dir + virtualenv as **linked** instalation

**Comment by gaborbernat** [comment]
This sounds like a pipe issue, not virtualenv.

**Comment by ManPython** [comment]
Myabe You are right. But what if module is instaled into "--base" and not use pip in virtualvenv? Why not do some symlink via virtualvenv in simple way into base python indicating just module? Eg. update virtualvenv with some package that are instaled? 
My idea is that after virtualvenv is created, the this virtualvenv know where is base, then can be updated this virtualvenv by some instaled modules as site-packages and can `clone` this maybe to other as pocket/portfolilo eg. like requiments.txt can be clone.txt or pacakge.txt pocket.txt that can be easy `cloned` to other venv or `linked`
