### ISSUE TITLE
Stop installing `setuptools` and `wheel` by default on Python 3.12+ environments

### ISSUE THREAD

**Issue by pradyunsg** [pypa/virtualenv#2487]
**What's the problem this feature will solve?**

pip can now operate without setuptools in the environment, and it will be removed from the default set of `venv` packages in Python 3.12+ (https://github.com/python/cpython/pull/101039)

**Describe the solution you'd like**

What the title says. :)

**Alternative Solutions**

Not doing this, and being inconsistent with `venv`.

**Additional context**

N/A

**Comment by chrysle** [comment]
I'll try to implement the requested behavior.

**Comment by gaborbernat** [comment]
Go ahead 😃

**Comment by chrysle** [comment]
@gaborbernat Did I get it right that the [seed packages](https://virtualenv.pypa.io/en/latest/user_guide.html#seeders) `setuptools` and `wheel` and their wheels are to be removed? Before I do anything wrong.

**Comment by gaborbernat** [comment]
We should not remove those. We should just by default disable installing this on 3.12 or later. The user might still enable it manually.

**Comment by chrysle** [comment]
> We should not remove those. We should just by default disable installing this on 3.12 or later. The user might still enable it manually.

Thanks for the quick response! Should an option like `--with-seeders` be created for that?

**Comment by gaborbernat** [comment]
No need we already have --setuptools --wheels whose default we can change.

**Comment by jaraco** [comment]
Really happy to see setuptools and wheel removed by default. Thanks for that!

In https://github.com/jaraco/pip-run/issues/73, I spent about an hour trying to figure out why the Python 3.12 builds were failing when the other Pythons weren't. I wouldn't have expected virtualenv to be providing version-specific features. One of the advantages of third-party packages is that they aren't coupled to Python releases and can provide users a consistent experience across Python versions.

By rolling out this feature based on the Python version, you're creating an extra dimension to the configuration space. I'd have rather seen it rolled out universally (or at least made opt-in for users on older Pythons).
