### ISSUE TITLE
platformdirs 3.0 compatibility

### ISSUE THREAD

**Issue by cdce8p** [pypa/virtualenv#2499]
**What's the problem this feature will solve?**
`platformdirs` version `3.0` was released a few hours ago. At the moment `virtualenv` pins `<3`. Is that necessary or would ´v3´ be compatible? Form the changelog, it looks like a change only to the default config dir on macOS.

https://github.com/pypa/virtualenv/blob/2a56eb219d9514886c25450fdae84c128ebe7afe/pyproject.toml#L42

https://github.com/platformdirs/platformdirs/blob/main/CHANGES.rst#platformdirs-300-2023-02-06

**Comment by gaborbernat** [comment]
Can unpin. PR welcome.

**Comment by cdce8p** [comment]
Opened #2501

**Comment by kendra-human** [comment]
Thanks, @cdce8p it took me a few hours to debug this (via a transitive dep). Kudos for raising the PR.

**Comment by johnthagen** [comment]
Just as reference, this will currently screw up Poetry's dependency resolution and push `virtualenv` back to an old version (which then can break things with old `setup.py install` behavior):

- https://github.com/platformdirs/platformdirs/issues/140

**Comment by gaborbernat** [comment]
Ah, poetry! Causing so many problems 😆 I personally don't understand why people use it 😆 will be fixed soon though.

**Comment by johnthagen** [comment]
> I personally don't understand why people use it 

😆 I love it, but definitely understand that it resolves dependencies differently than `pip`.

Can only dream one day packaging tools will all be unified/standardized.

**Comment by gaborbernat** [comment]
The only officially supported resolver is what pip uses. So using anything else leads to situations like this; if anything creates more discord, then help unity. So if you're hoping for unified ways, this is your chance to convince poetry not to roll their own standards and logic.

**Comment by johnthagen** [comment]
Can confirm that `virtualenv` [20.19.0](https://pypi.org/project/virtualenv/20.19.0/) solved this issue.

Thanks!
