### ISSUE TITLE
AttributeError: module 'site' has no attribute 'getsitepackages

### ISSUE THREAD

**Issue by shfarhee** [pypa/virtualenv#2529]
I am trying to import a project from git-hub to read the doc website where rst files are working and(source code) the python code is not showing anything. Where as the same setup is working fine in my local system.
ERROR- getting **'getsitepackages' issue (* AttributeError: module 'site' has no attribute 'getsitepackages'.** and some of the python files are showing and some isn't inReadthedoc .
[getsitepackages.txt](https://github.com/pypa/virtualenv/files/11042881/getsitepackages.txt)

**Comment by gaborbernat** [comment]
I don't think this is related to this project.

**Comment by gaborbernat** [comment]
This is only true for python 2 that's no longer supported.
