### ISSUE TITLE
Interpreter detection when using tea.xyz

### ISSUE THREAD

**Issue by jylin** [pypa/virtualenv#2533]
[Tea.xyz](https://tea.xyz) automatically downloads Python interpreters based on the command name. virtualenv seems to not play well with it. If you do something like this, you'll get an error:

```
> <install tea.xyz>
> pip install virtualenv
> python -m virtualenv
RuntimeError: failed to detect cpython3.11.2-64|cpython3.11.2|cpython3.11-64|cpython3.11|cpython3-64|cpython3|cpython-64|cpython|python3.11.2-64|python3.11.2|python3.11-64|python3.11|python3-64|python3|python-64|python in /Users/aa/.tea/python.org/v3.11.2
````

I think the problem is because the interpreters are at paths like: `/Users/aa/.tea/python.org/v3.11.2/bin/python`

If I do an ugly hack in `py_info.py` and change the call to `self._check_exe` to use `folder + '/bin'`, then things work as expected. That's obviously not a good fix, but just wanted to raise this issue for compatibility with the tea.xyz tool.

**Comment by gaborbernat** [comment]
Assuming you are on Linux it's tea.xyz responsability to put the interpreters (versioned) onto the PATH. Alternatively tea.xyz is invited to create a virtualenv plugin with custom discovery logic https://virtualenv.pypa.io/en/latest/extend.html#virtualenv.discovery.discover.Discover
