### ISSUE TITLE
Compatibility of licenses 

### ISSUE THREAD

**Issue by rahulmohang** [pypa/virtualenv#2567]
Hi, 

I have been analyzing the licenses in the source code of virtualenv - 20.22.0. When we could see the files inside https://github.com/pypa/virtualenv/blob/20.22.0/src/virtualenv/seed/wheels/embed/pip-23.1-py3-none-any.whl, we have seen that the chardet package at 'pip-23.1-py3-none-any.whl/pip/_vendor/chardet' is licensed under the LGPL v2.1 or later license. 

Do you think that because of the LGPL v2.1 or later license, the license of virtualenv, which is MIT, may get affected?

**Comment by gaborbernat** [comment]
IMHO not. We only vendor those packages.

**Comment by rahulmohang** [comment]
Thank you for the response.
