### ISSUE TITLE
[RuntimeError] failed to find interpreter for Builtin discover of python_spec='python3.8'

### ISSUE THREAD

**Issue by 1chooo** [pypa/virtualenv#2583]
**Issue**

I encountered a `RuntimeError` while trying to create a virtual environment using the command `virtualenv venv --python=python3.8`. This is the first time I've encountered this error, as I have successfully created several virtual environments in the past. I'm not sure what caused this problem, and I'm unsure how to proceed.
```console
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
```

**Environment**

Provide at least:

- OS: MACOS v12.6
- `which python3`: 
  ```console
  /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
  ```
- `which virtualenv`: 
  ```console
  installed:/Library/Frameworks/Python.framework/Versions/3.10/bin/virtualenv
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
```

BR, 
@1chooo

**Comment by gaborbernat** [comment]
You don't have 3.8 on the machine so cannot find it.

**Comment by 1chooo** [comment]
Hi @gaborbernat ,
However, I have successfully build the virtual environment with `python3.8.16`, but I have never installed `python3.8`.
