### ISSUE TITLE
Move to PyPA org on PyPI?

### ISSUE THREAD

**Issue by webknjaz** [pypa/virtualenv#2632]
With the orgs feature on PyPI, there's a PyPA org that exists already — https://pypi.org/org/pypa/. Why not make use of it?

_UPD_: Dustin explained the implications as an FAQ in the ML: https://mail.python.org/archives/list/pypa-committers@python.org/thread/E6MWIHEK3M232UILXGQFYPHGJHF7VYW7/.

**Comment by gaborbernat** [comment]
I don't own pypa so can't really make that transition.

**Comment by webknjaz** [comment]
I think @pradyunsg might have access. Or @di. Though, for this to happen, they have to have access to both the virtualenv project (as an Owner) on PyPI and to the org + have a Manager+ access in the org.

You'll need to invite that individual to the virtualenv project, I suppose.

Oh.. Maybe @pfmoore is in the org? That would probably be enough.

**Comment by webknjaz** [comment]
The individuals can still be added with Owner or Maintainer privileges. It'll show up under the org and the org will be linked from the project page.
Additionally, there would be a possibility to have teams added with the corresponding privileges. The team members aren't listed on the public project page but could publish if there's enough privileges configured. The individually added people are listed.

The trusted publishing setup isn't affected as it's connected to the projects and not the users.

As for the org owners, they are not public but I'd assume @di since he's just move pip-audit there. He'll know more since I don't have visibility into the org.

**Comment by pfmoore** [comment]
See my comments on the equivalent issue you raise over on the pip tracker. Basically, I'm -1 on doing this until we understand the implications on project governance better. And I think it should be a PyPA-wide decision, not a per-project one.

**Comment by gaborbernat** [comment]
> not a per-project one.

I'd argue that our current governance model does not allow authority over such per project topics. So must remain project specific.

**Comment by pfmoore** [comment]
> I'd argue that our current governance model does not allow authority over such per project topics. So must remain project specific.

Sorry, I wasn't clear. Whether to be part of the pypa org is a per-project decision, certainly. But whether and how to manage the pypa org is a PyPA decision, and as far as I can tell, projects can't reasonably join the pypa org until that's sorted out (if for no other reason than we have no process at the moment for deciding who will be owners/members of the PyPA org on PyPI, and hence be able to manage projects in that org - something I assume individual projects will care about).

**Comment by pradyunsg** [comment]
See https://github.com/pypa/pip/issues/12250#issuecomment-1698025213 -- let's hold off on this.

**Comment by webknjaz** [comment]
@gaborbernat Dustin posted some implications FAQ in the ML here: https://mail.python.org/archives/list/pypa-committers@python.org/thread/E6MWIHEK3M232UILXGQFYPHGJHF7VYW7/.

**Comment by gaborbernat** [comment]
I did reach out to him to go ahead, but he didn't get back since then.

**Comment by webknjaz** [comment]
So apparently it's already been transferred. Closing.
