### ISSUE TITLE
deactivate command not available in shell scripts or sub-shells (activate script does not export "deactivate")

### ISSUE THREAD

**Issue by geopanther** [pypa/virtualenv#2654]
**Issue**

When activating an venv environment, the command "deactivate" is only available in the current instance of the shell and not in a shellscript (a shellscript is always executed in sub-shell (separate instance)) or any subshel

**Environment**

Provide at least:

- OS: macOS Big Sur 11.7.10 (20G1427)
- Using bash version "3.2.57(1)-release" from Homebrew
- `pip list` of the host python where `virtualenv` is installed:
```console
$ pip list
Package    Version
---------- -------
pip        23.2.1
setuptools 56.0.0
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:
```console
$ python3 --with-traceback -vvv -m venv .venv_py3.11
unknown option --with-traceback
usage: /Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

```console
$ python3 -vvv -m venv .venv_py3.11
```
-> see attached [console-output.txt](https://github.com/pypa/virtualenv/files/13052602/console-output.txt)

Steps to reproduce:

```console
$ source .venv_py3.11/bin/activate
$ bash
$ deactivate
bash: deactivate: command not found
$ exit
exit
$ deactivate
$
```

Suggested solution:
Add `export -f deactivate` to <virtual_env_dir>/bin/activate

**Comment by gaborbernat** [comment]
That will still keep the activation in the first shell as it's not possible to change parent shell envs, so this would cause more confusion than benefit.
