### ISSUE TITLE
Update for platformdirs v4

### ISSUE THREAD

**Issue by jwodder** [pypa/virtualenv#2666]
[`platformdirs v4.0`](https://github.com/platformdirs/platformdirs/releases/tag/4.0.0) was released yesterday, yet virtualenv requires `platformdirs<4`.  Please update virtualenv to accept the latest version of platformdirs.

**Comment by johnthagen** [comment]
I wanted to add that if a library you depend upon requires `platformdirs`, dependency resolution can select `platformdirs` `4.0.0`, after which point, if another library depends on `virtualenv`, it will backtrack to `virtualenv` `20.4.7`, which then is so old it can fail because of a `SetuptoolsDeprecationWarning`.

One such example:

- https://github.com/johnthagen/python-blueprint/actions/runs/6834646086/job/18587635299

**Comment by alex** [comment]
https://github.com/pypa/virtualenv/commit/55650340d9c9415bf035596266f245a8d59c6993 was merged already, so this will be resolved whenever the next release happens

**Comment by kendra-human** [comment]
> [5565034](https://github.com/pypa/virtualenv/commit/55650340d9c9415bf035596266f245a8d59c6993) was merged already, so this will be resolved whenever the next release happens

Any rough ETA on when a release would occur?

**Comment by gaborbernat** [comment]
Probably later this week, I'm currently in hospital for a few days unexpectedly so things got delayed, sorry.

**Comment by gaborbernat** [comment]
Probably later this week, I'm currently in hospital for a few days unexpectedly so things got delayed, sorry.

**Comment by sigma67** [comment]
All the best @gaborbernat . Any other maintainers that could possibly jump in and help out?

**Comment by johnthagen** [comment]
@pfmoore I see you are listed as a maintainer [on PyPI](https://pypi.org/project/virtualenv/). Was wondering if you might be able to help out with this? ❤️

**Comment by pfmoore** [comment]
Nope, sorry. It's been quite a while since I worked on this repo, and I'm not sufficiently familiar with the current release process to want to try to do a release.

**Comment by sigma67** [comment]
Seems like it's as simple as creating a release on GitHub which will trigger the workflow: https://github.com/pypa/virtualenv/blob/main/.github/workflows/release.yml

But we can't be sure so it's probably better to wait for @gaborbernat

**Comment by johnthagen** [comment]
Thank you @gaborbernat! Hope you are doing well.

**Comment by gaborbernat** [comment]
Thank you, relatively speaking to last week, I'm better, however, the full recovery will take some more time.

**Comment by sigma67** [comment]
Thank you, speedy recovery!

Might be a good idea to document this release process in the contribution/maintainer docs

**Comment by pfmoore** [comment]
Just to be clear, while I still have maintainer rights here, I wouldn't have done an emergency release for this even if the process had been documented. I don't think it's unreasonable for there to be a week or two's delay on something like this if the lead maintainer is unavailable. (Pip, for example, only does a release every 3 months).

I agree that having the various project processes documented is a good thing to do, but let's keep things in perspective here.

Best wishes for your recovery @gaborbernat!

**Comment by sigma67** [comment]
@pfmoore I did not intend to imply that you would have.

Just always helps to have things documented for critical packages just in case 👍
