### ISSUE TITLE
Values in `pyvenv.cfg` do not reflect the real paths on case insensitive file systems

### ISSUE THREAD

**Issue by ofek** [pypa/virtualenv#2684]
I noticed this because within a virtual environment the paths that `sysconfig` returns are in all caps for some reason:

![Screenshot 2024-01-21 220244](https://github.com/pypa/virtualenv/assets/9677399/cee07de7-ba1d-48b8-9fbb-8ae66d35cff8)

```ini
home = C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311
implementation = CPython
version_info = 3.11.1.final.0
virtualenv = 20.25.0
include-system-site-packages = false
base-prefix = C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311
base-exec-prefix = C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311
base-executable = C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\PYTHON.EXE
```

This might not seem like a big deal but users see these paths in debug output when building packages if the build uses virtual environments.

**Comment by ofek** [comment]
Saving the resolved paths like [this issue](https://github.com/pypa/virtualenv/issues/2682) wants would also fix this because `os.path.realpath` returns the path as saved on disk.

**Comment by gaborbernat** [comment]
PR welcome to address this is welcome 👍

**Comment by ofek** [comment]
Can you please point to the general area of the code base that I should look at?

**Comment by gaborbernat** [comment]
Either https://github.com/pypa/virtualenv/tree/main/src/virtualenv/create/via_global_ref/builtin or https://github.com/pypa/virtualenv/blob/main/src/virtualenv/discovery/py_info.py#L35

**Comment by ofek** [comment]
I don't know why but upgrading from 3.11.1 to 3.11.7 fixed the issue.

**Comment by pelson** [comment]
Would this equally have been solved by calling `os.path.normpath`? I ask because the use of `os.path.realpath` (instead of recursively calling `os.readlink`) in #2686 is problematic and diverges from `venv` (and now `uv venv`).
