### ISSUE TITLE
https://bootstrap.pypa.io/virtualenv/3.11/virtualenv.pyz returns "Error 503 No healthy backends"

### ISSUE THREAD

**Issue by masenf** [pypa/virtualenv#2690]
**Issue**

Attempting to bootstrap virtualenv from the `pyz` archive, but the site appears to be unavailable for the last few hours.

Hopefully this is the correct place to report such an issue.

https://bootstrap.pypa.io/virtualenv/3.11/virtualenv.pyz

![image](https://github.com/pypa/virtualenv/assets/1524005/aca48aaf-a1ee-4440-902e-94780348b61f)

Accessing from the West Coast USA, but also seen failures in github actions as well.

**Comment by gaborbernat** [comment]
Cc @ewdurbin is this an issue on the PSF side?

**Comment by ewdurbin** [comment]
this is resolved, and was an oversight in resolving https://status.python.org/incidents/0r0fknxb1m9b

bootstrap.pypa.io's CDN configuration is in a separate account from the rest of the PSF infrastructure and wasn't considered when updating the new CA.

**Comment by gaborbernat** [comment]
Thanks a million!
