### ISSUE TITLE
virtualenv creation broken by filelock 3.15.0 release

### ISSUE THREAD

**Issue by tamird** [pypa/virtualenv#2735]
```
Creating virtualenv root in /codebuild/output/src4294789612/src/actions-runner/_work/python_monorepo/python_monorepo/.venv

object.__init__() takes exactly one argument (the instance to initialize)
Exception ignored in: <function BaseFileLock.__del__ at 0x7f8ac1d91760>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/poetry/lib/python3.11/site-packages/filelock/_api.py", line 365, in __del__
    self.release(force=True)
  File "/root/.local/share/pipx/venvs/poetry/lib/python3.11/site-packages/virtualenv/util/lock.py", line 34, in release
    with self.thread_safe:
         ^^^^^^^^^^^^^^^^
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

https://github.com/tox-dev/filelock/pull/334 looks the likeliest culprit.

**Comment by rlizzo** [comment]
+1 this issue is occuring for us as well

**Comment by EarningsCall** [comment]
Wow, searching far and wide and just now found this issue.  Looks like it's happening to everyone!

For me, I'll just pin filelock for the time being:

```bash
pip install --upgrade hatch filelock==3.14.0
```

**Comment by schmod** [comment]
The offending version of `filelock` has been yanked from PyPi, so this should basically be resolved.  You might need to force a reinstallation of virtualenv (or whatever depended on it).

**Comment by susodapop** [comment]
Note to others: if you're GH Actions checks are failing you may need to purge your env caches that are created by `actions/cache@v2`

**Comment by edgarrmondragon** [comment]
I think this has resurfaced with `filelock` 3.15.2?

**Comment by benjamin-awd** [comment]
Looks like 3.15.2 just got yanked from PyPI

![image](https://github.com/pypa/virtualenv/assets/62495124/060a5d03-9867-4cdc-8c15-77d74ca4fc42)

**Comment by sdmitriev1** [comment]
3.15.3 was released, fixed the problem for me
