### ISSUE TITLE
Minor documentation typo on Extend Functionality page

### ISSUE THREAD

**Issue by Evan0000000000** [pypa/virtualenv#2762]
Apologies if reporting this as an enhancement is incorrect, bug seems wrong as it's still fairly clear what is meant.

on https://virtualenv.pypa.io/en/latest/extend.html  the first line under Python Discovery reads

"The python discovery mechanism is a component that needs to **answer the following answer**: based on some type of user input give me a Python interpreter on the machine that matches that. "

There are a couple ways one could reword that, "answer the following question"  or "provide the following answer"  and so on, but in any case what's actually written seems unintended.

**Comment by gaborbernat** [comment]
PR welcome 👍
