### ISSUE TITLE
Add code comment re: base64-encoded code in virtualenv.py

### ISSUE THREAD

**Issue by cjerdonek** [pypa/virtualenv#286]
I think it would help to add a code comment near [here](https://github.com/pypa/virtualenv/blob/f450b9aaeb892cc20e39dc2823046989e761e19e/virtualenv.py#L1773) explaining why virtualenv.py includes base-64 encoded Python scripts, and where the sources for the scripts come from (e.g. are the human-readable versions stored or copied from elsewhere or are these the sources).

I came across this issue while troubleshooting issue #281.  The decoded version of DISTRIBUTE_SETUP_PY was being passed as the command-line argument to a subprocess call that wasn't behaving as expected.  The script being base-64 encoded makes the issue harder to debug and troubleshoot (and in particular, modify).

**Comment by cjerdonek** [comment]
Keep open.

**Comment by gaborbernat** [comment]
We indeed should document this, one should use the ``embed`` tox target (we now break the CI if someone forgets to do this).

**Comment by gaborbernat** [comment]
This is becoming obsolete with #1366 now in full swing.
