### ISSUE TITLE
Allow to inherit from other virtualenvs

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#33]
The general idea is to be able to have a new virtualenv inherit from existing VEs in the system. So, for instance, if I have a virtualenv with a set of django tools installed and another with some testing tools you could do:

```
#!bash
./virtualenv.py tmp/ --inherit=/home/nicolas/django_ve/,/testing_ve,/ --no-site-packages
```

and it will create a virtualenv that has those VEs in its path so that you can have reusable stuff installed only once.

I'm attaching a patch that adds the basic functionality. While it might need improvement it currently works.

Let me know what you think.

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/25
- Originally Reported By:  
- Originally Created At: 2010-02-23 22:35:43

**Comment by cagriy** [comment]
This would be fantastic

**Comment by gaborbernat** [comment]
Closing to lack of activity. This seems to be a hard problem to fix for the general case.
