### ISSUE TITLE
 virtualenv fails with long paths

### ISSUE THREAD

**Issue by elopio** [pypa/virtualenv#343]
This was reported on Launchpad by Michael Williamson: https://bugs.launchpad.net/ubuntu/+source/python-virtualenv/+bug/1000778

Trying to run virtualenv inside a directory with a long path causes virtualenv to fail to install pip:

~/a1234567890/b1234567890/c1234567890/d1234567890/e1234567890/f1234567890/g1234567890/h1234567890$ virtualenv _virtualenv
New python executable in _virtualenv/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...
  Error [Errno 13] Permission denied while executing command /home/mwilliamson/a1...env/bin/easy_install /usr/share/python-virtualenv/pip-1.1.tar.gz
...Installing pip...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 938, in main
    never_download=options.never_download)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1054, in create_environment
    install_pip(py_executable, search_dirs=search_dirs, never_download=never_download)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 643, in install_pip
    filter_stdout=_filter_setup)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 976, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by tardyp** [comment]
The problem is because on linux kernel, the shebang path is limited to 127 bytes.

http://lxr.free-electrons.com/source/include/uapi/linux/binfmts.h#L18
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/binfmt_script.c?id=HEAD#n22

virtualenv creates a pip executable like:
```
#!/home/foo/a1234567890/b1234567890/c1234567890/d1234567890/e1234567890/f1234567890/g1234567890/h1234567890/virtualenv/bin/python2.7
# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

linux truncates the path to python2.7 to 127 bytes, and the try to execute that.

**Comment by tardyp** [comment]
workaround is to make the virtualenv relocatable.

   wheelhouse/virtualenv.py  -p python2.7 out/virtualenv	
   wheelhouse/virtualenv.py --relocatable  out/virtualenv

**Comment by mohitsoni** [comment]
Reviving this thread again.

I was wondering why we cannot set the shabang path on *nix environments to be always:

```bash
#!/usr/bin/env python
```

The activate script modifies the `PATH` variable and prepends the `<virtualenv>/bin` to the existing `PATH`. This will ensure that `#!/usr/bin/env python` will evaluate to the virtualenv's 
version of `python` binary.

**Comment by pfmoore** [comment]
@mohitsoni Because executables in a virtualenv need to be runnable *without* the virtualenv activated. That's currently the case, and users rely on it (the documentation explicitly points out that you do't need to activate a virtualenv to use it).
