### ISSUE TITLE
site.py not compatible with python 2.7

### ISSUE THREAD

**Issue by leoliu** [pypa/virtualenv#355]
We use python 2.7 exclusively and it is a surprise to discover today that site.py in all virtual envs with python 2.7 use py2.6's site.py which lacks many new functions added in python 2.7.

**Comment by staticfloat** [comment]
This bit me today; it would be really, really nice to get an updated `site.py` included in `virtualenv` since the old 2.6 version doesn't have things like `site.getusersitepackages()`.

**Comment by RemiCardona** [comment]
It bit me too, and it caught me off guard. Now I'm even wondering what other files differ from the system python (especially when using `--system-site-packages`) and what other "bugs" lie in wait…

**Comment by stefano-m** [comment]
Still valid using **virtualenv 13.1.2** with Python 2.7.6, and it's getting in the way of some dev work I'm doing.

Here's some interactive fiddling:

##### getsitepackages is not present in virtualenv

    $ virtualenv --version
    13.1.2
    $ virtualenv test
    New python executable in test/bin/python
    Installing setuptools, pip, wheel...done.
    $ source test/bin/activate
    $ which python
    /home/user/test/bin/python
    $ python
    Python 2.7.6 (default, Jun 22 2015, 17:58:13)
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import site
    >>> 'getsitepackages' in dir(site)
    False
    >>> site.getsitepackages()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'getsitepackages'
    >>>

##### getsitepackages is present in system Python

    $ deactivate
    $ python
    Python 2.7.6 (default, Jun 22 2015, 17:58:13)
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import site
    >>> 'getsitepackages' in dir(site)
    True
    >>> site.getsitepackages()
    ['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
    >>>

**Comment by CptSpaceToaster** [comment]
I just got bitten by this one.  I'm very hesitant just throwing `--system-site-packages` into the args, as that seems to defeat many reasons for using `virtualenv` in the first place.


please consider upgrading `site.py` to provide `site.getsitepackages()`

**Comment by johnthagen** [comment]
Hit this issue with #555, which can cause different behaviour in a virtual environment if you run with -Werror because of the deprecation warning.  Since tox depends on this package to work internally, don't see much of a way around it.

**Comment by FrancescoRizzi** [comment]
+1 sad_panda and lots of tears

**Comment by jvrsantacruz** [comment]
+1 this bite me today, code works outside virtualenv but not inside.

**Comment by luchensk** [comment]
+1 bite, is there some update? Thanks.

**Comment by sergeny** [comment]
+1 same issue with rk (remote kernel for jupyter).

**Comment by HofmannHe** [comment]
+1 bite, works outside virtualenv but not inside.

**Comment by stefano-m** [comment]
All, I think that for the time being the best solution may be vendoring `site.py` (or parts of it) in your projects.

**Comment by zed** [comment]
As a workaround: `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`  manages to [find the location of my Python site-packages directory](https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory)

**Comment by F1ashhimself** [comment]
+1

**Comment by guoyejun** [comment]
+1 bite, is there some update? Thanks.

i'm using virtualenv 15.0.1 on Ubuntu 16.04 64bit

**Comment by tobiasherp** [comment]
+1 bite
(virtualenv 15.1.0 on CentOS 7.5.1804)

**Comment by RemiCardona** [comment]
Ever since moving on to py3, I've stopped using `virtualenv` and I use python's own `venv`. With python 3.6+, a minimalist `venv` comprises just a couple symlinks:

```
$ python3.6 -m venv --without-pip grut
$ tree grut/
grut/
├── bin
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── python -> python3.6
│   ├── python3 -> python3.6
│   └── python3.6 -> /usr/bin/python3.6
├── include
├── lib
│   └── python3.6
│       └── site-packages
├── lib64 -> lib
└── pyvenv.cfg

6 directories, 7 files
```

So, no more `virtualenv` and all its quirks for me. HTH other folks.

**Comment by johnthagen** [comment]
@RemiCardona I use Python 3's `venv` as much as I can, but unfortunately [`tox`](https://tox.readthedocs.io/en/latest/) still uses `virtualenv` (even when testing Python 3), so I'm hit with this problem every time I use `tox` to automate testing or do continuous integration. 😞
