### ISSUE TITLE
bin/activate doesn't remove alias after running deactivate

### ISSUE THREAD

**Issue by Mumage** [pypa/virtualenv#365]
If you source bin/activate, then run deactivate, the alias 'python -m pydoc' persists.  In the interest of leaving everything exactly as it was before sourcing bin/activate, perhaps it would be good to unalias the alias as part of the deactivate function?

**Comment by blueyed** [comment]
Fixed in #724 - it should have been `unalias` instead of `unset` in `deactivate`.
