### ISSUE TITLE
Virtualenv always using sytem site packages with macos 10.6 system python

### ISSUE THREAD

**Issue by brickZA** [pypa/virtualenv#369]
Creating a fresh virtualenv with either --system-site-packages or --no-site-packages results in the system site-packages being available in the venv. Furthermore, installing new packages don't override the system pacakges unless -e is used. Example:

`ofaletses-MacBook-Pro:~ ofaletse$ virtualenv --no-site-packages test_venv/
New python executable in test_venv/bin/python
Installing setuptools............done.
Installing pip...............done.
ofaletses-MacBook-Pro:~ ofaletse$ source test_venv/bin/activate
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$ python -c 'import blinker ; print blinker.__version__'
1.2
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$ # System installed version, should not be visible
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$ pip install blinker==1.0
Downloading/unpacking blinker==1.0
  Downloading blinker-1.0.tar.gz (61kB): 61kB downloaded
  Running setup.py egg_info for package blinker
Installing collected packages: blinker
  Found existing installation: blinker 1.2
    Not uninstalling blinker at /Library/Python/2.6/site-packages, outside environment /Users/ofaletse/test_venv/bin/..
  Running setup.py install for blinker
Successfully installed blinker
Cleaning up...
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$ python -c 'import blinker ; print blinker.__version__'
1.2
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$ # Still using system package
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$ ls test_venv/lib/python2.6/site-packages/
blinker             easy-install.pth        setuptools-0.6c11-py2.6.egg
blinker-1.0-py2.6.egg-info  pip-1.2.1-py2.6.egg     setuptools.pth
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$ # although blinker does seem to be installed in the virtualenv
(test_venv)ofaletses-MacBook-Pro:~ ofaletse$` 

Full version of MacOS: 10.6.8 (Snow Leopard), using system installed python2.6

**Comment by atugushev** [comment]
Hey guys! Any progress on this? Still not working =(

**Comment by gaborbernat** [comment]
I think this should be fixed, we don't support Python 2.6 anymore but if you can reproduce it with 2.7+ open it again.
