### ISSUE TITLE
Fix broken 3.3 build

### ISSUE THREAD

**Issue by pnasrat** [pypa/virtualenv#375]
Eg https://travis-ci.org/pypa/virtualenv/jobs/3575685

```
creating /usr/local/lib/python2.7/dist-packages/nose
error: could not create '/usr/local/lib/python2.7/dist-packages/nose': Permission denied
```

**Comment by hugovk** [comment]
This is old issue can be closed now because EOL Python 3.3 was deployed in https://github.com/pypa/virtualenv/pull/1089.
