### ISSUE TITLE
virtualenv with --no-site-packages should ignore PYTHONPATH

### ISSUE THREAD

**Issue by urbaniak** [pypa/virtualenv#396]
virtualenv created with --no-site-packages, when activated it's still using the packages which  are in directory pointed by PYTHONPATH environment variable, it should store value of that variable somewhere else and remove it, and restore it when deactivating virtualenv

**Comment by mlongval** [comment]
Hello, 
I am very new to this, and my question has probably already been answered, if so I apologise. 

Would adding this to bin/activate by default be a "Good Idea™" ????

In "deactivate()"
```
    if ! [ -z "${_OLD_PYTHONPATH+_}" ] ; then
        PYTHON_PATH="$_OLD_PYTHONPATH"
        export PYTHONPATH
        unset _OLD_PYTHONPATH
    fi
```
... and in main body: 
```
_OLD_PYTHONPATH="$PYTHONPATH"
PYTHONPATH="$VIRTUAL_ENV"
export PYTHONPATH
```

I end up doing manually for each env, but it may simply be my configuration is not  Pythonic.

Thanks

**Comment by gaborbernat** [comment]
Why do you want to mangle the python path? This is not needed for virtual environments?

**Comment by mlongval** [comment]
By default my PYTHONPATH is ""
When I am inside a ENV and try to run stuff I get "no module named ..." errors. 
If I make PYTHONPATH = the VENV then it runs. 
I am not a real programmer so my setup is probably borked from the outset.

**Comment by mlongval** [comment]
This is run in a virtualenv with normal PYTHONPATH:

```
doc at T420 in ~/src/pyvim on master!
± echo $PYTHONPATH

doc at T420 in ~/src/pyvim on master!
 ± source bin/activate
(pyvim) doc at T420 in ~/src/pyvim on master!
(pyvim)  ± echo $PYTHONPATH   

(pyvim) doc at T420 in ~/src/pyvim on master!
(pyvim)  ± ./run_pyvim.py 
Traceback (most recent call last):
  File "./run_pyvim.py", line 17, in <module>
    from pyvim.editor import Editor
ModuleNotFoundError: No module named 'pyvim'
(pyvim) doc at T420 in ~/src/pyvim on master!
(pyvim)  ± 
```
And this is with the modified "activate" shell script:

```
± echo $PYTHONPATH

doc at T420 in ~/src/pyvim on master!
 ± source bin/activate
(pyvim) doc at T420 in ~/src/pyvim on master!
(pyvim)  ± echo $PYTHONPATH
/home/doc/Documents/Source/pyvim
(pyvim) doc at T420 in ~/src/pyvim on master!
(pyvim)  ± ./run_pyvim.py
``` 
The second version works.
