### ISSUE TITLE
can't use a local build of python

### ISSUE THREAD

**Issue by rbtcollins** [pypa/virtualenv#456]
robertc@lifelesshp:~/work/cpython$ mkvirtualenv -p $(pwd)/python /tmp/testrepository-3.4
Running virtualenv with interpreter /home/robertc/work/cpython/python
Using base prefix '/usr/local'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2578, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 980, in main
    no_pip=options.no_pip)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1082, in create_environment
    site_packages=site_packages, clear=clear))
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1278, in install_python
    copy_required_modules(home_dir)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1216, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1186, in change_prefix
    (filename, prefixes)
AssertionError: Filename /home/robertc/work/cpython/Lib/os.py does not start with any of these prefixes: ['/usr/local', '/usr/local']

**Comment by jaraco** [comment]
In #745, @Ivoz suggests that one just needs to configure the `prefix` "correctly". However, I don't think the solution is so simple. I tried building CPython with `./configure --prefix=/Users/jaraco/p/cpython` (where that prefix is the location of the cpython checkout), and re-made python.

After, I tried invoking virtualenv against that python, but it fails with a different error:

```
$ python -m virtualenv --version              
15.0.3
$ python -m virtualenv --python /Users/jaraco/p/cpython/python.exe issue456
Running virtualenv with interpreter /Users/jaraco/p/cpython/python.exe
Using base prefix '/Users/jaraco/p/cpython'
New python executable in /Users/jaraco/Dropbox/code/public/cpython/issue456/bin/python.exe
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffd7a583c0 (most recent call first):
ERROR: The executable /Users/jaraco/Dropbox/code/public/cpython/issue456/bin/python.exe is not functioning
ERROR: It thinks sys.prefix is '/Users/jaraco/Dropbox/code/public/cpython' (should be '/Users/jaraco/Dropbox/code/public/cpython/issue456')
ERROR: virtualenv is not compatible with this system or executable
```

If I understand correctly, the 'prefix' is where the various dependent libraries reside (zlib, for example), so `/usr/local` is the correct prefix (at least for my build on macOS).

**Comment by pfmoore** [comment]
I don't know if it's relevant, but I have a suspicion that Python special-cases the situation when it's being run from a checkout (to make it easier to test a newly built Python without having to install it, AIUI). Could that be relevant here? Sorry, I don't know any more details than this.

**Comment by jaraco** [comment]
@pfmoore Yes, that could indeed be relevant. I am running python from the build. I'm also largely unfamiliar with the nuances of Python builds and install locations.
