### ISSUE TITLE
Virtualenv 1.10.1 on Python 3.2 on Ubuntu 12.04 fails with ImportError

### ISSUE THREAD

**Issue by retrogradeorbit** [pypa/virtualenv#506]
$ uname -a
Linux workstation 3.5.0-44-generic #67~precise1-Ubuntu SMP Wed Nov 13 16:16:57 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

$ apt-get install python3

$ python3
Python 3.2.3 (default, Sep 25 2013, 18:22:43) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

$ curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.10.1.tar.gz
$ tar xvfz virtualenv-1.10.1.tar.gz
$ cd virtualenv-1.10.1 && sudo python3.2 setup.py install
running install
running build
running build_py
running build_scripts
copying and adjusting scripts/virtualenv-3.2 -> build/scripts-3.2
running install_lib
running install_scripts
copying build/scripts-3.2/virtualenv-3.2 -> /usr/local/bin
changing mode of /usr/local/bin/virtualenv to 755
changing mode of /usr/local/bin/virtualenv-3.2 to 755
running install_egg_info
Removing /usr/local/lib/python3.2/dist-packages/virtualenv-1.10.1.egg-info
Writing /usr/local/lib/python3.2/dist-packages/virtualenv-1.10.1.egg-info

$ which virtualenv
/usr/local/bin/virtualenv
$ which virtualenv-3.2
/usr/local/bin/virtualenv-3.2

$ virtualenv-3.2 --help
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv-3.2", line 2, in <module>
    import virtualenv
ImportError: No module named virtualenv

**Comment by hugovk** [comment]
This is old issue can be closed now because EOL Python 3.2 was dropped a long time ago.
