### ISSUE TITLE
Permission error writing header files in pypy virtualenvs

### ISSUE THREAD

**Issue by qwcode** [pypa/virtualenv#510]
for the trace, see: https://travis-ci.org/pypa/pip/jobs/14962187

the error occurs running this pip test:
https://github.com/pypa/pip/blob/1.5.X/tests/functional/test_install_wheel.py#L40

although the test is intended to be a general wheel test, it happens to be using a wheel distribution with headers.

currently, in virtualenv for pypy,  the include dir ends up getting linked directly to the global include, _if_, the global pypy has an include dir already.

e.g. here's an example virtualenv structure on the latest ubuntu using pypy2.2.1 from ppa:pypy/ppa, which does include header files in it's global  `/usr/lib/pypy/include`

```
drwxrwxr-x 2 ubuntu ubuntu 4096 Dec  6 00:12 bin
lrwxrwxrwx 1 ubuntu ubuntu   21 Dec  6 00:12 include -> /usr/lib/pypy/include
drwxrwxr-x 2 ubuntu ubuntu 4096 Dec  6 00:12 lib_pypy
drwxrwxr-x 3 ubuntu ubuntu 4096 Dec  6 00:12 lib-python
drwxrwxr-x 3 ubuntu ubuntu 4096 Dec  6 00:12 site-packages
```

this is problematic if the global site is root permissions.  header files can't be installed into include (note, I'm assuming that the pip wheel installer had it correct in trying to install to include/site)

for comparison,  in linux cpython's, the linking occurs differently due to it following the "normal" distutil's schemes.

```
bin
include
   python2.7 -> /usr/include/python2.7
lib
```

it seems the logic needs to be updated to not link "include" dir itself, but the only the global files within.

P.S.  as for why this was not a problem in pip's tests with pypy1.9, here's 3 theories:
1) that distribution didn't include a global "include" dir
2) the permissions were different previously for the pypy1.9 install on travis
3) there's some other change in virtualenv (or wheel or pip), that I'm not seeing atm?

cc @dstufft , @alex, @pfmoore

**Comment by mattip** [comment]
I am reviving this since a user reported an [issue](https://bitbucket.org/pypy/pypy/issues/2647/unable-to-install-headers-in-virtualenv) on the PyPy issue tracker. Could we simply set symlink=False when copying the stdinc_dir on pypy, L1156 https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L1156
