### ISSUE TITLE
Make --relocatable even more relocatable

### ISSUE THREAD

**Issue by omribahumi** [pypa/virtualenv#558]
Apparently even when running `virtualenv --relocatable` on my virtualenv, it's still not entirely relocatable:
1. Links in `${VIRTUAL_ENV}/local` are absolute instead of symbolic
2. `VIRTUAL_ENV` environment variable defined in `bin/activate` is hard-coded

I'm thinking of fixing these myself, here's how I thought of doing it:
1. Walk the virtualenv directory tree, make all absolute links to destinations inside the virtualenv relative (absolute links to paths outside of the virtualenv root will stay absolute)
2. Replace hard-coded virtualenv path with bash magic (similar to [this](http://stackoverflow.com/a/246128/1351728)):

``` bash
VIRTUAL_ENV="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
```

Any thoughts?

Omri.

**Comment by aristidesfl** [comment]
+1

**Comment by kairichard** [comment]
+1

**Comment by dbarbeau** [comment]
Yes, the bash activate script should set VIRTUAL_ENV with bash magic. This would help a ton when packaging our projects for use with external tools like uwsgi. So a huge +1.

**Comment by arizvisa** [comment]
Adding a reference to the newest issue #1067 related to this to help consolidate efforts on solving this half-decade old problem with the activation scripts.
