### ISSUE TITLE
Command line utillity to discover virtualenv paths (cross platform)

### ISSUE THREAD

**Issue by jdufresne** [pypa/virtualenv#594]
To make cross platform scripting easier, I've created a utility that can be called from the command line to discover where virtualenv paths are located.

This solves the problem that can occur if one developer is using Python 2.7, while the deployment server is using Python 2.6 and automated scripts want to execute commands in the virtualenv bin. Or the problem where one developer develops on Linux while a different developer develops on Windows but an automated script wants to execute commands in the virtualenv bin. It is intended to be used in the following way:

```
$ $(virtualenvpath path/to/my/virtualenv bin)/pip install package
$ virtualenvpath path/to/my/virtualenv lib  # Using sed, place in an Apache config
```

Here is the script for inclusion, I'd be happy to continue polishing this up if there is interest (perhaps better command line help?), I know it would help me and my team.

```
#!/usr/bin/python
import argparse
import virtualenv


paths = ('home', 'lib', 'inc', 'bin')


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('home')
    parser.add_argument('path', nargs='?', default='home', choices=paths)
    return parser.parse_args()


def main():
    args = parse_args()
    paths = virtualenv.path_locations(args.home)
    d = dict(zip(('home', 'lib', 'inc', 'bin'), paths))
    print(d[args.path])


if __name__ == '__main__':
    main()
```

This was inspired when I used node.js and npm. npm has a command `bin`, that returns the directory of binaries. My scripts and Makefiles use $(npm bin) so I know I'm always pointing to the correct directory without hard coding paths.

https://www.npmjs.org/doc/cli/npm-bin.html

**Comment by merwok** [comment]
`python -m site` gives information, but not in a readily parseable format.
