### ISSUE TITLE
Whitespace in Python install folder causes error

### ISSUE THREAD

**Issue by AMWJ** [pypa/virtualenv#616]
This is during a VirtualEnv creation. An exception arises after "Cleaning up...". The last line is:

  File "C:\Program Files\Python\Python2\lib\site-packages\virtualenv_support\pip
-1.5.4-py2.py3-none-any.whl\pip_vendor\requests\sessions.py", line 526, in get_
adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'c:\Program'

**Comment by zevav** [comment]
ditto

**Comment by DiegoQueiroz** [comment]
I confirm this issue, and I think it should be addressed with some priority. pip also had the same issue in the past, but it is already fixed there.

While this is not done, here is one workaround:
Just follow the same steps described in this link http://stackoverflow.com/a/24627797 but on virtualenv.exe executable.

In short:
* open the virtualenv.exe file in any hexadecimal editor
* search for the path of your python.exe (mine was C:\Program Files\Python34\python.exe)
* change the path to some other path without using spaces (I changed mine to C:\Progra~1\Python34\python.exe, but you can also create a symlink/junction if you want)

**Comment by xflr6** [comment]
Same issue here.
As the Python 3.5 Windows installer [will change the default installation directory](http://stevedower.id.au/blog/the-python-3-5-installer/) to `C:\Program Files (x86)\Python35` (amongst others, for security reasons), this will likely affect a lot more users than currently.

**Comment by DiegoQueiroz** [comment]
I wasn't aware about this change when I commented. Now I think the priority is even higher, or we will see lots of users complaining here in the near future. :)
