### ISSUE TITLE
Skip "fix_local_scheme" for "virtualenv ."? (symlinks all files)

### ISSUE THREAD

**Issue by blueyed** [pypa/virtualenv#617]
I wonder if [fix_local_scheme](https://github.com/pypa/virtualenv/blob/develop/virtualenv.py#L1532-1550) should get skipped for the special case of `virtualenv .`, where it causes all files in the current directory to be symlinked from the `local` folder.

This causes some unexpected behavior with pytest_django's tests, which uses `virtualenv .`, and then confused `py.test`, because it found the `conftest.py` twice (see https://github.com/pelme/pytest_django/issues/102).

**Comment by bukzor** [comment]
fix_local_scheme should go away entirely.
The ubuntu patch that it was working around no longer exists.

**Comment by Ivoz** [comment]
@bukzor do you remember for which ubuntu versions that patch existed on?

**Comment by yan12125** [comment]
@Ivoz It's for Ubuntu 11.04 (#118). I'm not sure whether other Ubuntu versions are also affected or not.
