### ISSUE TITLE
1.11.6 creates right shebang but wrong file name

### ISSUE THREAD

**Issue by frumpel** [pypa/virtualenv#622]
When installing virtualenv using pip the shebang and file name don't match. Repro: 

On CentOS 6.4 install python with altinstall

```
tar -xf ${version}.tgz --ungzip
cd $version
./configure --prefix=/usr/local --with-zlib
make
#really important to make the altinstall if you want to install python2.7 next to python2.6
make altinstall
```

Install pip using the specific version of python desired

```
/usr/local/bin/easy_install-2.6 pip
/usr/local/bin/pip2.6 install virtualenv
```

The resulting virtualenv entries in /usr/local/bin end up being (note the WRONG version number):

```
/usr/local/bin/virtualenv
/usr/local/bin/virtualenv-2.7 
```

At the same time the file contains the (CORRECT) hashbang for the python executable:

```
#!/usr/local/bin/python2.6
```

This appears to have been introduced in the transition from 1.11.5 to 1.11.6

**Comment by gaborbernat** [comment]
I think this should be fixed, we don't support Python 2.6 anymore but if you can reproduce it with 2.7+ open it again.
