### ISSUE TITLE
docs: sitecustomize.py

### ISSUE THREAD

**Issue by guettli** [pypa/virtualenv#629]
Please explain how to use a  sitecustomize.py file in a virtual env in the docs. Thank you.

Up to now, there are no docs about this:
http://virtualenv.readthedocs.org/en/latest/search.html?q=sitecustomize&check_keywords=yes&area=default

**Comment by miraculixx** [comment]
+1. I have found this to work:

To have a per-virtualenv `sitecustomize.py` place it in `/path/to/venv/lib/python2.x`.

### Rationale

`sitecustomize.py` is [imported](https://docs.python.org/2/library/site.html) when all of `sys.path` has been set up. To find where it is loaded from, run:

```
$ virtualenv venv
$ python -c "import sitecustomize; print sitecustomize"
<module 'sitecustomize' from '/usr/lib/python2.7/sitecustomize.pyc'>
```

To have a sitecustomize that is active only in your venv, place it in `/path/to/venv/lib/python2.7` (or any other path that `python -m site` shows is before the path shown above.

**Comment by guettli** [comment]
@miraculixx  thank you that you found this. 

What do the virtualenv core experts think?

**Comment by pfmoore** [comment]
This seems to be standard Python behaviour (see https://docs.python.org/3.6/library/site.html) so I don't think it needs anything specific in the virtualenv docs.

**Comment by guettli** [comment]
I thought it is possible to provide a sitecustomize for every virtualenv.

But the sitecustomize from virtualenv gets loaded. But unfortunately the sitecustomize from the global interpreter gets loaded:

```
===> virtualenv  testenv
New python executable in /home/tguettler/projects/testenv/bin/python
Please make sure you remove any previous custom paths from your /home/tguettler/.pydistutils.cfg file.
Installing setuptools, pip, wheel...done.

===> cd testenv

===> . ./bin/activate

===(testenv)> python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sitecustomize
>>> sitecustomize.__file__
'/usr/lib/python2.7/sitecustomize.pyc'
```

**Comment by pfmoore** [comment]
> Is there no way to have a sitecustomize for every virtualenv?

No, there's no directory that gets added to ```sys.path``` "whenever you are in a virtualenv", but not when you're in a non-virtualenv environment.

You could probably put something together by using a global ```sitecustomize.py``` that checked if you were in a virtualenv (something like ```sys.prefix != sys.real_prefix```) and doing your "if I'm in a virtualenv" initialisation there. But again, that's just standard Python functionality. There's nothing specific that virtualenv does here.

**Comment by guettli** [comment]
I apologize! I was missing something.

In my context we mainly use one linux distribution. On this linux distribution no global sitecustomize exists. Since some years our team though we can put a sitecustomize into the virtualenv and have a way to do per virtualenv stuff.

Some linux distributions provide a global sitecustomize .... now our way to handle this failed.

We use usercustomize now, and this works perfectly.

My issue is resolved now. I think the docs don't need an update. What do you think?

**Comment by guettli** [comment]
No reply to:

> I think the docs don't need an update. What do you think?

ok, I close this issue.
