### ISSUE TITLE
upload virtualenv.py to https://bootstrap.pypa.io/

### ISSUE THREAD

**Issue by techtonik** [pypa/virtualenv#632]
`wget https://bootstrap.pypa.io/virtualenv.py` is much easier than 

```
open browser to lookup X.X
```

```
$ curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-X.X.tar.gz
$ tar xvfz virtualenv-X.X.tar.gz
$ cd virtualenv-X.X
$ python virtualenv.py myVE
```

From `use locally from source` at https://virtualenv.pypa.io/en/latest/virtualenv.html#installation

**Comment by abalkin** [comment]
The ideas in issue may resolve #1042.
