### ISSUE TITLE
virtualenv 1.11.6, Windows and spaces in paths

### ISSUE THREAD

**Issue by robi-wan** [pypa/virtualenv#637]
Please fix this issue https://github.com/pypa/pip/issues/1961, release a new pip and then a new virtualenv.

Currently it is not possible to create a virtualenv (with v1.11.6) under Windows if one path (path to python.exe or path to virtualenv) contains a space.

**Comment by reedcourty** [comment]
I think it is the same as #616.

**Comment by shimizukawa** [comment]
I think this issue is already fixed.

I tried this again with:

* Windows 10 64bit
* Python-2.7.11 x86(32bit)
* virtualenv-15.0.1

virtualenv command works fine for under white-spaced directory.
