### ISSUE TITLE
not in gzip format

### ISSUE THREAD

**Issue by leonli319** [pypa/virtualenv#643]
I can't extract from tarball "virtualenv-X.X.tar.gz".
This is what I got:

$ tar xfvz virtualenv-X.X.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error exit delayed from previous errors

**Comment by msabramo** [comment]
What tarball? Download from PyPI?

**Comment by pfmoore** [comment]
Did your download tool (browser?) notice the file was served as a gzip and automatically unzip it? IIRC some browsers used to do this.

**Comment by Ivoz** [comment]
Same command line invocation worked for me just now, using `.tar.gz` files from both github releases and pypi. Comment again if you're still having an issue.

**Comment by pramodsetlur** [comment]
I am unable to untar it using tar -zxvf or gunzip. 

USHOLPSE2-ML:tmp pramod.setlur$ tar -xf virtualenv-X.X.tar.gz 
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

USHOLPSE2-ML:tmp pramod.setlur$ gunzip virtualenv-X.X.tar.gz 
gunzip: virtualenv-X.X.tar.gz: not in gzip format
USHOLPSE2-ML:tmp pramod.setlur$

**Comment by Ivoz** [comment]
You probably need the zlib/gzip library installed.
