### ISSUE TITLE
virtualenv hangs while creating env near big .html files

### ISSUE THREAD

**Issue by YorikSar** [pypa/virtualenv#646]
I've stumbled upon the fact that ``virtualenv`` just hang when I was creating an environment in my ``~/tmp`` dir. Looking at ``top`` output I found out that ``pip`` process (or more precisely ``python -c 'import sys, pip; sys.exit(pip.main....``) was eating ~100% of CPU and a lot of memory (GBs).

Digging into the issue I found out that pip was parsing huge (if you call 64 Mb huge) ``.html`` file I had in ``~/tmp`` and I think was trying to determine its encoding. That process took a lot of CPU time which looked like it just hang.

I wondered why would pip parse arbitrary ``.html`` files in current directory. After stepping out of ~~rabbit hole~~ stack, I found out that for some reason ``virtualenv`` passes current dir in ``find_links`` to ``pip``.

It looks like this ``'.'`` has been in code since forever, but I can't find (didn't dig deep enough) the reason for it. We don't want to install stuff from current dir, do we? I think we should remove everything except ``virtualenv_support`` dir from ``file_search_dirs`` method since everything we want to install is in that dir anyway.

**Comment by Ivoz** [comment]
I believe that should be the case now in [`file_search_dirs`](https://github.com/pypa/virtualenv/blob/97090c4ca0fae61df378369e460622975ec8a0f8/virtualenv.py#L393).
