### ISSUE TITLE
virtualenv 1.11.6 not working with MSYS2

### ISSUE THREAD

**Issue by pe224** [pypa/virtualenv#650]
I'm using the latest version of [MSYS2](https://sourceforge.net/projects/msys2/) with Python 2.7.8 as the only system-wide Python.
Pip installed virtualenv 1.11.6 without problems.
Executing `virtualenv myenv` results in

```
Traceback (most recent call last):
  File "C:\msys64\home\eib/myvenv/lib/python2.7/site.py", line 703, in <module>
    main()
  File "C:\msys64\home\eib/myvenv/lib/python2.7/site.py", line 692, in main
    aliasmbcs()
  File "C:\msys64\home\eib/myvenv/lib/python2.7/site.py", line 515, in aliasmbcs
    import locale, codecs
  File "C:/msys64/home/eib/myvenv/lib/python2.7/locale.py", line 19, in <module>
    import functools
ImportError: No module named functools
New python executable in myvenv/Scripts/python.exe
ERROR: The executable myvenv/Scripts/python.exe is not functioning
ERROR: It thinks sys.prefix is u'c:\\msys64\\home\\eib' (should be u'c:\\msys64\\home\\eib\\myvenv')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for "Only this user" or have multiple versions of Python installed. Copying the appropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
```

Supplying additional arguments like an explicit --python didn't change anything.
Now there seem to be two problems:
First, the virtualenv is not created completely. Parts of myenv/lib are missing and there are no activation scripts.
Second, there is only a non-functioning python in myenv/Scripts/python.exe

Since there is no Python dll, I tried copying around libpython2.7.dll.a and libpython2.7.a, but to no avail. What made the myenv/Scripts/python.exe to work was to symlink the working Python lib/python2.7 to myvenv/lib/python2.7, then it could find the standard library.

Why does the virtualenv creation process stop in the middle? It looks like everything could be brought to work. Also, it seems that whole include/lib folders are copied, although MSYS2 is configured to do native windows symlinks with "ln -s". On my mac, virtualenv creates correct symlinks.

Is it a path issue? `$MSYS_HOME` is correctly set to `/c/msys64`
What's going on? Thanks for any pointers.

**Comment by dleslie** [comment]
This is a pain; having a broken virtualenv breaks Jedi in Emacs. It's a shame that the MSYS2 team patched Python so heavily.

**Comment by iongion** [comment]
It took 3 minutes to create the env, it did not complete successful, the size of this incomplete env directory is 301 MB, for some reason it actually contains the entire include path of msys2 toolchain.
I look at this with no joy:
```
$ virtualenv env --no-site-packages
New python executable in W:/Workspace/Nucleus/Neuron/env/Scripts/python2.exe
Also creating executable in W:/Workspace/Nucleus/Neuron/env/Scripts/python.exe
Traceback (most recent call last):
  File "W:/Workspace/Nucleus/Neuron/env/lib/python2.7/site.py", line 703, in <module>
    main()
  File "W:/Workspace/Nucleus/Neuron/env/lib/python2.7/site.py", line 692, in main
    aliasmbcs()
  File "W:/Workspace/Nucleus/Neuron/env/lib/python2.7/site.py", line 515, in aliasmbcs
    import locale, codecs
  File "W:/Workspace/Nucleus/Neuron/env/lib/python2.7/locale.py", line 17, in <module>
    import functools
ImportError: No module named functools
ERROR: The executable W:/Workspace/Nucleus/Neuron/env/Scripts/python2.exe is not functioning
ERROR: It thinks sys.prefix is u'w:/workspace/nucleus/neuron' (should be u'w:/workspace/nucleus/neuron/env')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for "Only this user" or have multiple versions of Python installed. Copying the appropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
```

**Comment by erikbsap** [comment]
so this problem is known since 2014 and still exists? Don't allow `pacman -S python3-pip` if you can't have virtualenvs working. Or in the installation print a warning or something to give an alternative approach.

**Comment by ca1ek** [comment]
nice way of removing issues you just don't want to fix, label them stale

**Comment by verm** [comment]
The fix offered by @pe224 on 2014-09-24 still works, I had to modify it for the latest source.

The problem is it assumes it's on Windows as Python in msys2 reports as 'win32' while msys2 offers a UNIX-like environment.  Once this is taken into account everything works as expected.  

If there's interest to fix this I can provide a patch.  I'm adding this here for anyone in the future who is interested.  If there is interest I can provide a proper patch.

**Comment by verm** [comment]
I've opened a new ticket with a patch for v16.0.0 see #1338
