### ISSUE TITLE
--always-copy flag doesn't copy

### ISSUE THREAD

**Issue by joedborg** [pypa/virtualenv#654]
``` python
$ python2.7
Python 2.7.6 (default, Nov 18 2013, 11:08:31) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>>

$ find /usr/local/lib/python2.7/site-packages -name "*django*"
# Lots of files listed.

$ virtualenv-2.7 --system-site-packages --always-copy django_branch

$ find ./django_branch/ -name "*django*"
# Nothing found.
```

**Comment by ionelmc** [comment]
In the current virtualenv incarnation `--always-copy` is meant for the bootstrap modules (and `include` dir perhaps).

For what @joedborg is asking, it essentially mean relocating modules from the global `site-packages`. I don't think this can be fixed (especially if we drop the relocatable support from the rewrite). Perhaps close this, @dstufft ?

@joedborg, what's your use-case for this?

**Comment by joedborg** [comment]
Hi @ionelmc, I was basically looking for a way of copying a Python instance, to then use for testing (e.g. copy it to a test server or update a package and test). 

I didn't think this would be fixed here (although having the flag in virtualenv leads one to believe that it works), so I have started a project (https://josephb.org/projects/vampire/) to create something for this.  Any help with the project would be greately received.
