### ISSUE TITLE
virtualenv installs pip 1.3.1 which has SSL issues

### ISSUE THREAD

**Issue by rmx90210** [pypa/virtualenv#665]
I'm trying to use virtualenv 1.9.1 on a Windows 7 machine. (FWIW I'm also using virtualenvwrapper-win.) When I `mkvirtualenv` it creates a new environment without any issues, but if I `pip install` something I get:

`CertificateError: hostname '[OUR PROXY SERVER]' doesn't match either of 'www.python.org', 'python.org', 'pypi.python.org', 'docs.python.org', 'testpypi.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.python.org', 'mail.python.org', 'packaging.python.org', 'pythonhosted.org', 'www.pythonhosted.org', 'test.pythonhosted.org', 'us.pycon.org', 'id.python.org'`

Full trace here: https://gist.github.com/rbrtmrtn/b68b277ce0ac46b6253f

I've looked into this and it seems like a problem with the version of pip being too old (1.3.1) and having SSL compatibility issues. I also found this StackOverflow thread that says it's not possible to force-install a higher version:
http://stackoverflow.com/questions/17156912/how-to-force-virtualenv-to-install-latest-setuptools-and-pip-from-pypi

Has anyone else run into this? Or know of a workaround? Much appreciated.

**Comment by vishaljain3991** [comment]
hey there I had the same problem..
So I installed the latest version of the virtualenv. Then I copied the pip files which comes when we install Python to the Scripts folder of my virtual environment directory
