### ISSUE TITLE
Cannot create virtualenv after upgrading OS X 10.6.8 Python to 2.7

### ISSUE THREAD

**Issue by levtatz** [pypa/virtualenv#694]
I just updated my system Python like so: http://wolfpaulus.com/jounal/mac/installing_python_osx/

Does anyone have any insight into the following error:

```
$ mkvirtualenv --no-site-packages example_name
New python executable in example_name/bin/python
ERROR: The executable example_name/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/System/Library/Frameworks/Python.framework/Versions/2.7' (should be u'/Users/lev/.virtualenvs/example_name')
ERROR: virtualenv is not compatible with this system or executable
```

```
$ which python
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python
$ which virtualenv
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv
$ which virtualenvwrapper.sh
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenvwrapper.sh
```

In my PATH, I have 
```
/System/Library/Frameworks/Python.framework/Versions/2.7/bin
```

Thank you for your time in advance.

**Comment by levtatz** [comment]
A possible workaround is described here: http://stackoverflow.com/a/5904670

For me:
```
/usr/bin/python2.6 /System/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv
```
seems to make it work

**Comment by Sane-Joker** [comment]
None of the above solutions work. I am also facing the same issue. Tried setting the PYTHONPATH variable as well.

**Comment by yan12125** [comment]
@Sane-Joker Are you using mkvirtualenv too? mkvirtualenv is part of virtualenvwrapper, and there were reports that virtualenvwrapper is broken on Mac. (#1006) Could you paste your commands and outputs?

**Comment by picarus** [comment]
I would say that in many cases the issue will be that the user has Anaconda, then the solution is:
https://stackoverflow.com/questions/5904319/problem-with-virtualenv-in-mac-os-x 
read answer by wastetime909 (not a waste of time at all!)

Regarding your documentation, for some other OS you cover the Anaconda case, I think for consistency and because of broad use, you should include it also for Mac OS.

**Comment by everttrollip** [comment]
If you are still struggling, and experiencing this issue:

`ERROR: virtualenv is not compatible with this system or executable`

Have you tried installing virtualenv with conda and trying again?

`conda install virtualenv`
