### ISSUE TITLE
How to add custom script into active

### ISSUE THREAD

**Issue by oyljerry** [pypa/virtualenv#707]
Hi.
I am using virtualenv 12.05, Now I want to add environment variable LD_LIBRARY_PATH before launch python in virtualenv, so I modify /bin/active script file.
But when I restart virtualenv "virtualenv ENV"
It prompts as below

New python executable in ENV/bin/python
Installing setuptools, pip...done.
Overwriting ENV/bin/activate with new content

It seems my modification is overwritten, and I can not set LD_LIBRARY_PATH variable.

How can I make it? Thanks!

**Comment by pfmoore** [comment]
Why are you running virtualenv on an existing environment? (That will
overwrite the activate script as you see - I'm not sure that making local
modifications to the activate script is a good idea, but that's a separate
issue)

Paul

**Comment by oyljerry** [comment]
Thanks pfmoore very much.
Yes, I mess up virtualenv create and start. I should use source ./bin/active to make my modification effectively, then it works fine.
