### ISSUE TITLE
TypeError with existing  /usr/bin/multiarch-platform file

### ISSUE THREAD

**Issue by baerwolf1983** [pypa/virtualenv#708]
Hi!
I justed installed virtualenv on my Arch Linux system and got an error upon trying to use it.
in virtualenv.py:1047

``` python
    inc_dir = join(home_dir, 'include', stdout.strip(), py_version + abiflags)
```

raises a TypeError: Can't mix strings and bytes in path components
The statement only gets executed if '/usr/bin/multiarch-platform' is executable.
A fix to this could be checking the type of stdout.strip() and decoding it if necessary.

``` python
    b = stdout.strip()
    if type(b) == bytes:
        b = b.decode('utf-8')
    inc_dir = join(home_dir, 'include', b, py_version + abiflags)
```

P.S.: This is my first time submitting an issue, hope I didn't do anything wrong!

**Comment by xals** [comment]
I have the same issue:

    $ LC_ALL=C virtualenv -p python3 test
    Already using interpreter /usr/bin/python3
    Traceback (most recent call last):
      File "/usr/bin/virtualenv", line 3, in <module>
        virtualenv.main()
      File "/usr/lib/python3.4/site-packages/virtualenv.py", line 825, in main
        symlink=options.symlink)
      File "/usr/lib/python3.4/site-packages/virtualenv.py", line 981, in create_environment
        home_dir, lib_dir, inc_dir, bin_dir = path_locations(home_dir)
      File "/usr/lib/python3.4/site-packages/virtualenv.py", line 1047, in path_locations
        inc_dir = join(home_dir, 'include', stdout.strip(), py_version + abiflags)
      File "/usr/lib/python3.4/posixpath.py", line 89, in join
        "components") from None
    TypeError: Can't mix strings and bytes in path components

When I use Python2, I don't have the issue:

     $ LC_ALL=C virtualenv -p python2 test
    Running virtualenv with interpreter /usr/bin/python2
    New python executable in test/bin/python2
    Also creating executable in test/bin/python
    Installing setuptools, pip...done.

And on a Gentoo box, I don't have the issue using python3:

    $ virtualenv -p python3 test
    Running virtualenv with interpreter /usr/bin/python3
    Using base prefix '/usr'
    New python executable in test/bin/python3
    Also creating executable in test/bin/python
    Installing setuptools, pip...done.

The versions are the same on both boxes (Python 3.4.3, virtualenv 12.1.1).

I checked the line 1047 in ``/usr/lib/python3.4/site-packages/virtualenv.py``, it is the same in both systems.

On Gentoo, virtualenv seems to be installed using easyinstall, and is launched using a Gentoo made wrapper named python-exec2.

Remplacing ``stdout.strip()`` by ``str(stdout.strip())`` fixes the issue on Archlinux system.

I can't say if it is an Archlinux or a Virtualenv issue.

**Comment by xals** [comment]
Actually, on Gentoo, we don't have any ``/usr/bin/multiarch-platform`` file, this is why we don't have the issue.

**Comment by xals** [comment]
This file seems to be shipped by "rpm" package (yes, in Archlinux, this command is used by some packages to use ones provided by other distros…). I replaced it by rpm-org package in AUR and it seems to work. Note that rpm package is no longer in Archlinux official repositories.
