### ISSUE TITLE
AttributeError when creating new enviornment

### ISSUE THREAD

**Issue by amalfra** [pypa/virtualenv#710]
I am running fedora 21 and python 2.7. Getting following error when creating new env:

AttributeError: 'module' object has no attribute 'python_version'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /media/DonotFormat/P...e/virtual/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1

**Comment by ionelmc** [comment]
Would help to know library versions. Try running these:
```
python -c "import pip; print pip.__version__"
python -c "import virtualenv; print virtualenv.__version__"
python -c "import setuptools; print setuptools.__version__"
```

**Comment by amalfra** [comment]
1.4
12.0.5
0.9.7

I managed to fix the error by installing 1.10

**Comment by pfmoore** [comment]
Those are pretty old pip and setuptools versions.

Could you also show the output of ```python -c "import sys; print sys.path```? The reason is that I suspect your pip 1.4 was installed as an egg and is getting forced to the front of sys.path (ahead of the wheel bundled in virtualenv) with the easy_install ```pth``` hacks...

**Comment by amalfra** [comment]
['', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']

**Comment by ionelmc** [comment]
What linux distro are you using?

**Comment by amalfra** [comment]
fedora 21

**Comment by ionelmc** [comment]
Could you also post logs of `virtualenv --verbose` ? (assuming you can still reproduce the problem)

**Comment by amalfra** [comment]
Unfortunately i am using 1.10 which fixes the problem....
