### ISSUE TITLE
tests folder for latest release

### ISSUE THREAD

**Issue by idella** [pypa/virtualenv#714]
virtualenv-12.0.6 has no tests folder hence testsuite in the tarball @ pypi.  There is also NO tarball lodged inhouse in guthub for virtualenv-12.0.6.
!. Was this the intention, to not add it
2. IFF no then please re-add it in future releases in the usual way.
3. Did someone forget to make a tarball for inhouse  github?

**Comment by koobs** [comment]
+1 to include (reinclude?) tests in the PyPi sdist.

Currently the test command fails with:

```
running build_ext
================================================================================================================ test session starts ================================================================================================================
platform freebsd11 -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4
ERROR: file not found: test
```

Precludes QA testing of downstream OS packages, which rely on official distribution files from PyPi.

cc @dstufft

**Comment by warsaw** [comment]
+1 for including the tests in the PyPI tarball.  In Debian-land we like to run the tests at package build time.

**Comment by rbtcollins** [comment]
Should just need a MANIFEST.in tweak, no?

**Comment by idella** [comment]
that should do it
