### ISSUE TITLE
[Rewrite] Embedding pip and setuptools

### ISSUE THREAD

**Issue by nrvnrvn** [pypa/virtualenv#717]
> The `virtualenv.py` script is _not_ supported if run without the
> necessary pip/setuptools/virtualenv distributions available locally. All
> of the installation methods above include a `virtualenv_support`
> directory alongside `virtualenv.py` which contains a complete set of
> pip and setuptools distributions, and so are fully supported.

As far as rewrite in progress, I've 1 question/suggestion:
1. Will the new version be available as a single `virtualenv.py` blob with all required dependencies embedded (including `pip` and `setuptools`)?

Thus, one could bootstrap venv via `curl https://raw.githubusercontent.com/pypa/virtualenv/master/virtualenv.py | python - <venvname>`

P.S. Well, my goal was to suggest it via pull request, but now I see that there's no sense in making such changes in the 12-branch.

**Comment by Ivoz** [comment]
You are welcome to make PRs / suggestion to the rewrite branch also. I'm kinda hesitant on having a 1.5-2mb `virtualenv.py` file though.

**Comment by pfmoore** [comment]
Agreed, I'm -1 on bundling. The way virtualenv works, it runs pip directly from the pip wheel to install the pip and setuptools wheels. For that to work the wheel files must be on the filesystem - so a bundled version would have to unbundle to a temp directory anyway. So as @Ivoz says, better to write a shell script if you need something like this. I wouldn't have thought it's that common to want to create just one venv and *not* keep the virtualenv script to use again...
