### ISSUE TITLE
create a pyvenv.cfg file like the venv module

### ISSUE THREAD

**Issue by wm75** [pypa/virtualenv#719]
The stdlib venv module generates a pyvenv.cfg file inside the virtual environment's main folder. This file stores information about the virtual environment such as the original python that the environment was cloned from (and which will provide the standard library) and the version of the interpreter.

virtualenv, instead, places a modified site.py in the environment to make the isolated interpreter use its home stdlib so it does not depend on a config file 'home' key.

However, the 'version' information could still be useful. Specifically on Windows, where the interpreter executable names do not provide version hints, there is currently no simple way to find out what interpreter version is used by a virtualenv without running the interpreter, while for a virtual environment created with venv one can simply inspect the pyvenv.cfg file.

A specific case, in which this information could be useful, is discussed on the python bug tracker - http://bugs.python.org/issue23465 (related to [PEP486](http://www.python.org/dev/peps/pep-0486/)) - and concerns inspection of the virtual environment by the py launcher.

It should also be noted that the current rewrite branch uses the venv module when available and will, thus, generate the pyvenv.cfg file anyway. So having the file created by the legacy builder would also improve consistency.
For this reason, I think the rewrite branch would also be the obvious branch to introduce this feature, but it could be added to the development branch, too.

I could certainly provide a PR if needed, but I would first like to know which repo branch to target.

**Comment by pfmoore** [comment]
Some points:

1. If virtualenv writes a pyvenv.cfg, it should probably identify itself somehow (e.g., with a "creator=virtualenv" entry).
2. You'd need to confirm that Python wouldn't get confused if a pyvenv.cfg was written by something other than venv. Does the mere existence of pyvenv.cfg cause Python to behave differently?
3. I'm not at all sure I'm in favour of the motivating use case in the referenced issue (which means adding more special casing to the shebang handling in the launcher). A better solution might be to enable path searching for ```#!/usr/bin/env pythonX.Y``` and modify virtualenv and venv to write ```pythonX.exe``` and ```pythonX.Y.exe``` executables as well as ```python.exe```. (There has been talk previously of the Windows installer providing ```pythonX.exe``` and ```python X.Y.exe``` for Unix compatibility, so extending that model to virtualenvs is not unreasonable). Or for that matter simply not doing anything, as it's not a particularly common issue (given the lack of bug reports or requests about it).

**Comment by ionelmc** [comment]
About (1) and (2), It doesn't necessarily need to be `pyvenv.cfg`, it could be a `virtualenv.cfg`. We're talking about a pylauncher feature that wasn't completed yet, it wouldn't be that bad to look for two kind of files.

**Comment by wm75** [comment]
concerning 1: that would be ok
concerning 2: the consequences of an existing pyvenf.cfg file are described as part of [PEP405](https://www.python.org/dev/peps/pep-0405/#id19). Before Python3.3 that file is not looked for, with 3.3+ the current rewrite branch (generating the file) proves that it is not causing any harm.

I leave point 3 up for discussion here.

**Comment by pfmoore** [comment]
1. Well, not really, as any code wanting to check would then need to look for either file. It's OK, but more messy than I'd like, and whether it's an acceptable level of messiness depends on what code ends up using it (we have at best one use case so far, see below for comments).
2. Yes, my point was that someone needs to do the research. Checking pep 405 it's *not* OK to use the same filename as that would trigger the core Python virtualenv support. Don't forget you have to consider the possibility of a pre-rewrite virtualenv (unless this issue gets deferred until after the rewrite lands, which is an option).
3. Point 3 should not be discussed here, but as part of proposing the feature for core Python (which needs at a minimum a new item on bugs.python.org, likely also a proposed patch, and quite possibly even a PEP). It's a controversial proposal, and I, for one, am currently against it, not least because it needs a virtualenv change to in order to work properly.

Taken in isolation, I was +0 on this change (it's never a bad thing to record information others might want to use, even though there is no actual use case that I agree with), but the fact that it needs to use a different filename is a point against it, and I'm starting to think it's not worth the effort.

**Comment by wm75** [comment]
"Checking pep 405 it's not OK to use the same filename as that would trigger the core Python virtualenv support."

More precisely, this is only the case if you write the 'home' key to the file. In its absence, the presence of the file has no effect even with Python3.3+.
So if the current development branch really is incompatible with the core Python virtualenv support, just do not write this specific key. It should be safe to include it in the rewrite branch.

As far as point 3 is concerned I'm not implying here that [PEP486](http://www.python.org/dev/peps/pep-0486/) should or MUST be updated. The feature I propose here for virtualenv merely provides the OPPORTUNITY for an additional pylauncher feature (whether introduced via a separate PEP or not; what I'm arguing over in the bug tracker is just that it would be nice to have this additional feature land in the same Python release as PEP486) and generally helps in inspecting virtualenvs (IMO at minimal costs). So I do not think my proposal here and PEP486 are intimately connected and should really be considered in isolation.

**Comment by pfmoore** [comment]
OK, cool. So there's some subtle issues about what gets written to the file and/or what it's named, which implies a support cost (2 years from now, a bug report "virtualenv doesn't write the home key in pyvenv.cfg"). That's fine, we just need to take care of such things.

To summarise my concerns over this, then:
1. Some risk of clashes with how PEP 405 uses pyvenv.cfg.
2. No real motivating use cases.

Let's see what other people think - I'm just repeating the same things now.

**Comment by ionelmc** [comment]
Reusing `pyvenv.cfg` is a bad idea IMO, because it add constraints on how venv might evolve in the future, and how virtualenv might evolve in the future.

I don't see why pylauncher couldn't look at a `virtualenv.cfg` file instead. Better to reuse the concept than to shoehorn something in an existing implementation.

**Comment by wm75** [comment]
"it add constraints on how venv might evolve in the future, and how virtualenv might evolve in the future."

that's an argument although if you look at the rewrite branch that constraint is accepted already by using the venv module internally (unless you would rename the cfg file after it's been generated).

**Comment by ionelmc** [comment]
> if you look at the rewrite branch that constraint is accepted already 

I'm not sure what you meant there. The rewrite branch just calls the venv module if available, it doesn't reimplement it. The result will work like a venv, not like a virtualenv (using the legacy bootstrap techniques).

Perhaps you can elaborate? Or look at the rewrite branch to see what it really does.

**Comment by wm75** [comment]
What I mean is that with the rewrite branch any virtualenv created from a Python3.3+ will contain a pyvenv.cfg file anyway and its contents will be determined by whatever the venv module chooses to write into it. So, in this sense, virtualenv and venv will be coupled.
IMO, it would make sense to have the same-named file present independent of how the virtualenv was created. But perhaps I didn't really understand the kind of constraint you had in mind ?

**Comment by ionelmc** [comment]
Ok, there are 3 issues I have in mind, if it's implemented exactly as you proposed:

* Virtualenv is forced to obey the "no `home` key" rule. What if it's desirable to use it?
* Consumer code will check the presence of said key to detect the type of virtualenv. I think this is wrong. Had PEP405 been designed to work with different implementation that would be ok, but alas, it was not. The whole point of PEP405 was that the interpreter has responsibility over all aspect pertaining to virtualenvs, not some other external tool. In a way this is an abuse of a tiny loophole in PEP405.
* Internals coupling. Currently the rewrite is not coupled with the internals of venv, nor it should ever be. How venv works is the sole responsability of venv. The rewrite is merely a client of venv, and it oblivious to the internals of venv. To say they are coupled is quite a stretch, they have an public, documented API contract and that's it. That's not coupling between implementations, it's just an API contract.

**Comment by wm75** [comment]
hmm,
- "Virtualenv is forced to obey the "no home key" rule. What if it's desirable to use it?"
why would it be desirable, if virtualenv has its own mechnism and if it has not been desirable until now ?

- "Consumer code will check the presence of said key to detect the type of virtualenv."
Consumer code could do the same right now by checking the presence of pyvenv.cfg.
The behaviour in case of a missing 'home' key is explicitly stated in the PEP (if that is what you are calling a tiny loophole).

- "To say they are coupled is quite a stretch, they have an public, documented API contract and that's it."
Ok, I agree with this one. But which additional sort of coupling exactly are you afraid of then ?
Is it that Python may start to look at other keys in the pyvenv.cfg file in the future ? That is indeed an argument for a differently named file although such a change in the interpreter behavior would itself be hard to push, particularly, with client code relying on the current behavior :)

**Comment by ionelmc** [comment]
Virtualenv works very differently than venv, anything that would make it possible to confuse one for the other scares the hell out of me.

I also like the fact that it's more easy to test for existence of `virtualenv.cfg` than parsing out `pyvenv.cfg`. This is usually a plus when writing deploy scripts.
