### ISSUE TITLE
Feature: virtualenv <name> --activate

### ISSUE THREAD

**Issue by techtonik** [pypa/virtualenv#728]
Add `--activate` option to create and activate disposable environment in one step.

**Comment by pfmoore** [comment]
This isn't possible because virtualenv is a Python script and so can't affect the parent shell's environment. That's why there are multiple activate scripts, one for each shell.

Alternative solutions like vex start a *new* shell. Something like that might be the sort of thing you want.

**Comment by pjdelport** [comment]
@techtonik: Note that virtualenvwrapper has a [mktmpenv](http://virtualenvwrapper.readthedocs.org/en/4.3/command_ref.html#mktmpenv) command that does just this.
