### ISSUE TITLE
TestPython@Python 3.5.0a2 : PermissionError:[WinError 5] Access Denied

### ISSUE THREAD

**Issue by gigaimage** [pypa/virtualenv#730]
Win7-64 bits : All Pythons are 64bit installer 
Pythons : 
                    C:\Python3.5
                    C:\Python34
                    C:\Python27  
Path :   C:\Python 3.5\Scripts\;C:\Python 3.5\;..............  (path was set by the Python 3.5 installer)

```
PS C:\> virtualenv -p C:\Python34\ --system-site-packages D:\workspace\projects\TestPython\TestPython@Python35
Running virtualenv with interpreter C:\Python34\
Traceback (most recent call last):
  File "C:\Python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python 3.5\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
  File "C:\Python 3.5\lib\site-packages\virtualenv.py", line 784, in main
    popen = subprocess.Popen([interpreter, file] + sys.argv[1:], env=env)
  File "C:\Python 3.5\lib\subprocess.py", line 855, in __init__
    restore_signals, start_new_session)
  File "C:\Python 3.5\lib\subprocess.py", line 1125, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied
PS C:\>
```

**Comment by cemrich** [comment]
Try to point to ```C:\Python34\python.exe``` instead of ```C:\Python34```. I haven't seen it properly documented but it works on my win8 64bit machine.

**Comment by cpoptic** [comment]
I encountered a similar issue with Windows 10, 64-bit machine.
From the command prompt, in the directory I wish to install the virtual environment, running the simple command
`virtualenv venv`
results in the error message popup windows: 

> This app can't work on your PC.  To find a version for your PC, check with the software publisher.
The command prompt displays 

> "Access is denied."

Suggestions to fix this issue? Thanks
