### ISSUE TITLE
Make --extra-search-dir a preferred location for deterministic installs

### ISSUE THREAD

**Issue by techtonik** [pypa/virtualenv#734]
https://github.com/gratipay/gratipay.com/issues/3268#issuecomment-83198372

The virtualenv fails, because system has newer setuptools/pip installed. The option should be checked first and used. It will also help to show message of which setuptools/pip package is installed.

**Comment by pfmoore** [comment]
It's "extra" not "instead". You always get the latest version. If you want a deterministic setup, use ```--no-setuptools --no-pip``` and install the exact versions you want manually.

**Comment by techtonik** [comment]
The bug above shows that the latest version is not compatible with older virtualenv, so it is a bad strategy.

Can you give an example how to do this properly? I need it to work from a Makefile.
https://github.com/gratipay/gratipay.com/blob/903f2d5927512614d1c7728f20cb27d8985cf283/Makefile#L19
