### ISSUE TITLE
insecure use of . and pip findlinks

### ISSUE THREAD

**Issue by rbtcollins** [pypa/virtualenv#753]
I happened to have a log from a failed test run in my pip tree. It was an html file called 'console.html' and contained this string:
2015-04-27 20:41:15.698 |   Downloading <a href='http://pypi.region-b.geo-1.openstack.org/packages/3.4/s/setuptools/setuptools-15.2-py2.py3-none-any.whl'>http://pypi.region-b.geo-1.openstack.org/packages/3.4/s/setuptools/setuptools-15.2-py2.py3-none-any.whl</a> (501kB)

Now, in venv we call into virtualenv which does this:

```
-> install_wheel(to_install, py_executable, search_dirs)
  /home/robertc/work/pip/.tox/py27/local/lib/python2.7/site-packages/virtualenv.py(964)install_wheel()
-> 'PIP_NO_INDEX': '1'
> /home/robertc/work/pip/.tox/py27/local/lib/python2.7/site-packages/virtualenv.py(871)call_subprocess()
```

with the following variables:

```
960                     'PYTHONPATH': pythonpath,
961                     'PIP_FIND_LINKS': findlinks,
962                     'PIP_USE_WHEEL': '1',
963                     'PIP_PRE': '1',
964  ->                 'PIP_NO_INDEX': '1'
```

but findlinks is set thusly:

```
". /home/robertc/work/pip/.tox/py27/local/lib/python2.7/site-packages /home/robertc/work/pip/.tox/py27/local/lib/python2.7/site-packages/virtualenv_support /home/robertc/work/pip/.tox/py27/local/lib/python2.7/site-packages/virtualenv_support
"
```

Note the leading '.'.

AFAICT this means that any cwd can cause an arbitrary setuptools to be installed, with no security warning, over an insecure channel when an html file containing a link to a setuptools wheel is found.

I'm not sure why . is present there- but its coming from file_search_dirs(), which hardcodes it.

**Comment by dstufft** [comment]
Fixed now in #755
