### ISSUE TITLE
13.0.1 pip InsecurePlatformWarning

### ISSUE THREAD

**Issue by franciscolourenco** [pypa/virtualenv#764]
After upgrading to virtualenv 13.0.1 and creating a new virtualenv, I get the following warning when I use pip from that virtualenv:

```
.../.virtualenv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

---

EDIT: Installing pyopenssl, ndg-httpsclient, and pyasn1 seems to [fix to this problem](https://github.com/pypa/pip/issues/2681#issuecomment-92546367). Shouldn't virtualenv install these packages along with pip?

**Comment by mkoval** [comment]
Thank you! The `InsecurePlatformWarning` warning was driving me crazy.

The documentation in the [URL included in the error message](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) makes it sound like you would need to add `urllib3.contrib.pyopenssl.inject_into_urllib3()` to `pip` to fix the issue. Thankfully, that is not the case.
