### ISSUE TITLE
path to activation script is different for MacOS and Windows

### ISSUE THREAD

**Issue by alexeyOnGitHub** [pypa/virtualenv#771]
for Windows:
    source venv/Scripts/activate

for MacOS:
    source venv/bin/activate

which means I need to put two commands with comments into all documentation - for Windows please use this, for Mac - that.

plus also have separate build scripts for Windows and MacOS servers. (or "if" statement in them)...

can you please change the scripts location so that it is the same for both Windows and MacOS?
e.g. to ENV_HOME/bin folder

**Comment by pfmoore** [comment]
That is behaviour as designed. The Windows platform has used Scripts for a long time (not just in virtualenv, but also in core Python venv and in distutils going back to pre-Python 2.0 days).

There was some discussion on changing to use "bin" everywhere, but it was decided that this would be too disruptive, as well as being a major backward compatibility break. So it's not likely that this will happen in the foreseeable future.

**Comment by alexeyOnGitHub** [comment]
so... maybe add "bin" there and make "Scripts" to be a link to "bin"?

**Comment by Ivoz** [comment]
> also in core Python venv 

They used that because virtualenv did, to be compatible.

> so... maybe add "bin" there and make "Scripts" to be a link to "bin" (for compatibility purpose)?

Only problem... Windows is *really* bad at symlinking. Generally needs admin priviledges to do so... T_T
