### ISSUE TITLE
PyPy + Windows: "Scripts" -> "bin"

### ISSUE THREAD

**Issue by jedie** [pypa/virtualenv#789]
If you create a virtualenv with PyPy2 under Windows, then you will get a "...env\bin\" directory instead of a "...env\Scripts\" directory... e.g.: https://bitbucket.org/pypy/pypy/issues/2125/tcl-doesnt-work-inside-a-virtualenv-on#comment-21247266

Think the code lines: https://github.com/pypa/virtualenv/blob/1ac8d8c052822879abd67bf4c3dad740830df73d/virtualenv.py#L1016-L1047 contains a wrong if-logic, isn't it?

btw. what's the reason why "bin" is named differently under windows? It comes from the python distribution that use "Scripts" in the windows version. But why?

**Comment by pfmoore** [comment]
> btw. what's the reason why "bin" is named differently under windows? It comes from the python distribution that use "Scripts" in the windows version. But why?

History. It was named that way a long time ago (for reasons lost in the mists of time, I suspect). It was proposed that this be changed, I don't have a reference to hand but it was around the release of Python 3.3 or 3.4 IIRC. But the huge amount of disruption and backward incompatibility that would be caused was considered too large to justify it.

> contains a wrong if-logic, isn't it?

It looks wrong, if PyPy uses "bin" on Windows (which is something I don't know - the code seems to assume that Jython and PyPy both use bin for all platforms). Someone who knows PyPy's behaviour better than I do would need to review this...
