### ISSUE TITLE
RFC: Selective system-site-packages

### ISSUE THREAD

**Issue by The-Compiler** [pypa/virtualenv#792]
With certain packages such as PyQt or the SciPy stack, it's impractical to use them inside a virtualenv for various reasons:
- They might be hard to build, or take a long time to do so
- They use non-standard setup methods (PyQt) which makes it even harder to set them up in a virtualenv.

The obvious solution for this is using `--system-site-packages`, but that provides poor isolation from the system Python install, which I'd like.

The solution I used for PyQt is to write a script, [link_pyqt.py](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/link_pyqt.py) to symlink PyQt into the virtualenv.

I think this could be simplified and generalized a bit, and then maybe included into virtualenv so you could do something like `--system-site-packages=PyQt5,NumPy` and it'd link/copy (depending on the os and 
`--always-copy`) those packages from the system Python into the virtualenv.

What do you think?

/cc @nicoddemus @raoulb

**Comment by raoulb** [comment]
> What do you think?

In principle I really like the idea. I'm not sure how this
would work best on import trees. If package A imports from B
and I say --system-site-packages=A, where does B come from?
Would this be the system-wide version of B or the one inside
virtualenv? Clearly we can get arbitrary large mess with
version number mismatches.

**Comment by nicoddemus** [comment]
In your example, assuming package `B` is a high-level package (iow, is not contained inside `A`), I believe it would use `B` from within the virtual environment. Unless Python import semantics change when using symlinks, this should not be an issue, IIUC.

**Comment by raoulb** [comment]
> I believe it would use `B` from within the virtual environment.

According to the search path I probably should.
In that case I'd have to add it to the list of
system packages. This can grow a long list for
some larger package A.

**Comment by nicoddemus** [comment]
> This can grow a long list for some larger package A.

Hmm I understand, thanks.
