### ISSUE TITLE
global site-packages are available, while they shouldn't be

### ISSUE THREAD

**Issue by compie** [pypa/virtualenv#800]
After creating a new virtualenv (without using the --system-site-packages option), I can still import modules from the system python installation. See the example below.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\jocompen\Downloads\virtualenv-13.1.2>python virtualenv.py --version
13.1.2

C:\Users\jocompen\Downloads\virtualenv-13.1.2>python virtualenv.py myVE
New python executable in myVE\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Users\jocompen\Downloads\virtualenv-13.1.2>myVE\Scripts\activate.bat
(myVE) C:\Users\jocompen\Downloads\virtualenv-13.1.2>python
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy
module 'numpy' from 'C:\Program Files (x86)\Python27\lib\site-packages\numpy\__
init__.py'>
(myVE) C:\Users\jocompen\Downloads\virtualenv-13.1.2>pip list
ipython (0.13.1)
matplotlib (1.2.1)
numpy (1.7.1)
PIL (1.1.7)
pip (7.1.2)
pyreadline (2.0)
pywin32 (218)
scipy (0.12.0)
setuptools (0.6rc11)
virtualenv (1.10)
wheel (0.24.0)
xlrd (0.7.9)
c:\users\jocompen\downloads\virtualenv-13.1.2\myve\lib\site-packages\pip\_vendor
\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLC
ontext object is not available. This prevents urllib3 from configuring SSL appro
priately and may cause certain SSL connections to fail. For more information, se
e https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarnin
g.
  InsecurePlatformWarning

(myVE) C:\Users\jocompen\Downloads\virtualenv-13.1.2>python
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> for p in sys.path: print p
...

C:\Program Files (x86)\Python27
C:\Program Files (x86)\Python27\lib\site-packages
C:\Program Files (x86)\Python27\Lib\site-packages\virtualenv-1.10-py2.7.egg
C:\Program Files (x86)\Python27\lib\site-packages\PIL
C:\Program Files (x86)\Python27\lib\site-packages\win32
C:\Program Files (x86)\Python27\lib\site-packages\win32\lib
C:\Program Files (x86)\Python27\lib\site-packages\Pythonwin
C:\WINDOWS\system32\python27.zip
C:\Users\jocompen\Downloads\virtualenv-13.1.2\myVE\DLLs
C:\Users\jocompen\Downloads\virtualenv-13.1.2\myVE\lib
C:\Users\jocompen\Downloads\virtualenv-13.1.2\myVE\lib\plat-win
C:\Users\jocompen\Downloads\virtualenv-13.1.2\myVE\lib\lib-tk
C:\Users\jocompen\Downloads\virtualenv-13.1.2\myVE\Scripts
C:\Program Files (x86)\Python27\Lib
C:\Program Files (x86)\Python27\DLLs
C:\Program Files (x86)\Python27\Lib\lib-tk
C:\Users\jocompen\Downloads\virtualenv-13.1.2\myVE
C:\Users\jocompen\Downloads\virtualenv-13.1.2\myVE\lib\site-packages
>>>
```

**Comment by Ivoz** [comment]
A) You might want to try installing virtualenv first, through pip. Rather than just unpacking it.

B) Could you try with `python virtualenv.py --no-site-packages myVE` as well?

**Comment by compie** [comment]
Ok, I did what you suggested:
Option A:
easy_install pip
pip install --upgrade virtualenv

C:\Localdata>virtualenv --version
13.1.2

C:\Localdata>virtualenv myVE
New python executable in myVE\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command C:\Localdata\myVE\Scripts\python.exe -c "import s
ys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  The repository located at None is not a trusted or secure host and is being ig
nored. If this repository is available via HTTPS it is recommended to use HTTPS
instead, otherwise you may silence this warning and allow it anyways with '--tru
sted-host None'.
  Could not find a version that satisfies the requirement setuptools (from versi
ons: )
No matching distribution found for setuptools
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "c:\program files (x86)\python27\lib\runpy.py", line 162, in _run_module_
as_main
    "__main__", fname, loader, pkg_name)
  File "c:\program files (x86)\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files (x86)\Python27\scripts\virtualenv.exe\__main__.py", lin
e 9, in <module>
  File "C:\Program Files (x86)\Python27\lib\site-packages\virtualenv.py", line 8
32, in main
    symlink=options.symlink)
  File "C:\Program Files (x86)\Python27\lib\site-packages\virtualenv.py", line 1
004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\virtualenv.py", line 9
69, in install_wheel
    'PIP_NO_INDEX': '1'
  File "C:\Program Files (x86)\Python27\lib\site-packages\virtualenv.py", line 9
10, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Localdata\myVE\Scripts\python.exe -c "import sys, pip; sys..
.d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1

C:\Localdata>

**Comment by compie** [comment]
And option B didn't help either. (I still shows the global python modules).

I will completely remove the old python installation from my PC and install it again. Hopefully that solves my issues.

**Comment by pfmoore** [comment]
Can you check if you have a PYTHONPATH environment variable set?

**Comment by compie** [comment]
I can't check that anymore because I already reinstalled Python (this
solved my issue).
Currently there's no PYTHONPATH environment variable on my PC.


2015-09-20 14:51 GMT+02:00 Paul Moore <notifications@github.com>:

**Comment by Ivoz** [comment]
If there *was* a `PYTHONPATH` set in your previous installation, that very likely would have been the source of trouble. I doubt we can reproduce this now, but glad you're no longer having the issue. Feel free to reopen if you come across the same thing again.
