### ISSUE TITLE
Make use of recent cached setuptools/pip/wheel wheels when creating

### ISSUE THREAD

**Issue by Ivoz** [pypa/virtualenv#801]
Given the presence of https://pip.pypa.io/en/stable/reference/pip_install/#wheel-cache

It might be possible that newer pip & setuptools & wheel wheels could be present there... is it worth trying to discover and use them, in priority of those present in `/virtualenv_support/`?

**Comment by FlipperPA** [comment]
Plus one to this, if possible. My python 3.5 branch of a Vagrant box I maintain currently removes wheel-0.24* from /virtualenv_support/ and copies wheel-0.26 in place, which works, but is ugly. I see that 0.26 is on the develop branch, so thanks for that!

**Comment by tysonclugg** [comment]
+1 on this, as setuptools 18.2 is being installed but doesn't support the python_platform_implementation environment marker which was introduced in setuptools 18.5.
