### ISSUE TITLE
Moved and relocatable virtualenv: pip/python commands require full path

### ISSUE THREAD

**Issue by fredrikaverpil** [pypa/virtualenv#819]
I create a virtualenv, pip install some modules into it, then deactivate and make it relocatable. Finally, I move it to a new location. 

In the new location, it's now not enough to simply activate the virtualenv in order to execute commands such as `pip list` or `python`. Instead, now I have to specify the path leading up to the executable, e.g. `myenv/bin/pip list` or `myenv/bin/python`. If I do not do this, it seems the installed modules are not found and pip cannot list the installed modules properly without errors.

This is on Ubuntu 14.04.3. 

Is this intended behavior?

**Comment by pfmoore** [comment]
No, and it's not what happens in my experience (but that may be because I do something different than what you did). To diagnose your issue we'll need more details as to what commands you ran and what you saw.

**Comment by fredrikaverpil** [comment]
Check out the below:

1. `pip list` to see what is installed on my system, lots of modules
2. Create a virtualenv "myenv"
3. Activate it and perform a `pip list`, which will only return a few modules
4. Dectivate the virtualenv and make it relocatable.
5. Move it to a folder
6. Activate it once again in its new location
7. Run a `pip list` once again, and you'll now see it will return what's on my system (not in the virtualenv).


```bash
fredrik@ubuntudev:~$ pip list
adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
cffi (1.3.0)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
cryptography (1.1)
debtagshw (0.1)
defer (1.0.6)
dirspec (13.10)
duplicity (0.6.23)
enum34 (1.0.4)
html5lib (0.999)
httplib2 (0.8)
idna (2.0)
ipaddress (1.0.14)
lockfile (0.8)
lxml (3.3.3)
ndg-httpsclient (0.4.0)
oauthlib (0.6.1)
oneconf (0.3.7.14.4.1)
PAM (0.4.2)
pexpect (3.1)
Pillow (2.3.0)
pip (7.1.2)
piston-mini-client (0.7.5)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.66)
pygobject (3.12.0)
pyOpenSSL (0.15.1)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
pyxdg (0.25)
reportlab (3.0)
requests (2.8.1)
sessioninstaller (0.0.0)
setuptools (18.5)
six (1.10.0)
software-center-aptd-plugins (0.0.0)
system-service (0.1.6)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
virtualenv (13.1.2)
wheel (0.24.0)
xdiagnose (3.6.3build2)
zope.interface (4.0.5)
fredrik@ubuntudev:~$ virtualenv --always-copy myenv
New python executable in myenv/bin/python
Installing setuptools, pip, wheel...done.
fredrik@ubuntudev:~$ source myenv/bin/activate
(myenv)fredrik@ubuntudev:~$ pip list
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)
(myenv)fredrik@ubuntudev:~$ deactivate
fredrik@ubuntudev:~$ virtualenv --relocatable myenv/
Making script myenv/bin/pip2.7 relative
Making script myenv/bin/wheel relative
Making script myenv/bin/easy_install-2.7 relative
Making script myenv/bin/easy_install relative
Making script myenv/bin/pip2 relative
Making script myenv/bin/pip relative
fredrik@ubuntudev:~$ mkdir my_virtualenvs
fredrik@ubuntudev:~$ mv myenv my_virtualenvs
fredrik@ubuntudev:~$ cd my_virtualenvs/
fredrik@ubuntudev:~/my_virtualenvs$ source myenv/bin/activate
(myenv)fredrik@ubuntudev:~/my_virtualenvs$ pip list
adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
cffi (1.3.0)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
cryptography (1.1)
debtagshw (0.1)
defer (1.0.6)
dirspec (13.10)
duplicity (0.6.23)
enum34 (1.0.4)
html5lib (0.999)
httplib2 (0.8)
idna (2.0)
ipaddress (1.0.14)
lockfile (0.8)
lxml (3.3.3)
ndg-httpsclient (0.4.0)
oauthlib (0.6.1)
oneconf (0.3.7.14.4.1)
PAM (0.4.2)
pexpect (3.1)
Pillow (2.3.0)
pip (7.1.2)
piston-mini-client (0.7.5)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.66)
pygobject (3.12.0)
pyOpenSSL (0.15.1)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
pyxdg (0.25)
reportlab (3.0)
requests (2.8.1)
sessioninstaller (0.0.0)
setuptools (18.5)
six (1.10.0)
software-center-aptd-plugins (0.0.0)
system-service (0.1.6)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
virtualenv (13.1.2)
wheel (0.24.0)
xdiagnose (3.6.3build2)
zope.interface (4.0.5)
```

**Comment by pfmoore** [comment]
Thanks. You mentioned in the title that you were using relocatable, but I missed it.

I suspect that's the issue - ```--relocatable``` isn't something I use, and I believe it has some peculiarities. It didn't mention that it made the activate script relocatable - maybe that's the problem?

**Comment by fredrikaverpil** [comment]
Ah, yes. That is why. I opened the `myenv/bin/activate` script and edited

    VIRTUAL_ENV="/home/fredrik/myenv"

into

    VIRTUAL_ENV="."

...which made `pip list` return the expected list of modules. Everything seems to work properly, but the name of the virtualenv is lost, so my prompt looks like this:

    fredrik@ubuntudev:~$ source myenv/bin/activate
    (.)fredrik@ubuntudev:~$
