### ISSUE TITLE
Hard-linking Python binary results in weird errors on Python upgrades

### ISSUE THREAD

**Issue by wichert** [pypa/virtualenv#821]
Our CI systems starting reporting rather bizar errors this week:

```
local/lib/python2.7/site-packages/webob/cookies.py:6: in <module>
    import hmac
/usr/lib/python2.7/hmac.py:8: in <module>
    from operator import _compare_digest as compare_digest
E   ImportError: cannot import name _compare_digest
```

This turned out to be caused by an upgrade of the system Python from 2.7.6 to 2.7.10. This upgrade changed the `operator` package. Since virtualenv uses a hardlink for the python interpreter this upgrade resulted in our virtualenvs using a Python 2.7.6 binary with the 2.7.10 stdlib. That combination does not work and resulted in the errors we were seeing.

I see two approaches to handling this:
1. use a symlink instead of a hardlink for the Python interpreter so this mismatch can not happen
2. use site.py (or a similar mechanism) to detect version changes in the Python interpreter and abort immediately, telling the user they need to re-create the virtualenv (that might require #776 to be fixed first).

**Comment by dstufft** [comment]
The first option won't work because Python uses the real location of the interpreter to look up the relative path of ``os.py`` which is how we make virtualenv work at all. The second option could work though.
