### ISSUE TITLE
Virtualenv cannot deal with Relocatable OS X Frameworks

### ISSUE THREAD

**Issue by mitsuhiko** [pypa/virtualenv#822]
This is a very frustrating issue but I can only assume nobody has it because OS X Python frameworks come slightly broken out of the box.  If you take a `Python.framework` and unbreak all the binaries and libraries within it to make it relocatable (this means set `@rpath` correctly and reference all libraries relative to `@rpath` and in turn `@executable_path`) you end up with a Python installation you can freely move around on the file system.

Unfortunately you cannot use such an installation to make a virtualenv.  The reason for this is that the python executable within this framework now refers to it's dependencies relatively.  As such it links against `@rpath/Python` which is the main python dylib.  When virtualenv copies out the executable (which I assume is what happens) that library is not copied along and everything falls apart.

I would like to advocate for such builds to become the default but it seems like this will not happen if virtualenv cannot support it.  Right now I'm not sure what the right solution for this issue is.

**Comment by pfmoore** [comment]
As a comparison, do stdlib venvs work as you'd expect?

**Comment by mitsuhiko** [comment]
What are stdlib venvs?

**Comment by pfmoore** [comment]
The venv module introduced in Python 3.3 or so. ```python -m venv FOO``` creates a virtual environment much like virtualenv does. But there's core support for the virtualisation, hence why I'm interested if it works better than virtualenv's approach. See https://docs.python.org/3.5/library/venv.html

**Comment by mitsuhiko** [comment]
I only managed so far to make a relocatable framework for Python 2.7 which is for a project of mine where it came up in the process.  I would need to see how much work that is to do the same for Python 3.  I will try to attempt it on the weekend.

**Comment by pfmoore** [comment]
OK, no problem - if your issue is for 2.X then the core support probably isn't that relevant to the issue.

**Comment by mitsuhiko** [comment]
To be honest, playing with this more, I think this would never work on 2.x any more as such a hypothetical release would break compatibility.  I do wonder though if support for such builds could still land in virtualenv as they are very useful for desktop application distribution.

**Comment by Ivoz** [comment]
I have little experience with OS X applications, in principle until a good reason for

> virtualenv cannot support it.

comes up I wouldn't be a priori against seeing if it could work.

**Comment by gst** [comment]
I think this would be solved by https://github.com/pypa/virtualenv/issues/1019 (which is also solving #1015 )
