### ISSUE TITLE
Please update virtualenv's wheel package to fix building errors on various packages

### ISSUE THREAD

**Issue by ZzAntares** [pypa/virtualenv#835]
Hello, I've been having trouble installing `lxml`, `coverage` and `simplejson` in a virtualenv due to building wheel error, after days of researching I found a solution exposed in this [bug report](https://bugs.launchpad.net/lxml/+bug/1504926) at lxml.

The error explained there can be avoided if using an updated version of `wheel`, in my system I have no problem because I have `wheel==0.26.0` but when inside a virtualenv I always have error's because of the default installed version of wheel `wheel==0.24.0`.

To avoid the error I have to upgrade `wheel` as soon as I create the virtualenv. 

Could anyone help and make that when creating a virtualenv automatically updates all the packages installed within the virtualenv?

Or someone can give me a hand to try to do it my self? Or at least update the `wheel` version packaged within virtualenv?

To clarify this is not a problem with lxml, coverage or simplejson, the problem is in the wheel version.

Thanks

**Comment by pfmoore** [comment]
The new version of wheel is bundled in develop, and will be in the next release of virtualenv. In the meantime, you can replace the ```.whl``` file in the ```virtualenv_support``` directory of your virtualenv installation with the newest wheel from the wheel project.

**Comment by ZzAntares** [comment]
Excelent, I see it was added 4 months ago, every when does virtualenv releases a new version?

Thanks

**Comment by Ivoz** [comment]
Virtualenv 14.x have upgraded to wheel 0.26.x, cheers
