### ISSUE TITLE
Can not create a virtualenv with Python 3.5 on Windows 10

### ISSUE THREAD

**Issue by Tset-Noitamotua** [pypa/virtualenv#837]
```shell
C:\Users\username\Envs>pip --version
pip 7.1.2 from c:\users\username\appdata\local\programs\python\python35-32\lib\site-packages (python 3.5)

C:\Users\username\Envs>pip list
pip (7.1.2)
setuptools (19.1.1)
virtualenv (13.2.0.dev0)
virtualenvwrapper-win (1.2.1)

C:\Users\username\Envs>virtualenv test34
Using base prefix 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python35-32'
New python executable in C:\Users\username\Envs\test34\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command C:\Users\username\En...4\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  Could not find a version that satisfies the requirement setuptools (from versions: )
No matching distribution found for setuptools
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\Scripts\virtualenv-script.py", line 9, in <module>
    load_entry_point('virtualenv==13.2.0.dev0', 'console_scripts', 'virtualenv')()
  File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv-13.2.0.dev0-py3.5.egg\virtualenv.py", line 699, in main
    symlink=options.symlink)
  File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv-13.2.0.dev0-py3.5.egg\virtualenv.py", line 872, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv-13.2.0.dev0-py3.5.egg\virtualenv.py", line 837, in install_wheel
    'PIP_USER': '0'
  File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv-13.2.0.dev0-py3.5.egg\virtualenv.py", line 777, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\username\En...4\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1

C:\Users\username\Envs>
```

**Comment by Ivoz** [comment]
Hi there, would you be able to try with the newest versions now? (pip 8 & virtualenv 14) (`python -m pip install -U pip virtualenv`)

**Comment by jh88680** [comment]
PLEASE SORT OUT THIS PROBLEM, I AM USING WIN 10

C:\Users\TEMP>mkvirtualenv test
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe

**Comment by Novak478** [comment]
I solved this issue by running it as an administrator rather than as my local user.

**Comment by sohaib684** [comment]
> Hi there, would you be able to try with the newest versions now? (pip 8 & virtualenv 14)
> 
> ```
> python -m pip install -U pip setuptools virtualenv
> ```

it helped bro thanks a lot. you saved my good time.@.@
