### ISSUE TITLE
Output bash ./activate script on Windows

### ISSUE THREAD

**Issue by coderanger** [pypa/virtualenv#85]
It would be nice if venv would still output the bash activate script for people using bash (probably through msysgit) on Windows.

**Comment by hjwp** [comment]
+1.  Git-Bash is a really appealing tool to point windows users to when they want to follow along with python tutorials...

**Comment by pfmoore** [comment]
I don't think this is a virtualenv issue - virtualenv does this. If (as the report says) this is related to the stdlib venv module, it should be reported on http://bugs.python.org.

**Comment by hjwp** [comment]
quite right, my apologies.

**Comment by hjwp** [comment]
The issue is here, if anyone is curious:  http://bugs.python.org/issue22343

**Comment by hjwp** [comment]
and i can confirm that the `activate` script that virtualenv outputs works under git-bash (the bash bundled with git on windows).  So I'd say this issue can probably be closed?

**Comment by pfmoore** [comment]
Thanks for the update
