### ISSUE TITLE
Virtualenv activation error

### ISSUE THREAD

**Issue by anistark** [pypa/virtualenv#853]
I installed with python3 and when I tried activating it, 

```
Missing end to balance this if statement
env/bin/activate (line 78): if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
                               ^
from sourcing file env/bin/activate
	called on standard input

source: Error while reading file 'env/bin/activate'
```

Please advise..

**Comment by Ivoz** [comment]
What shell are you using?

**Comment by anistark** [comment]
I'm using fish. Here's a screenshot : 

<img width="1280" alt="screen shot 2016-01-26 at 11 47 08 am" src="https://cloud.githubusercontent.com/assets/5357586/12573791/5eb4880e-c423-11e5-939e-fde3d78aa9ea.png">

**Comment by Ivoz** [comment]
Have you tried activating using the fish script instead?

    source py3env/bin/activate.fish

**Comment by Ivoz** [comment]
As a follow up, what documentation did you read prior to using virtualenv? I'm wondering if there are any pertinent places that could address that different shell users might need to run a different shell script.

**Comment by anistark** [comment]
Thanks @Ivoz I followed [this one](https://virtualenv.readthedocs.org/en/latest/userguide.html)

**Comment by Ivoz** [comment]
Thanks, I made a [note](https://github.com/pypa/virtualenv/commit/1d1f1de70e822892c92748ef5da150deee6c081e) to help.

**Comment by anistark** [comment]
Oops @Ivoz I thought I'll add it to the doc file myself and created [this PR](https://github.com/anistark/virtualenv/pull/1)

Shall I close it?

**Comment by Ivoz** [comment]
Yes, thanks for the thought.

**Comment by rishabhiitbhu** [comment]
How does shell matter in this case?

**Comment by Ivoz** [comment]
Which shell you are executing an activate script with (using the `source` command, typically), determines what syntax that activate script needs to be written in.

**Comment by Ruoh3kou** [comment]
> Which shell you are executing an activate script with (using the `source` command, typically), determines what syntax that activate script needs to be written in.

thank you a lot for solving my problem
