### ISSUE TITLE
os.path.normcase causing problems

### ISSUE THREAD

**Issue by atx7** [pypa/virtualenv#857]
virtualenv 14.0.2 changed the following line in 'virtualenv.py':
```
filename = os.path.normcase(os.path.abspath(filename))
```
to
```
filename = os.path.abspath(filename)
```

This causes 'C:\env> virtualenv x' to give error:

> ERROR: The executable C:\env\x\Scripts\python.exe is not functioning
> ERROR: It thinks sys.prefix is u'c:\\\\env' (should be u'c:\\\\env\\\\x')
> ERROR: virtualenv is not compatible with this system or executable

I have 32bit Python 2.7 installed on 64bit Windows

Is it safe to change it back?

**Comment by matthussey** [comment]
Breaks for me too. Virtualenv no lkonger works on windows. 64bit 27 on 64 bit windows.

**Comment by xflr6** [comment]
Same here (Python 2.7, Win7): `14.0.1` works, `14.0.2` and `14.0.3` fail with this error.

**Comment by Ivoz** [comment]
14.0.4 should be out which should fix this
