### ISSUE TITLE
The -p N.M shortcut doesn't work for Python 3.5 on Windows

### ISSUE THREAD

**Issue by pfmoore** [pypa/virtualenv#864]
The `--python` command line can take an abbreviated interpreter name. On Unix this is one of the versioned alias names (`python2.7`, `python3`, ...) and is looked up on `PATH`.

On Windows the versioned names don't exist so the registry is searched for the Python version specified. So, `-p 2.7` finds the location of Python 2.7 in the registry and uses that.

However, the registry layout is not well documented, and is complex (user installs, 32-bit vs 64-bit). It also seems to have changed in Python 3.5, and `-p 3.5` does not work. Rather than attempt to fix this, though, I propose that the feature be marked as deprecated, and left as it stands. It's not clear that it was ever widely used.

People wanting to use an abbreviated interpreter name would be better to run `py -N.M -m virtualenv` (assuming virtualenv is installed under Python N.M) or `py -N.M C:\path\to\virtualenv` to run a standalone copy of virtualenv. This uses the (fully supported) Python launcher to select the required Python version.

**Comment by Ivoz** [comment]
+1, never even knew that was a thing.

**Comment by pfmoore** [comment]
IIRC, it's a thing because I added it because I was too lazy to type in the full interpreter. Then  I never actually used it. Go figure.

Yeah, I'll see if I can work up a proper deprecation note. For now, I mainly raised the issue so we had somewhere that said "it's broken and not going to get fixed" to justify me skipping the test I just added for the feature :-)

**Comment by jurko-gospodnetic** [comment]
@asottile - this is actually important for your `pre-commit` project as it wants to be able to easily request a specific Python version to run a pre-commit hook, but does not want to duplicate the effort of detecting the installed Python executable location.
