### ISSUE TITLE
Problems creating virtualenv on Windows when Python is not installed for all users.

### ISSUE THREAD

**Issue by carljm** [pypa/virtualenv#87]
I'm not a Windows user, so I could be missing something, but this is what I'm seeing (ran into it trying to get the pip test suite running on Windows):

S:>virtualenv --no-site-packages blah
New python executable in blah\Scripts\python.exe
ERROR: The executable blah\Scripts\python.exe is not functioning
ERROR: It thinks sys.prefix is 'c:\python25' (should be 's:\blah')
ERROR: virtualenv is not compatible with this system or executable

S:>c:

C:>virtualenv --no-site-packages yo
New python executable in yo\Scripts\python.exe
Installing setuptools..............done.

Stefano Masini wrote on 2009-12-03:

I had the same problem.
I fixed it by reinstalling Python2.6. The difference is that the first time (when virtualenv didn't work) I had installed it with the option "Only for this user", while the next time (when it worked) I reinstalled Python with the option "For all users".

Ian Bicking wrote on 2009-12-03:

I've put in an extra error message on Windows when this occurs, suggesting that the user install Python for all users, and pointing them at this bug.

Robert Myers wrote on 2010-03-15:

The problem is that the pythonXX.dll is missing when you install for 'only this user'. Copying the correct dll into the virtual env scripts folder fixes this issue.

Anywhere before the test "[py_executable, '-c', 'import sys; print sys.prefix']" place the lines:

```
# Fix python on windows if installed for 'only this user'
if sys.platform == 'win32':
    # Windows 'may' be installed for 'Only this user' so lets fix it and try again.
    python_dll = os.path.join(os.path.dirname(sys.executable),
        'python%s%s.dll' % (sys.version_info[0], sys.version_info[1]))
    if os.path.isfile(python_dll):
        shutil.copyfile(python_dll, os.path.join(os.path.dirname(py_executable),
            'python%s%s.dll' % (sys.version_info[0], sys.version_info[1])))
```

Torsten Knodt wrote on 2010-07-27:

I have a Python 2.5.1 installation made by a Windows software into C:\Program Files\Common Files...\Python25. The python25.dll is in C:\WINNT\SYSTEM32 so I guess it's a installation for "All users" but virtualenv bails out with the error messages described in this bug.

Any suggestions?

**Comment by rahulrajaram** [comment]
In my case, the source of the problem was in not setting Python environment variables correctly. I got it to work by reinstalling both versions of Python (2.7.14 and 3.6.4) expect I checked the "Set environment variables" checkbox this time.

**Comment by jh88680** [comment]
KINDLY HELP TO SORT OUT THIS PROBLEM,I ALREADY FORMATTED MY MACHINE AND INSTALL AGAIN, I AM USING WINDOWS 10 PRO

C:\Users\TEMP>mkvirtualenv test
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
Running virtualenv with interpreter c:\users\temp\appdata\local\programs\python\python37-32\python.exe
