### ISSUE TITLE
virtualenv won't activate on non-primary nodes when using qsub

### ISSUE THREAD

**Issue by kilojoules** [pypa/virtualenv#878]
When I activate a virtualenv (openmdao 0.13 in this example) through qsub, it is only activated on the primary node. Here, you can see the virtualenv works fine on my primary node, but fails on all processors on the secondary node. Does anyone have an idea what could be causing this odd behavior?

    $ qsub -V -I -l nodes=2:ppn=24
    
    $ cd openmdao-0.10.3.2/
    
    $ . bin/activate
    
    $ mpirun -np 24 python -c "import openmdao"
    
    # no errors
    
    $ mpirun -np 30 python -c "import openmdao"
    
    Traceback (most recent call last):
    
      File "<string>", line 1, in <module>
    
    Traceback (most recent call last):
    
      File "<string>", line 1, in <module>
    
    Traceback (most recent call last):
    
      File "<string>", line 1, in <module>
    
    Traceback (most recent call last):
    
      File "<string>", line 1, in <module>
    
    Traceback (most recent call last):
    
      File "<string>", line 1, in <module>
    
    Traceback (most recent call last):
    
      File "<string>", line 1, in <module>
    
    ImportError: No module named openmdao
    
    ImportError: No module named openmdao
    
    ImportError: No module named openmdao
    
    ImportError: No module named openmdao
    
    ImportError: No module named openmdao
    
    ImportError: No module named openmdao

**Comment by Ivoz** [comment]
Note that `activate` only modifies the current shell environment.

If you wish to run a certain virtualenv python, you can just run its path directly-

    $ cd openmdao-0.10.3.2/
    $ mpirun -np 30 ./bin/python -c "import openmdao"

**Comment by kilojoules** [comment]
@Ivoz This didn't work for me. I need to have the virtualenv activated to import the package at all.

# error without activation
$ bin/python -c "import openmdao"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named openmdao

$ . bin/activate
$ bin/python -c "import openmdao"
# no error

**Comment by Ivoz** [comment]
try looking at `sys.path` before and after `. ./bin/activate`

If the difference is making the the difference between whether or not it's installable, then either A) openmdao isn't installed properly or B) the virtualenv is somehow broken.

**Comment by kilojoules** [comment]
@Ivoz `mpirun -np 27 python -c "import sys; "print sys.path"` shows the same series of paths printed out 27 times

**Comment by Ivoz** [comment]
Have you tried deleting and recreating the virtualenv?

**Comment by kilojoules** [comment]
Yes. I rebuilt openmdao in the qsub session and this did not help.

Best,
Julian

**Comment by kilojoules** [comment]
Activating the virtualenv before starting the qsub job fixed this for me

**Comment by Ivoz** [comment]
Sorry, I couldn't think of anything else to try in the stead of being able to sit down at your terminal and tinker, and I don't have any experience with qsub :/
