### ISSUE TITLE
activate.fish sets prompt to mostly white on white.

### ISSUE THREAD

**Issue by gillham** [pypa/virtualenv#884]
Commit 22d7773 does this:
(set_color normal) (set_color -o white) (basename "$VIRTUAL_ENV") (set_color normal)

Previous versions used 'set_color -b blue white' for example.  On OSX Terminal.app uses black on white and this prompt ends up being nearly invisible.   Configuring iTerm for black on white and it is invisible.
Other platforms / terminal emulators might use white on black as well and this color setting doesn't work too well as a default.

I think you should switch back to using a color scheme that doesn't make invisible text on an OS's default settings. (white on blue is unlikely to be invisible with any default installs)  Or make this a tunable so it isn't necessary to modify files installed with a package manager.

**Comment by Ivoz** [comment]
Perhaps it's easiest just removing all coloring all together. For now you can override virtualenv's prompt modification by setting the `$VIRTUAL_ENV_DISABLE_PROMPT` variable in your environment, and doing your own if you like.
