### ISSUE TITLE
Virtualenv created with python 3 still installing in and using system python 2

### ISSUE THREAD

**Issue by crdoconnor** [pypa/virtualenv#890]
This occurs on a Mac with a recently upgraded (with brew) python, python3 and a recently upgraded (with pip) virtualenv and pip::

    virtualenv venv --python=python3
    ./venv/bin/pip install pyyaml
    Requirement already satisfied (use --upgrade to upgrade): PyYAML in /Library/Python/2.7/site-packages

Note that it tried to update the system python2 PyYaml.

    User:test user$ ./venv/bin/python
    Python 3.5.1 (default, Apr 5 2016, 21:27:05)
    [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.

            import yaml
            Traceback (most recent call last):
            File "", line 1, in
            File "/Library/Python/2.7/site-packages/yaml/init.py", line 2, in
            from error import *
            ImportError: No module named 'error'

The python 3 code is trying to import python 2 from the system.

Is there anything that you know of that might be causing this python 2 / 3 crossover problem?

**Comment by hardkrash** [comment]
Did you activate your virtual environment?

e.g.
`source env/bin/activate`

**Comment by Ivoz** [comment]
@crdoconnor do you have any thing in `PYTHONPATH` env variable?

**Comment by mimischi** [comment]
The referenced issue above is resolved. It was some kind of weird thing with my local python installation. Solved it here https://github.com/hitchtest/hitch/issues/28#issuecomment-234770507.
This issue can thus be closed now.

**Comment by pfmoore** [comment]
Thanks for letting us know,
