### ISSUE TITLE
--relocatable seems not do it work right

### ISSUE THREAD

**Issue by Shellbye** [pypa/virtualenv#930]
I use the `--relocatable` relocated my env,  and than I moved my env, but after that, my `pip freeze` always git the global list, not the list in the env. I fixed this error by the guide of [this](http://stackoverflow.com/questions/20952797/pip-installing-in-global-site-packages-instead-of-virtualenv) question's accepted answer by modifing the line 42 of bin/active, which still is the old path of the env.

**Comment by sanyer** [comment]
Check this one out https://github.com/pypa/virtualenv/issues/558 and this is from the documentation:
`Note: scripts which have been made relocatable will only work if the virtualenv is activated, specifically the python executable from the virtualenv must be the first one on the system PATH. Also note that the activate scripts are not currently made relocatable by virtualenv --relocatable.`

**Comment by arizvisa** [comment]
Adding a reference to the newest issue #1067 related to this to help consolidate efforts on solving this half-decade old problem with the activation scripts.
