### ISSUE TITLE
Getting subprocess error with return code -9 when running virtualenv.py in openwrt

### ISSUE THREAD

**Issue by sebpiq** [pypa/virtualenv#934]
Hi!

I am trying to setup a virtualenv in openwrt, on a USB stick which has one _ext4_ partition. 
I haven't actually installed virtualenv (didn't run `setup.py`), I have just cloned the source code to the stick which is then mounted at `/mnt/SEBKEY/` on the openwrt router. When I try to run `python virtualenv.py /mnt/SEBKEY/env` I get the following error :  

```
New python executable in /mnt/SEBKEY/env/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /mnt/SEBKEY/env/bin/python - setuptools pip wheel:
  Collecting setuptools
  Using cached setuptools-23.0.0-py2.py3-none-any.whl
Collecting pip
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "virtualenv.py", line 2316, in <module>
    main()
  File "virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "virtualenv.py", line 941, in create_environment
    download=download,
  File "virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /mnt/SEBKEY/env/bin/python - setuptools pip wheel failed with error code -9
```

The strange thing is that the exact same operation used to work 2 months ago. It was a different USB stick and probably different versions of the code, or libs, but unfortunately I cannot recover these...
Couldn't get any answer from google, and couldn't figure out what this `-9` return code means. Any help would be greatly appreciated :)

**Comment by zyfworks** [comment]
Maybe memory wasn't enough.
