### ISSUE TITLE
virtualenv doesn't work on case sensitive Windows file systems

### ISSUE THREAD

**Issue by perlun** [pypa/virtualenv#935]
Background: I have my Windows set up using a case sensitive file system. (an HFS+ file system from the Mac which is formatted as case sensitive, since I prefer it like that for my `git` working copy. It's being shared with Windows using Parallels.)

Now, I was trying to use Python and virtualenv but I noted that it doesn't really cope with this scenario:

```
$ virtualenv foo
New python executable in V:\temp\foo\Scripts\python.exe
Installing setuptools, pip, wheel...done.

$ ls -l foo
total 0
drwxr-xr-x 1 plundberg Domain Users 0 Jun 11 19:51 Include
drwxr-xr-x 1 plundberg Domain Users 0 Jun 11 23:17 lib
drwxr-xr-x 1 plundberg Domain Users 0 Jun 11 23:17 Lib
drwxr-xr-x 1 plundberg Domain Users 0 Jun 11 23:17 Scripts
drwxr-xr-x 1 plundberg Domain Users 0 Jun 11 23:17 tcl
```

Note. I get _both_ a `lib` folder and a `Lib` folder. Let's see what we have in them:

```
$ ls -l foo/lib
total 686
-rw-r--r-- 1 plundberg Domain Users  19314 Nov  2  2015 _abcoll.py
-rw-r--r-- 1 plundberg Domain Users  25164 Jun 11 23:17 _abcoll.pyc
-rw-r--r-- 1 plundberg Domain Users   6115 Nov  2  2015 _weakrefset.py
-rw-r--r-- 1 plundberg Domain Users   9438 Jun 11 23:17 _weakrefset.pyc
-rw-r--r-- 1 plundberg Domain Users   7330 Nov  2  2015 abc.py
-rw-r--r-- 1 plundberg Domain Users   6088 Jun 11 23:17 abc.pyc
-rw-r--r-- 1 plundberg Domain Users  37208 Nov  2  2015 codecs.py
-rw-r--r-- 1 plundberg Domain Users  36372 Jun 11 23:17 codecs.pyc
-rw-r--r-- 1 plundberg Domain Users   7001 Nov  2  2015 copy_reg.py
-rw-r--r-- 1 plundberg Domain Users   5058 Jun 11 23:17 copy_reg.pyc
drwxr-xr-x 1 plundberg Domain Users      0 Jun 11 23:17 distutils
drwxr-xr-x 1 plundberg Domain Users      0 Jun 11 23:17 encodings
-rw-r--r-- 1 plundberg Domain Users   3435 Nov  2  2015 fnmatch.py
-rw-r--r-- 1 plundberg Domain Users   3584 Jun 11 23:17 fnmatch.pyc
-rw-r--r-- 1 plundberg Domain Users   3314 Nov  2  2015 genericpath.py
-rw-r--r-- 1 plundberg Domain Users   3462 Jun 11 23:17 genericpath.pyc
-rw-r--r-- 1 plundberg Domain Users   4166 Nov  2  2015 linecache.py
-rw-r--r-- 1 plundberg Domain Users   3242 Jun 11 23:17 linecache.pyc
-rw-r--r-- 1 plundberg Domain Users 101474 Dec  5  2015 locale.py
-rw-r--r-- 1 plundberg Domain Users  54924 Jun 11 23:17 locale.pyc
-rw-r--r-- 1 plundberg Domain Users      0 Jun 11 23:17 no-global-site-packages.txt
-rw-r--r-- 1 plundberg Domain Users  19981 Nov  2  2015 ntpath.py
-rw-r--r-- 1 plundberg Domain Users  13020 Jun 11 23:17 ntpath.pyc
-rw-r--r-- 1 plundberg Domain Users     11 Jun 11 23:17 orig-prefix.txt
-rw-r--r-- 1 plundberg Domain Users  26652 Nov  2  2015 os.py
-rw-r--r-- 1 plundberg Domain Users  25434 Jun 11 23:17 os.pyc
-rw-r--r-- 1 plundberg Domain Users  14364 Nov  2  2015 posixpath.py
-rw-r--r-- 1 plundberg Domain Users  11305 Jun 11 23:17 posixpath.pyc
-rw-r--r-- 1 plundberg Domain Users  13763 Nov  2  2015 re.py
-rw-r--r-- 1 plundberg Domain Users  13308 Jun 11 23:17 re.pyc
-rw-r--r-- 1 plundberg Domain Users  27543 Jun 11 23:17 site.py
-rw-r--r-- 1 plundberg Domain Users  23697 Jun 11 23:17 site.pyc
-rw-r--r-- 1 plundberg Domain Users    397 Nov  2  2015 sre.py
-rw-r--r-- 1 plundberg Domain Users  20413 Nov  2  2015 sre_compile.py
-rw-r--r-- 1 plundberg Domain Users  12484 Jun 11 23:17 sre_compile.pyc
-rw-r--r-- 1 plundberg Domain Users   7460 Nov  2  2015 sre_constants.py
-rw-r--r-- 1 plundberg Domain Users   6170 Jun 11 23:17 sre_constants.pyc
-rw-r--r-- 1 plundberg Domain Users  29745 Nov  2  2015 sre_parse.py
-rw-r--r-- 1 plundberg Domain Users  19837 Jun 11 23:17 sre_parse.pyc
-rw-r--r-- 1 plundberg Domain Users   1938 Nov  2  2015 stat.py
-rw-r--r-- 1 plundberg Domain Users   2701 Jun 11 23:17 stat.pyc
-rw-r--r-- 1 plundberg Domain Users   2180 Nov  2  2015 types.py
-rw-r--r-- 1 plundberg Domain Users   2690 Jun 11 23:17 types.pyc
-rw-r--r-- 1 plundberg Domain Users   7273 Nov  2  2015 UserDict.py
-rw-r--r-- 1 plundberg Domain Users   9486 Jun 11 23:17 UserDict.pyc
-rw-r--r-- 1 plundberg Domain Users  15170 Nov  2  2015 warnings.py
-rw-r--r-- 1 plundberg Domain Users  13499 Jun 11 23:17 warnings.pyc

$ ls -l foo/Lib
total 0
drwxr-xr-x 1 plundberg Domain Users 0 Jun 11 23:17 site-packages
```

Needless to say, the newly created virtualenv will not work correctly; it will not locate its Python modules etc., likely because it looks in the wrong folder.

I started looking into fixing it, but I'm actually quite unsure of what the proper fix is. There is logic in `virtualenv.py` that sets up Lib, Include and Scripts with an initial upper-case letter: https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L981. I don't fully know the background to this, but it seems to have been introduced around 2007: https://github.com/pypa/virtualenv/commit/993ba1316a83b760370f5a3872b3f5ef4dd904c1

Anyway, what I think we should do is to definitely try to make it work on case sensitive machines as well, and I'm willing to help (since I have my `git` folder set up like that).

My gut feeling would be that a KISS approach here is to just use the same folder structure everywhere. I mean, why make it different? Let all platforms use lower case for these folders, in the virtualenv. That makes our code simpler, and it makes it more homogeneous as well. The risk of breaking things for people is small, since 99% of all Windows users use case insensitive anyway. (and for the rest of us, it's already broken...) Having that said, I'm very much a noob when it comes to both Python and virtualenv so I can only comment from a general standpoint; I don't know all the details or the history behind the decisions.

What do you think? What would be the best way to get this fixed?

**Comment by yan12125** [comment]
+1 Got the same problem on a shared Samba folder.

**Comment by Ivoz** [comment]
I think combining https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L1178-L1181 will fix it

**Comment by perlun** [comment]
@Ivoz - and using `lib` in both cases? Or how do you suggest?

**Comment by gaborbernat** [comment]
@cdjc different platforms have different rules how a python installation works (true ideally we would want it the same, but can't have that now, backwards compatibility)

**Comment by cdjc** [comment]
@gaborbernat You are right regarding backwards compatibility, but it is still possible to make virtualenv on windows not be broken on case-sensitive filesystems without sacrificing compatibility: Simply be consistent about how to spell "Lib" on windows.

**Comment by gaborbernat** [comment]
Keep it open.

**Comment by marcostorto** [comment]
this issue cause havoc when trying to create a virtualenv inside a folder created by WSL, which sets case sensitive filesystem as default (see [https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/])

**Comment by gaborbernat** [comment]
I think the rewrite branch should have fixed this so please test it.
