### ISSUE TITLE
Uses the global pip and Python interpreter instead of the local one.

### ISSUE THREAD

**Issue by Timmate** [pypa/virtualenv#942]
Windows 10, Python 3.5.2, virtualenv 15.0.2. I use administrator account. Maybe it counts.
Any ideas, how to handle this?
I can create new path in PATH to the created venv but I thougth virtualenv or -m venv should handle this for me.
Sorry, maybe it's a dumb question but I did not find any answers on it.
Thank you.
![image](https://cloud.githubusercontent.com/assets/17045930/16984257/a5db3708-4e81-11e6-851d-40dfbc2f25ee.png)

**Comment by dholth** [comment]
Do you want to run C:\path\to\python35\scripts\pip.exe to see those packages?

**Comment by Timmate** [comment]
@dholth 
Yep! That is. But when I use activated virtual environment, I suppose, none of this packages should appear as new pip is used.

**Comment by dholth** [comment]
I'm afraid this is expected behavior for pip.

**Comment by pfmoore** [comment]
Can you do ```echo %PATH%``` to show what the search path is after you activated the venv? It looks like you're getting the system pip, not the one from the venv - which suggests a PATH issue. Also, could you run ```pip --version``` to confirm where you're getting the "pip" command from?

You're right, ```activate``` should put the executables from the venv in your PATH.

**Comment by Timmate** [comment]
@pfmoore 
Your idea to call `echo %PATH%`  was good!
It seems that my user account's name caused a problem to virtualenv as it's written with cyrillic symbols. I tried to create new account using name written with latin symbols and it worked!
Huge thanks!
![Uploading path_echo.png…]()
`

**Comment by pfmoore** [comment]
Glad you got things working. It's quite possible there is a bug in here worth fixing - my suspicion is that the ```activate.bat``` script is being written by virtualenv with the wrong encoding. It's going to be tricky to reproduce or fix, as I don't have a non-ASCII environment to test things on, and I'd need to research the precise details of Windows codepage handling.

If you're interested in helping out with a fix to the underlying problem, please reopen this issue, and post a copy of your activate.bat file, and I'll try to work on a fix you can test.

**Comment by pfmoore** [comment]
@Timmate if you're interested in testing it, I've just uploaded PR #943 which should fix your issue. You need to recreate your virtualenv, so that the ```activate.bat``` file gets rebuilt, but the rebuilt version should have your account name in the correct encoding.

If your account name isn't representable in the OEM (console) encoding, then the PR will cause the creation of the ```activate.bat``` file to fail with an encoding error. That needs fixing, but I'm not sure how, as there's no way the bat file can work in that case. But I'd appreciate knowing if the basic approach works.

**Comment by Timmate** [comment]
@pfmoore 
Hello again! Sorry for a late reply.
Wow, your approach with changing encoding to UTF-8 works well! 
Photo 1) Before.
Photo 2) After.
Thank you! 
![virtualenv_issue](https://cloud.githubusercontent.com/assets/17045930/17107196/f5cccb6e-5296-11e6-930e-1601cfd941d4.png)
![pfmoore_commit](https://cloud.githubusercontent.com/assets/17045930/17107203/f8ac6060-5296-11e6-9beb-e906faab4089.png)

**Comment by pfmoore** [comment]
Great, thanks for testing. I'll try to work out what to do about non-encodable characters, and then merge the change in. So hopefully this won't be an issue in the next version of pip.
