### ISSUE TITLE
Doesn't work with single-user python3.5 on Windows

### ISSUE THREAD

**Issue by davaya** [pypa/virtualenv#952]
On windows 7 with Python 3.5 installed for a single user (in c:\users\username\appdata\local\programs\python\python35), virtualenv fails with the message:

"virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for "only this user" or have multiple versions of python installed.  Copying the appropriate pythonxx.dll to the virtualenv scripts directory may fix this problem."

So virtualenv understands that there is a problem, but misdiagnosed the cause.  The py35\Scripts directory contains python.exe, pythonw.exe, and python35.dll.  It does not contain activate.bat or any other files.  Not surprisingly, trying to run py35\python.exe directly without an activate fails with a missing VCRUNTIME140.dll.

The same installation of virtualenv created a py27 environment with no problems from c:\python27.

**Comment by pfmoore** [comment]
Can you provide the virtualenv version? The command works for me with the same setup and virtualenv 15.0.3. Does your username have any non-ASCII characters or spaces in it?

**Comment by davaya** [comment]
My username was "dev".  I wound up manually copying the msvcrt dll from the python 3.5.1 directory into \windows\system32 and things seemed to work after that.  So I suspect that some path was not properly set to find the C runtime, even though it was present in the virtual environment directory.  When I get back to that machine I'll try deleting the dll from system32 and see if the problem can be reproduced.

Dave

-----Original Message-----
