### ISSUE TITLE
"python" command not found

### ISSUE THREAD

**Issue by LotosikRa** [pypa/virtualenv#963]
I'm using Win10 and PyCharm2016.2 .
I have python 3.4 which isn't registered in PATH.

Once I have created venv using PyCharm and succesful installed some libraries (using PyCharm again). But then I open cmd, succesful activate venv and type ˋpythonˋ, but cmd return to me error: ˋ"python" command not foundˋ. Then I have checked same command with deactivated venv and get the same error. 

I know how to make python avialable to be called from cmd in my system, but how to do this in virtual environment?

**Comment by pfmoore** [comment]
> then I open cmd, succesful activate venv and type ˋpythonˋ, but cmd return to me error: ˋ"python" command not foundˋ

That doesn't sound like you successfully activated the venv. You'll need to explain exactly what you did when activating the venv (I assume you ran the activate.bat script from the venv?) to confirm that it's not user error, but assuming it isn't, I'd question whether PyCharm is doing something wrong here.

It would be much easier to diagnose the issue if you could reproduce it without needing PyCharm.

But I'd suggest you provide a transcript of your CMD session. What did you run to activate the venv? What response did you get? What Python command did you run and again what was the exact error? Can you also show the output of ```echo %PATH%``` before and after activating the venv, as it looks like the venv wasn't correctly added to PATH.
