### ISSUE TITLE
pip install on macOS venv returns SSL CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jdandrea** [pypa/virtualenv#964]
Using virtualenv 15.0.3, python 2.7.12, pip 8.1.2, wheel 0.30.0.a0, and setuptools 18.5.

Note: If I try installing _without_ a venv it works, no SSL issues. Hence I wanted to check here in case there might be an issue related to `virtualenv`.

```
$ virtualenv tester
Installing setuptools, pip, wheel...done.
$ . tester/bin/activate
(tester) $ cd PROJECT
(tester) $ pip install -e .
Obtaining file:///Users/jdandrea/projects/MyProject
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pbr/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for pbr>=1.8
    Traceback (most recent call last):
    ......
```

See also: The [full traceback](http://paste.ofcode.org/U8VXXzLtHwuy8mnyq4Hyy2).

virtualenv 14.0.6 reportedly [solved an SSL issue regarding certs](https://github.com/pypa/virtualenv/commit/063ce7be8a54601d016b71f3c88d0627ddf49913). Maybe this is a different/new issue? Unsure.

**Comment by jdandrea** [comment]
Interesting. I just discovered that, if I install `pbr` manually _first_, then `pip install -e .` works without complaint.

I double checked this with a brand new venv too:

```
# go to project directory
$ pip install -e .
Obtaining file:///Users/jdandrea/projects/myproject
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pbr/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for pbr>=1.8
    Traceback (most recent call last):
    ......
$ pip install pbr>=1.8
$ pip list | grep pbr
pbr (1.10.0)
$ pip install -e
# everything installs, zero errors
```

I noticed everything was coming from cache though, so I recreated the venv and tried again using `--no-cache-dir`. It still failed unless I installed pbr separately as a first step, that is:

```
$ pip install --no-cache-dir 'pbr>=1.8'
Collecting pbr>=1.8
  Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB)
  ......
Installing collected packages: pbr
Successfully installed pbr-1.10.0
$ pip install --no-cache-dir -e .
# everything installs, zero errors
```

**Comment by jdandrea** [comment]
Problem solved! Not a virtualenv issue.

As I'm also using MacPorts, following [this step](http://andatche.com/blog/2012/02/fixing-ssl-ca-certificates-with-openssl-from-macports/) solved it straight away.

**Comment by predatorian3** [comment]
So you just had to install an actual ca-bundle into Python, or tell your OS to use a newer one?
