### ISSUE TITLE
Some builtin module not found

### ISSUE THREAD

**Issue by wd** [pypa/virtualenv#965]
After create a virtual environment use `virtualenv --always-copy VENV`, and copy the VENV dir to an other computer, I found some builtin module haven't been include in the package, like traceback, urllib, cgi etc. Am I miss something? How to make an environment include all the builtin modules?

**Comment by pfmoore** [comment]
Copying a virtualenv directory to another system isn't really a supported option, so I'd have to say it's not entirely surprising if it breaks.

Having said that, could you provide full details of the 2 systems (OS, what Python version(s) are installed, which Python you used to build the virtualenv, etc), and a complete transcript of what you did, including the errors you received? It's possible then that someone might be able to offer some help (or an explanation of why what you're trying to do won't work).

**Comment by wd** [comment]
The 2 system is the same OS and Arch, and I'm trying to deploy my code to production, at first I thought I can copy the whole directory to that system, there is no python installed on that system. Seems I made a serious miss understand about this?

**Comment by pfmoore** [comment]
You have definitely misunderstood. Virtualenv creates an isolated Python environment, but it does need the base Python installation you created the virtualenv from. So copying to a system with no Python definitely won't work.

**Comment by wd** [comment]
I see, thanks for your reply.
