### ISSUE TITLE
request --user-packages option as alternative to --site-packages

### ISSUE THREAD

**Issue by tutalk** [pypa/virtualenv#971]
Hi,

I have a request, an alternative to --site-packages: --user-packages.

 I think it would be nice to be able `pip install --user` any packages (such as Ipython, linters, etc), which I want to have access to globally, and if I pass this new option when creating a virtualenv have access to them.

This would be a nice alternative to --site-packages,  as one can have total control over what is installed in their user packages dir, while they may not have control over the system's packages or wish to access everything which is installed globally.

While, I've found that I can have access to packages installed in ~/.local/lib/<python_version>/site-packages by setting PYTHONPATH, it would be nice if the activate script would add ~/.local/bin to PATH *after* the venv's path. so that console scripts installed in the user package dir, such as ipython, would be found.

Just a thought,

-Scott

**Comment by piotr-dobrogost** [comment]
> (...) it would be nice if the activate script would add ~/.local/bin to PATH after the venv's path

Normally you should have `~/.local/bin` already added to PATH (in some startup script). As venv's path is being added in front of PATH the end result is what you want.
