### ISSUE TITLE
ImportError while using py.exe instead of python.exe

### ISSUE THREAD

**Issue by wdhwg001** [pypa/virtualenv#979]
```log
(venv) PS C:\Users\wdhwg001\study> py hello.py
Traceback (most recent call last):
  File "hello.py", line 5, in <module>
    from flask import Flask
ImportError: No module named 'flask'
```

```log
(venv) PS C:\Users\wdhwg001\study> py -m pip show flask
Name: Flask
Version: 0.11.1
Summary: A microframework based on Werkzeug, Jinja2 and good intentions
Home-page: http://github.com/pallets/flask/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: c:\users\wdhwg001\study\venv\lib\site-packages
Requires: click, Werkzeug, itsdangerous, Jinja2
```

```log
(venv) PS C:\Users\wdhwg001\study> python hello.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

```log
(venv) PS C:\Users\wdhwg001\study> py
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, os
>>> os.path.dirname(sys.executable)
'C:\\Users\\wdhwg001\\study\\venv\\Scripts'
>>> from flask import Flask
>>> app = Flask(__name__)
>>> @app.route('/')
... def hello_world():
...   return 'hello world!'
...
>>> app.run()
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
>>>
```

I'm wondering how does this happened?

I only installed flask in a python3 virtualenv, and here is hello.py:

```python
#! /usr/bin/env python3

""" A hello-world Flask server. """

from flask import Flask
app = Flask(__name__)


@app.route('/')
def hello_world():
    """ Hello World! """
    return 'Hello World!'

if __name__ == '__main__':
    app.run()
```

**Comment by pfmoore** [comment]
This is because of how the launcher (```py.exe```) behaves. The documentation at https://docs.python.org/3.6/using/windows.html#shebang-lines says that ```#!/usr/bin/env python3``` is a valid shebang, and it runs Python 3, but will search ```PATH``` before using the default Python 3 version. The problem is that there's no "python3" command on ```PATH``` (Windows doesn't use the versioned names) so the ```PATH``` search will fail, and you'll get the default version of Python 3, which will be the system install, *not* your virtualenv.

I agree this is somewhat confusing, and it may even be that it's not what "should" happen (although it's difficult to think how else it could behave, given that there's no way short of running it to tell what version a given ```python.exe``` is). But it is behaving as documented.

If you want to query the behaviour of ```py.exe```, you should raise an issue on ```bugs.python.org``` (and link back to this issue for context) but there's no pip issue here, as far as I can see.

**Comment by wdhwg001** [comment]
I manually add `python3.bat` to `venv\Scripts`, but the shebang still fails.

```batch
@echo off
python.exe %*
```

Then I switched the shebang to `#! python3`, `#! python`, `#! py -3`, but any of them didn't work.

Then I manually added the `C:\Users\wdhwg001\study\venv\Scripts` path to both user `PATH` and system `PATH`, but any kinds of shebang still didn't work.

However, shebang like `#! ./venv/Scripts/python` or `#! /usr/bin/env python` works.

So I dug a bit deeper, I made a simple test.py like this:

```python
#! python3

import sys
import os
print(os.path.dirname(sys.executable))
```

Then I run `py test.py` in venv, it gives me this:
```cmd
(venv) PS C:\Users\wdhwg001\study> py test.py
C:\Users\wdhwg001\AppData\Local\Programs\Python\35_x64
```

When using `#! python`:
```cmd
(venv) PS C:\Users\wdhwg001\study> py test.py
C:\Users\wdhwg001\AppData\Local\Programs\Python\27_x64
```

`#! /usr/bin/env python`:
```cmd
(venv) PS C:\Users\wdhwg001\study> py test.py
C:\Users\wdhwg001\study\venv\Scripts
```

`#! /usr/bin/env python3` and `#! py -3` work same as `#! python3`.

`#! py` hangs.

So it might be a bug of py.exe, that it will use system installed python 3 once the shebang includes `python3`. The right way is to search for `python3` from `PATH` when using shebang like `#! /usr/bin/env python3`.

And I think virtualenv should also make a fix that when creating a python 3 virtualenv, virtualenv will generate `python3.exe`(symbol-linked to `python.exe`) or `python3.bat` in Scripts.

**Comment by wdhwg001** [comment]
I raised an issue on `bugs.python.org`:
http://bugs.python.org/issue28686

**Comment by pfmoore** [comment]
> I manually add python3.bat to venv\Scripts, but the shebang still fails.

Bat files are not always treated as executable by Windows. It's quite possible that the PATH search isn't finding the bat file. (And that's an OS limitation, not a limitation of ```py.exe```.

I'd be curious to know if ```#!/usr/bin/env python3.bat``` worked. Sometimes Windows accepts bat files, but won't automatically add the extension.

Of course, to solve your actual problem, you can just use ```#!/usr/bin/env python``` (and simply don't try to run the script when Python 2 is your active Python) as a workaround. Or explicitly specify the full path to your virtualenv Python.

**Comment by wdhwg001** [comment]
`#!/usr/bin/env python3.bat` gives me this:
```cmd
(venv) PS C:\Users\wdhwg001\study> py test.py
Invalid version specification: '3.bat'.
In the first line of the script, 'python' needs to be followed by a valid version specifier.
Please check the documentation.
```

And moreover, I created a symbol link like this:
```cmd
C:\Users\wdhwg001\cubic_time\venv\Scripts>mklink /H python3.exe python.exe
Hardlink created for python3.exe <<===>> python.exe
```

Now with the Hardlink, `python3.exe` are exactly the same as `python.exe`.

But `#! /usr/bin/env python3` still cannot find `python3.exe` in `venv/Scripts`.

**Comment by pfmoore** [comment]
Ah, OK. Thanks for trying that - yes, ```python3.bat``` would fall foul of the fact that the final characters must be a version. I'm not sure why the hardlink doesn't work, though.

Your experiments with the ```test.py``` script look right to me.

**Comment by wdhwg001** [comment]
BTW, if you're using unix-like system, I'd like to know how `#! /usr/bin/env python3` in virtualenv behaves there.
I didn't see any python3 binary in `Scripts`, will `#! /usr/bin/env python3` works?
