### ISSUE TITLE
virtualenv attempts to overwrite in-use executable in place.

### ISSUE THREAD

**Issue by cstorey** [pypa/virtualenv#980]
Hi,

We've inherited some deployment scripts that attempt to ensure idempotency by unconditionally calling `virtualenv` to recreate an environment. However, in practice, we've found that this will often fail, with:

```
: ceri@misssplendid; virtualenv /tmp/test 
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /tmp/test/bin/python2.7
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 942, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1261, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/tmp/test/bin/python2.7'
: ceri@misssplendid;
```

This only happens when another process is running from the  given python executable, ie: `/tmp/test/bin/python2.7`. To re-interpret the error message then, the virtualenv process is trying to write directly into an executable that's running, which (if it worked) would also affect the running python process, unsafely swapping out the running machine code, and most likely causing a crash.

The usual pattern for this on Unix is to write the new file to a temporary pathname and then atomically rename, although I suspect that wouldn't work so well on Windows.

**Comment by mlazowik** [comment]
+1

**Comment by gaborbernat** [comment]
Not sure what's a good thing to do here. virtualenv does not know if the target is used or not. Doing the rename would similarly fail not?

**Comment by cstorey** [comment]
At least on Unix-family systems, it's safe to atomically rename a temporary file over the target, since the original file's data is decoupled from the name in the filesystem, and can exist independently.
I don't think that will be true on other systems, such as Windows, though. Although there, it'll be a choice between:

 * Fail because you can't rename over a file that is currently in use
 * Either Fail because you can't write to a file used as an executable, or have a running process fail because the executable code has changed in memory (depending on what the OS does).

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.
