### ISSUE TITLE
URL provided on website for installing virtualenv development version not working.

### ISSUE THREAD

**Issue by doctorBeast** [pypa/virtualenv#984]
URL(https://github.com/pypa/virtualenv/tarball/develop) to install development version on documentation website(https://virtualenv.readthedocs.io/en/stable/installation/) showing 404 error.

**Comment by yan12125** [comment]
It should be https://github.com/pypa/virtualenv/tarball/master

**Comment by doctorBeast** [comment]
In which file do we have make changes to for the above issue.

**Comment by yan12125** [comment]
Seems this one: https://github.com/pypa/virtualenv/blob/master/docs/installation.rst
