### ISSUE TITLE
Servoblaster & virtualenv

### ISSUE THREAD

**Issue by BBCBasic** [pypa/virtualenv#990]
Hi I'm trying to get Servoblaster & virtualenv working together, and I can't. 

Is this possible, if so how?

Cheers Rob

**Comment by yan12125** [comment]
What's the error?

**Comment by BBCBasic** [comment]
Thanks I got it to work. I had to install it outside the virtual environment.

Sent from my Phone

On 1 Dec 2016, at 04:34, Yen Chi Hsuan <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the error?

-

**Comment by BBCBasic** [comment]
Thanks I got it to work. I had to install it outside the virtual environment
