### ISSUE TITLE
Activation fails with set -u and unset PS1

### ISSUE THREAD

**Issue by niothiel** [pypa/virtualenv#991]
virtualenv: **15.1.0**

We use virtualenvs in our Jenkins jobs. The bash shell in which the job runs does not have the `PS1` variable set. In addition to this, we run our bash script with `set -u`. The combination of these two factors cause the activation script to fail with the error:

```bash
env/bin/activate:57: PS1: parameter not set
```

Reproduction:

```bash
$ virtualenv env/
.. setup stuff ..
Installing setuptools, pip, wheel...done.
$ set -u
$ unset PS1
source env/bin/activate
env/bin/activate:57: PS1: parameter not set
```

Seems like it would be easy enough to use bash's default completion: `${PS1:-}` to fix this issue.

If PRs are welcomed for this, I would gladly jump on it.

**Comment by ssbarnea** [comment]
@gaborbernat Please close this as fixed. The problem no longer happens with current master.

This was one bug that hunted me for years as I usually write bash scripts in stricts mode, which includes the set -u.

**Comment by gaborbernat** [comment]
![thanks](https://media.tenor.co/images/0f8a9abf556488c8fa0b327cec6b1a9f/tenor.gif)
