### ISSUE TITLE
Virtualenv looks at system site packages (Ubuntu 16.04)

### ISSUE THREAD

**Issue by kunaltyagi** [pypa/virtualenv#995]
I'm not sure if it is an issue with pip or virtualenv, I've noticed it with pip only. Managed to reproduce it everytime by ```$ sudo apt install python-pip```. Shouldn't local packages be given more priority?
```
(py2)$ which pip
/home/kunal/py2/bin/pip
(py2)$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
(py2)$ sudo apt remove python-pip
(py2)$ which pip
/home/kunal/py2/bin/pip
(py2)$ pip --version
pip 9.0.1 from /home/kunal/py2/local/lib/python2.7/site-packages (python 2.7)
(py2)$ virtualenv --version
15.0.1
$ uname -a
Linux alien 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
PS: Ignore the time (it's a dual boot fresh install system)

**Comment by yan12125** [comment]
Could you remove this line from ```virtualenv.py```:
```
fix_local_scheme(home_dir, symlink)
```
And try again? (create a new virtual env, pip ...)

Ref: #118

**Comment by kunaltyagi** [comment]
Thanks. This solves the issue. 

Is this the official fix? When is this coming as a part of [ubuntu package](http://packages.ubuntu.com/xenial/python/python-virtualenv)?

**Comment by yan12125** [comment]
> Is this the official fix?

Nope. That's just my guess. I don't know the actual cause, either.
