### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by Naatan** [pypa/virtualenv#996]
virtualenv seems to not include Python header files, making installation of some packages through pip impossible.

Steps to reproduce (on Arch linux);

 1. `virtualenv env -p ${which python2}`
 2. `source env/bin/activate`
 3. `pip install apsw`

Fails with:

```
    src/apsw.c:73:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by lmaddox** [comment]
Still have this issue in 2020. python3 -m pipenv install fails for numba, bitarray, cartopy, ephem, matplotlib, pyaudio, scipy, etc. All saying that it can't find Python.h, although python3-dev is installed.
